/**
 * doppler.h — umbrella header for the doppler C library.
 *
 * Include this header to access all component APIs, or include
 * individual component headers directly.
 *
 * Generated by just-makeit; updated on each `just-makeit init`.
 */
#ifndef DOPPLER_H
#define DOPPLER_H

#ifdef __cplusplus
extern "C" {
#endif

/* ── Components ─────────────────────────────────────────────────────────── */

#include "acc_f32/acc_f32_core.h"

#include "acc_cf64/acc_cf64_core.h"

#include "fir/fir_core.h"

#include "cic/cic_core.h"

#include "nco/nco_core.h"

#include "lo/lo_core.h"

#include "delay/delay_core.h"

#include "fft/fft_core.h"

#include "fft2d/fft2d_core.h"

#include "corr/corr_core.h"

#include "corr2d/corr2d_core.h"

#include "detector/detector_core.h"

#include "detector2d/detector2d_core.h"

#include "Resampler/Resampler_core.h"

#include "HalfbandDecimator/HalfbandDecimator_core.h"

#include "agc/agc_core.h"

#ifdef __cplusplus
}
#endif

#endif /* DOPPLER_H */
