/**
 * doppler.h — umbrella header for the doppler C library.
 *
 * Include this header to access all component APIs, or include
 * individual component headers directly.
 *
 * Generated by just-makeit; updated on each `just-makeit init`.
 */
#ifndef DOPPLER_JM_H
#define DOPPLER_JM_H

#ifdef __cplusplus
extern "C"
{
#endif

  /* ── Components ───────────────────────────────────────────────────────────
   */

#include "fir/fir_core.h"

#include "nco/nco_core.h"

#include "lo/lo_core.h"

#include "acc_f32/acc_f32_core.h"

#include "acc_cf64/acc_cf64_core.h"

#include "delay/delay_core.h"

#include "fft/fft_core.h"

#include "fft2d/fft2d_core.h"

#include "Resampler/Resampler_core.h"

#include "HalfbandDecimator/HalfbandDecimator_core.h"

  /* ── Version ──────────────────────────────────────────────────────────────
   */

#include "doppler/version.h"

#include "agc/agc_core.h"

#ifdef __cplusplus
}
#endif

#endif /* DOPPLER_JM_H */
