# wfm_compose.pyi — composer OO types (jm; gh-287).
from __future__ import annotations
from typing import Any, Iterator
import numpy as np
from numpy.typing import NDArray

class Synth:
    def __init__(self, type: str = ..., freq: float = ..., snr: float = ..., snr_mode: str = ..., seed: int = ..., sps: int = ..., pn_length: int = ..., pn_poly: int = ..., lfsr: str = ..., level: float = ..., f_end: float = ..., bits: bytes | None = ..., modulation: str = ..., pulse: str = ..., rrc_beta: float = ..., rrc_span: int = ..., fs: float = ...) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def steps(self, n: int) -> NDArray[np.complex64]: ...
    def step(self) -> complex: ...
    def reset(self) -> None: ...

class Segment:
    sources: list[Synth]
    type: str
    freq: float
    snr: float
    snr_mode: str
    seed: int
    sps: int
    pn_length: int
    pn_poly: int
    lfsr: str
    level: float
    f_end: float
    bits: bytes | None
    modulation: str
    pulse: str
    rrc_beta: float
    rrc_span: int
    def __init__(self, type: str = ..., freq: float = ..., snr: float = ..., snr_mode: str = ..., seed: int = ..., sps: int = ..., pn_length: int = ..., pn_poly: int = ..., lfsr: str = ..., level: float = ..., f_end: float = ..., bits: bytes | None = ..., modulation: str = ..., pulse: str = ..., rrc_beta: float = ..., rrc_span: int = ..., fs: float = ..., num_samples: int = ..., off_samples: int = ...) -> None: ...
    @classmethod
    def sum(cls, *sources: Synth, fs: float = ..., num_samples: int = ..., off_samples: int = ...) -> Segment: ...
    def add(self, *others: Segment) -> Timeline: ...

class Timeline:
    segments: list[Segment]
    def __init__(self, segments: list[Segment]) -> None: ...
    def add(self, *segments: Segment) -> Timeline: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __getitem__(self, i): ...

class Composer:
    segments: list[Segment]
    repeat: bool
    continuous: bool
    def __init__(self, segments: Segment | Timeline | list[Segment] | None = ..., *, repeat: bool = ..., continuous: bool = ..., **segment_kwargs) -> None: ...
    def execute(self, n: int) -> NDArray[np.complex64]: ...
    def compose(self, block: int = ...) -> NDArray[np.complex64]: ...
    def stream(self, block: int = ...) -> Iterator[NDArray[np.complex64]]: ...
    def to_dict(self) -> dict: ...
    def close(self) -> None: ...
    def __enter__(self) -> Composer: ...
    def __exit__(self, *exc) -> None: ...
    @classmethod
    def from_json(cls, json: str) -> Composer: ...
    @classmethod
    def from_file(cls, path: str) -> Composer: ...
    def to_json(self) -> str: ...

def tone(**kw: Any) -> Synth: ...
def noise(**kw: Any) -> Synth: ...
def pn(**kw: Any) -> Synth: ...
def bpsk(**kw: Any) -> Synth: ...
def qpsk(**kw: Any) -> Synth: ...
def chirp(**kw: Any) -> Synth: ...
def bits(**kw: Any) -> Synth: ...
