/**
 * @file resamp.h
 * @brief Continuously-variable polyphase resampler for cf64 IQ samples.
 *
 * Combines a dual-buffer delay line, a polyphase FIR coefficient bank,
 * and a 32-bit phase accumulator to resample IQ streams at any rational
 * rate in a single streaming pass.
 *
 * ### Rate parameter
 *
 * @p rate = @c fs_out / @c fs_in (samples-out per sample-in):
 *
 * | rate   | meaning               |
 * |--------|-----------------------|
 * | > 1    | interpolation (up)    |
 * | < 1    | decimation (down)     |
 * | = 1    | unity (pass-through)  |
 *
 * Non-integer and irrational rates are fully supported.
 *
 * ### Phase accumulator
 *
 * The accumulator is a 32-bit unsigned integer that advances by a fixed
 * @e step on every driver tick:
 *
 * - **Interpolation** (rate ≥ 1) — output-driven.  One tick per output
 *   sample; step = round(2^32 / rate).  Accumulator overflow means one
 *   input sample period has elapsed → push the next input sample.
 *
 * - **Decimation** (rate < 1) — input-driven.  One tick per input
 *   sample; step = round(2^32 × rate).  Accumulator overflow means one
 *   output sample period has elapsed → MAC and emit an output sample.
 *
 * The top @e log₂(num_phases) bits of the accumulator select the
 * polyphase branch at each output moment, giving continuous fractional
 * delay at no extra cost.
 *
 * ### Coefficient bank
 *
 * A row-major float32 array of shape @c [num_phases][num_taps].  Use
 * @c doppler.polyphase.to_c_header (Python) to generate the bank; pass
 * the flat pointer here.  The resampler copies the bank on creation so
 * the caller's buffer may be freed immediately after.
 *
 * ### Usage (interpolation 1 → 2, i.e. 2× upsample)
 *
 * ```c
 * #include <dp/resamp.h>
 *
 * // bank[NUM_PHASES][NUM_TAPS] generated by doppler.polyphase
 * dp_resamp_cf64_t *r = dp_resamp_cf64_create(
 *     NUM_PHASES, NUM_TAPS, &bank[0][0], 2.0);
 *
 * dp_cf64_t out[2 * IN_LEN + 4];
 * size_t n_out = dp_resamp_cf64_execute(
 *     r, in, IN_LEN, out, sizeof(out)/sizeof(out[0]));
 *
 * dp_resamp_cf64_destroy(r);
 * ```
 *
 * ### Output buffer sizing
 *
 * - Interpolation: allocate at least @c ceil(num_in × rate) + 2 samples.
 * - Decimation:    allocate at least @c ceil(num_in × rate) + 2 samples.
 */

#ifndef DP_RESAMP_H
#define DP_RESAMP_H

#include <dp/stream.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

  /** @brief Opaque polyphase resampler state. */
  typedef struct dp_resamp_cf64 dp_resamp_cf64_t;

  /* ------------------------------------------------------------------
   * Lifecycle
   * ------------------------------------------------------------------ */

  /**
   * @brief Create a polyphase cf64 resampler.
   *
   * The coefficient bank is copied internally; the caller may free
   * @p bank immediately after this call returns.
   *
   * @p num_phases must be a power of two ≥ 1.
   *
   * @param num_phases  Number of polyphase branches (power of two).
   * @param num_taps    Taps per branch (filter length ≥ 1).
   * @param bank        Flat row-major array [num_phases][num_taps],
   *                    float32 coefficients.
   * @param rate        Output rate / input rate  (fs_out / fs_in).
   *                    Must be > 0.
   * @return            Heap-allocated resampler, or NULL on failure.
   */
  dp_resamp_cf64_t *dp_resamp_cf64_create (size_t       num_phases,
                                           size_t       num_taps,
                                           const float *bank,
                                           double       rate);

  /**
   * @brief Free a resampler.
   * @param r  May be NULL (no-op).
   */
  void dp_resamp_cf64_destroy (dp_resamp_cf64_t *r);

  /**
   * @brief Zero the sample history and reset the phase accumulator.
   *
   * Use after a stream discontinuity.
   *
   * @param r  Must be non-NULL.
   */
  void dp_resamp_cf64_reset (dp_resamp_cf64_t *r);

  /* ------------------------------------------------------------------
   * Properties
   * ------------------------------------------------------------------ */

  /** @brief Return the rate (fs_out / fs_in) the resampler was created
   *  with. */
  double dp_resamp_cf64_rate (const dp_resamp_cf64_t *r);

  /** @brief Return the number of polyphase branches. */
  size_t dp_resamp_cf64_num_phases (const dp_resamp_cf64_t *r);

  /** @brief Return the taps per branch. */
  size_t dp_resamp_cf64_num_taps (const dp_resamp_cf64_t *r);

  /* ------------------------------------------------------------------
   * Processing
   * ------------------------------------------------------------------ */

  /**
   * @brief Resample a block of cf64 IQ samples.
   *
   * Processes @p num_in input samples and writes at most @p max_out
   * output samples.  Internal state (phase accumulator, delay history)
   * is preserved across calls, so blocks may be any size.
   *
   * **Interpolation** (rate ≥ 1): the function consumes all @p num_in
   * inputs.  Provide @p max_out ≥ ceil(num_in × rate) + 2.
   *
   * **Decimation** (rate < 1): the function consumes all @p num_in
   * inputs unless @p max_out is exhausted first.  Provide
   * @p max_out ≥ ceil(num_in × rate) + 2.
   *
   * @param r        Must be non-NULL.
   * @param in       Input sample array (may be NULL if num_in == 0).
   * @param num_in   Number of input samples.
   * @param out      Output sample buffer (must hold ≥ max_out samples).
   * @param max_out  Capacity of @p out in samples.
   * @return         Number of output samples written to @p out.
   */
  size_t dp_resamp_cf64_execute (dp_resamp_cf64_t *r,
                                 const dp_cf64_t  *in,
                                 size_t            num_in,
                                 dp_cf64_t        *out,
                                 size_t            max_out);

#ifdef __cplusplus
}
#endif

#endif /* DP_RESAMP_H */
