/*
 * dp_accumulator.c — Python C extension for dp/accumulator.h
 *
 * AUTO-GENERATED by tools/gen_pyext.py — hand-tuned for:
 *   - no-arg constructors
 *   - float / dp_cf64_t scalar returns (get, dump)
 *   - dp_cf64_t scalar arg (push)
 *   - numpy array args (add, madd, add2d, madd2d)
 * Regenerate scaffold:
 *   python tools/gen_pyext.py c/include/dp/accumulator.h
 */

#define PY_SSIZE_T_CLEAN
#include <Python.h>
#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
#include <numpy/arrayobject.h>

#include <dp/accumulator.h>
#include <dp/stream.h> /* dp_cf64_t */

/* ======================================================== */
/* AccF32Object — wraps dp_acc_f32_t *
 * ======================================================== */

typedef struct
{
  PyObject_HEAD dp_acc_f32_t *handle;
} AccF32Object;

static void
AccF32_dealloc (AccF32Object *self)
{
  if (self->handle)
    dp_acc_f32_destroy (self->handle);
  Py_TYPE (self)->tp_free ((PyObject *)self);
}

static PyObject *
AccF32_new (PyTypeObject *type, PyObject *args, PyObject *kwds)
{
  AccF32Object *self = (AccF32Object *)type->tp_alloc (type, 0);
  if (self)
    self->handle = NULL;
  return (PyObject *)self;
}

static int
AccF32_init (AccF32Object *self, PyObject *args, PyObject *kwds)
{
  (void)args;
  (void)kwds;
  self->handle = dp_acc_f32_create ();
  if (!self->handle)
    {
      PyErr_SetString (PyExc_MemoryError, "dp_acc_f32_create returned NULL");
      return -1;
    }
  return 0;
}

/* ── reset ─────────────────────────────────────────────── */

static PyObject *
AccF32_reset (AccF32Object *self, PyObject *Py_UNUSED (ignored))
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  dp_acc_f32_reset (self->handle);
  Py_RETURN_NONE;
}

/* ── get / dump ────────────────────────────────────────── */

static PyObject *
AccF32_get (AccF32Object *self, PyObject *Py_UNUSED (ignored))
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  return PyFloat_FromDouble ((double)dp_acc_f32_get (self->handle));
}

static PyObject *
AccF32_dump (AccF32Object *self, PyObject *Py_UNUSED (ignored))
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  return PyFloat_FromDouble ((double)dp_acc_f32_dump (self->handle));
}

/* ── push ──────────────────────────────────────────────── */

static PyObject *
AccF32_push (AccF32Object *self, PyObject *args)
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  float x = 0;
  if (!PyArg_ParseTuple (args, "f", &x))
    return NULL;
  dp_acc_f32_push (self->handle, x);
  Py_RETURN_NONE;
}

/* ── add ───────────────────────────────────────────────── */

static PyObject *
AccF32_add (AccF32Object *self, PyObject *args)
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  PyObject *xo;
  if (!PyArg_ParseTuple (args, "O", &xo))
    return NULL;
  PyArrayObject *xa = (PyArrayObject *)PyArray_FROM_OTF (
      xo, NPY_FLOAT32, NPY_ARRAY_C_CONTIGUOUS);
  if (!xa)
    return NULL;

  dp_acc_f32_add (self->handle, (const float *)PyArray_DATA (xa),
                  (size_t)PyArray_SIZE (xa));
  Py_DECREF (xa);
  Py_RETURN_NONE;
}

/* ── madd ──────────────────────────────────────────────── */

static PyObject *
AccF32_madd (AccF32Object *self, PyObject *args)
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  PyObject *xo, *ho;
  if (!PyArg_ParseTuple (args, "OO", &xo, &ho))
    return NULL;

  PyArrayObject *xa = (PyArrayObject *)PyArray_FROM_OTF (
      xo, NPY_FLOAT32, NPY_ARRAY_C_CONTIGUOUS);
  if (!xa)
    return NULL;
  PyArrayObject *ha = (PyArrayObject *)PyArray_FROM_OTF (
      ho, NPY_FLOAT32, NPY_ARRAY_C_CONTIGUOUS);
  if (!ha)
    {
      Py_DECREF (xa);
      return NULL;
    }

  Py_ssize_t n = PyArray_SIZE (xa);
  if (PyArray_SIZE (ha) < n)
    n = PyArray_SIZE (ha);

  dp_acc_f32_madd (self->handle, (const float *)PyArray_DATA (xa),
                   (const float *)PyArray_DATA (ha), (size_t)n);
  Py_DECREF (xa);
  Py_DECREF (ha);
  Py_RETURN_NONE;
}

/* ── destroy / context manager ─────────────────────────── */

static PyObject *
AccF32_destroy (AccF32Object *self, PyObject *Py_UNUSED (ignored))
{
  if (self->handle)
    {
      dp_acc_f32_destroy (self->handle);
      self->handle = NULL;
    }
  Py_RETURN_NONE;
}

static PyObject *
AccF32_enter (AccF32Object *self, PyObject *Py_UNUSED (ignored))
{
  Py_INCREF (self);
  return (PyObject *)self;
}

static PyObject *
AccF32_exit (AccF32Object *self, PyObject *args)
{
  (void)args;
  if (self->handle)
    {
      dp_acc_f32_destroy (self->handle);
      self->handle = NULL;
    }
  Py_RETURN_NONE;
}

static PyMethodDef AccF32_methods[] = {
  { "reset", (PyCFunction)AccF32_reset, METH_NOARGS, "dp_acc_f32_reset." },
  { "get", (PyCFunction)AccF32_get, METH_NOARGS, "dp_acc_f32_get." },
  { "dump", (PyCFunction)AccF32_dump, METH_NOARGS,
    "dp_acc_f32_dump — read and zero." },
  { "push", (PyCFunction)AccF32_push, METH_VARARGS, "push(x: float)." },
  { "add", (PyCFunction)AccF32_add, METH_VARARGS, "add(x: np.ndarray[f32])." },
  { "madd", (PyCFunction)AccF32_madd, METH_VARARGS,
    "madd(x: np.ndarray[f32], h: np.ndarray[f32])." },
  { "destroy", (PyCFunction)AccF32_destroy, METH_NOARGS,
    "Release resources." },
  { "__enter__", (PyCFunction)AccF32_enter, METH_NOARGS, NULL },
  { "__exit__", (PyCFunction)AccF32_exit, METH_VARARGS, NULL },
  { NULL }
};

static PyTypeObject AccF32Type = {
  PyVarObject_HEAD_INIT (NULL, 0).tp_name = "dp_accumulator.AccF32",
  .tp_basicsize = sizeof (AccF32Object),
  .tp_dealloc = (destructor)AccF32_dealloc,
  .tp_flags = Py_TPFLAGS_DEFAULT,
  .tp_doc = "Wraps dp_acc_f32_t.",
  .tp_methods = AccF32_methods,
  .tp_new = AccF32_new,
  .tp_init = (initproc)AccF32_init,
};

/* ======================================================== */
/* AccCf64Object — wraps dp_acc_cf64_t *
 * ======================================================== */

typedef struct
{
  PyObject_HEAD dp_acc_cf64_t *handle;
} AccCf64Object;

static void
AccCf64_dealloc (AccCf64Object *self)
{
  if (self->handle)
    dp_acc_cf64_destroy (self->handle);
  Py_TYPE (self)->tp_free ((PyObject *)self);
}

static PyObject *
AccCf64_new (PyTypeObject *type, PyObject *args, PyObject *kwds)
{
  AccCf64Object *self = (AccCf64Object *)type->tp_alloc (type, 0);
  if (self)
    self->handle = NULL;
  return (PyObject *)self;
}

static int
AccCf64_init (AccCf64Object *self, PyObject *args, PyObject *kwds)
{
  (void)args;
  (void)kwds;
  self->handle = dp_acc_cf64_create ();
  if (!self->handle)
    {
      PyErr_SetString (PyExc_MemoryError, "dp_acc_cf64_create returned NULL");
      return -1;
    }
  return 0;
}

/* ── reset ─────────────────────────────────────────────── */

static PyObject *
AccCf64_reset (AccCf64Object *self, PyObject *Py_UNUSED (ignored))
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  dp_acc_cf64_reset (self->handle);
  Py_RETURN_NONE;
}

/* ── get / dump ────────────────────────────────────────── */

static PyObject *
AccCf64_get (AccCf64Object *self, PyObject *Py_UNUSED (ignored))
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  dp_cf64_t v = dp_acc_cf64_get (self->handle);
  return PyComplex_FromDoubles (v.i, v.q);
}

static PyObject *
AccCf64_dump (AccCf64Object *self, PyObject *Py_UNUSED (ignored))
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  dp_cf64_t v = dp_acc_cf64_dump (self->handle);
  return PyComplex_FromDoubles (v.i, v.q);
}

/* ── push ──────────────────────────────────────────────── */

static PyObject *
AccCf64_push (AccCf64Object *self, PyObject *args)
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  Py_complex z;
  if (!PyArg_ParseTuple (args, "D", &z))
    return NULL;
  dp_cf64_t x = { z.real, z.imag };
  dp_acc_cf64_push (self->handle, x);
  Py_RETURN_NONE;
}

/* ── add ───────────────────────────────────────────────── */

static PyObject *
AccCf64_add (AccCf64Object *self, PyObject *args)
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  PyObject *xo;
  if (!PyArg_ParseTuple (args, "O", &xo))
    return NULL;
  PyArrayObject *xa = (PyArrayObject *)PyArray_FROM_OTF (
      xo, NPY_COMPLEX128, NPY_ARRAY_C_CONTIGUOUS);
  if (!xa)
    return NULL;

  dp_acc_cf64_add (self->handle, (const dp_cf64_t *)PyArray_DATA (xa),
                   (size_t)PyArray_SIZE (xa));
  Py_DECREF (xa);
  Py_RETURN_NONE;
}

/* ── madd ──────────────────────────────────────────────── */

static PyObject *
AccCf64_madd (AccCf64Object *self, PyObject *args)
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  PyObject *xo, *ho;
  if (!PyArg_ParseTuple (args, "OO", &xo, &ho))
    return NULL;

  PyArrayObject *xa = (PyArrayObject *)PyArray_FROM_OTF (
      xo, NPY_COMPLEX128, NPY_ARRAY_C_CONTIGUOUS);
  if (!xa)
    return NULL;
  PyArrayObject *ha = (PyArrayObject *)PyArray_FROM_OTF (
      ho, NPY_FLOAT32, NPY_ARRAY_C_CONTIGUOUS);
  if (!ha)
    {
      Py_DECREF (xa);
      return NULL;
    }

  Py_ssize_t n = PyArray_SIZE (xa);
  if (PyArray_SIZE (ha) < n)
    n = PyArray_SIZE (ha);

  dp_acc_cf64_madd (self->handle, (const dp_cf64_t *)PyArray_DATA (xa),
                    (const float *)PyArray_DATA (ha), (size_t)n);
  Py_DECREF (xa);
  Py_DECREF (ha);
  Py_RETURN_NONE;
}

/* ── destroy / context manager ─────────────────────────── */

static PyObject *
AccCf64_destroy (AccCf64Object *self, PyObject *Py_UNUSED (ignored))
{
  if (self->handle)
    {
      dp_acc_cf64_destroy (self->handle);
      self->handle = NULL;
    }
  Py_RETURN_NONE;
}

static PyObject *
AccCf64_enter (AccCf64Object *self, PyObject *Py_UNUSED (ignored))
{
  Py_INCREF (self);
  return (PyObject *)self;
}

static PyObject *
AccCf64_exit (AccCf64Object *self, PyObject *args)
{
  (void)args;
  if (self->handle)
    {
      dp_acc_cf64_destroy (self->handle);
      self->handle = NULL;
    }
  Py_RETURN_NONE;
}

static PyMethodDef AccCf64_methods[] = {
  { "reset", (PyCFunction)AccCf64_reset, METH_NOARGS, "dp_acc_cf64_reset." },
  { "get", (PyCFunction)AccCf64_get, METH_NOARGS,
    "dp_acc_cf64_get — read without clearing." },
  { "dump", (PyCFunction)AccCf64_dump, METH_NOARGS,
    "dp_acc_cf64_dump — read and zero." },
  { "push", (PyCFunction)AccCf64_push, METH_VARARGS, "push(x: complex)." },
  { "add", (PyCFunction)AccCf64_add, METH_VARARGS,
    "add(x: np.ndarray[complex128])." },
  { "madd", (PyCFunction)AccCf64_madd, METH_VARARGS,
    "madd(x: np.ndarray[complex128], h: np.ndarray[f32])." },
  { "destroy", (PyCFunction)AccCf64_destroy, METH_NOARGS,
    "Release resources." },
  { "__enter__", (PyCFunction)AccCf64_enter, METH_NOARGS, NULL },
  { "__exit__", (PyCFunction)AccCf64_exit, METH_VARARGS, NULL },
  { NULL }
};

static PyTypeObject AccCf64Type = {
  PyVarObject_HEAD_INIT (NULL, 0).tp_name = "dp_accumulator.AccCf64",
  .tp_basicsize = sizeof (AccCf64Object),
  .tp_dealloc = (destructor)AccCf64_dealloc,
  .tp_flags = Py_TPFLAGS_DEFAULT,
  .tp_doc = "Wraps dp_acc_cf64_t.",
  .tp_methods = AccCf64_methods,
  .tp_new = AccCf64_new,
  .tp_init = (initproc)AccCf64_init,
};

/* ======================================================== */
/* Module                                                    */
/* ======================================================== */

static PyModuleDef dp_accumulator_module = {
  PyModuleDef_HEAD_INIT,
  .m_name = "dp_accumulator",
  .m_doc = "Python binding for dp/accumulator.h.",
  .m_size = -1,
};

PyMODINIT_FUNC
PyInit_dp_accumulator (void)
{
  import_array ();

  if (PyType_Ready (&AccF32Type) < 0)
    return NULL;
  if (PyType_Ready (&AccCf64Type) < 0)
    return NULL;

  PyObject *m = PyModule_Create (&dp_accumulator_module);
  if (!m)
    return NULL;

  Py_INCREF (&AccF32Type);
  if (PyModule_AddObject (m, "AccF32", (PyObject *)&AccF32Type) < 0)
    {
      Py_DECREF (&AccF32Type);
      Py_DECREF (m);
      return NULL;
    }

  Py_INCREF (&AccCf64Type);
  if (PyModule_AddObject (m, "AccCf64", (PyObject *)&AccCf64Type) < 0)
    {
      Py_DECREF (&AccCf64Type);
      Py_DECREF (m);
      return NULL;
    }

  return m;
}
