/*
 * wfm_compose_ext.c — composer extension for `wfm_compose` (generated by jm; gh-287).
 *
 * The Synth / Segment / Timeline / Composer OO types live here, in the .so;
 * the composition kernels stay hand-written in the backing _core.c.
 */
#define PY_SSIZE_T_CLEAN
#include <Python.h>
#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
#include <numpy/arrayobject.h>
#include <complex.h>
#include <stdlib.h>
#include <string.h>

#include "wfm/wfm_compose.h"
#include "wfm_synth/wfm_synth_core.h"
/* project bridge (straight C, no CPython): build the generator. */
extern wfm_synth_state_t *wfm_source_to_synth(const wfm_source_t *, double);
#include "timing/timing_core.h"
#include "wfm/wfm_writer.h"

/* String-enum tables — order is the C int (the [[enum]] SSOT). */
static int
_enum_index(const char *const *tab, const char *s)
{
    for (int i = 0; tab[i]; i++)
        if (strcmp(tab[i], s) == 0)
            return i;
    return -1;
}

static const char *const _enum_wfm_type[] = {
    "tone",
    "noise",
    "pn",
    "bpsk",
    "qpsk",
    "chirp",
    "bits",
    "symbols",
    "dsss",
    NULL,
};

static const char *const _enum_snr_mode[] = {
    "auto",
    "fs",
    "ebno",
    "esno",
    NULL,
};

static const char *const _enum_wfm_lfsr[] = {
    "galois",
    "fibonacci",
    NULL,
};

static const char *const _enum_bitmod[] = {
    "none",
    "bpsk",
    "qpsk",
    NULL,
};

static const char *const _enum_wfm_pulse[] = {
    "rect",
    "rrc",
    NULL,
};

static const char *const _enum_crc[] = {
    "none",
    "crc16",
    NULL,
};

static const char *const _enum_gap_noise[] = {
    "auto",
    "off",
    NULL,
};

static const char *const _enum_stype[] = {
    "cf32",
    "cf64",
    "ci32",
    "ci16",
    "ci8",
    NULL,
};

static const char *const _enum_endian[] = {
    "le",
    "be",
    NULL,
};

static int
_jm_parse_range(PyObject *o, double *lo, double *hi, int *is_range)
{
    if (PySequence_Check(o) && !PyUnicode_Check(o)
        && !PyBytes_Check(o)) {
        if (PySequence_Size(o) != 2) {
            PyErr_SetString(PyExc_ValueError,
                            "range must be a (low, high) pair");
            return 0;
        }
        PyObject *a = PySequence_GetItem(o, 0);
        PyObject *b = PySequence_GetItem(o, 1);
        double dlo = a ? PyFloat_AsDouble(a) : -1.0;
        double dhi = b ? PyFloat_AsDouble(b) : -1.0;
        Py_XDECREF(a);
        Py_XDECREF(b);
        if (PyErr_Occurred())
            return 0;
        *lo = dlo;
        *hi = dhi;
        *is_range = 1;
        return 1;
    }
    {
        double v = PyFloat_AsDouble(o);
        if (PyErr_Occurred())
            return 0;
        *lo = v;
        *is_range = 0;
    }
    return 1;
}

typedef struct {
    PyObject_HEAD
    wfm_source_t src;
    double   fs;
    wfm_synth_state_t *_gen;
} SynthObject;

static void
Synth_dealloc(SynthObject *self)
{
    if (self->_gen) wfm_synth_destroy(self->_gen);
    free(self->src.bits);
    free(self->src.symbols);
    free(self->src.acq_code);
    free(self->src.data_code);
    free(self->src.sync);
    Py_TYPE(self)->tp_free((PyObject *)self);
}

/* Copy a numpy complex64 array (or None) into src->symbols (owned). */
static int
_attach_symbols(wfm_source_t *src, PyObject *obj)
{
    free(src->symbols);
    src->symbols   = NULL;
    src->n_symbols = 0;
    if (!obj || obj == Py_None)
        return 1;
    PyArrayObject *_arr = (PyArrayObject *)PyArray_FROM_OTF(
        obj, NPY_COMPLEX64, NPY_ARRAY_C_CONTIGUOUS | NPY_ARRAY_FORCECAST);
    if (!_arr)
        return 0;
    Py_ssize_t _n = PyArray_SIZE(_arr);
    if (_n <= 0) { Py_DECREF(_arr); return 1; }
    float _Complex *_buf
        = (float _Complex *)malloc((size_t)_n * sizeof *_buf);
    if (!_buf) { Py_DECREF(_arr); PyErr_NoMemory(); return 0; }
    memcpy(_buf, PyArray_DATA(_arr), (size_t)_n * sizeof *_buf);
    Py_DECREF(_arr);
    src->symbols   = _buf;
    src->n_symbols = (size_t)_n;
    return 1;
}

/* Coerce a 0/1 pattern (bytes | binary/hex str | int sequence) into an owned *dst/*n_dst (one shared
 * coercer; each bytes field passes its own struct destination). */
static int
_attach_bytes(uint8_t **dst, size_t *n_dst, PyObject *obj)
{
    free(*dst);
    *dst   = NULL;
    *n_dst = 0;
    if (!obj || obj == Py_None)
        return 1;
    if (PyBytes_Check(obj)) {
        Py_ssize_t nb = PyBytes_GET_SIZE(obj);
        if (nb <= 0)
            return 1;
        uint8_t *buf = (uint8_t *)malloc((size_t)nb);
        if (!buf) { PyErr_NoMemory(); return 0; }
        memcpy(buf, PyBytes_AS_STRING(obj), (size_t)nb);
    *dst   = buf;
    *n_dst = (size_t)nb;
    return 1;
    }
    if (PyUnicode_Check(obj)) {
        Py_ssize_t slen;
        const char *s = PyUnicode_AsUTF8AndSize(obj, &slen);
        if (!s)
            return 0;
        if (slen >= 2 && s[0] == '0' && (s[1] == 'x' || s[1] == 'X')) {
            Py_ssize_t nd = slen - 2, nb = nd * 4; /* hex digit -> 4 bits MSB */
            uint8_t *buf = (uint8_t *)malloc(nb ? (size_t)nb : 1);
            if (!buf) { PyErr_NoMemory(); return 0; }
            for (Py_ssize_t i = 0; i < nd; i++) {
                char c = s[2 + i];
                int v = (c >= '0' && c <= '9')   ? c - '0'
                        : (c >= 'a' && c <= 'f') ? c - 'a' + 10
                        : (c >= 'A' && c <= 'F') ? c - 'A' + 10
                                                 : -1;
                if (v < 0) {
                    free(buf);
                    PyErr_SetString(PyExc_ValueError, "invalid hex digit");
                    return 0;
                }
                for (int b = 0; b < 4; b++)
                    buf[i * 4 + b] = (uint8_t)((v >> (3 - b)) & 1);
            }
    *dst   = buf;
    *n_dst = (size_t)nb;
    return 1;
        }
        uint8_t *buf = (uint8_t *)malloc(slen ? (size_t)slen : 1);
        if (!buf) { PyErr_NoMemory(); return 0; }
        for (Py_ssize_t i = 0; i < slen; i++) {
            if (s[i] != '0' && s[i] != '1') {
                free(buf);
                PyErr_SetString(PyExc_ValueError,
                                "bit string must be 0/1 or '0x..' hex");
                return 0;
            }
            buf[i] = (uint8_t)(s[i] - '0');
        }
        Py_ssize_t nb = slen;
    *dst   = buf;
    *n_dst = (size_t)nb;
    return 1;
    }
    {
        PyObject *seq = PySequence_Fast(
            obj, "bits must be bytes, a 0/1 string, or a sequence of ints");
        if (!seq)
            return 0;
        Py_ssize_t nb = PySequence_Fast_GET_SIZE(seq);
        uint8_t *buf = (uint8_t *)malloc(nb ? (size_t)nb : 1);
        if (!buf) { Py_DECREF(seq); PyErr_NoMemory(); return 0; }
        for (Py_ssize_t i = 0; i < nb; i++) {
            long v = PyLong_AsLong(PySequence_Fast_GET_ITEM(seq, i));
            if (v == -1 && PyErr_Occurred()) {
                free(buf);
                Py_DECREF(seq);
                return 0;
            }
            buf[i] = (uint8_t)(v != 0);
        }
        Py_DECREF(seq);
    *dst   = buf;
    *n_dst = (size_t)nb;
    return 1;
    }
}

static int
Synth_init(SynthObject *self, PyObject *args, PyObject *kwds)
{
    static char *kwlist[] = {"type", "freq", "snr", "snr_mode", "seed", "sps", "pn_length", "pn_poly", "lfsr", "level", "f_end", "bits", "modulation", "pulse", "rrc_beta", "rrc_span", "symbols", "acq_code", "acq_reps", "data_code", "sync", "crc", "symbol_rate", "dsss_code_only", "fs", NULL};
    const char *type = "tone";
    PyObject *freq = NULL;
    PyObject *snr = NULL;
    const char *snr_mode = "auto";
    uint32_t seed = 0;
    int sps = 1;
    int pn_length = 15;
    uint64_t pn_poly = 0;
    const char *lfsr = "galois";
    PyObject *level = NULL;
    PyObject *f_end = NULL;
    PyObject *bits = NULL;
    const char *modulation = "bpsk";
    const char *pulse = "rect";
    double rrc_beta = 0.35;
    int rrc_span = 8;
    PyObject *symbols = NULL;
    PyObject *acq_code = NULL;
    size_t acq_reps = 1;
    PyObject *data_code = NULL;
    PyObject *sync = NULL;
    const char *crc = "crc16";
    double symbol_rate = 0.0;
    int dsss_code_only = 0;
    double fs = 1e6;
    PyObject *_kw = kwds;
    int _kw_owned = 0;
    if (kwds) {
        {
            PyObject *_a = PyDict_GetItemString(kwds, "f_start");
            if (_a) {
                if (!_kw_owned) {
                    _kw = PyDict_Copy(kwds);
                    if (!_kw) return -1;
                    _kw_owned = 1;
                }
                if (PyDict_GetItemString(_kw, "freq")) {
                    PyErr_SetString(PyExc_TypeError,
                        "freq and f_start are aliases — pass only one");
                    Py_DECREF(_kw);
                    return -1;
                }
                if (PyDict_SetItemString(_kw, "freq", _a) < 0
                    || PyDict_DelItemString(_kw, "f_start") < 0) {
                    Py_DECREF(_kw);
                    return -1;
                }
            }
        }
        {
            PyObject *_a = PyDict_GetItemString(kwds, "pattern");
            if (_a) {
                if (!_kw_owned) {
                    _kw = PyDict_Copy(kwds);
                    if (!_kw) return -1;
                    _kw_owned = 1;
                }
                if (PyDict_GetItemString(_kw, "bits")) {
                    PyErr_SetString(PyExc_TypeError,
                        "bits and pattern are aliases — pass only one");
                    Py_DECREF(_kw);
                    return -1;
                }
                if (PyDict_SetItemString(_kw, "bits", _a) < 0
                    || PyDict_DelItemString(_kw, "pattern") < 0) {
                    Py_DECREF(_kw);
                    return -1;
                }
            }
        }
        {
            PyObject *_a = PyDict_GetItemString(kwds, "payload");
            if (_a) {
                if (!_kw_owned) {
                    _kw = PyDict_Copy(kwds);
                    if (!_kw) return -1;
                    _kw_owned = 1;
                }
                if (PyDict_GetItemString(_kw, "bits")) {
                    PyErr_SetString(PyExc_TypeError,
                        "bits and payload are aliases — pass only one");
                    Py_DECREF(_kw);
                    return -1;
                }
                if (PyDict_SetItemString(_kw, "bits", _a) < 0
                    || PyDict_DelItemString(_kw, "payload") < 0) {
                    Py_DECREF(_kw);
                    return -1;
                }
            }
        }
    }
    if (!PyArg_ParseTupleAndKeywords(args, _kw, "|sOOsIiiKsOOOssdiOOnOOsdid", kwlist,
            &type, &freq, &snr, &snr_mode, &seed, &sps, &pn_length, &pn_poly, &lfsr, &level, &f_end, &bits, &modulation, &pulse, &rrc_beta, &rrc_span, &symbols, &acq_code, &acq_reps, &data_code, &sync, &crc, &symbol_rate, &dsss_code_only, &fs)) {
        if (_kw_owned) Py_DECREF(_kw);
        return -1;
    }
    if (_kw_owned) Py_DECREF(_kw);
    self->fs = fs;
    if (self->_gen) { wfm_synth_destroy(self->_gen); self->_gen = NULL; }
    {
        int _i = _enum_index(_enum_wfm_type, type);
        if (_i < 0) {
            PyErr_Format(PyExc_ValueError,
                         "invalid type '%s'", type);
            return -1;
        }
        self->src.type = _i;
    }
    if (freq != NULL) {
        double _lo, _hi;
        int    _r;
        if (!_jm_parse_range(freq, &_lo, &_hi, &_r))
            return -1;
        self->src.freq = (double)_lo;
        if (_r) {
            self->src.freq_hi = (double)_hi;
            self->src.ranged |= WFM_RANGE_FREQ;
        } else {
            self->src.ranged &= ~(unsigned)WFM_RANGE_FREQ;
        }
    } else {
        self->src.freq = (double)0.0;
    }
    if (snr != NULL) {
        double _lo, _hi;
        int    _r;
        if (!_jm_parse_range(snr, &_lo, &_hi, &_r))
            return -1;
        self->src.snr = (double)_lo;
        if (_r) {
            self->src.snr_hi = (double)_hi;
            self->src.ranged |= WFM_RANGE_SNR;
        } else {
            self->src.ranged &= ~(unsigned)WFM_RANGE_SNR;
        }
    } else {
        self->src.snr = (double)100.0;
    }
    {
        int _i = _enum_index(_enum_snr_mode, snr_mode);
        if (_i < 0) {
            PyErr_Format(PyExc_ValueError,
                         "invalid snr_mode '%s'", snr_mode);
            return -1;
        }
        self->src.snr_mode = _i;
    }
    self->src.seed = seed;
    self->src.sps = sps;
    self->src.pn_length = pn_length;
    self->src.pn_poly = pn_poly;
    {
        int _i = _enum_index(_enum_wfm_lfsr, lfsr);
        if (_i < 0) {
            PyErr_Format(PyExc_ValueError,
                         "invalid lfsr '%s'", lfsr);
            return -1;
        }
        self->src.lfsr = _i;
    }
    if (level != NULL) {
        double _lo, _hi;
        int    _r;
        if (!_jm_parse_range(level, &_lo, &_hi, &_r))
            return -1;
        self->src.level = (double)_lo;
        if (_r) {
            self->src.level_hi = (double)_hi;
            self->src.ranged |= WFM_RANGE_LEVEL;
        } else {
            self->src.ranged &= ~(unsigned)WFM_RANGE_LEVEL;
        }
    } else {
        self->src.level = (double)0.0;
    }
    if (f_end != NULL) {
        double _lo, _hi;
        int    _r;
        if (!_jm_parse_range(f_end, &_lo, &_hi, &_r))
            return -1;
        self->src.f_end = (double)_lo;
        if (_r) {
            self->src.f_end_hi = (double)_hi;
            self->src.ranged |= WFM_RANGE_FEND;
        } else {
            self->src.ranged &= ~(unsigned)WFM_RANGE_FEND;
        }
    } else {
        self->src.f_end = (double)0.0;
    }
    if (!_attach_bytes(&self->src.bits, &self->src.n_bits, bits))
        return -1;
    {
        int _i = _enum_index(_enum_bitmod, modulation);
        if (_i < 0) {
            PyErr_Format(PyExc_ValueError,
                         "invalid modulation '%s'", modulation);
            return -1;
        }
        self->src.modulation = _i;
    }
    {
        int _i = _enum_index(_enum_wfm_pulse, pulse);
        if (_i < 0) {
            PyErr_Format(PyExc_ValueError,
                         "invalid pulse '%s'", pulse);
            return -1;
        }
        self->src.pulse = _i;
    }
    self->src.rrc_beta = rrc_beta;
    self->src.rrc_span = rrc_span;
    if (!_attach_symbols(&self->src, symbols))
        return -1;
    if (!_attach_bytes(&self->src.acq_code, &self->src.n_acq_code, acq_code))
        return -1;
    self->src.acq_reps = acq_reps;
    if (!_attach_bytes(&self->src.data_code, &self->src.n_data_code, data_code))
        return -1;
    if (!_attach_bytes(&self->src.sync, &self->src.n_sync, sync))
        return -1;
    {
        int _i = _enum_index(_enum_crc, crc);
        if (_i < 0) {
            PyErr_Format(PyExc_ValueError,
                         "invalid crc '%s'", crc);
            return -1;
        }
        self->src.crc = _i;
    }
    self->src.symbol_rate = symbol_rate;
    self->src.dsss_code_only = dsss_code_only;
    return 0;
}

static PyObject *
Synth_get_type(SynthObject *self, void *closure)
{
    (void)closure;
    return PyUnicode_FromString(_enum_wfm_type[self->src.type]);
}
static int
Synth_set_type(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    const char *s = PyUnicode_AsUTF8(value);
    if (!s) return -1;
    int _i = _enum_index(_enum_wfm_type, s);
    if (_i < 0) {
        PyErr_Format(PyExc_ValueError, "invalid type '%s'", s);
        return -1;
    }
    self->src.type = _i;
    return 0;
}
static PyObject *
Synth_get_freq(SynthObject *self, void *closure)
{
    (void)closure;
    if (self->src.ranged & WFM_RANGE_FREQ)
        return Py_BuildValue("(dd)", (double)self->src.freq,
                             (double)self->src.freq_hi);
    return PyFloat_FromDouble((double)self->src.freq);
}
static int
Synth_set_freq(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    double _lo, _hi;
    int    _r;
    if (!_jm_parse_range(value, &_lo, &_hi, &_r))
        return -1;
    self->src.freq = (double)_lo;
    if (_r) {
        self->src.freq_hi = (double)_hi;
        self->src.ranged |= WFM_RANGE_FREQ;
    } else {
        self->src.ranged &= ~(unsigned)WFM_RANGE_FREQ;
    }
    return 0;
}
static PyObject *
Synth_get_snr(SynthObject *self, void *closure)
{
    (void)closure;
    if (self->src.ranged & WFM_RANGE_SNR)
        return Py_BuildValue("(dd)", (double)self->src.snr,
                             (double)self->src.snr_hi);
    return PyFloat_FromDouble((double)self->src.snr);
}
static int
Synth_set_snr(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    double _lo, _hi;
    int    _r;
    if (!_jm_parse_range(value, &_lo, &_hi, &_r))
        return -1;
    self->src.snr = (double)_lo;
    if (_r) {
        self->src.snr_hi = (double)_hi;
        self->src.ranged |= WFM_RANGE_SNR;
    } else {
        self->src.ranged &= ~(unsigned)WFM_RANGE_SNR;
    }
    return 0;
}
static PyObject *
Synth_get_snr_mode(SynthObject *self, void *closure)
{
    (void)closure;
    return PyUnicode_FromString(_enum_snr_mode[self->src.snr_mode]);
}
static int
Synth_set_snr_mode(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    const char *s = PyUnicode_AsUTF8(value);
    if (!s) return -1;
    int _i = _enum_index(_enum_snr_mode, s);
    if (_i < 0) {
        PyErr_Format(PyExc_ValueError, "invalid snr_mode '%s'", s);
        return -1;
    }
    self->src.snr_mode = _i;
    return 0;
}
static PyObject *
Synth_get_seed(SynthObject *self, void *closure)
{
    (void)closure;
    return PyLong_FromUnsignedLong((unsigned long)self->src.seed);
}
static int
Synth_set_seed(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    self->src.seed = (uint32_t)PyLong_AsLong(value);
    if (PyErr_Occurred()) return -1;
    return 0;
}
static PyObject *
Synth_get_sps(SynthObject *self, void *closure)
{
    (void)closure;
    return PyLong_FromLong((long)self->src.sps);
}
static int
Synth_set_sps(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    self->src.sps = (int)PyLong_AsLong(value);
    if (PyErr_Occurred()) return -1;
    return 0;
}
static PyObject *
Synth_get_pn_length(SynthObject *self, void *closure)
{
    (void)closure;
    return PyLong_FromLong((long)self->src.pn_length);
}
static int
Synth_set_pn_length(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    self->src.pn_length = (int)PyLong_AsLong(value);
    if (PyErr_Occurred()) return -1;
    return 0;
}
static PyObject *
Synth_get_pn_poly(SynthObject *self, void *closure)
{
    (void)closure;
    return PyLong_FromUnsignedLongLong((unsigned long long)self->src.pn_poly);
}
static int
Synth_set_pn_poly(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    self->src.pn_poly = (uint64_t)PyLong_AsUnsignedLongLong(value);
    if (PyErr_Occurred()) return -1;
    return 0;
}
static PyObject *
Synth_get_lfsr(SynthObject *self, void *closure)
{
    (void)closure;
    return PyUnicode_FromString(_enum_wfm_lfsr[self->src.lfsr]);
}
static int
Synth_set_lfsr(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    const char *s = PyUnicode_AsUTF8(value);
    if (!s) return -1;
    int _i = _enum_index(_enum_wfm_lfsr, s);
    if (_i < 0) {
        PyErr_Format(PyExc_ValueError, "invalid lfsr '%s'", s);
        return -1;
    }
    self->src.lfsr = _i;
    return 0;
}
static PyObject *
Synth_get_level(SynthObject *self, void *closure)
{
    (void)closure;
    if (self->src.ranged & WFM_RANGE_LEVEL)
        return Py_BuildValue("(dd)", (double)self->src.level,
                             (double)self->src.level_hi);
    return PyFloat_FromDouble((double)self->src.level);
}
static int
Synth_set_level(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    double _lo, _hi;
    int    _r;
    if (!_jm_parse_range(value, &_lo, &_hi, &_r))
        return -1;
    self->src.level = (double)_lo;
    if (_r) {
        self->src.level_hi = (double)_hi;
        self->src.ranged |= WFM_RANGE_LEVEL;
    } else {
        self->src.ranged &= ~(unsigned)WFM_RANGE_LEVEL;
    }
    return 0;
}
static PyObject *
Synth_get_f_end(SynthObject *self, void *closure)
{
    (void)closure;
    if (self->src.ranged & WFM_RANGE_FEND)
        return Py_BuildValue("(dd)", (double)self->src.f_end,
                             (double)self->src.f_end_hi);
    return PyFloat_FromDouble((double)self->src.f_end);
}
static int
Synth_set_f_end(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    double _lo, _hi;
    int    _r;
    if (!_jm_parse_range(value, &_lo, &_hi, &_r))
        return -1;
    self->src.f_end = (double)_lo;
    if (_r) {
        self->src.f_end_hi = (double)_hi;
        self->src.ranged |= WFM_RANGE_FEND;
    } else {
        self->src.ranged &= ~(unsigned)WFM_RANGE_FEND;
    }
    return 0;
}
static PyObject *
Synth_get_bits(SynthObject *self, void *closure)
{
    (void)closure;
    if (self->src.bits && self->src.n_bits)
        return PyBytes_FromStringAndSize(
            (const char *)self->src.bits, (Py_ssize_t)self->src.n_bits);
    Py_RETURN_NONE;
}
static int
Synth_set_bits(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    return _attach_bytes(&self->src.bits, &self->src.n_bits, value) ? 0 : -1;
}
static PyObject *
Synth_get_modulation(SynthObject *self, void *closure)
{
    (void)closure;
    return PyUnicode_FromString(_enum_bitmod[self->src.modulation]);
}
static int
Synth_set_modulation(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    const char *s = PyUnicode_AsUTF8(value);
    if (!s) return -1;
    int _i = _enum_index(_enum_bitmod, s);
    if (_i < 0) {
        PyErr_Format(PyExc_ValueError, "invalid modulation '%s'", s);
        return -1;
    }
    self->src.modulation = _i;
    return 0;
}
static PyObject *
Synth_get_pulse(SynthObject *self, void *closure)
{
    (void)closure;
    return PyUnicode_FromString(_enum_wfm_pulse[self->src.pulse]);
}
static int
Synth_set_pulse(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    const char *s = PyUnicode_AsUTF8(value);
    if (!s) return -1;
    int _i = _enum_index(_enum_wfm_pulse, s);
    if (_i < 0) {
        PyErr_Format(PyExc_ValueError, "invalid pulse '%s'", s);
        return -1;
    }
    self->src.pulse = _i;
    return 0;
}
static PyObject *
Synth_get_rrc_beta(SynthObject *self, void *closure)
{
    (void)closure;
    return PyFloat_FromDouble((double)self->src.rrc_beta);
}
static int
Synth_set_rrc_beta(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    self->src.rrc_beta = (double)PyFloat_AsDouble(value);
    if (PyErr_Occurred()) return -1;
    return 0;
}
static PyObject *
Synth_get_rrc_span(SynthObject *self, void *closure)
{
    (void)closure;
    return PyLong_FromLong((long)self->src.rrc_span);
}
static int
Synth_set_rrc_span(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    self->src.rrc_span = (int)PyLong_AsLong(value);
    if (PyErr_Occurred()) return -1;
    return 0;
}
static PyObject *
Synth_get_symbols(SynthObject *self, void *closure)
{
    (void)closure;
    if (self->src.symbols && self->src.n_symbols) {
        npy_intp _d[1] = {(npy_intp)self->src.n_symbols};
        PyObject *_a = PyArray_SimpleNew(1, _d, NPY_COMPLEX64);
        if (!_a) return NULL;
        memcpy(PyArray_DATA((PyArrayObject *)_a), self->src.symbols,
               self->src.n_symbols * sizeof(float _Complex));
        return _a;
    }
    Py_RETURN_NONE;
}
static int
Synth_set_symbols(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    return _attach_symbols(&self->src, value) ? 0 : -1;
}
static PyObject *
Synth_get_acq_code(SynthObject *self, void *closure)
{
    (void)closure;
    if (self->src.acq_code && self->src.n_acq_code)
        return PyBytes_FromStringAndSize(
            (const char *)self->src.acq_code, (Py_ssize_t)self->src.n_acq_code);
    Py_RETURN_NONE;
}
static int
Synth_set_acq_code(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    return _attach_bytes(&self->src.acq_code, &self->src.n_acq_code, value) ? 0 : -1;
}
static PyObject *
Synth_get_acq_reps(SynthObject *self, void *closure)
{
    (void)closure;
    return PyLong_FromSize_t((size_t)self->src.acq_reps);
}
static int
Synth_set_acq_reps(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    self->src.acq_reps = (size_t)PyLong_AsLong(value);
    if (PyErr_Occurred()) return -1;
    return 0;
}
static PyObject *
Synth_get_data_code(SynthObject *self, void *closure)
{
    (void)closure;
    if (self->src.data_code && self->src.n_data_code)
        return PyBytes_FromStringAndSize(
            (const char *)self->src.data_code, (Py_ssize_t)self->src.n_data_code);
    Py_RETURN_NONE;
}
static int
Synth_set_data_code(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    return _attach_bytes(&self->src.data_code, &self->src.n_data_code, value) ? 0 : -1;
}
static PyObject *
Synth_get_sync(SynthObject *self, void *closure)
{
    (void)closure;
    if (self->src.sync && self->src.n_sync)
        return PyBytes_FromStringAndSize(
            (const char *)self->src.sync, (Py_ssize_t)self->src.n_sync);
    Py_RETURN_NONE;
}
static int
Synth_set_sync(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    return _attach_bytes(&self->src.sync, &self->src.n_sync, value) ? 0 : -1;
}
static PyObject *
Synth_get_crc(SynthObject *self, void *closure)
{
    (void)closure;
    return PyUnicode_FromString(_enum_crc[self->src.crc]);
}
static int
Synth_set_crc(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    const char *s = PyUnicode_AsUTF8(value);
    if (!s) return -1;
    int _i = _enum_index(_enum_crc, s);
    if (_i < 0) {
        PyErr_Format(PyExc_ValueError, "invalid crc '%s'", s);
        return -1;
    }
    self->src.crc = _i;
    return 0;
}
static PyObject *
Synth_get_symbol_rate(SynthObject *self, void *closure)
{
    (void)closure;
    return PyFloat_FromDouble((double)self->src.symbol_rate);
}
static int
Synth_set_symbol_rate(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    self->src.symbol_rate = (double)PyFloat_AsDouble(value);
    if (PyErr_Occurred()) return -1;
    return 0;
}
static PyObject *
Synth_get_dsss_code_only(SynthObject *self, void *closure)
{
    (void)closure;
    return PyLong_FromLong((long)self->src.dsss_code_only);
}
static int
Synth_set_dsss_code_only(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    self->src.dsss_code_only = (int)PyLong_AsLong(value);
    if (PyErr_Occurred()) return -1;
    return 0;
}
static PyObject *
Synth_get_fs(SynthObject *self, void *closure)
{
    (void)closure;
    return PyFloat_FromDouble(self->fs);
}
static int
Synth_set_fs(SynthObject *self, PyObject *value, void *closure)
{
    (void)closure;
    self->fs = PyFloat_AsDouble(value);
    if (PyErr_Occurred()) return -1;
    return 0;
}

static PyGetSetDef Synth_getset[] = {
    {"type", (getter)Synth_get_type, (setter)Synth_set_type, NULL, NULL},
    {"freq", (getter)Synth_get_freq, (setter)Synth_set_freq, NULL, NULL},
    {"snr", (getter)Synth_get_snr, (setter)Synth_set_snr, NULL, NULL},
    {"snr_mode", (getter)Synth_get_snr_mode, (setter)Synth_set_snr_mode, NULL, NULL},
    {"seed", (getter)Synth_get_seed, (setter)Synth_set_seed, NULL, NULL},
    {"sps", (getter)Synth_get_sps, (setter)Synth_set_sps, NULL, NULL},
    {"pn_length", (getter)Synth_get_pn_length, (setter)Synth_set_pn_length, NULL, NULL},
    {"pn_poly", (getter)Synth_get_pn_poly, (setter)Synth_set_pn_poly, NULL, NULL},
    {"lfsr", (getter)Synth_get_lfsr, (setter)Synth_set_lfsr, NULL, NULL},
    {"level", (getter)Synth_get_level, (setter)Synth_set_level, NULL, NULL},
    {"f_end", (getter)Synth_get_f_end, (setter)Synth_set_f_end, NULL, NULL},
    {"bits", (getter)Synth_get_bits, (setter)Synth_set_bits, NULL, NULL},
    {"modulation", (getter)Synth_get_modulation, (setter)Synth_set_modulation, NULL, NULL},
    {"pulse", (getter)Synth_get_pulse, (setter)Synth_set_pulse, NULL, NULL},
    {"rrc_beta", (getter)Synth_get_rrc_beta, (setter)Synth_set_rrc_beta, NULL, NULL},
    {"rrc_span", (getter)Synth_get_rrc_span, (setter)Synth_set_rrc_span, NULL, NULL},
    {"symbols", (getter)Synth_get_symbols, (setter)Synth_set_symbols, NULL, NULL},
    {"acq_code", (getter)Synth_get_acq_code, (setter)Synth_set_acq_code, NULL, NULL},
    {"acq_reps", (getter)Synth_get_acq_reps, (setter)Synth_set_acq_reps, NULL, NULL},
    {"data_code", (getter)Synth_get_data_code, (setter)Synth_set_data_code, NULL, NULL},
    {"sync", (getter)Synth_get_sync, (setter)Synth_set_sync, NULL, NULL},
    {"crc", (getter)Synth_get_crc, (setter)Synth_set_crc, NULL, NULL},
    {"symbol_rate", (getter)Synth_get_symbol_rate, (setter)Synth_set_symbol_rate, NULL, NULL},
    {"dsss_code_only", (getter)Synth_get_dsss_code_only, (setter)Synth_set_dsss_code_only, NULL, NULL},
    {"fs", (getter)Synth_get_fs, (setter)Synth_set_fs, NULL, NULL},
    {NULL, NULL, NULL, NULL, NULL}
};

/* Lazily build the composed generator from this source's config. */
static int
Synth_ensure_gen(SynthObject *self)
{
    if (!self->_gen) {
        self->_gen = wfm_source_to_synth(&self->src, self->fs);
        if (!self->_gen) {
            PyErr_SetString(PyExc_RuntimeError,
                            "wfm_source_to_synth returned NULL");
            return -1;
        }
    }
    return 0;
}

static PyObject *
Synth_steps(SynthObject *self, PyObject *args)
{
    Py_ssize_t n;
    if (!PyArg_ParseTuple(args, "n", &n))
        return NULL;
    if (n < 0) {
        PyErr_SetString(PyExc_ValueError, "n must be >= 0");
        return NULL;
    }
    if (Synth_ensure_gen(self) < 0)
        return NULL;
    npy_intp dims[1] = { n };
    PyObject *arr = PyArray_SimpleNew(1, dims, NPY_COMPLEX64);
    if (!arr)
        return NULL;
    float complex *out = (float complex *)PyArray_DATA((PyArrayObject *)arr);
    Py_BEGIN_ALLOW_THREADS
    wfm_synth_steps(self->_gen, out, (size_t)n);
    Py_END_ALLOW_THREADS
    return arr;
}

static PyObject *
Synth_step(SynthObject *self, PyObject *Py_UNUSED(ignored))
{
    if (Synth_ensure_gen(self) < 0)
        return NULL;
    float complex y = wfm_synth_step(self->_gen);
    return PyComplex_FromDoubles(crealf(y), cimagf(y));
}

static PyObject *
Synth_reset(SynthObject *self, PyObject *Py_UNUSED(ignored))
{
    if (self->_gen)
        wfm_synth_reset(self->_gen);
    Py_RETURN_NONE;
}

static PyMethodDef Synth_methods[] = {
    {"steps", (PyCFunction)Synth_steps, METH_VARARGS,
     "steps(n) -> complex64[n] — generate n samples standalone."},
    {"step", (PyCFunction)Synth_step, METH_NOARGS,
     "step() -> complex — generate one sample standalone."},
    {"reset", (PyCFunction)Synth_reset, METH_NOARGS,
     "reset() -> None — rewind the generator to sample 0."},
    {NULL, NULL, 0, NULL}
};

static PyTypeObject SynthType = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name      = "doppler.wfm.Synth",
    .tp_basicsize = sizeof(SynthObject),
    .tp_flags     = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
    .tp_new       = PyType_GenericNew,
    .tp_init      = (initproc)Synth_init,
    .tp_dealloc   = (destructor)Synth_dealloc,
    .tp_getset    = Synth_getset,
    .tp_methods   = Synth_methods,
    .tp_doc       = PyDoc_STR("Synth — one composable source configuration."),
};

/* Factory shared body: inject {type: <name>} into kwds, call the type. */
static PyObject *
_Synth_factory(const char *kind, PyObject *args, PyObject *kwds)
{
    PyObject *k = kwds ? PyDict_Copy(kwds) : PyDict_New();
    if (!k) return NULL;
    PyObject *v = PyUnicode_FromString(kind);
    if (!v || PyDict_SetItemString(k, "type", v) < 0) {
        Py_XDECREF(v);
        Py_DECREF(k);
        return NULL;
    }
    Py_DECREF(v);
    PyObject *r = PyObject_Call((PyObject *)&SynthType, args, k);
    Py_DECREF(k);
    return r;
}

static PyObject *
_factory_tone(PyObject *mod, PyObject *args, PyObject *kwds)
{
    (void)mod;
    return _Synth_factory("tone", args, kwds);
}

static PyObject *
_factory_noise(PyObject *mod, PyObject *args, PyObject *kwds)
{
    (void)mod;
    return _Synth_factory("noise", args, kwds);
}

static PyObject *
_factory_pn(PyObject *mod, PyObject *args, PyObject *kwds)
{
    (void)mod;
    return _Synth_factory("pn", args, kwds);
}

static PyObject *
_factory_bpsk(PyObject *mod, PyObject *args, PyObject *kwds)
{
    (void)mod;
    return _Synth_factory("bpsk", args, kwds);
}

static PyObject *
_factory_qpsk(PyObject *mod, PyObject *args, PyObject *kwds)
{
    (void)mod;
    return _Synth_factory("qpsk", args, kwds);
}

static PyObject *
_factory_chirp(PyObject *mod, PyObject *args, PyObject *kwds)
{
    (void)mod;
    return _Synth_factory("chirp", args, kwds);
}

static PyObject *
_factory_bits(PyObject *mod, PyObject *args, PyObject *kwds)
{
    (void)mod;
    return _Synth_factory("bits", args, kwds);
}

static PyTypeObject SegmentType;

static PyTypeObject TimelineType;

typedef struct {
    PyObject_HEAD
    PyObject *sources;   /* list of Synth, length >= 1 */
    double fs;
    size_t num_samples;
    size_t off_samples;
    size_t repeats;
    size_t delay_samples;
    int gap_noise;
    unsigned ranged;
    size_t num_samples_hi;
    size_t off_samples_hi;
    size_t delay_samples_hi;
} SegmentObject;

static void
Segment_dealloc(SegmentObject *self)
{
    Py_XDECREF(self->sources);
    Py_TYPE(self)->tp_free((PyObject *)self);
}

static int
Segment_init(SegmentObject *self, PyObject *args, PyObject *kwds)
{
    self->fs = 1.0;
    self->num_samples = 1024;
    self->off_samples = 0;
    self->repeats = 1;
    self->delay_samples = 0;
    self->gap_noise = 0;
    self->ranged = 0;
    self->num_samples_hi = 0;
    self->off_samples_hi = 0;
    self->delay_samples_hi = 0;
    PyObject *kw = kwds ? PyDict_Copy(kwds) : PyDict_New();
    if (!kw)
        return -1;
    {
        PyObject *_o = PyDict_GetItemString(kw, "fs");
        if (_o) {
            self->fs = (double)PyFloat_AsDouble(_o);
            if (PyErr_Occurred()) goto fail;
        if (PyDict_DelItemString(kw, "fs") < 0) goto fail;
        }
    }
    {
        PyObject *_o = PyDict_GetItemString(kw, "num_samples");
        if (_o) {
            double _lo, _hi;
            int    _r;
            if (!_jm_parse_range(_o, &_lo, &_hi, &_r))
                goto fail;
            self->num_samples = (size_t)_lo;
            if (_r) { self->num_samples_hi = (size_t)_hi; self->ranged |= WFM_RANGE_NUM_SAMPLES; }
            else { self->ranged &= ~(unsigned)WFM_RANGE_NUM_SAMPLES; }
        if (PyDict_DelItemString(kw, "num_samples") < 0) goto fail;
        }
    }
    {
        PyObject *_o = PyDict_GetItemString(kw, "off_samples");
        if (_o) {
            double _lo, _hi;
            int    _r;
            if (!_jm_parse_range(_o, &_lo, &_hi, &_r))
                goto fail;
            self->off_samples = (size_t)_lo;
            if (_r) { self->off_samples_hi = (size_t)_hi; self->ranged |= WFM_RANGE_OFF_SAMPLES; }
            else { self->ranged &= ~(unsigned)WFM_RANGE_OFF_SAMPLES; }
        if (PyDict_DelItemString(kw, "off_samples") < 0) goto fail;
        }
    }
    {
        PyObject *_o = PyDict_GetItemString(kw, "repeats");
        if (_o) {
            self->repeats = (size_t)PyLong_AsSize_t(_o);
            if (PyErr_Occurred()) goto fail;
        if (PyDict_DelItemString(kw, "repeats") < 0) goto fail;
        }
    }
    {
        PyObject *_o = PyDict_GetItemString(kw, "delay_samples");
        if (_o) {
            double _lo, _hi;
            int    _r;
            if (!_jm_parse_range(_o, &_lo, &_hi, &_r))
                goto fail;
            self->delay_samples = (size_t)_lo;
            if (_r) { self->delay_samples_hi = (size_t)_hi; self->ranged |= WFM_RANGE_DELAY_SAMPLES; }
            else { self->ranged &= ~(unsigned)WFM_RANGE_DELAY_SAMPLES; }
        if (PyDict_DelItemString(kw, "delay_samples") < 0) goto fail;
        }
    }
    {
        PyObject *_o = PyDict_GetItemString(kw, "gap_noise");
        if (_o) {
            const char *_s = PyUnicode_AsUTF8(_o);
            if (!_s) goto fail;
            int _i = _enum_index(_enum_gap_noise, _s);
            if (_i < 0) {
                PyErr_Format(PyExc_ValueError,
                             "invalid gap_noise '%s'", _s);
                goto fail;
            }
            self->gap_noise = _i;
        if (PyDict_DelItemString(kw, "gap_noise") < 0) goto fail;
        }
    }
    PyObject *one = PyObject_Call((PyObject *)&SynthType, args, kw);
    Py_DECREF(kw);
    if (!one)
        return -1;
    PyObject *list = PyList_New(1);
    if (!list) {
        Py_DECREF(one);
        return -1;
    }
    PyList_SET_ITEM(list, 0, one); /* steals */
    Py_XSETREF(self->sources, list);
    return 0;
fail:
    Py_DECREF(kw);
    return -1;
}

static PyObject *
Segment_sum(PyObject *cls, PyObject *args, PyObject *kwds)
{
    (void)cls;
    Py_ssize_t nsrc = PyTuple_GET_SIZE(args);
    if (nsrc < 1) {
        PyErr_SetString(PyExc_ValueError,
                        "Segment.sum needs at least one source");
        return NULL;
    }
    PyObject *list = PyList_New(nsrc);
    if (!list)
        return NULL;
    for (Py_ssize_t i = 0; i < nsrc; i++) {
        PyObject *it = PyTuple_GET_ITEM(args, i);
        if (!PyObject_TypeCheck(it, &SynthType)) {
            PyErr_SetString(PyExc_TypeError,
                            "Segment.sum sources must be Synth");
            Py_DECREF(list);
            return NULL;
        }
        Py_INCREF(it);
        PyList_SET_ITEM(list, i, it);
    }
    SegmentObject *self = (SegmentObject *)SegmentType.tp_alloc(&SegmentType, 0);
    if (!self) {
        Py_DECREF(list);
        return NULL;
    }
    self->sources = list;
    self->fs = 1.0;
    self->num_samples = 1024;
    self->off_samples = 0;
    self->repeats = 1;
    self->delay_samples = 0;
    self->gap_noise = 0;
    self->ranged = 0;
    self->num_samples_hi = 0;
    self->off_samples_hi = 0;
    self->delay_samples_hi = 0;
    PyObject *kw = kwds; /* borrowed; read-only */
    if (kw) {
    {
        PyObject *_o = PyDict_GetItemString(kw, "fs");
        if (_o) {
            self->fs = (double)PyFloat_AsDouble(_o);
            if (PyErr_Occurred()) goto fail;
        }
    }
    {
        PyObject *_o = PyDict_GetItemString(kw, "num_samples");
        if (_o) {
            double _lo, _hi;
            int    _r;
            if (!_jm_parse_range(_o, &_lo, &_hi, &_r))
                goto fail;
            self->num_samples = (size_t)_lo;
            if (_r) { self->num_samples_hi = (size_t)_hi; self->ranged |= WFM_RANGE_NUM_SAMPLES; }
            else { self->ranged &= ~(unsigned)WFM_RANGE_NUM_SAMPLES; }
        }
    }
    {
        PyObject *_o = PyDict_GetItemString(kw, "off_samples");
        if (_o) {
            double _lo, _hi;
            int    _r;
            if (!_jm_parse_range(_o, &_lo, &_hi, &_r))
                goto fail;
            self->off_samples = (size_t)_lo;
            if (_r) { self->off_samples_hi = (size_t)_hi; self->ranged |= WFM_RANGE_OFF_SAMPLES; }
            else { self->ranged &= ~(unsigned)WFM_RANGE_OFF_SAMPLES; }
        }
    }
    {
        PyObject *_o = PyDict_GetItemString(kw, "repeats");
        if (_o) {
            self->repeats = (size_t)PyLong_AsSize_t(_o);
            if (PyErr_Occurred()) goto fail;
        }
    }
    {
        PyObject *_o = PyDict_GetItemString(kw, "delay_samples");
        if (_o) {
            double _lo, _hi;
            int    _r;
            if (!_jm_parse_range(_o, &_lo, &_hi, &_r))
                goto fail;
            self->delay_samples = (size_t)_lo;
            if (_r) { self->delay_samples_hi = (size_t)_hi; self->ranged |= WFM_RANGE_DELAY_SAMPLES; }
            else { self->ranged &= ~(unsigned)WFM_RANGE_DELAY_SAMPLES; }
        }
    }
    {
        PyObject *_o = PyDict_GetItemString(kw, "gap_noise");
        if (_o) {
            const char *_s = PyUnicode_AsUTF8(_o);
            if (!_s) goto fail;
            int _i = _enum_index(_enum_gap_noise, _s);
            if (_i < 0) {
                PyErr_Format(PyExc_ValueError,
                             "invalid gap_noise '%s'", _s);
                goto fail;
            }
            self->gap_noise = _i;
        }
    }
    }
    return (PyObject *)self;
fail:
    Py_DECREF(self);
    return NULL;
}

static PyObject *
Segment_get_sources(SegmentObject *self, void *closure)
{
    (void)closure;
    Py_INCREF(self->sources);
    return self->sources;
}
static PyObject *
Segment_get_fs(SegmentObject *self, void *closure)
{
    (void)closure;
    return PyFloat_FromDouble((double)self->fs);
}
static int
Segment_set_fs(SegmentObject *self, PyObject *value, void *closure)
{
    (void)closure;
    self->fs = (double)PyFloat_AsDouble(value);
    if (PyErr_Occurred()) return -1;
    return 0;
}
static PyObject *
Segment_get_num_samples(SegmentObject *self, void *closure)
{
    (void)closure;
    if (self->ranged & WFM_RANGE_NUM_SAMPLES)
        return Py_BuildValue("(nn)", (Py_ssize_t)self->num_samples,
                             (Py_ssize_t)self->num_samples_hi);
    return PyLong_FromSize_t((size_t)self->num_samples);
}
static int
Segment_set_num_samples(SegmentObject *self, PyObject *value, void *closure)
{
    (void)closure;
    double _lo, _hi;
    int    _r;
    if (!_jm_parse_range(value, &_lo, &_hi, &_r))
        return -1;
    self->num_samples = (size_t)_lo;
    if (_r) {
        self->num_samples_hi = (size_t)_hi;
        self->ranged |= WFM_RANGE_NUM_SAMPLES;
    } else {
        self->ranged &= ~(unsigned)WFM_RANGE_NUM_SAMPLES;
    }
    return 0;
}
static PyObject *
Segment_get_off_samples(SegmentObject *self, void *closure)
{
    (void)closure;
    if (self->ranged & WFM_RANGE_OFF_SAMPLES)
        return Py_BuildValue("(nn)", (Py_ssize_t)self->off_samples,
                             (Py_ssize_t)self->off_samples_hi);
    return PyLong_FromSize_t((size_t)self->off_samples);
}
static int
Segment_set_off_samples(SegmentObject *self, PyObject *value, void *closure)
{
    (void)closure;
    double _lo, _hi;
    int    _r;
    if (!_jm_parse_range(value, &_lo, &_hi, &_r))
        return -1;
    self->off_samples = (size_t)_lo;
    if (_r) {
        self->off_samples_hi = (size_t)_hi;
        self->ranged |= WFM_RANGE_OFF_SAMPLES;
    } else {
        self->ranged &= ~(unsigned)WFM_RANGE_OFF_SAMPLES;
    }
    return 0;
}
static PyObject *
Segment_get_repeats(SegmentObject *self, void *closure)
{
    (void)closure;
    return PyLong_FromSize_t((size_t)self->repeats);
}
static int
Segment_set_repeats(SegmentObject *self, PyObject *value, void *closure)
{
    (void)closure;
    self->repeats = (size_t)PyLong_AsSize_t(value);
    if (PyErr_Occurred()) return -1;
    return 0;
}
static PyObject *
Segment_get_delay_samples(SegmentObject *self, void *closure)
{
    (void)closure;
    if (self->ranged & WFM_RANGE_DELAY_SAMPLES)
        return Py_BuildValue("(nn)", (Py_ssize_t)self->delay_samples,
                             (Py_ssize_t)self->delay_samples_hi);
    return PyLong_FromSize_t((size_t)self->delay_samples);
}
static int
Segment_set_delay_samples(SegmentObject *self, PyObject *value, void *closure)
{
    (void)closure;
    double _lo, _hi;
    int    _r;
    if (!_jm_parse_range(value, &_lo, &_hi, &_r))
        return -1;
    self->delay_samples = (size_t)_lo;
    if (_r) {
        self->delay_samples_hi = (size_t)_hi;
        self->ranged |= WFM_RANGE_DELAY_SAMPLES;
    } else {
        self->ranged &= ~(unsigned)WFM_RANGE_DELAY_SAMPLES;
    }
    return 0;
}
static PyObject *
Segment_get_gap_noise(SegmentObject *self, void *closure)
{
    (void)closure;
    return PyUnicode_FromString(_enum_gap_noise[self->gap_noise]);
}
static int
Segment_set_gap_noise(SegmentObject *self, PyObject *value, void *closure)
{
    (void)closure;
    const char *s = PyUnicode_AsUTF8(value);
    if (!s) return -1;
    int _i = _enum_index(_enum_gap_noise, s);
    if (_i < 0) {
        PyErr_Format(PyExc_ValueError, "invalid gap_noise '%s'", s);
        return -1;
    }
    self->gap_noise = _i;
    return 0;
}
static PyObject *
Segment_flat_type(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "type is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "type");
}
static PyObject *
Segment_flat_freq(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "freq is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "freq");
}
static PyObject *
Segment_flat_snr(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "snr is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "snr");
}
static PyObject *
Segment_flat_snr_mode(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "snr_mode is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "snr_mode");
}
static PyObject *
Segment_flat_seed(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "seed is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "seed");
}
static PyObject *
Segment_flat_sps(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "sps is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "sps");
}
static PyObject *
Segment_flat_pn_length(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "pn_length is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "pn_length");
}
static PyObject *
Segment_flat_pn_poly(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "pn_poly is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "pn_poly");
}
static PyObject *
Segment_flat_lfsr(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "lfsr is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "lfsr");
}
static PyObject *
Segment_flat_level(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "level is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "level");
}
static PyObject *
Segment_flat_f_end(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "f_end is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "f_end");
}
static PyObject *
Segment_flat_bits(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "bits is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "bits");
}
static PyObject *
Segment_flat_modulation(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "modulation is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "modulation");
}
static PyObject *
Segment_flat_pulse(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "pulse is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "pulse");
}
static PyObject *
Segment_flat_rrc_beta(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "rrc_beta is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "rrc_beta");
}
static PyObject *
Segment_flat_rrc_span(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "rrc_span is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "rrc_span");
}
static PyObject *
Segment_flat_symbols(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "symbols is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "symbols");
}
static PyObject *
Segment_flat_acq_code(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "acq_code is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "acq_code");
}
static PyObject *
Segment_flat_acq_reps(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "acq_reps is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "acq_reps");
}
static PyObject *
Segment_flat_data_code(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "data_code is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "data_code");
}
static PyObject *
Segment_flat_sync(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "sync is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "sync");
}
static PyObject *
Segment_flat_crc(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "crc is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "crc");
}
static PyObject *
Segment_flat_symbol_rate(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "symbol_rate is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "symbol_rate");
}
static PyObject *
Segment_flat_dsss_code_only(SegmentObject *self, void *closure)
{
    (void)closure;
    if (PyList_GET_SIZE(self->sources) != 1) {
        PyErr_SetString(PyExc_AttributeError,
                        "dsss_code_only is only on a single-source Segment");
        return NULL;
    }
    return PyObject_GetAttrString(PyList_GET_ITEM(self->sources, 0), "dsss_code_only");
}

static PyObject *
Segment_add(SegmentObject *self, PyObject *args)
{
    Py_ssize_t n = PyTuple_GET_SIZE(args);
    PyObject *list = PyList_New(n + 1);
    if (!list)
        return NULL;
    Py_INCREF(self);
    PyList_SET_ITEM(list, 0, (PyObject *)self);
    for (Py_ssize_t i = 0; i < n; i++) {
        PyObject *it = PyTuple_GET_ITEM(args, i);
        Py_INCREF(it);
        PyList_SET_ITEM(list, i + 1, it);
    }
    PyObject *tl =
        PyObject_CallFunctionObjArgs((PyObject *)&TimelineType, list, NULL);
    Py_DECREF(list);
    return tl;
}


static PyGetSetDef Segment_getset[] = {
    {"sources", (getter)Segment_get_sources, NULL, NULL, NULL},
    {"fs", (getter)Segment_get_fs, (setter)Segment_set_fs, NULL, NULL},
    {"num_samples", (getter)Segment_get_num_samples, (setter)Segment_set_num_samples, NULL, NULL},
    {"off_samples", (getter)Segment_get_off_samples, (setter)Segment_set_off_samples, NULL, NULL},
    {"repeats", (getter)Segment_get_repeats, (setter)Segment_set_repeats, NULL, NULL},
    {"delay_samples", (getter)Segment_get_delay_samples, (setter)Segment_set_delay_samples, NULL, NULL},
    {"gap_noise", (getter)Segment_get_gap_noise, (setter)Segment_set_gap_noise, NULL, NULL},
    {"type", (getter)Segment_flat_type, NULL, NULL, NULL},
    {"freq", (getter)Segment_flat_freq, NULL, NULL, NULL},
    {"snr", (getter)Segment_flat_snr, NULL, NULL, NULL},
    {"snr_mode", (getter)Segment_flat_snr_mode, NULL, NULL, NULL},
    {"seed", (getter)Segment_flat_seed, NULL, NULL, NULL},
    {"sps", (getter)Segment_flat_sps, NULL, NULL, NULL},
    {"pn_length", (getter)Segment_flat_pn_length, NULL, NULL, NULL},
    {"pn_poly", (getter)Segment_flat_pn_poly, NULL, NULL, NULL},
    {"lfsr", (getter)Segment_flat_lfsr, NULL, NULL, NULL},
    {"level", (getter)Segment_flat_level, NULL, NULL, NULL},
    {"f_end", (getter)Segment_flat_f_end, NULL, NULL, NULL},
    {"bits", (getter)Segment_flat_bits, NULL, NULL, NULL},
    {"modulation", (getter)Segment_flat_modulation, NULL, NULL, NULL},
    {"pulse", (getter)Segment_flat_pulse, NULL, NULL, NULL},
    {"rrc_beta", (getter)Segment_flat_rrc_beta, NULL, NULL, NULL},
    {"rrc_span", (getter)Segment_flat_rrc_span, NULL, NULL, NULL},
    {"symbols", (getter)Segment_flat_symbols, NULL, NULL, NULL},
    {"acq_code", (getter)Segment_flat_acq_code, NULL, NULL, NULL},
    {"acq_reps", (getter)Segment_flat_acq_reps, NULL, NULL, NULL},
    {"data_code", (getter)Segment_flat_data_code, NULL, NULL, NULL},
    {"sync", (getter)Segment_flat_sync, NULL, NULL, NULL},
    {"crc", (getter)Segment_flat_crc, NULL, NULL, NULL},
    {"symbol_rate", (getter)Segment_flat_symbol_rate, NULL, NULL, NULL},
    {"dsss_code_only", (getter)Segment_flat_dsss_code_only, NULL, NULL, NULL},
    {NULL, NULL, NULL, NULL, NULL}
};

static PyMethodDef Segment_methods[] = {
    {"sum", (PyCFunction)(void (*)(void))Segment_sum,
     METH_VARARGS | METH_KEYWORDS | METH_CLASS,
     "sum(*sources, **segment_fields) -> Segment"},
    {"add", (PyCFunction)Segment_add, METH_VARARGS,
     "add(*others) -> Timeline"},
    {NULL, NULL, 0, NULL}
};

static PyTypeObject SegmentType = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name      = "doppler.wfm.Segment",
    .tp_basicsize = sizeof(SegmentObject),
    .tp_flags     = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
    .tp_new       = PyType_GenericNew,
    .tp_init      = (initproc)Segment_init,
    .tp_dealloc   = (destructor)Segment_dealloc,
    .tp_getset    = Segment_getset,
    .tp_methods   = Segment_methods,
    .tp_doc       = PyDoc_STR(
        "Segment — one segment: a list of sources + its span."),
};

typedef struct {
    PyObject_HEAD
    PyObject *segments;   /* a Python list */
} TimelineObject;

static void
Timeline_dealloc(TimelineObject *self)
{
    Py_XDECREF(self->segments);
    Py_TYPE(self)->tp_free((PyObject *)self);
}

static int
Timeline_init(TimelineObject *self, PyObject *args, PyObject *kwds)
{
    static char *kwlist[] = {"segments", NULL};
    PyObject *seq;
    if (!PyArg_ParseTupleAndKeywords(args, kwds, "O", kwlist, &seq))
        return -1;
    PyObject *list = PySequence_List(seq); /* copies; accepts any iterable */
    if (!list)
        return -1;
    Py_XSETREF(self->segments, list);
    return 0;
}

static PyObject *
Timeline_add(TimelineObject *self, PyObject *args)
{
    Py_ssize_t n = PyTuple_GET_SIZE(args);
    for (Py_ssize_t i = 0; i < n; i++)
        if (PyList_Append(self->segments, PyTuple_GET_ITEM(args, i)) < 0)
            return NULL;
    Py_INCREF(self);
    return (PyObject *)self;
}

static PyObject *
Timeline_get_segments(TimelineObject *self, void *closure)
{
    (void)closure;
    Py_INCREF(self->segments);
    return self->segments;
}

static Py_ssize_t
Timeline_length(TimelineObject *self)
{
    return PyList_GET_SIZE(self->segments);
}

static PyObject *
Timeline_subscript(TimelineObject *self, PyObject *key)
{
    return PyObject_GetItem(self->segments, key);
}

static PyObject *
Timeline_iter(TimelineObject *self)
{
    return PyObject_GetIter(self->segments);
}

static PyMappingMethods Timeline_as_mapping = {
    .mp_length    = (lenfunc)Timeline_length,
    .mp_subscript = (binaryfunc)Timeline_subscript,
};

static PyGetSetDef Timeline_getset[] = {
    {"segments", (getter)Timeline_get_segments, NULL, NULL, NULL},
    {NULL, NULL, NULL, NULL, NULL}
};

static PyMethodDef Timeline_methods[] = {
    {"add", (PyCFunction)Timeline_add, METH_VARARGS,
     "add(*segments) -> Timeline"},
    {NULL, NULL, 0, NULL}
};

static PyTypeObject TimelineType = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name      = "doppler.wfm.Timeline",
    .tp_basicsize = sizeof(TimelineObject),
    .tp_flags     = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
    .tp_new       = PyType_GenericNew,
    .tp_init      = (initproc)Timeline_init,
    .tp_dealloc   = (destructor)Timeline_dealloc,
    .tp_iter      = (getiterfunc)Timeline_iter,
    .tp_as_mapping = &Timeline_as_mapping,
    .tp_getset    = Timeline_getset,
    .tp_methods   = Timeline_methods,
    .tp_doc       = PyDoc_STR("Timeline — segments played back-to-back."),
};

static PyTypeObject ComposerType; /* fwd: from_json/from_file alloc */

typedef struct {
    PyObject_HEAD
    wfm_compose_state_t *state;
    int                destroyed;
} ComposerObject;

/* Build a transient wfm_segment_t[] from a list of Segment objects. Each
 * source's bits pointer ALIASES the Synth's owned buffer; wfm_compose_create
 * deep-copies it, so we free only these transient arrays afterwards. */
static wfm_segment_t *
_build_wfm_compose_segments(PyObject *seglist, size_t *n_out)
{
    Py_ssize_t nseg = PyList_GET_SIZE(seglist);
    wfm_segment_t *segs = (wfm_segment_t *)calloc((size_t)nseg, sizeof *segs);
    if (!segs) {
        PyErr_NoMemory();
        return NULL;
    }
    for (Py_ssize_t i = 0; i < nseg; i++) {
        SegmentObject *seg = (SegmentObject *)PyList_GET_ITEM(seglist, i);
        Py_ssize_t ns = PyList_GET_SIZE(seg->sources);
        wfm_source_t *srcs =
            (wfm_source_t *)calloc((size_t)(ns ? ns : 1), sizeof *srcs);
        if (!srcs) {
            for (Py_ssize_t j = 0; j < i; j++)
                free(segs[j].sources);
            free(segs);
            PyErr_NoMemory();
            return NULL;
        }
        for (Py_ssize_t k = 0; k < ns; k++) {
            SynthObject *syn =
                (SynthObject *)PyList_GET_ITEM(seg->sources, k);
            srcs[k] = syn->src; /* scalars + aliased bits ptr */
        }
        segs[i].sources = srcs;
        segs[i].n_sources = (size_t)ns;
        segs[i].fs = seg->fs;
        segs[i].num_samples = seg->num_samples;
        segs[i].off_samples = seg->off_samples;
        segs[i].repeats = seg->repeats;
        segs[i].delay_samples = seg->delay_samples;
        segs[i].gap_noise = seg->gap_noise;
        segs[i].ranged = seg->ranged;
        segs[i].num_samples_hi = seg->num_samples_hi;
        segs[i].off_samples_hi = seg->off_samples_hi;
        segs[i].delay_samples_hi = seg->delay_samples_hi;
    }
    *n_out = (size_t)nseg;
    return segs;
}

static void
_free_wfm_compose_segments(wfm_segment_t *segs, size_t n)
{
    if (!segs)
        return;
    for (size_t i = 0; i < n; i++)
        free(segs[i].sources); /* NOT the bits — owned by Synth */
    free(segs);
}

/* Rebuild a list of Segment objects from a resolved wfm_segment_t[] (deep-copies
 * each source's bits so the new Synth objects own their own). */
static PyObject *
_wfm_compose_segments_to_list(const wfm_segment_t *src, size_t n)
{
    PyObject *list = PyList_New((Py_ssize_t)n);
    if (!list)
        return NULL;
    for (size_t i = 0; i < n; i++) {
        PyObject *srclist = PyList_New((Py_ssize_t)src[i].n_sources);
        if (!srclist) {
            Py_DECREF(list);
            return NULL;
        }
        for (size_t k = 0; k < src[i].n_sources; k++) {
            SynthObject *syn =
                (SynthObject *)SynthType.tp_alloc(&SynthType, 0);
            if (!syn) {
                Py_DECREF(srclist);
                Py_DECREF(list);
                return NULL;
            }
            syn->src = src[i].sources[k]; /* scalars + bits ptr */
            syn->fs = src[i].fs;
            if (syn->src.bits && syn->src.n_bits) {
                uint8_t *copy = (uint8_t *)malloc(syn->src.n_bits);
                if (copy)
                    memcpy(copy, syn->src.bits, syn->src.n_bits);
                syn->src.bits = copy;
            } else {
                syn->src.bits = NULL;
                syn->src.n_bits = 0;
            }
            PyList_SET_ITEM(srclist, (Py_ssize_t)k, (PyObject *)syn);
        }
        SegmentObject *sg =
            (SegmentObject *)SegmentType.tp_alloc(&SegmentType, 0);
        if (!sg) {
            Py_DECREF(srclist);
            Py_DECREF(list);
            return NULL;
        }
        sg->sources = srclist;
        sg->fs = src[i].fs;
        sg->num_samples = src[i].num_samples;
        sg->off_samples = src[i].off_samples;
        sg->repeats = src[i].repeats;
        sg->delay_samples = src[i].delay_samples;
        sg->gap_noise = src[i].gap_noise;
        sg->ranged = src[i].ranged;
        sg->num_samples_hi = src[i].num_samples_hi;
        sg->off_samples_hi = src[i].off_samples_hi;
        sg->delay_samples_hi = src[i].delay_samples_hi;
        PyList_SET_ITEM(list, (Py_ssize_t)i, (PyObject *)sg);
    }
    return list;
}

static void
Composer_dealloc(ComposerObject *self)
{
    if (!self->destroyed && self->state)
        wfm_compose_destroy(self->state);
    Py_TYPE(self)->tp_free((PyObject *)self);
}

static int
_pop_flag(PyObject *kw, const char *name, int *out)
{
    PyObject *o = PyDict_GetItemString(kw, name); /* borrowed */
    if (o) {
        int v = PyObject_IsTrue(o);
        if (v < 0)
            return -1;
        *out = v;
        if (PyDict_DelItemString(kw, name) < 0)
            return -1;
    }
    return 0;
}

static int
Composer_init(ComposerObject *self, PyObject *args, PyObject *kwds)
{
    self->state = NULL;
    self->destroyed = 0;
    int repeat = 0, continuous = 0;

    PyObject *kw = kwds ? PyDict_Copy(kwds) : PyDict_New();
    if (!kw)
        return -1;
    if (_pop_flag(kw, "repeat", &repeat) < 0 ||
        _pop_flag(kw, "continuous", &continuous) < 0) {
        Py_DECREF(kw);
        return -1;
    }

    PyObject *segments = NULL; /* borrowed */
    if (PyTuple_GET_SIZE(args) >= 1)
        segments = PyTuple_GET_ITEM(args, 0);
    {
        PyObject *o = PyDict_GetItemString(kw, "segments");
        if (o) {
            segments = o;
            if (PyDict_DelItemString(kw, "segments") < 0) {
                Py_DECREF(kw);
                return -1;
            }
        }
    }

    PyObject *seglist = NULL; /* owned list of Segment */
    if (segments == NULL || segments == Py_None) {
        /* Build a single Segment from the remaining keyword arguments. */
        PyObject *empty = PyTuple_New(0);
        PyObject *one = empty ? PyObject_Call((PyObject *)&SegmentType, empty, kw)
                              : NULL;
        Py_XDECREF(empty);
        Py_DECREF(kw);
        if (!one)
            return -1;
        seglist = PyList_New(1);
        if (!seglist) {
            Py_DECREF(one);
            return -1;
        }
        PyList_SET_ITEM(seglist, 0, one); /* steals */
    } else {
        if (PyDict_Size(kw) > 0) {
            PyErr_SetString(PyExc_TypeError,
                "pass either segments or single-segment kwargs, not both");
            Py_DECREF(kw);
            return -1;
        }
        Py_DECREF(kw);
        if (PyObject_TypeCheck(segments, &SegmentType)) {
            seglist = PyList_New(1);
            if (!seglist)
                return -1;
            Py_INCREF(segments);
            PyList_SET_ITEM(seglist, 0, segments);
        } else {
            seglist = PySequence_List(segments); /* iterates a Timeline/list */
            if (!seglist)
                return -1;
        }
    }

    Py_ssize_t nseg = PyList_GET_SIZE(seglist);
    if (nseg < 1) {
        PyErr_SetString(PyExc_ValueError, "need at least one segment");
        Py_DECREF(seglist);
        return -1;
    }
    for (Py_ssize_t i = 0; i < nseg; i++) {
        if (!PyObject_TypeCheck(PyList_GET_ITEM(seglist, i), &SegmentType)) {
            PyErr_SetString(PyExc_TypeError,
                            "segments must be Segment objects");
            Py_DECREF(seglist);
            return -1;
        }
    }

    size_t n;
    wfm_segment_t *segs = _build_wfm_compose_segments(seglist, &n);
    if (!segs) {
        Py_DECREF(seglist);
        return -1;
    }
    /* The transient segs' bits pointers ALIAS the Synth objects' buffers, so
     * seglist must outlive wfm_compose_create (which deep-copies them) — dropping it
     * earlier would, in the single-segment-kwargs path where seglist is the
     * sole owner, free the bits out from under the read. */
    self->state = wfm_compose_create(segs, n, repeat, continuous);
    _free_wfm_compose_segments(segs, n);
    Py_DECREF(seglist);
    if (!self->state) {
        PyErr_SetString(PyExc_ValueError, "wfm_compose_create failed");
        return -1;
    }
    return 0;
}

static PyObject *
Composer_execute(ComposerObject *self, PyObject *args)
{
    Py_ssize_t max;
    if (!PyArg_ParseTuple(args, "n", &max))
        return NULL;
    if (self->destroyed) {
        PyErr_SetString(PyExc_RuntimeError, "composer already closed");
        return NULL;
    }
    if (max < 0) {
        PyErr_SetString(PyExc_ValueError, "n must be >= 0");
        return NULL;
    }
    npy_intp dims[] = {max};
    PyObject *arr = PyArray_SimpleNew(1, dims, NPY_COMPLEX64);
    if (!arr)
        return NULL;
    float _Complex *out =
        (float _Complex *)PyArray_DATA((PyArrayObject *)arr);
    size_t got;
    Py_BEGIN_ALLOW_THREADS
    got = wfm_compose_execute(self->state, out, (size_t)max);
    Py_END_ALLOW_THREADS
    PyObject *stop = PyLong_FromSsize_t((Py_ssize_t)got);
    PyObject *slice = stop ? PySlice_New(NULL, stop, NULL) : NULL;
    Py_XDECREF(stop);
    PyObject *view = slice ? PyObject_GetItem(arr, slice) : NULL;
    Py_XDECREF(slice);
    Py_DECREF(arr);
    return view;
}

static PyObject *
Composer_compose(ComposerObject *self, PyObject *args, PyObject *kwds)
{
    static char *kwlist[] = {"block", NULL};
    Py_ssize_t block = 4096;
    if (!PyArg_ParseTupleAndKeywords(args, kwds, "|n", kwlist, &block))
        return NULL;
    if (self->destroyed) {
        PyErr_SetString(PyExc_RuntimeError, "composer already closed");
        return NULL;
    }
    {
        size_t n;
        int repeat = 0, continuous = 0;
        wfm_compose_segments(self->state, &n, &repeat, &continuous);
        if (continuous) {
            PyErr_SetString(PyExc_ValueError,
                "cannot compose() a continuous spec; use execute()");
            return NULL;
        }
    }
    PyObject *chunks = PyList_New(0);
    if (!chunks)
        return NULL;
    for (;;) {
        npy_intp dims[] = {block};
        PyObject *arr = PyArray_SimpleNew(1, dims, NPY_COMPLEX64);
        if (!arr) {
            Py_DECREF(chunks);
            return NULL;
        }
        float _Complex *out =
            (float _Complex *)PyArray_DATA((PyArrayObject *)arr);
        size_t got;
        Py_BEGIN_ALLOW_THREADS
        got = wfm_compose_execute(self->state, out, (size_t)block);
        Py_END_ALLOW_THREADS
        if (got == 0) {
            Py_DECREF(arr);
            break;
        }
        PyArray_DIMS((PyArrayObject *)arr)[0] = (npy_intp)got; /* trim view */
        if (PyList_Append(chunks, arr) < 0) {
            Py_DECREF(arr);
            Py_DECREF(chunks);
            return NULL;
        }
        Py_DECREF(arr);
        if (got < (size_t)block)
            break;
    }
    PyObject *result;
    if (PyList_GET_SIZE(chunks) == 0) {
        npy_intp z[] = {0};
        result = PyArray_SimpleNew(1, z, NPY_COMPLEX64);
    } else {
        result = PyArray_Concatenate(chunks, 0);
    }
    Py_DECREF(chunks);
    return result;
}

/* (segments, repeat, continuous) of the resolved spec. */
static PyObject *
_Composer_resolved(ComposerObject *self)
{
    if (self->destroyed) {
        PyErr_SetString(PyExc_RuntimeError, "composer already closed");
        return NULL;
    }
    size_t n;
    int repeat = 0, continuous = 0;
    const wfm_segment_t *segs =
        wfm_compose_segments(self->state, &n, &repeat, &continuous);
    PyObject *list = _wfm_compose_segments_to_list(segs, n);
    if (!list)
        return NULL;
    return Py_BuildValue("(NOO)", list, repeat ? Py_True : Py_False,
                         continuous ? Py_True : Py_False);
}

static PyObject *
Composer_get_segments(ComposerObject *self, void *closure)
{
    (void)closure;
    PyObject *r = _Composer_resolved(self);
    if (!r)
        return NULL;
    PyObject *segs = PyTuple_GET_ITEM(r, 0);
    Py_INCREF(segs);
    Py_DECREF(r);
    return segs;
}

static PyObject *
Composer_get_repeat(ComposerObject *self, void *closure)
{
    (void)closure;
    PyObject *r = _Composer_resolved(self);
    if (!r)
        return NULL;
    PyObject *v = PyTuple_GET_ITEM(r, 1);
    Py_INCREF(v);
    Py_DECREF(r);
    return v;
}

static PyObject *
Composer_get_continuous(ComposerObject *self, void *closure)
{
    (void)closure;
    PyObject *r = _Composer_resolved(self);
    if (!r)
        return NULL;
    PyObject *v = PyTuple_GET_ITEM(r, 2);
    Py_INCREF(v);
    Py_DECREF(r);
    return v;
}

static PyObject *
Composer_close(ComposerObject *self, PyObject *Py_UNUSED(ignored))
{
    if (!self->destroyed && self->state) {
        wfm_compose_destroy(self->state);
        self->destroyed = 1;
    }
    Py_RETURN_NONE;
}

static PyObject *
Composer_enter(ComposerObject *self, PyObject *Py_UNUSED(ignored))
{
    Py_INCREF(self);
    return (PyObject *)self;
}

static PyObject *
Composer_exit(ComposerObject *self, PyObject *args)
{
    (void)args;
    return Composer_close(self, NULL);
}

static PyObject *
Composer_from_json(PyObject *cls, PyObject *args)
{
    PyTypeObject *type = (PyTypeObject *)cls; /* alloc via cls: subclass round-trips */
    const char *json;
    if (!PyArg_ParseTuple(args, "s", &json))
        return NULL;
    wfm_compose_state_t *st = wfm_compose_from_json(json);
    if (!st) {
        PyErr_SetString(PyExc_ValueError, "wfm_compose_from_json failed");
        return NULL;
    }
    ComposerObject *self = (ComposerObject *)type->tp_alloc(type, 0);
    if (!self) {
        wfm_compose_destroy(st);
        return NULL;
    }
    self->state = st;
    self->destroyed = 0;
    return (PyObject *)self;
}

static PyObject *
Composer_from_file(PyObject *cls, PyObject *args)
{
    PyTypeObject *type = (PyTypeObject *)cls; /* alloc via cls: subclass round-trips */
    PyObject *pathobj;
    if (!PyArg_ParseTuple(args, "O&", PyUnicode_FSConverter, &pathobj))
        return NULL;
    wfm_compose_state_t *st = wfm_compose_from_file(PyBytes_AS_STRING(pathobj));
    Py_DECREF(pathobj);
    if (!st) {
        PyErr_SetString(PyExc_OSError, "wfm_compose_from_file failed");
        return NULL;
    }
    ComposerObject *self = (ComposerObject *)type->tp_alloc(type, 0);
    if (!self) {
        wfm_compose_destroy(st);
        return NULL;
    }
    self->state = st;
    self->destroyed = 0;
    return (PyObject *)self;
}

static PyObject *
Composer_to_json(ComposerObject *self, PyObject *Py_UNUSED(ignored))
{
    if (self->destroyed) {
        PyErr_SetString(PyExc_RuntimeError, "composer already closed");
        return NULL;
    }
    size_t n;
    int repeat = 0, continuous = 0;
    const wfm_segment_t *segs =
        wfm_compose_segments(self->state, &n, &repeat, &continuous);
    char *js = wfm_spec_to_json(segs, n, repeat, continuous, 0.0);
    if (!js) {
        PyErr_SetString(PyExc_RuntimeError, "wfm_spec_to_json failed");
        return NULL;
    }
    PyObject *s = PyUnicode_FromString(js);
    free(js);
    return s;
}

static PyGetSetDef Composer_getset[] = {
    {"segments", (getter)Composer_get_segments, NULL, NULL, NULL},
    {"repeat", (getter)Composer_get_repeat, NULL, NULL, NULL},
    {"continuous", (getter)Composer_get_continuous, NULL, NULL, NULL},
    {NULL, NULL, NULL, NULL, NULL}
};

/* Iterator returned by Composer.stream(): drains execute() into blocks. */
typedef struct {
    PyObject_HEAD
    PyObject  *composer; /* strong ref to the Composer */
    Py_ssize_t block;
    double realtime;
    void *clk;
} ComposerStreamObject;

static PyTypeObject ComposerStreamType;

static void
ComposerStream_dealloc(ComposerStreamObject *self)
{
    if (self->clk)
        dp_sample_clock_destroy(self->clk);
    Py_XDECREF(self->composer);
    Py_TYPE(self)->tp_free((PyObject *)self);
}

static PyObject *
ComposerStream_iter(PyObject *self)
{
    Py_INCREF(self);
    return self;
}

static PyObject *
ComposerStream_next(ComposerStreamObject *self)
{
    PyObject *blk =
        PyObject_CallMethod(self->composer, "execute", "n", self->block);
    if (!blk)
        return NULL;
    Py_ssize_t n = PyObject_Length(blk);
    if (n < 0) { /* error from execute */
        Py_DECREF(blk);
        return NULL;
    }
    if (n == 0) { /* finite spec drained -> StopIteration (NULL, no exception) */
        Py_DECREF(blk);
        return NULL;
    }
    if (self->realtime > 0.0) {
        if (!self->clk)
            self->clk = dp_sample_clock_create(self->realtime, 0);
        Py_BEGIN_ALLOW_THREADS
        dp_sample_clock_pace(self->clk, (size_t)n);
        Py_END_ALLOW_THREADS
    }
    return blk;
}

static PyTypeObject ComposerStreamType = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name      = "doppler.wfm.ComposerStream",
    .tp_basicsize = sizeof(ComposerStreamObject),
    .tp_flags     = Py_TPFLAGS_DEFAULT,
    .tp_dealloc   = (destructor)ComposerStream_dealloc,
    .tp_iter      = ComposerStream_iter,
    .tp_iternext  = (iternextfunc)ComposerStream_next,
    .tp_doc       = PyDoc_STR("Iterator over Composer.stream() blocks."),
};

static PyObject *
Composer_stream(ComposerObject *self, PyObject *args, PyObject *kwds)
{
    static char *kwlist[] = {"block", "realtime", NULL};
    Py_ssize_t block = 4096;
    double realtime = 0.0;
    if (!PyArg_ParseTupleAndKeywords(args, kwds, "|nd", kwlist,
            &block, &realtime))
        return NULL;
    if (block <= 0) {
        PyErr_SetString(PyExc_ValueError, "block must be > 0");
        return NULL;
    }
    ComposerStreamObject *it =
        PyObject_New(ComposerStreamObject, &ComposerStreamType);
    if (!it)
        return NULL;
    Py_INCREF(self);
    it->composer = (PyObject *)self;
    it->block = block;
    it->realtime = realtime;
    it->clk = NULL;
    return (PyObject *)it;
}

/* Serialize one resolved object's named fields into a dict via its getsets
 * (enums → str, bits → bytes) — generic over the SSOT field list. */
static PyObject *
_Composer_obj_to_dict(PyObject *o, const char *const *keys)
{
    PyObject *d = PyDict_New();
    if (!d)
        return NULL;
    for (Py_ssize_t i = 0; keys[i]; i++) {
        PyObject *v = PyObject_GetAttrString(o, keys[i]);
        if (!v) { Py_DECREF(d); return NULL; }
        int rc = PyDict_SetItemString(d, keys[i], v);
        Py_DECREF(v);
        if (rc < 0) { Py_DECREF(d); return NULL; }
    }
    return d;
}

static const char *const _Composer_seg_keys[] = { "fs", "num_samples", "off_samples", "repeats", "delay_samples", "gap_noise", NULL };
static const char *const _Composer_src_keys[] = { "type", "freq", "snr", "snr_mode", "seed", "sps", "pn_length", "pn_poly", "lfsr", "level", "f_end", "bits", "modulation", "pulse", "rrc_beta", "rrc_span", "symbols", "acq_code", "acq_reps", "data_code", "sync", "crc", "symbol_rate", "dsss_code_only", NULL };

static PyObject *
Composer_to_dict(ComposerObject *self, PyObject *Py_UNUSED(ignored))
{
    PyObject *r = _Composer_resolved(self);
    if (!r)
        return NULL;
    PyObject *seglist = PyTuple_GET_ITEM(r, 0); /* borrowed */
    Py_ssize_t nseg = PyList_GET_SIZE(seglist);
    PyObject *segs_out = PyList_New(nseg);
    if (!segs_out)
        goto fail;
    for (Py_ssize_t i = 0; i < nseg; i++) {
        PyObject *seg = PyList_GET_ITEM(seglist, i); /* borrowed */
        PyObject *sd = _Composer_obj_to_dict(seg, _Composer_seg_keys);
        if (!sd)
            goto fail_segs;
        PyObject *srcs = PyObject_GetAttrString(seg, "sources");
        if (!srcs) { Py_DECREF(sd); goto fail_segs; }
        Py_ssize_t nsrc = PyList_GET_SIZE(srcs);
        PyObject *src_out = PyList_New(nsrc);
        if (!src_out) { Py_DECREF(srcs); Py_DECREF(sd); goto fail_segs; }
        for (Py_ssize_t k = 0; k < nsrc; k++) {
            PyObject *kd = _Composer_obj_to_dict(
                PyList_GET_ITEM(srcs, k), _Composer_src_keys);
            if (!kd) {
                Py_DECREF(src_out); Py_DECREF(srcs); Py_DECREF(sd);
                goto fail_segs;
            }
            PyList_SET_ITEM(src_out, k, kd); /* steals */
        }
        Py_DECREF(srcs);
        int rc = PyDict_SetItemString(sd, "sources", src_out);
        Py_DECREF(src_out);
        if (rc < 0) { Py_DECREF(sd); goto fail_segs; }
        PyList_SET_ITEM(segs_out, i, sd); /* steals */
    }
    {
        PyObject *out = Py_BuildValue(
            "{s:O,s:O,s:N}", "repeat", PyTuple_GET_ITEM(r, 1),
            "continuous", PyTuple_GET_ITEM(r, 2), "segments", segs_out);
        Py_DECREF(r);
        return out; /* Py_BuildValue stole segs_out via N */
    }
fail_segs:
    Py_DECREF(segs_out);
fail:
    Py_DECREF(r);
    return NULL;
}

static PyObject *
Composer_to_sigmf(ComposerObject *self, PyObject *args, PyObject *kwds)
{
    if (self->destroyed) {
        PyErr_SetString(PyExc_RuntimeError, "composer already closed");
        return NULL;
    }
    const char *sample_type = "cf32";
    const char *endian = "le";
    double fs = 1e6;
    double fc = 0.0;
    static char *kwlist[] = {"sample_type", "endian", "fs", "fc", NULL};
    if (!PyArg_ParseTupleAndKeywords(args, kwds, "|ssdd", kwlist,
            &sample_type, &endian, &fs, &fc))
        return NULL;
    int _e_sample_type = _enum_index(_enum_stype, sample_type);
    if (_e_sample_type < 0) {
        PyErr_Format(PyExc_ValueError, "invalid sample_type '%s'", sample_type);
        return NULL;
    }
    int _e_endian = _enum_index(_enum_endian, endian);
    if (_e_endian < 0) {
        PyErr_Format(PyExc_ValueError, "invalid endian '%s'", endian);
        return NULL;
    }
    size_t _n; int _rep = 0, _cont = 0;
    const wfm_segment_t *segs =
        wfm_compose_segments(self->state, &_n, &_rep, &_cont);
    char *_js = wfm_sigmf_meta_json(_e_sample_type, _e_endian, fs, fc, segs, _n);
    if (!_js) {
        PyErr_SetString(PyExc_RuntimeError, "wfm_sigmf_meta_json failed");
        return NULL;
    }
    PyObject *_s = PyUnicode_FromString(_js);
    free(_js);
    return _s;
}
static PyMethodDef Composer_methods[] = {
    {"execute", (PyCFunction)Composer_execute, METH_VARARGS,
     "execute(n) -> ndarray[complex64]"},
    {"compose", (PyCFunction)(void (*)(void))Composer_compose,
     METH_VARARGS | METH_KEYWORDS, "compose(block=4096) -> ndarray[complex64]"},
    {"close", (PyCFunction)Composer_close, METH_NOARGS, "close() -> None"},
    {"__enter__", (PyCFunction)Composer_enter, METH_NOARGS, NULL},
    {"__exit__", (PyCFunction)Composer_exit, METH_VARARGS, NULL},
    {"stream", (PyCFunction)(void (*)(void))Composer_stream,
     METH_VARARGS | METH_KEYWORDS,
     "stream(block=4096, realtime=0.0) -> iterator (realtime=fs paces)"},
    {"to_dict", (PyCFunction)Composer_to_dict, METH_NOARGS,
     "to_dict() -> dict (resolved repeat/continuous/segments)"},
    {"to_sigmf", (PyCFunction)(void (*)(void))Composer_to_sigmf,
     METH_VARARGS | METH_KEYWORDS, "to_sigmf(...) -> str"},
    {"from_json", (PyCFunction)Composer_from_json,
     METH_VARARGS | METH_CLASS, "from_json(json) -> Composer"},
    {"from_file", (PyCFunction)Composer_from_file,
     METH_VARARGS | METH_CLASS, "from_file(path) -> Composer"},
    {"to_json", (PyCFunction)Composer_to_json, METH_NOARGS,
     "to_json() -> str"},
    {NULL, NULL, 0, NULL}
};

static PyTypeObject ComposerType = {
    PyVarObject_HEAD_INIT(NULL, 0)
    .tp_name      = "doppler.wfm.Composer",
    .tp_basicsize = sizeof(ComposerObject),
    .tp_flags     = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE,
    .tp_new       = PyType_GenericNew,
    .tp_init      = (initproc)Composer_init,
    .tp_dealloc   = (destructor)Composer_dealloc,
    .tp_getset    = Composer_getset,
    .tp_methods   = Composer_methods,
    .tp_doc       = PyDoc_STR("Composer — multi-segment composer."),
};

static PyMethodDef _methods[] = {
    {"tone", (PyCFunction)(void (*)(void))_factory_tone, METH_VARARGS | METH_KEYWORDS,
     "tone(**kw) -> Synth"},
    {"noise", (PyCFunction)(void (*)(void))_factory_noise, METH_VARARGS | METH_KEYWORDS,
     "noise(**kw) -> Synth"},
    {"pn", (PyCFunction)(void (*)(void))_factory_pn, METH_VARARGS | METH_KEYWORDS,
     "pn(**kw) -> Synth"},
    {"bpsk", (PyCFunction)(void (*)(void))_factory_bpsk, METH_VARARGS | METH_KEYWORDS,
     "bpsk(**kw) -> Synth"},
    {"qpsk", (PyCFunction)(void (*)(void))_factory_qpsk, METH_VARARGS | METH_KEYWORDS,
     "qpsk(**kw) -> Synth"},
    {"chirp", (PyCFunction)(void (*)(void))_factory_chirp, METH_VARARGS | METH_KEYWORDS,
     "chirp(**kw) -> Synth"},
    {"bits", (PyCFunction)(void (*)(void))_factory_bits, METH_VARARGS | METH_KEYWORDS,
     "bits(**kw) -> Synth"},
    {NULL, NULL, 0, NULL}
};

static struct PyModuleDef _moduledef = {
    PyModuleDef_HEAD_INIT, "wfm_compose", NULL, -1, _methods,
    NULL, NULL, NULL, NULL
};

PyMODINIT_FUNC
PyInit_wfm_compose(void)
{
    import_array();
    if (PyType_Ready(&SynthType) < 0) return NULL;
    if (PyType_Ready(&SegmentType) < 0) return NULL;
    if (PyType_Ready(&TimelineType) < 0) return NULL;
    if (PyType_Ready(&ComposerType) < 0) return NULL;
    if (PyType_Ready(&ComposerStreamType) < 0) return NULL;
    PyObject *m = PyModule_Create(&_moduledef);
    if (!m) return NULL;
    Py_INCREF(&SynthType);
    PyModule_AddObject(m, "Synth", (PyObject *)&SynthType);
    Py_INCREF(&SegmentType);
    PyModule_AddObject(m, "Segment", (PyObject *)&SegmentType);
    Py_INCREF(&TimelineType);
    PyModule_AddObject(m, "Timeline", (PyObject *)&TimelineType);
    Py_INCREF(&ComposerType);
    PyModule_AddObject(m, "Composer", (PyObject *)&ComposerType);
    return m;
}
