/**
 * @file RateConverter_core.c
 * @brief Optimal-speed rate conversion cascade -- implementation.
 *
 * Stage selection mirrors _plan_cascade() from the validated Python
 * prototype (src/doppler/resample/rate_converter.py, 33/33 tests).
 *
 * The CIC "compound stage" bundles the CIC decimator and its optional
 * droop-compensating FIR into a single cascade slot so that n_stages
 * exactly equals the number of human-readable stage labels.
 *
 * Intermediate ping-pong buffers (bufs[0] and bufs[1]) are grown lazily
 * on the first execute call.  buf_cap equals n_in so any decimation
 * stage's intermediate output fits without a second alloc.
 */

#include "RateConverter/RateConverter_core.h"

#include "cic/cic_core.h"
#include "fir/fir_core.h"
#include "hbdecim/hbdecim_core.h"
#include "resamp/resamp_core.h"
#include "resample/resample_core.h" /* ciccompmf */

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef M_LN2
#define M_LN2 0.6931471805599453
#endif

/* ------------------------------------------------------------------ */
/* Constants                                                           */
/* ------------------------------------------------------------------ */

/* |log2(D) - round(log2(D))| < this --> exact power-of-2            */
#define _EXACT_TOL 1e-9

/* Decimation factors below this threshold don't benefit from a CIC.  */
#define _CIC_MIN_D 8.0

/* ------------------------------------------------------------------ */
/* Pre-computed halfband FIR coefficients                              */
/*                                                                     */
/* Generated by:                                                       */
/*   from doppler.resample import _halfband_bank                       */
/*   bank = _halfband_bank(60.0, 0.4, 0.6)   # (2, 19) float32       */
/*   centre = bank.shape[1] // 2                                       */
/*   fir_row = 0 if abs(bank[0,c]) < abs(bank[1,c]) else 1            */
/*   h = bank[fir_row]  # FIR branch (row 1 for 60dB/0.4-0.6 spec)   */
/* ------------------------------------------------------------------ */

#define _HB_NTAPS 19

static const float _HB_FIR[_HB_NTAPS] = {
  0.0015790532f,  -0.0046757734f, 0.0104431789f,  -0.0201746244f,
  0.0357989259f,  -0.0608663708f, 0.1041134074f,  -0.1975378096f,
  0.6316009164f,  0.6316009164f,  -0.1975378096f, 0.1041134074f,
  -0.0608663708f, 0.0357989259f,  -0.0201746244f, 0.0104431789f,
  -0.0046757734f, 0.0015790532f,  0.0000000000f,
};

/* ------------------------------------------------------------------ */
/* CIC compound stage                                                  */
/*                                                                     */
/* Bundles CIC + optional compensation FIR into one cascade slot so   */
/* n_stages equals the visible stage count.  Labels read "CIC(R)+FIR" */
/* when compensate != 0.                                               */
/* ------------------------------------------------------------------ */

typedef struct
{
  cic_state_t *cic;
  fir_state_t *fir; /* NULL when compensate == 0 */
  int          R;
  int          compensate;
} rc_cic_stage_t;

/* ------------------------------------------------------------------ */
/* Stage-selection plan                                                */
/* ------------------------------------------------------------------ */

typedef struct
{
  rc_stage_t type;
  int        R;           /* CIC: decimation factor */
  double     resamp_rate; /* RESAMP: rate ratio      */
  int        compensate;  /* CIC: droop-comp flag    */
} rc_plan_entry_t;

/* Portable log2 via log(x)/log(2). */
static double
_log2 (double x)
{
  return log (x) / M_LN2;
}

/*
 * Plan the cascade for `rate'.  Returns the number of stages (0 on
 * invalid rate, else 1 or 2).  Fills plan[0..n-1] with descriptors.
 *
 * Mirrors _plan_cascade() from the Python prototype exactly.
 */
static int
_plan (double rate, int compensate, rc_plan_entry_t plan[RC_MAX_STAGES])
{
  if (rate <= 0.0)
    return 0;

  if (rate >= 1.0)
    {
      plan[0].type        = RC_STAGE_RESAMP;
      plan[0].resamp_rate = rate;
      return 1;
    }

  double D = 1.0 / rate;
  if (D < 2.0)
    {
      plan[0].type        = RC_STAGE_RESAMP;
      plan[0].resamp_rate = rate;
      return 1;
    }

  double log2_D = _log2 (D);
  int    n      = (int)round (log2_D);

  if (fabs (log2_D - n) < _EXACT_TOL)
    {
      /* Exact power-of-2 decimation. */
      if (n == 1)
        {
          plan[0].type = RC_STAGE_HB;
          return 1;
        }
      if (n == 2)
        {
          plan[0].type = RC_STAGE_HB;
          plan[1].type = RC_STAGE_HB;
          return 2;
        }
      /* n >= 3: CIC(R), capped at 4096. */
      int R              = (n <= 12) ? (1 << n) : 4096;
      plan[0].type       = RC_STAGE_CIC;
      plan[0].R          = R;
      plan[0].compensate = compensate;
      return 1;
    }

  if (D >= _CIC_MIN_D)
    {
      /* Non-power-of-2, large D: CIC + Resampler correction. */
      int    n_lo  = (int)floor (log2_D);
      int    R_lo  = 1 << n_lo;
      int    R_hi  = (n_lo + 1 <= 12) ? (1 << (n_lo + 1)) : 4096;
      double co_lo = (double)R_lo / D;
      double co_hi = (double)R_hi / D;
      int    R;
      double corr;
      /* Pick correction whose log2 is closest to 0 (nearest to 1.0). */
      if (fabs (_log2 (co_lo)) <= fabs (_log2 (co_hi)))
        {
          R    = R_lo;
          corr = co_lo;
        }
      else
        {
          R    = R_hi;
          corr = co_hi;
        }
      plan[0].type       = RC_STAGE_CIC;
      plan[0].R          = R;
      plan[0].compensate = compensate;
      int ns             = 1;
      if (fabs (corr - 1.0) > 1e-6)
        {
          plan[ns].type        = RC_STAGE_RESAMP;
          plan[ns].resamp_rate = corr;
          ns++;
        }
      return ns;
    }

  /* D in [2, 8), non-integer: polyphase resampler handles it cheaply. */
  plan[0].type        = RC_STAGE_RESAMP;
  plan[0].resamp_rate = rate;
  return 1;
}

/* ------------------------------------------------------------------ */
/* Stage dispatch helpers                                              */
/* ------------------------------------------------------------------ */

static void
_stage_destroy (rc_stage_t type, void *ptr)
{
  if (!ptr)
    return;
  switch (type)
    {
    case RC_STAGE_HB:
      hbdecim_destroy ((hbdecim_state_t *)ptr);
      break;
    case RC_STAGE_CIC:
      {
        rc_cic_stage_t *cs = (rc_cic_stage_t *)ptr;
        cic_destroy (cs->cic);
        if (cs->fir)
          fir_destroy (cs->fir);
        free (cs);
      }
      break;
    case RC_STAGE_RESAMP:
      resamp_destroy ((resamp_state_t *)ptr);
      break;
    }
}

static void
_stage_reset (rc_stage_t type, void *ptr)
{
  switch (type)
    {
    case RC_STAGE_HB:
      hbdecim_reset ((hbdecim_state_t *)ptr);
      break;
    case RC_STAGE_CIC:
      {
        rc_cic_stage_t *cs = (rc_cic_stage_t *)ptr;
        cic_reset (cs->cic);
        if (cs->fir)
          fir_reset (cs->fir);
      }
      break;
    case RC_STAGE_RESAMP:
      resamp_reset ((resamp_state_t *)ptr);
      break;
    }
}

/* ── Serializable state — compose the active stages' leaf serializers ────────
 */

static size_t
_stage_state_bytes (rc_stage_t type, const void *ptr)
{
  switch (type)
    {
    case RC_STAGE_HB:
      return hbdecim_state_bytes ((const hbdecim_state_t *)ptr);
    case RC_STAGE_CIC:
      {
        const rc_cic_stage_t *cs = (const rc_cic_stage_t *)ptr;
        size_t                b  = cic_state_bytes (cs->cic);
        if (cs->fir)
          b += fir_state_bytes (cs->fir);
        return b;
      }
    case RC_STAGE_RESAMP:
      return resamp_state_bytes ((const resamp_state_t *)ptr);
    }
  return 0;
}

static char *
_stage_get_state (rc_stage_t type, const void *ptr, char *p)
{
  switch (type)
    {
    case RC_STAGE_HB:
      hbdecim_get_state ((const hbdecim_state_t *)ptr, p);
      p += hbdecim_state_bytes ((const hbdecim_state_t *)ptr);
      break;
    case RC_STAGE_CIC:
      {
        const rc_cic_stage_t *cs = (const rc_cic_stage_t *)ptr;
        cic_get_state (cs->cic, p);
        p += cic_state_bytes (cs->cic);
        if (cs->fir)
          {
            fir_get_state (cs->fir, p);
            p += fir_state_bytes (cs->fir);
          }
      }
      break;
    case RC_STAGE_RESAMP:
      resamp_get_state ((const resamp_state_t *)ptr, p);
      p += resamp_state_bytes ((const resamp_state_t *)ptr);
      break;
    }
  return p;
}

static const char *
_stage_set_state (rc_stage_t type, void *ptr, const char *p)
{
  switch (type)
    {
    case RC_STAGE_HB:
      hbdecim_set_state ((hbdecim_state_t *)ptr, p);
      p += hbdecim_state_bytes ((const hbdecim_state_t *)ptr);
      break;
    case RC_STAGE_CIC:
      {
        rc_cic_stage_t *cs = (rc_cic_stage_t *)ptr;
        cic_set_state (cs->cic, p);
        p += cic_state_bytes (cs->cic);
        if (cs->fir)
          {
            fir_set_state (cs->fir, p);
            p += fir_state_bytes (cs->fir);
          }
      }
      break;
    case RC_STAGE_RESAMP:
      resamp_set_state ((resamp_state_t *)ptr, p);
      p += resamp_state_bytes ((const resamp_state_t *)ptr);
      break;
    }
  return p;
}

/*
 * Execute stage from (in, n_in) into (out, max_out).
 * Returns the number of output samples produced.
 */
static size_t
_stage_exec (rc_stage_t type, void *ptr, const float _Complex *in, size_t n_in,
             float _Complex *out, size_t max_out)
{
  switch (type)
    {
    case RC_STAGE_HB:
      return hbdecim_execute ((hbdecim_state_t *)ptr, in, n_in, out, max_out);
    case RC_STAGE_CIC:
      {
        rc_cic_stage_t *cs = (rc_cic_stage_t *)ptr;
        size_t          n  = cic_decimate (cs->cic, in, n_in, out);
        if (cs->fir)
          {
            /* Compensation FIR in-place: CIC output is already in out.
             * fir_execute() documents that in==out is safe. */
            n = fir_execute (cs->fir, out, n, out);
          }
        return n;
      }
    case RC_STAGE_RESAMP:
      return resamp_execute ((resamp_state_t *)ptr, in, n_in, out, max_out);
    default:
      return 0;
    }
}

/* ------------------------------------------------------------------ */
/* Build / destroy all stages                                          */
/* ------------------------------------------------------------------ */

static void
_destroy_all_stages (RateConverter_state_t *s)
{
  for (int i = 0; i < s->n_stages; i++)
    {
      _stage_destroy (s->stage_types[i], s->stage_ptrs[i]);
      s->stage_ptrs[i] = NULL;
    }
  s->n_stages = 0;
  free (s->bufs[0]);
  free (s->bufs[1]);
  s->bufs[0] = s->bufs[1] = NULL;
  s->buf_cap              = 0;
}

/*
 * Instantiate C stage objects from the plan.
 * Returns 1 on success, 0 on any allocation failure (partially-built
 * stages are cleaned up before returning).
 */
static int
_build_stages (RateConverter_state_t *s, const rc_plan_entry_t *plan, int n)
{
  int i;
  for (i = 0; i < n; i++)
    {
      void *obj = NULL;
      switch (plan[i].type)
        {
        case RC_STAGE_HB:
          obj = hbdecim_create (_HB_NTAPS, _HB_FIR);
          break;

        case RC_STAGE_CIC:
          {
            rc_cic_stage_t *cs = (rc_cic_stage_t *)calloc (1, sizeof (*cs));
            if (!cs)
              goto fail;
            cs->R          = plan[i].R;
            cs->compensate = plan[i].compensate;
            cs->cic        = cic_create ((uint32_t)plan[i].R);
            if (!cs->cic)
              {
                free (cs);
                goto fail;
              }
            if (plan[i].compensate)
              {
                /* 7-tap CIC droop compensator at the decimated rate. */
                double h64[7];
                ciccompmf (h64, 4, (uint32_t)plan[i].R, 7);
                float h32[7];
                for (int j = 0; j < 7; j++)
                  h32[j] = (float)h64[j];
                cs->fir = fir_create_real (h32, 7);
                if (!cs->fir)
                  {
                    cic_destroy (cs->cic);
                    free (cs);
                    goto fail;
                  }
              }
            obj = cs;
          }
          break;

        case RC_STAGE_RESAMP:
          obj = resamp_create (plan[i].resamp_rate);
          break;
        }

      if (!obj)
        goto fail;

      s->stage_types[i] = plan[i].type;
      s->stage_ptrs[i]  = obj;
    }
  s->n_stages = n;
  return 1;

fail:
  for (int j = 0; j < i; j++)
    {
      _stage_destroy (s->stage_types[j], s->stage_ptrs[j]);
      s->stage_ptrs[j] = NULL;
    }
  s->n_stages = 0;
  return 0;
}

/* ------------------------------------------------------------------ */
/* Public API                                                          */
/* ------------------------------------------------------------------ */

RateConverter_state_t *
RateConverter_create (double rate, int compensate)
{
  if (rate <= 0.0)
    return NULL;

  rc_plan_entry_t plan[RC_MAX_STAGES];
  int             n = _plan (rate, compensate, plan);
  if (n == 0)
    return NULL;

  RateConverter_state_t *s = (RateConverter_state_t *)calloc (1, sizeof (*s));
  if (!s)
    return NULL;

  s->rate       = rate;
  s->compensate = compensate;

  if (!_build_stages (s, plan, n))
    {
      free (s);
      return NULL;
    }
  return s;
}

void
RateConverter_destroy (RateConverter_state_t *s)
{
  if (!s)
    return;
  _destroy_all_stages (s);
  free (s);
}

void
RateConverter_reset (RateConverter_state_t *s)
{
  for (int i = 0; i < s->n_stages; i++)
    _stage_reset (s->stage_types[i], s->stage_ptrs[i]);
}

/* ── Serializable state — concatenate the active stages in cascade order ────
 */

size_t
RateConverter_state_bytes (const RateConverter_state_t *s)
{
  size_t b = sizeof (dp_state_hdr_t);
  for (int i = 0; i < s->n_stages; i++)
    b += _stage_state_bytes (s->stage_types[i], s->stage_ptrs[i]);
  return b;
}

void
RateConverter_get_state (const RateConverter_state_t *s, void *blob)
{
  dp_writer_t w = dp_writer_init (blob, RateConverter_state_bytes (s));
  dp_w_hdr (&w, RC_STATE_MAGIC, RC_STATE_VERSION,
            RateConverter_state_bytes (s));
  char *p = (char *)blob + sizeof (dp_state_hdr_t);
  for (int i = 0; i < s->n_stages; i++)
    p = _stage_get_state (s->stage_types[i], s->stage_ptrs[i], p);
}

int
RateConverter_set_state (RateConverter_state_t *s, const void *blob)
{
  int rc = dp_state_validate (blob, RateConverter_state_bytes (s),
                              RC_STATE_MAGIC, RC_STATE_VERSION);
  if (rc != DP_OK)
    return rc;
  const char *p = (const char *)blob + sizeof (dp_state_hdr_t);
  for (int i = 0; i < s->n_stages; i++)
    p = _stage_set_state (s->stage_types[i], s->stage_ptrs[i], p);
  return DP_OK;
}

size_t
RateConverter_execute (RateConverter_state_t *s, const float _Complex *in,
                       size_t n_in, float _Complex *out, size_t max_out)
{
  if (s->n_stages == 0)
    return 0;

  /* Grow ping-pong buffers lazily to n_in on first call. */
  if (n_in > s->buf_cap)
    {
      free (s->bufs[0]);
      free (s->bufs[1]);
      s->bufs[0] = (float _Complex *)malloc (n_in * sizeof (float _Complex));
      s->bufs[1] = (float _Complex *)malloc (n_in * sizeof (float _Complex));
      if (!s->bufs[0] || !s->bufs[1])
        {
          free (s->bufs[0]);
          free (s->bufs[1]);
          s->bufs[0] = s->bufs[1] = NULL;
          s->buf_cap              = 0;
          return 0;
        }
      s->buf_cap = n_in;
    }

  if (s->n_stages == 1)
    return _stage_exec (s->stage_types[0], s->stage_ptrs[0], in, n_in, out,
                        max_out);

  /* Multi-stage: route through ping-pong intermediate buffers. */
  const float _Complex *src  = in;
  size_t                n    = n_in;
  int                   ping = 0;

  for (int i = 0; i < s->n_stages - 1; i++)
    {
      float _Complex *dst = s->bufs[ping];
      n   = _stage_exec (s->stage_types[i], s->stage_ptrs[i], src, n, dst,
                         s->buf_cap);
      src = dst;
      ping ^= 1;
    }
  return _stage_exec (s->stage_types[s->n_stages - 1],
                      s->stage_ptrs[s->n_stages - 1], src, n, out, max_out);
}

size_t
RateConverter_execute_max_out (RateConverter_state_t *s)
{
  /* Upper bound for a 65536-sample input at the current rate.
   * For interpolation (rate > 1) the buffer is ceil(65536 * rate) + 2. */
  return (size_t)(65536.0 * (s->rate > 1.0 ? s->rate : 1.0)) + 2;
}

double
RateConverter_get_rate (const RateConverter_state_t *s)
{
  return s->rate;
}

void
RateConverter_set_rate (RateConverter_state_t *s, double rate)
{
  if (rate <= 0.0)
    return;

  rc_plan_entry_t plan[RC_MAX_STAGES];
  int             n = _plan (rate, s->compensate, plan);
  if (n == 0)
    return;

  _destroy_all_stages (s);
  s->rate = rate;

  if (!_build_stages (s, plan, n))
    s->n_stages = 0;
}

int
RateConverter_stage_label (RateConverter_state_t *s, int i, char *buf,
                           size_t len)
{
  if (i < 0 || i >= s->n_stages)
    return 0;

  switch (s->stage_types[i])
    {
    case RC_STAGE_HB:
      snprintf (buf, len, "HalfbandDecimator");
      break;
    case RC_STAGE_CIC:
      {
        rc_cic_stage_t *cs = (rc_cic_stage_t *)s->stage_ptrs[i];
        if (cs->compensate)
          snprintf (buf, len, "CIC(%d)+FIR", cs->R);
        else
          snprintf (buf, len, "CIC(%d)", cs->R);
      }
      break;
    case RC_STAGE_RESAMP:
      {
        double r = resamp_get_rate ((resamp_state_t *)s->stage_ptrs[i]);
        snprintf (buf, len, "Resampler(%g)", r);
      }
      break;
    default:
      snprintf (buf, len, "Unknown");
      break;
    }
  return 1;
}

size_t
RateConverter_convert (double rate, int compensate, const float _Complex *in,
                       size_t n_in, float _Complex *out, size_t max_out)
{
  RateConverter_state_t *rc = RateConverter_create (rate, compensate);
  if (!rc)
    return 0;
  size_t n = RateConverter_execute (rc, in, n_in, out, max_out);
  RateConverter_destroy (rc);
  return n;
}
