/**
 * @file RateConverter_core.c
 * @brief Optimal-speed rate conversion cascade -- implementation.
 *
 * Stage selection mirrors _plan_cascade() from the validated Python
 * prototype (src/doppler/resample/rate_converter.py, 33/33 tests).
 *
 * The CIC "compound stage" bundles the CIC decimator and its optional
 * droop-compensating FIR into a single cascade slot so that n_stages
 * exactly equals the number of human-readable stage labels.
 *
 * Intermediate ping-pong buffers (bufs[0] and bufs[1]) are grown lazily
 * on the first execute call.  buf_cap equals n_in so any decimation
 * stage's intermediate output fits without a second alloc.
 */

#include "RateConverter/RateConverter_core.h"

#include "cic/cic_core.h"
#include "fir/fir_core.h"
#include "hbdecim/hbdecim_core.h"
#include "resamp/resamp_core.h"
#include "resample/resample_core.h" /* ciccompmf */
#include "wfm/wfm_dsp.h" /* wfm_rrc_h — the RRC formula's one home */

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef M_LN2
#define M_LN2 0.6931471805599453
#endif

/* ------------------------------------------------------------------ */
/* Constants                                                           */
/* ------------------------------------------------------------------ */

/* |log2(D) - round(log2(D))| < this --> exact power-of-2            */
#define _EXACT_TOL 1e-9

/* Decimation factors below this threshold don't benefit from a CIC.  */
#define _CIC_MIN_D 8.0

/* ------------------------------------------------------------------ */
/* Pre-computed halfband FIR coefficients                              */
/*                                                                     */
/* Generated by:                                                       */
/*   from doppler.resample import _halfband_bank                       */
/*   bank = _halfband_bank(60.0, 0.4, 0.6)   # (2, 19) float32       */
/*   centre = bank.shape[1] // 2                                       */
/*   fir_row = 0 if abs(bank[0,c]) < abs(bank[1,c]) else 1            */
/*   h = bank[fir_row]  # FIR branch (row 1 for 60dB/0.4-0.6 spec)   */
/* ------------------------------------------------------------------ */

#define _HB_NTAPS 19

static const float _HB_FIR[_HB_NTAPS] = {
  0.0015790532f,  -0.0046757734f, 0.0104431789f,  -0.0201746244f,
  0.0357989259f,  -0.0608663708f, 0.1041134074f,  -0.1975378096f,
  0.6316009164f,  0.6316009164f,  -0.1975378096f, 0.1041134074f,
  -0.0608663708f, 0.0357989259f,  -0.0201746244f, 0.0104431789f,
  -0.0046757734f, 0.0015790532f,  0.0000000000f,
};

/* ------------------------------------------------------------------ */
/* CIC compound stage                                                  */
/*                                                                     */
/* Bundles CIC + optional compensation FIR into one cascade slot so   */
/* n_stages equals the visible stage count.  Labels read "CIC(R)+FIR" */
/* when compensate != 0.                                               */
/* ------------------------------------------------------------------ */

typedef struct
{
  cic_state_t *cic;
  fir_state_t *fir; /* NULL when compensate == 0 */
  int          R;
  int          compensate;
} rc_cic_stage_t;

/* ------------------------------------------------------------------ */
/* Stage-selection plan                                                */
/* ------------------------------------------------------------------ */

typedef struct
{
  rc_stage_t type;
  int        R;           /* CIC: decimation factor */
  double     resamp_rate; /* RESAMP: rate ratio      */
  int        compensate;  /* CIC: droop-comp flag    */
} rc_plan_entry_t;

/* Portable log2 via log(x)/log(2). */
static double
_log2 (double x)
{
  return log (x) / M_LN2;
}

/*
 * Plan the cascade for `rate'.  Returns the number of stages (0 on
 * invalid rate, else 1..3).  Fills plan[0..n-1] with descriptors.
 *
 * Mirrors _plan_cascade() from the Python prototype exactly, with one
 * addition: `force_terminal' guarantees the plan ENDS in a fractional
 * Resampler stage even when the rate needs no fractional correction.
 *
 * That matters only for the matched-filter path, where the terminal stage is
 * not merely a rate correction: it is simultaneously the matched filter and
 * the timing element a loop steers.  Without it, `rate = 2/64' plans a bare
 * CIC(32) — perfectly good arithmetic, nothing steerable at the end — so the
 * stage is appended at rate R/D (exactly 1.0 whenever the integer stages
 * already landed the rate).
 */
static int
_plan (double rate, int compensate, int force_terminal,
       rc_plan_entry_t plan[RC_MAX_STAGES])
{
  if (rate <= 0.0)
    return 0;

  if (rate >= 1.0)
    {
      plan[0].type        = RC_STAGE_RESAMP;
      plan[0].resamp_rate = rate;
      return 1;
    }

  double D = 1.0 / rate;
  if (D < 2.0)
    {
      plan[0].type        = RC_STAGE_RESAMP;
      plan[0].resamp_rate = rate;
      return 1;
    }

  double log2_D = _log2 (D);
  int    n      = (int)round (log2_D);

  if (fabs (log2_D - n) < _EXACT_TOL)
    {
      /* Exact power-of-2 decimation. */
      int ns = 0;
      int R  = 0; /* 0 = decimation done by halfband stages */
      if (n == 1)
        {
          plan[ns++].type = RC_STAGE_HB;
        }
      else if (n == 2)
        {
          plan[ns++].type = RC_STAGE_HB;
          plan[ns++].type = RC_STAGE_HB;
        }
      else
        {
          /* n >= 3: CIC(R), capped at 4096. */
          R                   = (n <= 12) ? (1 << n) : 4096;
          plan[ns].type       = RC_STAGE_CIC;
          plan[ns].R          = R;
          plan[ns].compensate = compensate;
          ns++;
        }
      if (force_terminal)
        {
          /* Whatever the integer stages left over — 1.0 for n <= 12, the
             residual D/4096 for a capped CIC. */
          int R_done           = R ? R : (1 << n);
          plan[ns].type        = RC_STAGE_RESAMP;
          plan[ns].resamp_rate = (double)R_done / D;
          ns++;
        }
      return ns;
    }

  if (D >= _CIC_MIN_D)
    {
      /* Non-power-of-2, large D: CIC + Resampler correction. */
      int    n_lo  = (int)floor (log2_D);
      int    R_lo  = 1 << n_lo;
      int    R_hi  = (n_lo + 1 <= 12) ? (1 << (n_lo + 1)) : 4096;
      double co_lo = (double)R_lo / D;
      double co_hi = (double)R_hi / D;
      int    R;
      double corr;
      /* Pick correction whose log2 is closest to 0 (nearest to 1.0). */
      if (fabs (_log2 (co_lo)) <= fabs (_log2 (co_hi)))
        {
          R    = R_lo;
          corr = co_lo;
        }
      else
        {
          R    = R_hi;
          corr = co_hi;
        }
      plan[0].type       = RC_STAGE_CIC;
      plan[0].R          = R;
      plan[0].compensate = compensate;
      int ns             = 1;
      if (force_terminal || fabs (corr - 1.0) > 1e-6)
        {
          plan[ns].type        = RC_STAGE_RESAMP;
          plan[ns].resamp_rate = corr;
          ns++;
        }
      return ns;
    }

  /* D in [2, 8), non-integer: polyphase resampler handles it cheaply. */
  plan[0].type        = RC_STAGE_RESAMP;
  plan[0].resamp_rate = rate;
  return 1;
}

/* ------------------------------------------------------------------ */
/* Pulse-shaped terminal bank                                          */
/*                                                                     */
/* The bank belongs here, not in a downstream timing object: this is   */
/* the only party that knows its own CIC geometry (for the droop fold) */
/* and the terminal stage's rate (which sets the tap grid).            */
/* ------------------------------------------------------------------ */

/* Number of taps the CIC droop compensator uses when folded into the bank. */
#define _RC_COMP_NTAPS 7
/* CIC differential delay assumed by ciccompmf (matches cic_create). */
#define _RC_CIC_ORDER 4

/* Pulse h(t), t in SYMBOL periods from the pulse centre. */
static double
_pulse_h (int pulse, double t, double beta)
{
  if (pulse == RC_PULSE_IANDD)
    /* Unit rectangle over one symbol — the matched filter for a rectangular
       symbol, and exactly what an integrate-and-dump computes. Half-open at
       the trailing edge so two adjacent symbols never both claim t = ±0.5. */
    return (t >= -0.5 && t < 0.5) ? 1.0 : 0.0;
  return wfm_rrc_h (t, beta); /* the canonical RRC, one home */
}

/* One-sided support in symbols. The rectangle is one symbol wide whatever
   `span' says. */
static double
_pulse_support (int pulse, size_t span)
{
  return pulse == RC_PULSE_IANDD ? 0.5 : (double)span;
}

/*
 * Build the terminal stage's polyphase bank.
 *
 * `sps' is the symbol period measured in the terminal stage's INPUT samples
 * — that is the grid the taps live on, and it is what makes this bank small:
 * the integer stages have already done the bulk decimation, so sps is ~2
 * whatever the input rate was.  `pulse_sps' is the same period counted in
 * OUTPUT samples, so one output period is `1/pulse_sps' symbols — the span an
 * arm sweeps, because the accumulator's fractional remainder (which selects
 * the arm) is measured in output periods.
 *
 * Layout is `bank[p][t] = h(-t/sps + support + (p/num_phases)/pulse_sps)':
 * arm p moves the sampling instant in the SAME direction crossing an
 * accumulator boundary moves it.  Getting that backwards makes the arm and the
 * accumulator fight and the effective sampling instant becomes a
 * one-output-period sawtooth (it still "works", it just jitters), which is why
 * this must match the unified accumulator path — see
 * resamp_execute_ctrl_push().
 *
 * When `comp' is non-NULL the CIC droop compensator is folded in by convolving
 * every arm with it.  This is exact, not an approximation: ciccompmf's taps
 * run at the decimated rate, which IS this bank's tap grid, so the composite
 * response of (comp FIR then bank arm) is just their convolution — no separate
 * stage, no resampling of one grid onto another.
 *
 * Returns a malloc'd num_phases x (*out_ntaps) bank, or NULL on OOM.
 */
static float *
_build_bank (int pulse, double beta, double sps, double pulse_sps, size_t span,
             size_t num_phases, const double *comp, size_t n_comp,
             size_t *out_ntaps)
{
  double support = _pulse_support (pulse, span);
  /* Cover the full pulse for EVERY arm: the last arm displaces the window by
     one whole output period (1/pulse_sps symbols), so the tap count has to
     carry that on top of the two-sided support. */
  size_t raw = (size_t)ceil ((2.0 * support + 1.0 / pulse_sps) * sps) + 1u;
  size_t nt  = comp ? raw + n_comp - 1u : raw;

  float *bank = (float *)calloc (num_phases * nt, sizeof (float));
  if (!bank)
    return NULL;

  for (size_t p = 0; p < num_phases; p++)
    {
      double arm = (double)p / (double)num_phases / pulse_sps;
      float *row = bank + p * nt;
      for (size_t t = 0; t < raw; t++)
        {
          /* tap t multiplies x[n-t]: the delay line is newest-first. */
          double ts = -(double)t / sps + support + arm;
          double h  = _pulse_h (pulse, ts, beta);
          if (!comp)
            row[t] = (float)h;
          else
            /* Composite of comp FIR then this arm: both index x[n-k], so
               the tap that multiplies x[n-(t+j)] gains comp[j]*h. */
            for (size_t j = 0; j < n_comp; j++)
              row[t + j] += (float)(comp[j] * h);
        }
    }

  /* ONE common scale across all arms, taken from arm 0.  Normalising each arm
     to unit energy independently would make the cascade's gain a function of
     the timing phase — a gain ripple synchronous with the very quantity a
     downstream loop is trying to estimate. */
  double e0 = 0.0;
  for (size_t t = 0; t < nt; t++)
    e0 += (double)bank[t] * (double)bank[t];
  float g = (float)(e0 > 0.0 ? 1.0 / sqrt (e0) : 1.0);
  for (size_t i = 0; i < num_phases * nt; i++)
    bank[i] *= g;

  *out_ntaps = nt;
  return bank;
}

/* ------------------------------------------------------------------ */
/* Stage dispatch helpers                                              */
/* ------------------------------------------------------------------ */

static void
_stage_destroy (rc_stage_t type, void *ptr)
{
  if (!ptr)
    return;
  switch (type)
    {
    case RC_STAGE_HB:
      hbdecim_destroy ((hbdecim_state_t *)ptr);
      break;
    case RC_STAGE_CIC:
      {
        rc_cic_stage_t *cs = (rc_cic_stage_t *)ptr;
        cic_destroy (cs->cic);
        if (cs->fir)
          fir_destroy (cs->fir);
        free (cs);
      }
      break;
    case RC_STAGE_RESAMP:
      resamp_destroy ((resamp_state_t *)ptr);
      break;
    }
}

static void
_stage_reset (rc_stage_t type, void *ptr)
{
  switch (type)
    {
    case RC_STAGE_HB:
      hbdecim_reset ((hbdecim_state_t *)ptr);
      break;
    case RC_STAGE_CIC:
      {
        rc_cic_stage_t *cs = (rc_cic_stage_t *)ptr;
        cic_reset (cs->cic);
        if (cs->fir)
          fir_reset (cs->fir);
      }
      break;
    case RC_STAGE_RESAMP:
      resamp_reset ((resamp_state_t *)ptr);
      break;
    }
}

/* ── Serializable state — compose the active stages' leaf serializers ────────
 */

static size_t
_stage_state_bytes (rc_stage_t type, const void *ptr)
{
  switch (type)
    {
    case RC_STAGE_HB:
      return hbdecim_state_bytes ((const hbdecim_state_t *)ptr);
    case RC_STAGE_CIC:
      {
        const rc_cic_stage_t *cs = (const rc_cic_stage_t *)ptr;
        size_t                b  = cic_state_bytes (cs->cic);
        if (cs->fir)
          b += fir_state_bytes (cs->fir);
        return b;
      }
    case RC_STAGE_RESAMP:
      return resamp_state_bytes ((const resamp_state_t *)ptr);
    }
  return 0;
}

static char *
_stage_get_state (rc_stage_t type, const void *ptr, char *p)
{
  switch (type)
    {
    case RC_STAGE_HB:
      hbdecim_get_state ((const hbdecim_state_t *)ptr, p);
      p += hbdecim_state_bytes ((const hbdecim_state_t *)ptr);
      break;
    case RC_STAGE_CIC:
      {
        const rc_cic_stage_t *cs = (const rc_cic_stage_t *)ptr;
        cic_get_state (cs->cic, p);
        p += cic_state_bytes (cs->cic);
        if (cs->fir)
          {
            fir_get_state (cs->fir, p);
            p += fir_state_bytes (cs->fir);
          }
      }
      break;
    case RC_STAGE_RESAMP:
      resamp_get_state ((const resamp_state_t *)ptr, p);
      p += resamp_state_bytes ((const resamp_state_t *)ptr);
      break;
    }
  return p;
}

static const char *
_stage_set_state (rc_stage_t type, void *ptr, const char *p)
{
  switch (type)
    {
    case RC_STAGE_HB:
      hbdecim_set_state ((hbdecim_state_t *)ptr, p);
      p += hbdecim_state_bytes ((const hbdecim_state_t *)ptr);
      break;
    case RC_STAGE_CIC:
      {
        rc_cic_stage_t *cs = (rc_cic_stage_t *)ptr;
        cic_set_state (cs->cic, p);
        p += cic_state_bytes (cs->cic);
        if (cs->fir)
          {
            fir_set_state (cs->fir, p);
            p += fir_state_bytes (cs->fir);
          }
      }
      break;
    case RC_STAGE_RESAMP:
      resamp_set_state ((resamp_state_t *)ptr, p);
      p += resamp_state_bytes ((const resamp_state_t *)ptr);
      break;
    }
  return p;
}

/*
 * Execute stage from (in, n_in) into (out, max_out).
 * Returns the number of output samples produced.
 */
static size_t
_stage_exec (rc_stage_t type, void *ptr, const float _Complex *in, size_t n_in,
             float _Complex *out, size_t max_out)
{
  switch (type)
    {
    case RC_STAGE_HB:
      return hbdecim_execute ((hbdecim_state_t *)ptr, in, n_in, out, max_out);
    case RC_STAGE_CIC:
      {
        rc_cic_stage_t *cs = (rc_cic_stage_t *)ptr;
        size_t          n  = cic_decimate (cs->cic, in, n_in, out, max_out);
        if (cs->fir)
          {
            /* Compensation FIR in-place: CIC output is already in out.
             * fir_execute() documents that in==out is safe. */
            n = fir_execute (cs->fir, out, n, out);
          }
        return n;
      }
    case RC_STAGE_RESAMP:
      return resamp_execute ((resamp_state_t *)ptr, in, n_in, out, max_out);
    default:
      return 0;
    }
}

/* ------------------------------------------------------------------ */
/* Build / destroy all stages                                          */
/* ------------------------------------------------------------------ */

static void
_destroy_all_stages (RateConverter_state_t *s)
{
  for (int i = 0; i < s->n_stages; i++)
    {
      _stage_destroy (s->stage_types[i], s->stage_ptrs[i]);
      s->stage_ptrs[i] = NULL;
    }
  s->n_stages = 0;
  free (s->bufs[0]);
  free (s->bufs[1]);
  s->bufs[0] = s->bufs[1] = NULL;
  s->buf_cap              = 0;
}

/*
 * Instantiate C stage objects from the plan.
 * Returns 1 on success, 0 on any allocation failure (partially-built
 * stages are cleaned up before returning).
 *
 * When s->pulse != RC_PULSE_NONE the terminal stage gets a pulse-shaped bank
 * instead of resamp's default Kaiser one, with any CIC droop folded into it.
 */
static int
_build_stages (RateConverter_state_t *s, const rc_plan_entry_t *plan, int n)
{
  int i;
  for (i = 0; i < n; i++)
    {
      void *obj      = NULL;
      int   terminal = (i == n - 1) && s->pulse != RC_PULSE_NONE;

      if (terminal)
        {
          /* Only a Resampler stage can carry a bank; _plan(force_terminal)
             guarantees one, so this is an assertion of that contract. */
          if (plan[i].type != RC_STAGE_RESAMP)
            goto fail;

          /* Droop compensation folds into the bank when an upstream CIC
             asked for it — same tap grid, so the fold is exact and this
             path never appends a comp FIR stage. */
          double  comp[_RC_COMP_NTAPS];
          double *compp = NULL;
          for (int k = 0; k < i; k++)
            if (plan[k].type == RC_STAGE_CIC && s->compensate)
              {
                ciccompmf (comp, _RC_CIC_ORDER, (uint32_t)plan[k].R,
                           _RC_COMP_NTAPS);
                compp = comp;
              }

          /* Symbol period on the TERMINAL stage's input grid: pulse_sps
             output samples per symbol, at this stage's rate. */
          double bank_sps = s->pulse_sps / plan[i].resamp_rate;
          size_t ntaps    = 0;
          float *bank = _build_bank (s->pulse, s->beta, bank_sps, s->pulse_sps,
                                     s->span, s->num_phases, compp,
                                     _RC_COMP_NTAPS, &ntaps);
          if (!bank)
            goto fail;
          obj = resamp_create_custom (s->num_phases, ntaps, bank,
                                      plan[i].resamp_rate);
          free (bank);
          if (!obj)
            goto fail;
          s->stage_types[i] = plan[i].type;
          s->stage_ptrs[i]  = obj;
          continue;
        }

      switch (plan[i].type)
        {
        case RC_STAGE_HB:
          obj = hbdecim_create (_HB_NTAPS, _HB_FIR);
          break;

        case RC_STAGE_CIC:
          {
            rc_cic_stage_t *cs = (rc_cic_stage_t *)calloc (1, sizeof (*cs));
            if (!cs)
              goto fail;
            cs->R          = plan[i].R;
            cs->compensate = plan[i].compensate;
            cs->cic        = cic_create ((uint32_t)plan[i].R);
            if (!cs->cic)
              {
                free (cs);
                goto fail;
              }
            if (plan[i].compensate)
              {
                /* 7-tap CIC droop compensator at the decimated rate. */
                double h64[7];
                ciccompmf (h64, 4, (uint32_t)plan[i].R, 7);
                float h32[7];
                for (int j = 0; j < 7; j++)
                  h32[j] = (float)h64[j];
                cs->fir = fir_create_real (h32, 7);
                if (!cs->fir)
                  {
                    cic_destroy (cs->cic);
                    free (cs);
                    goto fail;
                  }
              }
            obj = cs;
          }
          break;

        case RC_STAGE_RESAMP:
          obj = resamp_create (plan[i].resamp_rate);
          break;
        }

      if (!obj)
        goto fail;

      s->stage_types[i] = plan[i].type;
      s->stage_ptrs[i]  = obj;
    }
  s->n_stages = n;
  return 1;

fail:
  for (int j = 0; j < i; j++)
    {
      _stage_destroy (s->stage_types[j], s->stage_ptrs[j]);
      s->stage_ptrs[j] = NULL;
    }
  s->n_stages = 0;
  return 0;
}

/* ------------------------------------------------------------------ */
/* Public API                                                          */
/* ------------------------------------------------------------------ */

RateConverter_state_t *
RateConverter_create (double rate, int compensate)
{
  if (rate <= 0.0)
    return NULL;

  RateConverter_state_t *s = (RateConverter_state_t *)calloc (1, sizeof (*s));
  if (!s)
    return NULL;

  /* NOT the calloc default: RC_PULSE_NONE is 2 so that 0/1 line up with the
     receiver's IANDD/RRC vocabulary. */
  s->pulse      = RC_PULSE_NONE;
  s->rate       = rate;
  s->compensate = compensate;

  rc_plan_entry_t plan[RC_MAX_STAGES];
  int             n = _plan (rate, compensate, 0, plan);
  if (n == 0 || !_build_stages (s, plan, n))
    {
      free (s);
      return NULL;
    }
  return s;
}

RateConverter_state_t *
RateConverter_create_matched (double rate, int compensate, int pulse,
                              double beta, size_t span, double pulse_sps,
                              size_t num_phases)
{
  /* Written as !(x >= y) so a NaN parameter is rejected, not accepted. */
  if (!(rate > 0.0) || !(beta >= 0.0) || !(beta <= 1.0) || span < 1
      || !(pulse_sps > 0.0) || num_phases < 2u
      || (num_phases & (num_phases - 1u)) != 0u
      || (pulse != RC_PULSE_IANDD && pulse != RC_PULSE_RRC))
    return NULL;

  RateConverter_state_t *s = (RateConverter_state_t *)calloc (1, sizeof (*s));
  if (!s)
    return NULL;

  s->rate       = rate;
  s->compensate = compensate;
  s->pulse      = pulse;
  s->beta       = beta;
  s->span       = span;
  s->pulse_sps  = pulse_sps;
  s->num_phases = num_phases;
  /* The rectangle is exactly one symbol wide, so its matched filter is a
     boxcar of pulse_sps taps — a 2-3 tap sum below four samples per symbol. */
  s->narrow_pulse = (pulse == RC_PULSE_IANDD && pulse_sps < 4.0);

  rc_plan_entry_t plan[RC_MAX_STAGES];
  /* force_terminal: the terminal stage IS the matched filter and the timing
     element, so it exists even when the rate needs no correction. */
  int n = _plan (rate, compensate, 1, plan);
  /* The fold replaces the comp FIR — never both. */
  for (int i = 0; i < n; i++)
    plan[i].compensate = 0;
  if (n == 0 || !_build_stages (s, plan, n))
    {
      free (s);
      return NULL;
    }
  return s;
}

bool
RateConverter_get_clipped (const RateConverter_state_t *s)
{
  for (int i = 0; i < s->n_stages; i++)
    if (s->stage_types[i] == RC_STAGE_CIC
        && ((const rc_cic_stage_t *)s->stage_ptrs[i])->cic->clipped)
      return 1;
  return 0;
}

void
RateConverter_destroy (RateConverter_state_t *s)
{
  if (!s)
    return;
  _destroy_all_stages (s);
  free (s);
}

void
RateConverter_reset (RateConverter_state_t *s)
{
  for (int i = 0; i < s->n_stages; i++)
    _stage_reset (s->stage_types[i], s->stage_ptrs[i]);
}

/* ── Serializable state — concatenate the active stages in cascade order ────
 */

size_t
RateConverter_state_bytes (const RateConverter_state_t *s)
{
  size_t b = sizeof (dp_state_hdr_t);
  for (int i = 0; i < s->n_stages; i++)
    b += _stage_state_bytes (s->stage_types[i], s->stage_ptrs[i]);
  return b;
}

void
RateConverter_get_state (const RateConverter_state_t *s, void *blob)
{
  dp_writer_t w = dp_writer_init (blob, RateConverter_state_bytes (s));
  dp_w_hdr (&w, RC_STATE_MAGIC, RC_STATE_VERSION,
            RateConverter_state_bytes (s));
  char *p = (char *)blob + sizeof (dp_state_hdr_t);
  for (int i = 0; i < s->n_stages; i++)
    p = _stage_get_state (s->stage_types[i], s->stage_ptrs[i], p);
}

int
RateConverter_set_state (RateConverter_state_t *s, const void *blob)
{
  int rc = dp_state_validate (blob, RateConverter_state_bytes (s),
                              RC_STATE_MAGIC, RC_STATE_VERSION);
  if (rc != DP_OK)
    return rc;
  const char *p = (const char *)blob + sizeof (dp_state_hdr_t);
  for (int i = 0; i < s->n_stages; i++)
    p = _stage_set_state (s->stage_types[i], s->stage_ptrs[i], p);
  return DP_OK;
}

size_t
RateConverter_execute (RateConverter_state_t *s, const float _Complex *in,
                       size_t n_in, float _Complex *out, size_t max_out)
{
  if (s->n_stages == 0)
    return 0;

  /* A pulse-shaped bank is laid out for the unified accumulator (arm p
     advances the sampling instant), while resamp_execute()'s decimating path
     is transposed-form and indexes arms the other way — different algorithms,
     not just different code paths. So a matched cascade always runs through
     the accumulator, at zero deviation. One structure, one bank layout. */
  if (s->pulse != RC_PULSE_NONE)
    return RateConverter_execute_ctrl (s, in, n_in, 0.0, out, max_out);

  /* Grow ping-pong buffers lazily to n_in on first call. */
  if (n_in > s->buf_cap)
    {
      free (s->bufs[0]);
      free (s->bufs[1]);
      s->bufs[0] = (float _Complex *)malloc (n_in * sizeof (float _Complex));
      s->bufs[1] = (float _Complex *)malloc (n_in * sizeof (float _Complex));
      if (!s->bufs[0] || !s->bufs[1])
        {
          free (s->bufs[0]);
          free (s->bufs[1]);
          s->bufs[0] = s->bufs[1] = NULL;
          s->buf_cap              = 0;
          return 0;
        }
      s->buf_cap = n_in;
    }

  if (s->n_stages == 1)
    return _stage_exec (s->stage_types[0], s->stage_ptrs[0], in, n_in, out,
                        max_out);

  /* Multi-stage: route through ping-pong intermediate buffers. */
  const float _Complex *src  = in;
  size_t                n    = n_in;
  int                   ping = 0;

  for (int i = 0; i < s->n_stages - 1; i++)
    {
      float _Complex *dst = s->bufs[ping];
      n   = _stage_exec (s->stage_types[i], s->stage_ptrs[i], src, n, dst,
                         s->buf_cap);
      src = dst;
      ping ^= 1;
    }
  return _stage_exec (s->stage_types[s->n_stages - 1],
                      s->stage_ptrs[s->n_stages - 1], src, n, out, max_out);
}

/* Run a resamp stage with a constant rate deviation on every input — the
 * scalar control-port form, built on the per-input streaming push. */
static size_t
_resamp_exec_ctrl (resamp_state_t *r, const float _Complex *in, size_t n_in,
                   double ctrl, float _Complex *out, size_t max_out)
{
  size_t oi = 0;
  for (size_t i = 0; i < n_in && oi < max_out; i++)
    oi += resamp_execute_ctrl_push (r, in[i], ctrl, out + oi, max_out - oi);
  return oi;
}

size_t
RateConverter_execute_ctrl (RateConverter_state_t *s, const float _Complex *x,
                            size_t n_in, double ctrl, float _Complex *out,
                            size_t max_out)
{
  if (s->n_stages == 0)
    return 0;
  int last = s->n_stages - 1;
  /* Only a terminal Resampler stage has a steerable fractional accumulator; a
     pure integer HB/CIC cascade has nothing to steer → un-steered execute. */
  if (s->stage_types[last] != RC_STAGE_RESAMP)
    return RateConverter_execute (s, x, n_in, out, max_out);

  /* Grow ping-pong buffers lazily to n_in (mirrors RateConverter_execute). */
  if (n_in > s->buf_cap)
    {
      free (s->bufs[0]);
      free (s->bufs[1]);
      s->bufs[0] = (float _Complex *)malloc (n_in * sizeof (float _Complex));
      s->bufs[1] = (float _Complex *)malloc (n_in * sizeof (float _Complex));
      if (!s->bufs[0] || !s->bufs[1])
        {
          free (s->bufs[0]);
          free (s->bufs[1]);
          s->bufs[0] = s->bufs[1] = NULL;
          s->buf_cap              = 0;
          return 0;
        }
      s->buf_cap = n_in;
    }

  if (s->n_stages == 1)
    return _resamp_exec_ctrl ((resamp_state_t *)s->stage_ptrs[0], x, n_in,
                              ctrl, out, max_out);

  /* Upstream integer stages run plain; the terminal Resampler is steered. */
  const float _Complex *src  = x;
  size_t                n    = n_in;
  int                   ping = 0;
  for (int i = 0; i < last; i++)
    {
      float _Complex *dst = s->bufs[ping];
      n   = _stage_exec (s->stage_types[i], s->stage_ptrs[i], src, n, dst,
                         s->buf_cap);
      src = dst;
      ping ^= 1;
    }
  return _resamp_exec_ctrl ((resamp_state_t *)s->stage_ptrs[last], src, n,
                            ctrl, out, max_out);
}

size_t
RateConverter_execute_ctrl_push (RateConverter_state_t *s, float _Complex x,
                                 double ctrl, float _Complex *out,
                                 size_t max_out)
{
  if (s->n_stages == 0 || max_out == 0)
    return 0;
  int last = s->n_stages - 1;

  /* Every non-terminal stage is an integer decimator (the planner only ever
     puts HB/CIC ahead of the fractional tail), so one input yields at most one
     intermediate sample and two scalars suffice — no buffers, no allocation
     on the per-sample path. */
  float _Complex cur = x;
  size_t n           = 1;
  for (int i = 0; i < last; i++)
    {
      float _Complex nxt;
      n = _stage_exec (s->stage_types[i], s->stage_ptrs[i], &cur, 1, &nxt, 1);
      if (n == 0)
        return 0; /* stage swallowed it (between decimation strobes) */
      cur = nxt;
    }

  if (s->stage_types[last] != RC_STAGE_RESAMP)
    return _stage_exec (s->stage_types[last], s->stage_ptrs[last], &cur, 1,
                        out, max_out);
  return resamp_execute_ctrl_push ((resamp_state_t *)s->stage_ptrs[last], cur,
                                   ctrl, out, max_out);
}

size_t
RateConverter_execute_max_out (RateConverter_state_t *s)
{
  /* Upper bound for a 65536-sample input at the current rate.
   * For interpolation (rate > 1) the buffer is ceil(65536 * rate) + 2. */
  return (size_t)(65536.0 * (s->rate > 1.0 ? s->rate : 1.0)) + 2;
}

double
RateConverter_get_rate (const RateConverter_state_t *s)
{
  return s->rate;
}

void
RateConverter_set_rate (RateConverter_state_t *s, double rate)
{
  if (rate <= 0.0)
    return;

  int             matched = s->pulse != RC_PULSE_NONE;
  rc_plan_entry_t plan[RC_MAX_STAGES];
  int             n = _plan (rate, s->compensate, matched, plan);
  if (n == 0)
    return;
  if (matched)
    for (int i = 0; i < n; i++)
      plan[i].compensate = 0;

  _destroy_all_stages (s);
  s->rate = rate;

  if (!_build_stages (s, plan, n))
    s->n_stages = 0;
}

bool
RateConverter_get_narrow_pulse (const RateConverter_state_t *s)
{
  return s->narrow_pulse;
}

size_t
RateConverter_num_stages (const RateConverter_state_t *s)
{
  return (size_t)s->n_stages;
}

const char *
RateConverter_stages_value (const RateConverter_state_t *s, size_t i)
{
  /* Thread-local so concurrent readers cannot tread on each other; the
     binding converts to a Python string before this thread calls again. */
  static _Thread_local char buf[64];
  if (i >= (size_t)s->n_stages)
    return NULL;
  /* stage_label takes a mutable state only because it predates this
     accessor; it reads nothing mutable. */
  if (!RateConverter_stage_label ((RateConverter_state_t *)s, (int)i, buf,
                                  sizeof buf))
    return NULL;
  return buf;
}

/* The bank shape is a 2-element sequence, empty when the cascade ends in an
   integer decimator and therefore has no polyphase bank to describe. */
size_t
RateConverter_num_bank_shape (const RateConverter_state_t *s)
{
  if (s->n_stages == 0 || s->stage_types[s->n_stages - 1] != RC_STAGE_RESAMP)
    return 0;
  return 2;
}

size_t
RateConverter_bank_shape_value (const RateConverter_state_t *s, size_t i)
{
  const resamp_state_t *r
      = (const resamp_state_t *)s->stage_ptrs[s->n_stages - 1];
  return i == 0 ? resamp_get_num_phases (r) : resamp_get_num_taps (r);
}

size_t
RateConverter_execute_ctrl_max_out (RateConverter_state_t *s)
{
  (void)s;
  return 0; /* 0 -> the binding sizes the buffer from the input block */
}

size_t
RateConverter_execute_ctrl_push_max_out (RateConverter_state_t *s)
{
  double rate = s->rate;
  return (size_t)(rate > 1.0 ? rate : 1.0) + 2;
}

int
RateConverter_stage_label (RateConverter_state_t *s, int i, char *buf,
                           size_t len)
{
  if (i < 0 || i >= s->n_stages)
    return 0;

  switch (s->stage_types[i])
    {
    case RC_STAGE_HB:
      snprintf (buf, len, "HalfbandDecimator");
      break;
    case RC_STAGE_CIC:
      {
        rc_cic_stage_t *cs = (rc_cic_stage_t *)s->stage_ptrs[i];
        if (cs->compensate)
          snprintf (buf, len, "CIC(%d)+FIR", cs->R);
        else
          snprintf (buf, len, "CIC(%d)", cs->R);
      }
      break;
    case RC_STAGE_RESAMP:
      {
        double r = resamp_get_rate ((resamp_state_t *)s->stage_ptrs[i]);
        /* Only the terminal stage can carry a pulse-shaped bank; naming it
           is how a caller sees that the matched filter is IN the cascade
           rather than a stage someone still has to append. */
        if (i == s->n_stages - 1 && s->pulse == RC_PULSE_RRC)
          snprintf (buf, len, "Resampler(%g,rrc)", r);
        else if (i == s->n_stages - 1 && s->pulse == RC_PULSE_IANDD)
          snprintf (buf, len, "Resampler(%g,iandd)", r);
        else
          snprintf (buf, len, "Resampler(%g)", r);
      }
      break;
    default:
      snprintf (buf, len, "Unknown");
      break;
    }
  return 1;
}

size_t
RateConverter_convert (double rate, int compensate, const float _Complex *in,
                       size_t n_in, float _Complex *out, size_t max_out)
{
  RateConverter_state_t *rc = RateConverter_create (rate, compensate);
  if (!rc)
    return 0;
  size_t n = RateConverter_execute (rc, in, n_in, out, max_out);
  RateConverter_destroy (rc);
  return n;
}
