[cic]
arg_type = "float _Complex"
return_type = "float _Complex"
mutable = "false"
no_state = "true"
no_step = "true"
class_name = "CIC"

[[cic.init_params]]
name = "R"
type = "uint32_t"
default = "16"

[[cic.methods]]
name = "reconfigure"
arg_type = "void"
return_type = "void"
params = [{name = "R", type = "uint32_t"}]

[[cic.methods]]
name = "decimate"
arg_type = "float _Complex"
return_type = "float _Complex"
variable_output = true

[[cic.properties]]
name = "R"
type = "uint32_t"
field = true

[[cic.properties]]
name = "shift"
type = "uint32_t"
field = true
