[ddc]
arg_type = "float _Complex"
return_type = "float _Complex"
mutable = "false"
no_state = "true"
no_step = "true"
class_name = "DDC"
depends_on = [{ name = "lo", link = true }, { name = "RateConverter", link = true }, { name = "resamp", link = true }, { name = "hbdecim", link = true }, { name = "hbdecim_r2c", link = true }, { name = "cic", link = true }, { name = "fir", link = true }, { name = "resample", link = true }]

[[ddc.init_params]]
name = "norm_freq"
type = "double"
default = "0.0"

[[ddc.init_params]]
name = "rate"
type = "double"
default = "0.25"

[[ddc.methods]]
name = "execute"
doc = "Mix input block with LO, then rate-convert."
arg_type = "void"
return_type = "float _Complex"
variable_output = true
pass_capacity = true
nogil = true
params = [{name = "x", type = "float _Complex[]"}]

[[ddc.methods]]
name = "reset"
doc = "Zero LO phase and filter history."
arg_type = "void"
return_type = "void"

[[ddc.properties]]
name = "norm_freq"
type = "double"
writable = true

[[ddc.properties]]
name = "rate"
type = "double"
