[hbdecim_q15]
arg_type = "int16_t"
return_type = "int16_t"
mutable = "false"
no_state = "true"
no_step = "true"
class_name = "HBDecimQ15"
serializable = "true"

[[hbdecim_q15.init_params]]
name = "h"
type = "float[]"

[[hbdecim_q15.methods]]
name = "execute"
arg_type = "void"
return_type = "int16_t"
variable_output = true
params = [{name = "x", type = "int16_t[]"}]

[[hbdecim_q15.methods]]
name = "reset"
arg_type = "void"
return_type = "void"

[[hbdecim_q15.properties]]
name = "num_taps"
type = "size_t"

[[hbdecim_q15.properties]]
name = "rate"
type = "double"
