[i16u32_to_f32]
arg_type = "uint32_t"
return_type = "float"
mutable = "false"
no_state = "true"
no_step = "false"
class_name = "I16U32ToF32"

[[i16u32_to_f32.init_params]]
name = "scale"
type = "float"
default = "32768.0f"
