[i32_to_f32]
arg_type = "int32_t"
return_type = "float"
mutable = "false"
no_state = "true"
no_step = "false"
class_name = "I32ToF32"

[[i32_to_f32.init_params]]
name = "scale"
type = "float"
default = "2147483648.0f"
