/*
 * wfm_compose_bridge.h — straight-C seams of the `wfm_compose` composer
 * (generated by jm; gh-998).
 *
 * Every function declared here is written by THIS PROJECT, in plain C, and
 * called by the generated binding. The declarations are jm's so that there
 * is exactly one of each: include this header from a test, a benchmark or a
 * sibling component rather than re-declaring a signature jm already owns.
 */
#ifndef DP_WFM_COMPOSE_BRIDGE_H
#define DP_WFM_COMPOSE_BRIDGE_H

#include "doppler/wfm/wfm_compose.h"
#include "doppler/wfm_synth/wfm_synth_core.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Build the composed generator from a source config (source -> generator). */
dp_wfm_synth_state_t *dp_wfm_source_to_synth(const wfm_source_t *, double);

/* Why dp_wfm_source_to_synth() refused: a reason raised as ValueError, or NULL
 * for none (RuntimeError). Same arguments; called only after it returned
 * NULL (gh-1307). */
const char *dp_wfm_source_to_synth_error(const wfm_source_t *, double);

/* Read a str as the bits of `bits`, `acq_code`, `data_code`, `sync`
 * (coerce_str_fn, gh-1709): out NULL sizes; returns the bit count, or 0
 * with *why set on a refusal. */
size_t dp_wfm_source_bits_refuse_text(const char *, uint8_t *, size_t, const char **);

#ifdef __cplusplus
}
#endif

#endif /* DP_WFM_COMPOSE_BRIDGE_H */
