/**
 * @file bench_ddc_hb2.c
 * @brief Three-way DDC pipeline benchmark.
 *
 * Compares three configurations for each total decimation rate:
 *   (A) Plain DDC    — 0.4/0.6 DPMFS at rate r  (default)
 *   (B) HB → DDC    — halfband (÷2) → 0.4/0.6 DDC at rate 2r
 *   (C) DDC → HB    — 0.2/0.8 DPMFS at rate 2r → halfband (÷2)
 *
 * Config (C) exploits the 3× wider transition band of 0.2/0.8 to cut
 * the DPMFS tap count from N=19 to N=7 while keeping M=3 and 60 dB
 * stopband rejection.  Running at rate 2r doubles the output, but
 * 4×(M+1)×7 = 56 vs 4×(M+1)×19 = 76 ops/input — net 26% fewer MACs.
 *
 * HB uses 60 dB Kaiser halfband (n_fir=19, N=19 FIR branch).
 * All throughputs are effective input MSamples/s at the original rate.
 *
 * Run with: ./bench_ddc_hb2_c
 */

#include <dp/ddc.h>
#include <dp/hbdecim.h>

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

#define BLOCK_SIZE 65536
#define ITERATIONS 200

/* ------------------------------------------------------------------ */
/* Timer                                                               */
/* ------------------------------------------------------------------ */

static double
elapsed_sec (struct timespec *t0, struct timespec *t1)
{
  return (double)(t1->tv_sec - t0->tv_sec)
         + (double)(t1->tv_nsec - t0->tv_nsec) * 1e-9;
}

/* ------------------------------------------------------------------ */
/* 0.2/0.8 DPMFS coefficients: M=3, N=7 (60 dB, fit_rms=1.54e-04)   */
/* Generated by:                                                       */
/*   _, bank = kaiser_prototype(atten=60, passband=0.2, stopband=0.8) */
/*   fit_dpmfs(bank, M=3)                                             */
/* ------------------------------------------------------------------ */

#define DPMFS28_M 3
#define DPMFS28_N 7

/* clang-format off */
static const float s_dpmfs28_c0[(DPMFS28_M + 1) * DPMFS28_N] = {
    /* m=0 */
    -2.39651999e-05f,  2.06220965e-03f, -1.23678846e-02f,  9.98494506e-01f,
     1.44633986e-02f, -2.76785181e-03f,  1.64894009e-05f,
    /* m=1 */
     1.13854744e-03f, -5.75938486e-02f,  3.37066054e-01f,  5.29944636e-02f,
    -4.07487094e-01f,  7.83771127e-02f, -1.49898828e-04f,
    /* m=2 */
     1.72820631e-02f, -1.04729109e-01f,  3.73803705e-01f, -5.66931307e-01f,
     3.50842178e-01f, -8.31104964e-02f,  3.24767811e-04f,
    /* m=3 */
    -4.47622593e-03f,  5.48459701e-02f, -1.29266396e-01f,  1.32168114e-01f,
    -6.87601939e-02f,  2.26346701e-02f, -1.97919973e-04f,
};

static const float s_dpmfs28_c1[(DPMFS28_M + 1) * DPMFS28_N] = {
    /* m=0 */
     1.37665793e-02f, -1.04688279e-01f,  5.67895234e-01f,  6.18097007e-01f,
    -1.11728728e-01f,  1.53254392e-02f,  0.00000000e+00f,
    /* m=1 */
     2.05764715e-02f, -1.01112239e-01f,  6.95320010e-01f, -6.81986928e-01f,
     8.70639384e-02f, -2.10449323e-02f,  0.00000000e+00f,
    /* m=2 */
    -7.59944553e-03f,  1.15273163e-01f, -1.16730273e-01f, -6.53096884e-02f,
     8.43984708e-02f, -7.36867310e-04f,  0.00000000e+00f,
    /* m=3 */
    -2.43786387e-02f,  7.78500289e-02f, -1.47918329e-01f,  1.43865705e-01f,
    -6.27691671e-02f,  6.71317056e-03f,  0.00000000e+00f,
};
/* clang-format on */

/* ------------------------------------------------------------------ */
/* Kaiser halfband FIR branch (60 dB, n_fir=19, N=19)                */
/* ------------------------------------------------------------------ */

static double
bessel_i0 (double x)
{
  double sum = 1.0, term = 1.0;
  for (int k = 1; k < 30; k++)
    {
      term *= (x / (2.0 * k)) * (x / (2.0 * k));
      sum += term;
      if (term < 1e-20 * sum)
        break;
    }
  return sum;
}

static double
kaiser_win (int n, int N, double beta)
{
  double mid = (N - 1) / 2.0;
  double arg = 2.0 * (n - mid) / (N - 1);
  return bessel_i0 (beta * sqrt (1.0 - arg * arg)) / bessel_i0 (beta);
}

static float *
build_hb_fir (int n_fir, double atten, size_t *N_out)
{
  int M = n_fir - 1;
  int htaps = 2 * M + 1;
  double beta = (atten > 50.0)    ? 0.1102 * (atten - 8.7)
                : (atten >= 21.0) ? 0.5842 * pow (atten - 21.0, 0.4)
                                        + 0.07886 * (atten - 21.0)
                                  : 0.0;

  double *h = calloc ((size_t)htaps, sizeof (double));
  for (int n = 0; n < htaps; n++)
    {
      double w = kaiser_win (n, htaps, beta);
      double m = n - M;
      double s = (m == 0.0) ? 0.5 : sin (0.5 * M_PI * m) / (M_PI * m);
      h[n] = w * s * 2.0;
    }

  size_t N = (size_t)M + 1;
  float *bank0 = malloc (N * sizeof (float));
  float *bank1 = malloc (N * sizeof (float));
  for (size_t k = 0; k < N; k++)
    {
      bank0[k] = (2 * k < (size_t)htaps) ? (float)h[2 * k] : 0.0f;
      bank1[k] = (2 * k + 1 < (size_t)htaps) ? (float)h[2 * k + 1] : 0.0f;
    }
  free (h);

  size_t centre = N / 2;
  float *fir_branch;
  if (fabsf (bank0[centre]) > fabsf (bank1[centre]))
    {
      fir_branch = bank1;
      free (bank0);
    }
  else
    {
      fir_branch = bank0;
      free (bank1);
    }

  *N_out = N;
  return fir_branch;
}

/* ------------------------------------------------------------------ */
/* Benchmark runners                                                   */
/* ------------------------------------------------------------------ */

/* (A) Plain DDC: default 0.4/0.6 at rate r. */
static double
bench_plain_ddc (float norm_freq, double rate, const dp_cf32_t *in,
                 dp_cf32_t *out)
{
  dp_ddc_t *ddc = dp_ddc_create (norm_freq, BLOCK_SIZE, rate);
  if (!ddc)
    return 0.0;
  size_t max_out = dp_ddc_max_out (ddc);
  dp_ddc_execute (ddc, in, BLOCK_SIZE, out, max_out);
  dp_ddc_reset (ddc);

  struct timespec t0, t1;
  clock_gettime (CLOCK_MONOTONIC, &t0);
  for (int i = 0; i < ITERATIONS; i++)
    dp_ddc_execute (ddc, in, BLOCK_SIZE, out, max_out);
  clock_gettime (CLOCK_MONOTONIC, &t1);
  dp_ddc_destroy (ddc);
  return (double)ITERATIONS * BLOCK_SIZE / elapsed_sec (&t0, &t1) / 1e6;
}

/* (B) HB → DDC: halfband ÷2, then default 0.4/0.6 DDC at rate 2r. */
static double
bench_hb_then_ddc (float norm_freq, double rate, size_t hb_N,
                   const float *hb_fir, const dp_cf32_t *in, dp_cf32_t *mid,
                   dp_cf32_t *out)
{
  dp_hbdecim_cf32_t *hb = dp_hbdecim_cf32_create (hb_N, hb_fir);
  size_t hb_max_out = BLOCK_SIZE / 2 + hb_N + 2;
  dp_ddc_t *ddc = dp_ddc_create (norm_freq, BLOCK_SIZE / 2, rate * 2.0);
  if (!hb || !ddc)
    return 0.0;
  size_t ddc_max = dp_ddc_max_out (ddc);

  size_t n;
  n = dp_hbdecim_cf32_execute (hb, in, BLOCK_SIZE, mid, hb_max_out);
  dp_ddc_execute (ddc, mid, n, out, ddc_max);
  dp_hbdecim_cf32_reset (hb);
  dp_ddc_reset (ddc);

  struct timespec t0, t1;
  clock_gettime (CLOCK_MONOTONIC, &t0);
  for (int i = 0; i < ITERATIONS; i++)
    {
      n = dp_hbdecim_cf32_execute (hb, in, BLOCK_SIZE, mid, hb_max_out);
      dp_ddc_execute (ddc, mid, n, out, ddc_max);
    }
  clock_gettime (CLOCK_MONOTONIC, &t1);
  dp_hbdecim_cf32_destroy (hb);
  dp_ddc_destroy (ddc);
  return (double)ITERATIONS * BLOCK_SIZE / elapsed_sec (&t0, &t1) / 1e6;
}

/* (C) DDC → HB: custom 0.2/0.8 DDC at rate 2r, then halfband ÷2. */
static double
bench_ddc28_then_hb (float norm_freq, double rate, size_t hb_N,
                     const float *hb_fir, const dp_cf32_t *in, dp_cf32_t *mid,
                     dp_cf32_t *out)
{
  dp_resamp_dpmfs_t *r = dp_resamp_dpmfs_create (
      DPMFS28_M, DPMFS28_N, s_dpmfs28_c0, s_dpmfs28_c1, rate * 2.0);
  dp_ddc_t *ddc = dp_ddc_create_custom (norm_freq, BLOCK_SIZE, r);
  if (!ddc)
    return 0.0;
  size_t ddc_max = dp_ddc_max_out (ddc);

  size_t mid_cap = ddc_max + hb_N + 4;
  dp_hbdecim_cf32_t *hb = dp_hbdecim_cf32_create (hb_N, hb_fir);
  size_t hb_max = mid_cap / 2 + 2;
  if (!hb)
    {
      dp_ddc_destroy (ddc);
      return 0.0;
    }

  size_t n;
  n = dp_ddc_execute (ddc, in, BLOCK_SIZE, mid, ddc_max);
  dp_hbdecim_cf32_execute (hb, mid, n, out, hb_max);
  dp_ddc_reset (ddc);
  dp_hbdecim_cf32_reset (hb);

  struct timespec t0, t1;
  clock_gettime (CLOCK_MONOTONIC, &t0);
  for (int i = 0; i < ITERATIONS; i++)
    {
      n = dp_ddc_execute (ddc, in, BLOCK_SIZE, mid, ddc_max);
      dp_hbdecim_cf32_execute (hb, mid, n, out, hb_max);
    }
  clock_gettime (CLOCK_MONOTONIC, &t1);
  dp_ddc_destroy (ddc);
  dp_hbdecim_cf32_destroy (hb);
  return (double)ITERATIONS * BLOCK_SIZE / elapsed_sec (&t0, &t1) / 1e6;
}

/* ------------------------------------------------------------------ */
/* Main                                                                */
/* ------------------------------------------------------------------ */

int
main (void)
{
  printf ("=== Three-way DDC pipeline benchmark ===\n");
  printf ("  block=%d  iters=%d\n", BLOCK_SIZE, ITERATIONS);
  printf ("  (A) plain DDC      0.4/0.6 M=3 N=19 at rate r\n");
  printf ("  (B) HB → DDC      HB(60dB,N=19) ÷2, then 0.4/0.6 at 2r\n");
  printf ("  (C) DDC → HB      0.2/0.8 M=3 N=7 at 2r, then HB(60dB) ÷2\n");
  printf ("  All MSa/s relative to original input rate.\n\n");

  size_t hb_N;
  float *hb_fir = build_hb_fir (19, 60.0, &hb_N);

  dp_cf32_t *input = malloc (BLOCK_SIZE * sizeof *input);
  dp_cf32_t *mid = malloc ((BLOCK_SIZE * 2 + 64) * sizeof *mid);
  dp_cf32_t *output = malloc ((BLOCK_SIZE * 2 + 64) * sizeof *output);
  if (!input || !mid || !output || !hb_fir)
    {
      fprintf (stderr, "allocation failed\n");
      return 1;
    }

  for (size_t i = 0; i < BLOCK_SIZE; i++)
    {
      double t0 = 2.0 * M_PI * 0.05 * (double)i;
      double t1 = 2.0 * M_PI * 0.23 * (double)i;
      input[i].i = (float)(cos (t0) + cos (t1));
      input[i].q = (float)(sin (t0) + sin (t1));
    }

  const float norm_freq = -0.05f;

  struct
  {
    double rate;
    const char *label;
  } cases[] = {
    { 0.5, "2x decim" },  { 0.25, "4x decim" },   { 0.125, "8x decim" },
    { 0.1, "10x decim" }, { 0.01, "100x decim" },
  };
  size_t ncases = sizeof cases / sizeof cases[0];

  printf ("  %-10s  %-12s  %10s  %10s  %10s\n", "rate", "config", "(A)plain",
          "(B)HB→DDC", "(C)DDC→HB");
  printf ("  %-10s  %-12s  %10s  %10s  %10s\n", "----------", "------------",
          " MSa/s", " MSa/s", " MSa/s");

  for (size_t i = 0; i < ncases; i++)
    {
      double a = bench_plain_ddc (norm_freq, cases[i].rate, input, output);
      double b = bench_hb_then_ddc (norm_freq, cases[i].rate, hb_N, hb_fir,
                                    input, mid, output);
      double c = bench_ddc28_then_hb (norm_freq, cases[i].rate, hb_N, hb_fir,
                                      input, mid, output);
      printf ("  %-10.4f  %-12s  %10.1f  %10.1f  %10.1f\n", cases[i].rate,
              cases[i].label, a, b, c);
    }

  printf ("\n");
  free (input);
  free (mid);
  free (output);
  free (hb_fir);
  return 0;
}
