/*
 * test_wfm_frame.c — the frame descriptor: geometry, materialisation, CRC.
 *
 * The descriptor exists so that a frame's layout is stated ONCE and read from
 * both ends. Its value is therefore entirely in agreement — between the
 * offsets it reports and the bits it writes, between a generated field here
 * and the same field regenerated by a receiver holding the same numbers, and
 * between this and the DSSS assembler it now backs (that last one is checked
 * where it belongs, by test_wfm_dsp's existing round-trips staying
 * bit-identical across the refactor).
 *
 * `wfm_frame_crc_ok` gets particular attention because it is what makes a
 * TRUTH-FREE frame error rate possible: it needs the layout and the received
 * bits and no payload truth at all, which is the one metric that works on a
 * real capture AND still catches a false lock.
 */
#define _GNU_SOURCE
#include "dp_test.h"
#include "wfm/wfm_frame.h"

#include "pn/pn_core.h"

#include <stdio.h>
#include <string.h>

#define CAP 4096

static uint8_t buf[CAP];

int
main (void)
{
  /* ── geometry: the offsets and the bits must agree ──────────────────── */
  {
    static const uint8_t sync_bits[13]
        = { 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1 }; /* Barker-13 */
    wfm_frame_t f      = { 0 };
    f.preamble.kind    = WFM_SEQ_DOTTED;
    f.preamble.len     = 8;
    f.preamble_reps    = 4;
    f.sync.kind        = WFM_SEQ_LITERAL;
    f.sync.bits        = sync_bits;
    f.sync.len         = 13;
    f.payload.kind     = WFM_SEQ_PN;
    f.payload.len      = 100;
    f.payload.reg_bits = 7;
    f.payload.seed     = 1;
    f.crc              = 1;

    wfm_frame_layout_t l;
    DP_REQUIRE_MSG (wfm_frame_layout (&f, &l) == 0, "layout");
    DP_REQUIRE_MSG (l.preamble_off == 0 && l.preamble_bits == 32,
                    "preamble is len*reps at the front");
    DP_REQUIRE_MSG (l.sync_off == 32 && l.sync_bits == 13, "sync follows");
    DP_REQUIRE_MSG (l.payload_off == 45 && l.payload_bits == 100, "payload");
    DP_REQUIRE_MSG (l.crc_off == 145 && l.crc_bits == 16, "crc trails");
    DP_REQUIRE_MSG (l.total_bits == 161, "total");
    DP_REQUIRE_MSG (wfm_frame_nbits (&f) == l.total_bits,
                    "nbits agrees with the layout it summarises");

    size_t n = wfm_frame_bits (&f, buf, CAP);
    DP_REQUIRE_MSG (n == l.total_bits, "bits written == total");
    for (size_t i = 0; i < n; i++)
      DP_REQUIRE_MSG (buf[i] <= 1, "every output is 0 or 1");

    /* The fields land WHERE the layout says. A descriptor whose offsets and
       whose bytes disagree is worse than no descriptor: both ends would be
       reading one and writing the other. */
    for (size_t i = 0; i < 32; i++)
      DP_REQUIRE_MSG (buf[l.preamble_off + i] == (i % 2 == 0),
                      "dotted preamble is 1010...");
    DP_REQUIRE_MSG (
        memcmp (buf + l.sync_off, sync_bits, 13) == 0,
        "the literal sync word appears verbatim at its stated offset");

    /* A repeated preamble must REPEAT -- period is what a coherent
       integration across reps depends on, so a generated preamble drawing
       fresh bits per rep would be a different waveform entirely. */
    for (size_t r = 1; r < 4; r++)
      DP_REQUIRE_MSG (memcmp (buf, buf + r * 8, 8) == 0,
                      "every preamble repetition is identical");
  }

  /* ── generated fields regenerate from the descriptor alone ──────────── */
  {
    wfm_frame_t f      = { 0 };
    f.payload.kind     = WFM_SEQ_PN;
    f.payload.len      = 300;
    f.payload.reg_bits = 9;
    f.payload.seed     = 7;

    size_t n = wfm_frame_bits (&f, buf, CAP);
    DP_REQUIRE_MSG (n == 300, "pn payload materialises");

    /* The receiver's side: the same three numbers, through pn directly. This
       is the whole argument for generated kinds -- truth for a long record
       without carrying the array, and a capture reproducible from its
       metadata. If these ever diverge, every regenerated-truth BER is scored
       against the wrong sequence.

       NOTE the poly: `pn_mls_poly (9)`, not the descriptor's literal 0.
       pn_create() takes the tap mask verbatim, so a 0 there is a register
       with NO FEEDBACK. This comparison used to pass `0` on both sides and
       agreed perfectly -- on two all-zero sequences. That is what a
       consistency test does when the defect is shared: it confirms the two
       halves match and says nothing about whether either is a PN. */
    static uint8_t want[300];
    pn_state_t    *p = pn_create (pn_mls_poly (9), 7, 9, 0);
    DP_REQUIRE_MSG (p != NULL, "pn_create");
    DP_REQUIRE_MSG (pn_generate (p, 300, want, 300) == 300, "pn_generate");
    pn_destroy (p);
    DP_REQUIRE_MSG (memcmp (buf, want, 300) == 0,
                    "a PN field IS pn_generate of its own descriptor");

    /* And the property no agreement between two halves can establish: the
       sequence is actually MAXIMAL-LENGTH. One full period of a length-n MLS
       carries exactly 2^(n-1) ones, so a balance check over 2^n-1 bits is a
       direct, cheap test that the descriptor resolved a real polynomial. It
       reads 1 against 256 when it does not. */
    {
      wfm_frame_t bal      = { 0 };
      bal.payload.kind     = WFM_SEQ_PN;
      bal.payload.len      = 511; /* one period of a 9-bit register */
      bal.payload.reg_bits = 9;
      bal.payload.seed     = 7;
      size_t ones          = 0;
      DP_REQUIRE_MSG (wfm_frame_bits (&bal, buf, CAP) == 511, "one period");
      for (size_t i = 0; i < 511; i++)
        ones += buf[i];
      DP_REQUIRE_MSG (ones == 256,
                      "a default-poly PN field is BALANCED over its period "
                      "-- i.e. it is maximal-length, not a drained register");
    }

    /* Same descriptor, same bits, every time. */
    static uint8_t again[300];
    DP_REQUIRE_MSG (wfm_frame_bits (&f, again, 300) == 300, "second build");
    DP_REQUIRE_MSG (memcmp (buf, again, 300) == 0, "deterministic");
  }

  /* ── the CRC: what makes a truth-free FER possible ──────────────────── */
  {
    wfm_frame_t f      = { 0 };
    f.payload.kind     = WFM_SEQ_PN;
    f.payload.len      = 64;
    f.payload.reg_bits = 7;
    f.payload.seed     = 3;
    f.crc              = 1;

    size_t n = wfm_frame_bits (&f, buf, CAP);
    DP_REQUIRE_MSG (n == 80, "64 payload + 16 crc");
    DP_REQUIRE_MSG (wfm_frame_crc_ok (&f, buf) == 1,
                    "a frame we just built must check");

    /* One flipped payload bit must fail -- and it must fail without anyone
       supplying the payload that was sent. That is the property: no truth. */
    for (size_t i = 0; i < 64; i += 17)
      {
        buf[i] ^= 1u;
        DP_REQUIRE_MSG (wfm_frame_crc_ok (&f, buf) == 0,
                        "a corrupted payload must fail the check");
        buf[i] ^= 1u;
      }
    /* A flipped CRC bit too: the trailer is part of what is checked. */
    buf[70] ^= 1u;
    DP_REQUIRE_MSG (wfm_frame_crc_ok (&f, buf) == 0, "corrupted CRC fails");
    buf[70] ^= 1u;
    DP_REQUIRE_MSG (wfm_frame_crc_ok (&f, buf) == 1, "restored, passes again");

    /* No CRC is -1, NOT 0: "this frame carries no check" and "the check
       failed" are different answers, and an FER that conflated them would
       count every unprotected frame as an error. */
    wfm_frame_t g = f;
    g.crc         = 0;
    DP_REQUIRE_MSG (wfm_frame_crc_ok (&g, buf) == -1, "no CRC reports -1");
  }

  /* ── the rules the geometry enforces ─────────────────────────────────── */
  {
    wfm_frame_t f = { 0 };
    f.crc         = 1; /* a CRC over nothing protects nothing */
    wfm_frame_layout_t l;
    wfm_frame_layout (&f, &l);
    DP_REQUIRE_MSG (l.crc_bits == 0 && l.total_bits == 0,
                    "crc is dropped when there is no payload");
    DP_REQUIRE_MSG (wfm_frame_nbits (&f) == 0, "an empty frame is 0 bits");
    DP_REQUIRE_MSG (wfm_frame_bits (&f, buf, CAP) == 0, "and writes nothing");

    /* A field that cannot be built refuses outright rather than writing a
       short frame: a half-materialised frame would be scored against a truth
       nobody can reproduce. */
    wfm_frame_t bad  = { 0 };
    bad.payload.kind = WFM_SEQ_LITERAL;
    bad.payload.len  = 32;
    bad.payload.bits = NULL; /* a literal with no array */
    DP_REQUIRE_MSG (wfm_frame_bits (&bad, buf, CAP) == 0,
                    "a literal with no array cannot build");

    wfm_frame_t small  = { 0 };
    small.payload.kind = WFM_SEQ_DOTTED;
    small.payload.len  = 64;
    DP_REQUIRE_MSG (wfm_frame_bits (&small, buf, 63) == 0,
                    "too small an output buffer writes nothing");
    DP_REQUIRE_MSG (wfm_frame_bits (&small, buf, 64) == 64, "exact fits");

    DP_REQUIRE_MSG (wfm_frame_layout (NULL, &l) == -1, "NULL frame");
    DP_REQUIRE_MSG (wfm_frame_crc_ok (NULL, buf) == -1, "NULL frame, crc");

    /* `preamble_reps = 0` means NO preamble, which this struct documents and
       nothing asserted -- found by sabotage: making a zero count emit one
       period instead of nothing passed every test in this file, in
       test_dp_frame and in test_frame_core. It matters because a preamble is
       the coherent-integration target, so an unasked-for one is 8 bits a
       receiver would try to acquire on. */
    wfm_frame_t norep   = { 0 };
    norep.preamble.kind = WFM_SEQ_DOTTED;
    norep.preamble.len  = 8;
    norep.preamble_reps = 0;
    norep.payload.kind  = WFM_SEQ_DOTTED;
    norep.payload.len   = 16;
    DP_REQUIRE (wfm_frame_layout (&norep, &l) == 0);
    DP_CHECK_MSG (l.preamble_bits == 0,
                  "preamble_reps = 0 must emit no preamble at all");
    DP_CHECK_MSG (l.payload_off == 0 && l.total_bits == 16,
                  "...so the payload starts at bit 0");
  }

  /* ── the description the geometry above is a CONFIGURATION of ─────────
   *
   * `wfm_frame_t` is four fields and one stage of `wfm_frame_desc_t`, and
   * `wfm_frame_layout()` is `wfm_frame_desc_layout()` read back through named
   * members. What is checked here is the general form's own rules, on
   * descriptions the closed struct cannot express -- because those are the
   * rules every future configuration rests on, and none of them is reachable
   * through the four-field face.
   *
   * See docs/design/frame-description.md. The CCSDS coverage table is the
   * other configuration and is checked in test_ccsds_tm_frame.c, beside the
   * standard it comes from.
   */
  {
    /* A stage's cover is DECLARED, never inherited from what ran before it.
       Two stages over the same fields, reaching different distances: if a
       stage took "everything so far", both spans would be equal. That is the
       failure ccsds_tm_frame.h predicts for any chain of optional transforms,
       and it is a property of ordinary frames too, not a CCSDS curiosity. */
    wfm_frame_desc_t d;
    memset (&d, 0, sizeof d);
    d.n_fields = 3u;
    for (unsigned i = 0; i < 3u; i++)
      {
        d.field[i].seq.kind = WFM_SEQ_DOTTED;
        d.field[i].seq.len  = 8u * (i + 1u); /* 8, 16, 24 */
      }
    d.n_stages             = 2u;
    d.stage[0].first_field = 1u; /* fields 1..2: 16 + 24 = 40 bits at 8  */
    d.stage[0].n_fields    = 2u;
    d.stage[1].first_field = 0u; /* fields 0..2: the whole 48 bits at 0  */
    d.stage[1].n_fields    = 3u;

    wfm_frame_desc_layout_t l;
    DP_REQUIRE (wfm_frame_desc_layout (&d, &l) == 0);
    DP_CHECK (l.frame_bits == 48u && l.out_bits == 48u);
    DP_CHECK_MSG (l.stage[0].first == 8u && l.stage[0].n == 40u,
                  "a stage covers what it declares, starting where it says");
    DP_CHECK_MSG (l.stage[1].first == 0u && l.stage[1].n == 48u,
                  "...and a wider stage over the same fields reaches wider");

    /* A stage that did not run reports n == 0 AND first == 0. Both halves:
       an implementation that left `first` at the field offset would report a
       plausible-looking span for a stage that never ran, which a caller
       reading the spans to decide what to undo would act on. */
    d.stage[0].n_fields = 0u;
    DP_REQUIRE (wfm_frame_desc_layout (&d, &l) == 0);
    DP_CHECK_MSG (l.stage[0].n == 0u && l.stage[0].first == 0u,
                  "a stage that did not run reports first = 0 and n = 0");

    /* A derived field is dropped when its stage covers nothing supplied --
       the general form of "a CRC over an empty payload protects nothing".
       Asserted from BOTH sides, because a rule that only ever zeroes is
       satisfied by a field that is always zero. */
    memset (&d, 0, sizeof d);
    d.n_fields             = 2u;
    d.field[0].seq.kind    = WFM_SEQ_DOTTED;
    d.field[0].seq.len     = 24u;
    d.field[1].bits        = 16u;
    d.field[1].derived_by  = 1u;
    d.n_stages             = 1u;
    d.stage[0].first_field = 0u;
    d.stage[0].n_fields    = 2u;
    DP_REQUIRE (wfm_frame_desc_layout (&d, &l) == 0);
    DP_CHECK_MSG (l.field_bits[1] == 16u && l.frame_bits == 40u,
                  "a derived field is emitted when its stage covers data");

    d.field[0].seq.len = 0u; /* nothing left to protect */
    DP_REQUIRE (wfm_frame_desc_layout (&d, &l) == 0);
    DP_CHECK_MSG (l.field_bits[1] == 0u && l.frame_bits == 0u,
                  "...and dropped when it covers nothing");

    /* Refusals: a cover past the end of the field list, and a derived field
       naming a stage that is not there. Both are descriptions a caller can
       write, and neither may be read as a layout. */
    memset (&d, 0, sizeof d);
    d.n_fields          = 1u;
    d.field[0].seq.kind = WFM_SEQ_DOTTED;
    d.field[0].seq.len  = 8u;
    d.n_stages          = 1u;
    d.stage[0].n_fields = 2u; /* one past the single field */
    DP_CHECK_MSG (wfm_frame_desc_layout (&d, &l) == -1,
                  "a cover running past the field list must refuse");

    d.stage[0].n_fields   = 1u;
    d.field[0].derived_by = 9u; /* no such stage */
    DP_CHECK_MSG (wfm_frame_desc_layout (&d, &l) == -1,
                  "a derived field naming no stage must refuse");

    DP_CHECK (wfm_frame_desc_layout (NULL, &l) == -1);
    DP_CHECK (wfm_frame_describe (NULL, &d) == -1);

    /* A derived field must be the LAST field of its stage's cover. That is
       what lets one in-place op signature serve a CRC, an outer code and a
       randomiser alike -- the kernel reads the information at the head of
       the span and writes the check symbols into its tail -- so a
       description that puts the parity in the middle of the data is refused
       rather than handed to a kernel that cannot know its shape. */
    memset (&d, 0, sizeof d);
    d.n_fields             = 2u;
    d.field[0].bits        = 16u;
    d.field[0].derived_by  = 1u; /* derived, but FIRST in the cover */
    d.field[1].seq.kind    = WFM_SEQ_DOTTED;
    d.field[1].seq.len     = 24u;
    d.n_stages             = 1u;
    d.stage[0].first_field = 0u;
    d.stage[0].n_fields    = 2u;
    DP_CHECK_MSG (wfm_frame_desc_layout (&d, &l) == -1,
                  "a derived field must be last in its stage's cover");
  }

  /* ── assembling a description, and what it refuses ────────────────────
   *
   * `wfm_frame_bits` is `wfm_frame_assemble` over the four-field
   * configuration, so the sections above already exercise the field writing
   * and the built-in CRC. What is left is the part only a general
   * description reaches: a stage whose kernel this component does not own.
   */
  {
    uint8_t          buf[256];
    wfm_frame_desc_t d;
    memset (&d, 0, sizeof d);
    d.n_fields             = 1u;
    d.field[0].seq.kind    = WFM_SEQ_DOTTED;
    d.field[0].seq.len     = 32u;
    d.n_stages             = 1u;
    d.stage[0].kind        = WFM_STAGE_RS; /* nobody here implements it */
    d.stage[0].depth       = 1u;
    d.stage[0].first_field = 0u;
    d.stage[0].n_fields    = 1u;

    /* A stage with no kernel is a REFUSAL, never a silent skip. A skipped
       stage produces a frame that still assembles, still decodes against
       itself and syncs to nothing -- and it is indistinguishable in a log
       from one that ran, which is the same reason the validation harnesses
       fail rather than skip on a missing binary.

       Found by sabotage: making the assembler `continue` past an unknown
       kind passed every other test in the tree, because every other test
       supplies the kernels its description names. */
    memset (buf, 0xAAu, sizeof buf);
    DP_CHECK_MSG (wfm_frame_assemble (&d, NULL, buf, sizeof buf) == 0,
                  "a stage with no kernel must refuse, not run silently");
    int untouched = 1;
    for (size_t i = 0; i < sizeof buf; i++)
      if (buf[i] != 0xAAu)
        untouched = 0;
    DP_CHECK_MSG (untouched, "...and must not have written anything");

    /* The same description WITH a kernel must assemble, or the check above
       is satisfied by an assembler that refuses everything. */
    d.stage[0].kind = WFM_STAGE_CRC16; /* the built-in, over 32 - 16 bits */
    d.n_fields      = 2u;
    d.field[1].bits = WFM_FRAME_CRC_BITS;
    d.field[1].derived_by = 1u;
    d.stage[0].n_fields   = 2u;
    DP_CHECK_MSG (wfm_frame_assemble (&d, NULL, buf, sizeof buf) == 48u,
                  "...while a stage the built-ins DO cover assembles");

    DP_CHECK (wfm_frame_assemble (NULL, NULL, buf, sizeof buf) == 0);
    DP_CHECK (wfm_frame_assemble (&d, NULL, buf, 47u) == 0);
  }

  DP_TEST_END ("wfm_frame");
}
