/* test_dp_event_log_symbols.c -- generated by just-makeit (gh-1361).
 *
 * The address of every function the Python binding calls. This
 * file is linked into the C test, so a function that is declared
 * and never defined fails the build here, naming it -- rather than
 * at import, where a shared object's undefined symbol surfaces.
 * Regenerated by `jm apply`; do not edit.
 */
#include "dp_event_log/dp_event_log_core.h"

typedef void (*jm_any_fn) (void);

extern const jm_any_fn jm_bound_symbols_dp_event_log[];
/* `used` keeps the compiler from dropping the table; `retain` keeps
 * the linker's --gc-sections from dropping it (measured: without it
 * a -Wl,--gc-sections build links a missing definition cleanly). On
 * Mach-O, `used` alone already marks it no-dead-strip. */
#if defined(__has_attribute)
#if __has_attribute(retain)
__attribute__ ((used, retain))
#elif __has_attribute(used)
__attribute__ ((used))
#endif
#endif
const jm_any_fn jm_bound_symbols_dp_event_log[] = {
  (jm_any_fn)dp_event_log_open,        (jm_any_fn)dp_event_log_close,
  (jm_any_fn)dp_event_log_destroy,     (jm_any_fn)dp_event_log_field,
  (jm_any_fn)dp_event_log_field_str,   (jm_any_fn)dp_event_log_append,
  (jm_any_fn)dp_event_log_count,       (jm_any_fn)dp_event_log_finalize,
  (jm_any_fn)dp_event_log_set_dataset, (jm_any_fn)dp_event_log_set_telemetry,
};
