/* test_dp_interrupt_guard_symbols.c -- generated by just-makeit (gh-1361).
 *
 * The address of every function the Python binding calls. This
 * file is linked into the C test, so a function that is declared
 * and never defined fails the build here, naming it -- rather than
 * at import, where a shared object's undefined symbol surfaces.
 * Regenerated by `jm apply`; do not edit.
 */
#include "dp_interrupt_guard/dp_interrupt_guard_core.h"

typedef void (*jm_any_fn) (void);

extern const jm_any_fn jm_bound_symbols_dp_interrupt_guard[];
/* `used` keeps the compiler from dropping the table; `retain` keeps
 * the linker's --gc-sections from dropping it (measured: without it
 * a -Wl,--gc-sections build links a missing definition cleanly). On
 * Mach-O, `used` alone already marks it no-dead-strip. */
#if defined(__has_attribute)
#if __has_attribute(retain)
__attribute__ ((used, retain))
#elif __has_attribute(used)
__attribute__ ((used))
#endif
#endif
const jm_any_fn jm_bound_symbols_dp_interrupt_guard[] = {
  (jm_any_fn)dp_interrupt_guard_create,
  (jm_any_fn)dp_interrupt_guard_destroy,
  (jm_any_fn)dp_interrupt_guard_interrupt,
  (jm_any_fn)dp_interrupt_guard_interrupted,
  (jm_any_fn)dp_interrupt_guard_resume,
  (jm_any_fn)dp_interrupt_guard_latency_ms,
};
