/* test_burst_demod_symbols.c -- generated by just-makeit (gh-1361).
 *
 * The address of every function the Python binding calls. This
 * file is linked into the C test, so a function that is declared
 * and never defined fails the build here, naming it -- rather than
 * at import, where a shared object's undefined symbol surfaces.
 * Regenerated by `jm apply`; do not edit.
 */
#include "doppler/burst_demod/burst_demod_core.h"

typedef void (*jm_any_fn)(void);

extern const jm_any_fn jm_bound_symbols_burst_demod[];
/* `used` keeps the compiler from dropping the table; `retain` keeps
 * the linker's --gc-sections from dropping it (measured: without it
 * a -Wl,--gc-sections build links a missing definition cleanly). On
 * Mach-O, `used` alone already marks it no-dead-strip. */
#if defined(__has_attribute)
#if __has_attribute(retain)
__attribute__((used, retain))
#elif __has_attribute(used)
__attribute__((used))
#endif
#endif
const jm_any_fn jm_bound_symbols_burst_demod[] = {
    (jm_any_fn)dp_burst_demod_create,
    (jm_any_fn)dp_burst_demod_destroy,
    (jm_any_fn)dp_burst_demod_reset,
    (jm_any_fn)dp_burst_demod_set_preamble,
    (jm_any_fn)dp_burst_demod_set_sync,
    (jm_any_fn)dp_burst_demod_llrs,
    (jm_any_fn)dp_burst_demod_llrs_max_out,
    (jm_any_fn)dp_burst_demod_symbols,
    (jm_any_fn)dp_burst_demod_symbols_max_out,
    (jm_any_fn)dp_burst_demod_set_prior,
    (jm_any_fn)dp_burst_demod_demod_max_out,
    (jm_any_fn)dp_burst_demod_demod,
};
