/* test_dp_tlm_capture_symbols.c -- generated by just-makeit (gh-1361).
 *
 * The address of every function the Python binding calls. This
 * file is linked into the C test, so a function that is declared
 * and never defined fails the build here, naming it -- rather than
 * at import, where a shared object's undefined symbol surfaces.
 * Regenerated by `jm apply`; do not edit.
 */
#include "dp_tlm_capture/dp_tlm_capture_core.h"

typedef void (*jm_any_fn) (void);

extern const jm_any_fn jm_bound_symbols_dp_tlm_capture[];
/* `used` keeps the compiler from dropping the table; `retain` keeps
 * the linker's --gc-sections from dropping it (measured: without it
 * a -Wl,--gc-sections build links a missing definition cleanly). On
 * Mach-O, `used` alone already marks it no-dead-strip. */
#if defined(__has_attribute)
#if __has_attribute(retain)
__attribute__ ((used, retain))
#elif __has_attribute(used)
__attribute__ ((used))
#endif
#endif
const jm_any_fn jm_bound_symbols_dp_tlm_capture[] = {
  (jm_any_fn)dp_tlm_capture_open,
  (jm_any_fn)dp_tlm_capture_open_memory,
  (jm_any_fn)dp_tlm_capture_block,
  (jm_any_fn)dp_tlm_capture_close,
  (jm_any_fn)dp_tlm_capture_count,
  (jm_any_fn)dp_tlm_capture_records,
  (jm_any_fn)dp_tlm_capture_read_max_out,
  (jm_any_fn)dp_tlm_capture_read,
  (jm_any_fn)dp_tlm_capture_dropped,
  (jm_any_fn)dp_tlm_capture_context,
  (jm_any_fn)dp_tlm_capture_destroy,
};
