/* test_acc_q8_symbols.c -- generated by just-makeit (gh-1361).
 *
 * The address of every function the Python binding calls. This
 * file is linked into the C test, so a function that is declared
 * and never defined fails the build here, naming it -- rather than
 * at import, where a shared object's undefined symbol surfaces.
 * Regenerated by `jm apply`; do not edit.
 */
#include "doppler/acc_q8/acc_q8_core.h"

typedef void (*jm_any_fn)(void);

extern const jm_any_fn jm_bound_symbols_acc_q8[];
/* `used` keeps the compiler from dropping the table; `retain` keeps
 * the linker's --gc-sections from dropping it (measured: without it
 * a -Wl,--gc-sections build links a missing definition cleanly). On
 * Mach-O, `used` alone already marks it no-dead-strip. */
#if defined(__has_attribute)
#if __has_attribute(retain)
__attribute__((used, retain))
#elif __has_attribute(used)
__attribute__((used))
#endif
#endif
const jm_any_fn jm_bound_symbols_acc_q8[] = {
    (jm_any_fn)dp_acc_q8_create,
    (jm_any_fn)dp_acc_q8_destroy,
    (jm_any_fn)dp_acc_q8_reset,
    (jm_any_fn)dp_acc_q8_steps,
    (jm_any_fn)dp_acc_q8_get_acc,
    (jm_any_fn)dp_acc_q8_set_acc,
    (jm_any_fn)dp_acc_q8_get,
    (jm_any_fn)dp_acc_q8_dump,
    (jm_any_fn)dp_acc_q8_madd,
    (jm_any_fn)dp_acc_q8_state_bytes,
    (jm_any_fn)dp_acc_q8_get_state,
    (jm_any_fn)dp_acc_q8_set_state,
};
