/* test_async_dsss_pool_symbols.c -- generated by just-makeit (gh-1361).
 *
 * The address of every function the Python binding calls. This
 * file is linked into the C test, so a function that is declared
 * and never defined fails the build here, naming it -- rather than
 * at import, where a shared object's undefined symbol surfaces.
 * Regenerated by `jm apply`; do not edit.
 */
#include "doppler/async_dsss_pool/async_dsss_pool_core.h"

typedef void (*jm_any_fn)(void);

extern const jm_any_fn jm_bound_symbols_async_dsss_pool[];
/* `used` keeps the compiler from dropping the table; `retain` keeps
 * the linker's --gc-sections from dropping it (measured: without it
 * a -Wl,--gc-sections build links a missing definition cleanly). On
 * Mach-O, `used` alone already marks it no-dead-strip. */
#if defined(__has_attribute)
#if __has_attribute(retain)
__attribute__((used, retain))
#elif __has_attribute(used)
__attribute__((used))
#endif
#endif
const jm_any_fn jm_bound_symbols_async_dsss_pool[] = {
    (jm_any_fn)dp_async_dsss_pool_create,
    (jm_any_fn)dp_async_dsss_pool_destroy,
    (jm_any_fn)dp_async_dsss_pool_reset,
    (jm_any_fn)dp_async_dsss_pool_push,
    (jm_any_fn)dp_async_dsss_pool_status,
    (jm_any_fn)dp_async_dsss_pool_symbols_max_out,
    (jm_any_fn)dp_async_dsss_pool_symbols,
    (jm_any_fn)dp_async_dsss_pool_set_event_log,
    (jm_any_fn)dp_async_dsss_pool_state_bytes,
    (jm_any_fn)dp_async_dsss_pool_get_state,
    (jm_any_fn)dp_async_dsss_pool_set_state,
};
