/* test_f32_to_i8_symbols.c -- generated by just-makeit (gh-1361).
 *
 * The address of every function the Python binding calls. This
 * file is linked into the C test, so a function that is declared
 * and never defined fails the build here, naming it -- rather than
 * at import, where a shared object's undefined symbol surfaces.
 * Regenerated by `jm apply`; do not edit.
 */
#include "f32_to_i8/f32_to_i8_core.h"

typedef void (*jm_any_fn)(void);

extern const jm_any_fn jm_bound_symbols_f32_to_i8[];
/* `used` keeps the compiler from dropping the table; `retain` keeps
 * the linker's --gc-sections from dropping it (measured: without it
 * a -Wl,--gc-sections build links a missing definition cleanly). On
 * Mach-O, `used` alone already marks it no-dead-strip. */
#if defined(__has_attribute)
#if __has_attribute(retain)
__attribute__((used, retain))
#elif __has_attribute(used)
__attribute__((used))
#endif
#endif
const jm_any_fn jm_bound_symbols_f32_to_i8[] = {
    (jm_any_fn)f32_to_i8_create,
    (jm_any_fn)f32_to_i8_destroy,
    (jm_any_fn)f32_to_i8_reset,
    (jm_any_fn)f32_to_i8_steps,
    (jm_any_fn)f32_to_i8_state_bytes,
    (jm_any_fn)f32_to_i8_get_state,
    (jm_any_fn)f32_to_i8_set_state,
};
