/* test_acq_symbols.c -- generated by just-makeit (gh-1361).
 *
 * The address of every function the Python binding calls. This
 * file is linked into the C test, so a function that is declared
 * and never defined fails the build here, naming it -- rather than
 * at import, where a shared object's undefined symbol surfaces.
 * Regenerated by `jm apply`; do not edit.
 */
#include "acq/acq_core.h"

typedef void (*jm_any_fn) (void);

extern const jm_any_fn jm_bound_symbols_acq[];
/* `used` keeps the compiler from dropping the table; `retain` keeps
 * the linker's --gc-sections from dropping it (measured: without it
 * a -Wl,--gc-sections build links a missing definition cleanly). On
 * Mach-O, `used` alone already marks it no-dead-strip. */
#if defined(__has_attribute)
#if __has_attribute(retain)
__attribute__ ((used, retain))
#elif __has_attribute(used)
__attribute__ ((used))
#endif
#endif
const jm_any_fn jm_bound_symbols_acq[] = {
  (jm_any_fn)acq_create_continuous,
  (jm_any_fn)acq_destroy,
  (jm_any_fn)acq_reset,
  (jm_any_fn)acq_configure_search_raw,
  (jm_any_fn)acq_set_max_peaks,
  (jm_any_fn)acq_set_carrier_freq_hz,
  (jm_any_fn)acq_set_threads,
  (jm_any_fn)acq_set_telemetry,
  (jm_any_fn)acq_surface,
  (jm_any_fn)acq_surface_doppler_hz,
  (jm_any_fn)acq_surface_chip_phase,
  (jm_any_fn)acq_surface_complex,
  (jm_any_fn)acq_block_prompt,
  (jm_any_fn)acq_block_raw,
  (jm_any_fn)acq_push,
  (jm_any_fn)acq_state_bytes,
  (jm_any_fn)acq_get_state,
  (jm_any_fn)acq_set_state,
};
