/* test_viterbi_symbols.c -- generated by just-makeit (gh-1361).
 *
 * The address of every function the Python binding calls. This
 * file is linked into the C test, so a function that is declared
 * and never defined fails the build here, naming it -- rather than
 * at import, where a shared object's undefined symbol surfaces.
 * Regenerated by `jm apply`; do not edit.
 */
#include "doppler/viterbi/viterbi_core.h"

typedef void (*jm_any_fn)(void);

extern const jm_any_fn jm_bound_symbols_viterbi[];
/* `used` keeps the compiler from dropping the table; `retain` keeps
 * the linker's --gc-sections from dropping it (measured: without it
 * a -Wl,--gc-sections build links a missing definition cleanly). On
 * Mach-O, `used` alone already marks it no-dead-strip. */
#if defined(__has_attribute)
#if __has_attribute(retain)
__attribute__((used, retain))
#elif __has_attribute(used)
__attribute__((used))
#endif
#endif
const jm_any_fn jm_bound_symbols_viterbi[] = {
    (jm_any_fn)dp_viterbi_create,
    (jm_any_fn)dp_viterbi_destroy,
    (jm_any_fn)dp_viterbi_reset,
    (jm_any_fn)dp_viterbi_decode_max_out,
    (jm_any_fn)dp_viterbi_decode,
    (jm_any_fn)dp_viterbi_state_bytes,
    (jm_any_fn)dp_viterbi_get_state,
    (jm_any_fn)dp_viterbi_set_state,
};
