/*
 * test_wfm_frame.c — the frame descriptor: geometry, materialisation, CRC.
 *
 * The descriptor exists so that a frame's layout is stated ONCE and read from
 * both ends. Its value is therefore entirely in agreement — between the
 * offsets it reports and the bits it writes, between a generated field here
 * and the same field regenerated by a receiver holding the same numbers, and
 * between this and the DSSS assembler it now backs (that last one is checked
 * where it belongs, by test_wfm_dsp's existing round-trips staying
 * bit-identical across the refactor).
 *
 * `wfm_frame_crc_ok` gets particular attention because it is what makes a
 * TRUTH-FREE frame error rate possible: it needs the layout and the received
 * bits and no payload truth at all, which is the one metric that works on a
 * real capture AND still catches a false lock.
 */
#include "dp_test.h"
#include "wfm/wfm_dsp.h" /* the four-field DSSS pair, for the equivalence */
#include "wfm/wfm_frame.h"

#include "gold/gold_core.h"
#include "pn/pn_core.h"

#include <stdio.h>
#include <string.h>

#define CAP 4096

static uint8_t buf[CAP];

/* ── a synthetic stage table ──────────────────────────────────────────────
 *
 * Deliberately NOT ccsds_tm's. The descriptor is general and CCSDS is one
 * CONFIGURATION of it, so a test that reached the general machinery only
 * through ccsds_tm would be evidence about CCSDS — and the general claims
 * would hold, or fail, unobserved. That was the state before this file: the
 * receive mirror, the ops table and the second built-in had zero mentions
 * here and were exercised only in test_ccsds_tm_frame.c.
 *
 * These kernels are arithmetic nobody ships. They need to be exactly two
 * things: order-sensitive against each other, and checkable.
 */

/* TOY_SUM — the last 8 bits of the cover carry the number of 1s in the head,
   MSB-first. A check symbol in the shape every in-place stage uses: read the
   information at the head, write what you derive into the tail. */
#define TOY_SUM_BITS 8u

static unsigned
toy_sum_head (const uint8_t *bits, size_t prot)
{
  unsigned n = 0;
  for (size_t i = 0; i < prot; i++)
    n += (bits[i] & 1u);
  return n & 0xFFu;
}

static int
toy_sum_in_unit (const wfm_stage_t *st, uint8_t *bits, size_t n, void *user)
{
  (void)st;
  (void)user;
  if (n <= TOY_SUM_BITS)
    return -1;
  const size_t   prot = n - TOY_SUM_BITS;
  const unsigned s    = toy_sum_head (bits, prot);
  for (size_t i = 0; i < TOY_SUM_BITS; i++)
    bits[prot + i] = (uint8_t)((s >> (7u - i)) & 1u);
  return 0;
}

static int
toy_sum_undo (const wfm_stage_t *st, uint8_t *bits, size_t n,
              wfm_frame_stage_rx_t *rx, void *user)
{
  (void)st;
  (void)user;
  if (n <= TOY_SUM_BITS)
    return -1;
  const size_t   prot = n - TOY_SUM_BITS;
  const unsigned want = toy_sum_head (bits, prot);
  unsigned       got  = 0;
  for (size_t i = 0; i < TOY_SUM_BITS; i++)
    got = (got << 1) | (bits[prot + i] & 1u);
  rx->units   = 1u;
  rx->ok      = (want == got) ? 1u : 0u;
  rx->checked = 1;
  return 0;
}

/* TOY_FLIP — XOR every bit of the cover. Its own inverse, which is what
   makes it order-sensitive against TOY_SUM: a sum written before the flip
   does not describe the bits after it. */
static int
toy_flip_in_unit (const wfm_stage_t *st, uint8_t *bits, size_t n, void *user)
{
  (void)st;
  (void)user;
  for (size_t i = 0; i < n; i++)
    bits[i] ^= 1u;
  return 0;
}

static int
toy_flip_undo (const wfm_stage_t *st, uint8_t *bits, size_t n,
               wfm_frame_stage_rx_t *rx, void *user)
{
  toy_flip_in_unit (st, bits, n, user);
  rx->units   = 1u;
  rx->ok      = 1u;
  rx->checked = 1;
  return 0;
}

/* TOY_NOOP — transforms nothing and has NO undo, modelling the one stage
   shape the receive side must report honestly: reversed somewhere else, or
   not at all. Identity on purpose, so skipping its undo cannot corrupt the
   span a later assertion reads. */
static int
toy_noop_in_unit (const wfm_stage_t *st, uint8_t *bits, size_t n, void *user)
{
  (void)st;
  (void)bits;
  (void)n;
  (void)user;
  return 0;
}

static const wfm_stage_op_t TOY_OPS[] = {
  { WFM_STAGE_RS, toy_sum_in_unit, NULL, toy_sum_undo },
  { WFM_STAGE_RANDOMISE, toy_flip_in_unit, NULL, toy_flip_undo },
  { WFM_STAGE_CONV, toy_noop_in_unit, NULL, NULL },
  /* A kind doppler has never heard of, allocated out of the caller range. */
  { WFM_STAGE_USER + 1u, toy_flip_in_unit, NULL, toy_flip_undo },
};

static wfm_frame_ops_t
toy_ops (void)
{
  wfm_frame_ops_t o;
  o.op   = TOY_OPS;
  o.n_op = (unsigned)(sizeof TOY_OPS / sizeof TOY_OPS[0]);
  o.user = NULL;
  return o;
}

/* ── wfm_seq_bits: "the one place a wfm_seq_t becomes bits", untested ────
 *
 * Inventory against wfm_frame.h. This object is well covered -- 18 declared
 * entry points, 16 of them exercised -- and the two that were not are the
 * interesting ones. `wfm_seq_bits` had ZERO mentions in any C test in the
 * tree, and its own doc calls it the single place this conversion happens:
 * a descriptor materialises its fields through it, and the DSSS chip
 * builder calls it to expand a generated sequence before consuming a raw
 * array.
 *
 * Every claim below is one the header states, and each is checked against
 * arithmetic or against the defining property of the sequence -- never
 * against another doppler path that could share the same mistake.
 */
static int
test_seq_bits (void)
{
  uint8_t out[512];

  /* ── LITERAL copies, and MASKS to 0/1 ────────────────────────────────
     The mask matters: a caller who hands in a byte array that is not
     already 0/1 (a parsed hex nibble, say) must not get 2s and 3s written
     into a bit stream that everything downstream treats as one-per-byte. */
  {
    const uint8_t src[8] = { 1, 0, 1, 1, 2, 3, 0, 255 };
    wfm_seq_t     s      = { .kind = WFM_SEQ_LITERAL, .len = 8, .bits = src };
    memset (out, 0xAA, sizeof out);
    DP_REQUIRE_MSG (wfm_seq_bits (&s, out, sizeof out) == 8,
                    "LITERAL writes len bits");
    for (size_t i = 0; i < 8; i++)
      DP_REQUIRE_MSG (out[i] == (uint8_t)(src[i] & 1u),
                      "LITERAL copies, masked to 0/1");
    /* a LITERAL with no array is unbuildable, not a silent zero field */
    wfm_seq_t empty = { .kind = WFM_SEQ_LITERAL, .len = 8, .bits = NULL };
    DP_REQUIRE_MSG (wfm_seq_bits (&empty, out, sizeof out) == 0,
                    "a LITERAL with no array returns 0");
  }

  /* ── DOTTED is 1010..., and it STARTS HIGH ───────────────────────────
     The header says why in as many words: "Starts high so a one-bit field
     is not silently the same as zeros." A dotting field that began low
     would make len==1 indistinguishable from an absent one, which is
     exactly the failure a settling pattern must not have. */
  {
    wfm_seq_t s = { .kind = WFM_SEQ_DOTTED, .len = 9 };
    memset (out, 0xAA, sizeof out);
    DP_REQUIRE_MSG (wfm_seq_bits (&s, out, sizeof out) == 9,
                    "DOTTED writes len bits");
    for (size_t i = 0; i < 9; i++)
      DP_REQUIRE_MSG (out[i] == (uint8_t)((i & 1u) ^ 1u), "DOTTED alternates");
    DP_REQUIRE_MSG (out[0] == 1u, "and it starts HIGH, not low");
    wfm_seq_t one = { .kind = WFM_SEQ_DOTTED, .len = 1 };
    DP_REQUIRE_MSG (wfm_seq_bits (&one, out, sizeof out) == 1 && out[0] == 1u,
                    "a one-bit dotted field is a 1, not a 0");
  }

  /* ── PN: poly 0 means "the MLS polynomial", NOT a literal 0 ──────────
     The header spells out the hazard: a literal 0 reaching pn_create() is
     a register with no feedback, which emits the seed and then zeros --
     "a CONSTANT field that still looks like a field". So the check is not
     that bits came out, it is that they are an m-sequence: over one full
     period 2^n - 1 there are exactly 2^(n-1) ones, and the run is not
     constant. That is arithmetic about maximal-length sequences, and owes
     nothing to doppler. */
  {
    for (uint32_t n = 5; n <= 9; n += 2)
      {
        const size_t period = ((size_t)1u << n) - 1u;
        wfm_seq_t    s      = { .kind     = WFM_SEQ_PN,
                                .len      = period,
                                .poly     = 0, /* 0 => pn_mls_poly (n) */
                                .seed     = 0, /* 0 => 1               */
                                .reg_bits = n };
        DP_REQUIRE_MSG (wfm_seq_bits (&s, out, sizeof out) == period,
                        "PN writes len bits");
        size_t ones = 0;
        for (size_t i = 0; i < period; i++)
          {
            DP_REQUIRE_MSG (out[i] <= 1u, "PN emits 0/1");
            ones += out[i];
          }
        /* an m-sequence of period 2^n-1 has exactly 2^(n-1) ones */
        DP_REQUIRE_MSG (ones == ((size_t)1u << (n - 1)),
                        "poly 0 gives a maximal-length sequence, not a "
                        "feedback-free register emitting zeros");
      }
    /* a zero seed must not lock the register at its fixed point */
    wfm_seq_t z = {
      .kind = WFM_SEQ_PN, .len = 31, .poly = 0, .seed = 0, .reg_bits = 5
    };
    DP_REQUIRE_MSG (wfm_seq_bits (&z, out, sizeof out) == 31,
                    "a zero seed still builds");
    size_t nz = 0;
    for (size_t i = 0; i < 31; i++)
      nz += out[i];
    DP_REQUIRE_MSG (nz == 16, "seed 0 resolves to 1, not an all-zero "
                              "register stuck at its fixed point");
    /* a register width with no MLS entry is a refusal, not a zero field */
    wfm_seq_t bad = {
      .kind = WFM_SEQ_PN, .len = 8, .poly = 0, .seed = 1, .reg_bits = 0
    };
    DP_REQUIRE_MSG (wfm_seq_bits (&bad, out, sizeof out) == 0,
                    "a generator that refuses its parameters returns 0");
  }

  /* ── GOLD builds, and is not its own component sequence ──────────────
     A Gold code is two LFSRs combined; the failure worth catching is one
     of them being ignored, which would silently ship a plain m-sequence
     under a Gold label. So the test is that changing ONLY the second
     register's seed changes the output. */
  {
    uint8_t   a[255], b[255];
    wfm_seq_t g1 = { .kind     = WFM_SEQ_GOLD,
                     .len      = 255,
                     .reg_bits = 8,
                     .taps_a   = 0,
                     .seed_a   = 1,
                     .taps_b   = 0,
                     .seed_b   = 1 };
    wfm_seq_t g2 = g1;
    g2.seed_b    = 2;
    size_t n1    = wfm_seq_bits (&g1, a, sizeof a);
    size_t n2    = wfm_seq_bits (&g2, b, sizeof b);
    DP_REQUIRE_MSG (n1 == 255 && n2 == 255, "GOLD writes len bits");
    DP_REQUIRE_MSG (memcmp (a, b, 255) != 0,
                    "the SECOND register participates -- a Gold code that "
                    "ignored it would be a plain m-sequence");
  }

  /* ── the refusals, which are what keep a half-built field out ────────
     Every one of these is a 0 return rather than a partial write, so a
     caller cannot end up scoring against a truth nobody can reproduce. */
  {
    const uint8_t src[4] = { 1, 0, 1, 0 };
    wfm_seq_t     s      = { .kind = WFM_SEQ_LITERAL, .len = 4, .bits = src };
    DP_REQUIRE_MSG (wfm_seq_bits (NULL, out, sizeof out) == 0,
                    "a NULL sequence returns 0");
    DP_REQUIRE_MSG (wfm_seq_bits (&s, out, 3) == 0,
                    "a length past the capacity returns 0, not a truncation");
    /* and it wrote nothing on the way to refusing */
    memset (out, 0xAA, sizeof out);
    DP_REQUIRE_MSG (wfm_seq_bits (&s, out, 3) == 0, "still 0");
    DP_REQUIRE_MSG (out[0] == 0xAA,
                    "a refused build leaves the caller's buffer alone");
    wfm_seq_t zero_len = { .kind = WFM_SEQ_LITERAL, .len = 0, .bits = src };
    DP_REQUIRE_MSG (wfm_seq_bits (&zero_len, out, sizeof out) == 0,
                    "len 0 means the field is absent");
  }
  return 0;
}

/* ── wfm_frame_dsss_nchips: the burst geometry, in this object's own test
 *
 * Reached only through wfm_synth's tests until now -- so the chip count a
 * DSSS burst occupies was certified as a side effect of testing the
 * synthesiser, never as a claim of the frame layer that owns it. The
 * arithmetic is stated in the header and checked here against it:
 * acq_len*acq_reps preamble chips, then (sync + payload + CRC) frame bits,
 * each spread by data_len.
 */
static int
test_dsss_nchips (void)
{
  const struct
  {
    size_t acq_len, acq_reps, data_len, sync_len, payload_len;
    int    crc;
    size_t want;
  } cases[] = {
    /* preamble only: no frame bits, so no spreading term */
    { 8, 3, 4, 0, 0, 0, 8 * 3 },
    /* the wfm_synth fixture: 8*3 + (2 + 5 + 16) * 4 */
    { 8, 3, 4, 2, 5, 1, 8 * 3 + (2 + 5 + 16) * 4 },
    /* the same without a CRC drops exactly WFM_FRAME_CRC_BITS symbols */
    { 8, 3, 4, 2, 5, 0, 8 * 3 + (2 + 5) * 4 },
    /* no preamble at all: frame only */
    { 0, 0, 16, 8, 32, 1, (8 + 32 + 16) * 16 },
  };
  for (size_t k = 0; k < sizeof cases / sizeof cases[0]; k++)
    {
      size_t got = wfm_frame_dsss_nchips (cases[k].acq_len, cases[k].acq_reps,
                                          cases[k].data_len, cases[k].sync_len,
                                          cases[k].payload_len, cases[k].crc);
      DP_REQUIRE_MSG (got == cases[k].want,
                      "dsss_nchips is preamble + spread frame bits");
    }
  /* frame bits with no spreading code is a refusal: there is no chip count
     for a frame nothing spreads, and 0 is how the synth learns to reject it */
  DP_REQUIRE_MSG (wfm_frame_dsss_nchips (8, 3, 0, 2, 5, 1) == 0,
                  "frame bits with no data code is unbuildable");
  DP_REQUIRE_MSG (wfm_frame_dsss_nchips (0, 0, 4, 0, 0, 0) == 0,
                  "an empty burst is unbuildable");
  /* the CRC term is exactly WFM_FRAME_CRC_BITS symbols wide */
  DP_REQUIRE_MSG (wfm_frame_dsss_nchips (0, 0, 1, 0, 1, 1)
                          - wfm_frame_dsss_nchips (0, 0, 1, 0, 1, 0)
                      == WFM_FRAME_CRC_BITS,
                  "a CRC costs exactly WFM_FRAME_CRC_BITS spread symbols");
  return 0;
}

int
main (void)
{
  /* ── geometry: the offsets and the bits must agree ──────────────────── */
  {
    static const uint8_t sync_bits[13]
        = { 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1 }; /* Barker-13 */
    wfm_frame_t f      = { 0 };
    f.preamble.kind    = WFM_SEQ_DOTTED;
    f.preamble.len     = 8;
    f.preamble_reps    = 4;
    f.sync.kind        = WFM_SEQ_LITERAL;
    f.sync.bits        = sync_bits;
    f.sync.len         = 13;
    f.payload.kind     = WFM_SEQ_PN;
    f.payload.len      = 100;
    f.payload.reg_bits = 7;
    f.payload.seed     = 1;
    f.crc              = 1;

    wfm_frame_layout_t l;
    DP_REQUIRE_MSG (wfm_frame_layout (&f, &l) == 0, "layout");
    DP_REQUIRE_MSG (l.preamble_off == 0 && l.preamble_bits == 32,
                    "preamble is len*reps at the front");
    DP_REQUIRE_MSG (l.sync_off == 32 && l.sync_bits == 13, "sync follows");
    DP_REQUIRE_MSG (l.payload_off == 45 && l.payload_bits == 100, "payload");
    DP_REQUIRE_MSG (l.crc_off == 145 && l.crc_bits == 16, "crc trails");
    DP_REQUIRE_MSG (l.total_bits == 161, "total");
    DP_REQUIRE_MSG (wfm_frame_nbits (&f) == l.total_bits,
                    "nbits agrees with the layout it summarises");

    size_t n = wfm_frame_bits (&f, buf, CAP);
    DP_REQUIRE_MSG (n == l.total_bits, "bits written == total");
    for (size_t i = 0; i < n; i++)
      DP_REQUIRE_MSG (buf[i] <= 1, "every output is 0 or 1");

    /* The fields land WHERE the layout says. A descriptor whose offsets and
       whose bytes disagree is worse than no descriptor: both ends would be
       reading one and writing the other. */
    for (size_t i = 0; i < 32; i++)
      DP_REQUIRE_MSG (buf[l.preamble_off + i] == (i % 2 == 0),
                      "dotted preamble is 1010...");
    DP_REQUIRE_MSG (
        memcmp (buf + l.sync_off, sync_bits, 13) == 0,
        "the literal sync word appears verbatim at its stated offset");

    /* A repeated preamble must REPEAT -- period is what a coherent
       integration across reps depends on, so a generated preamble drawing
       fresh bits per rep would be a different waveform entirely. */
    for (size_t r = 1; r < 4; r++)
      DP_REQUIRE_MSG (memcmp (buf, buf + r * 8, 8) == 0,
                      "every preamble repetition is identical");
  }

  /* ── generated fields regenerate from the descriptor alone ──────────── */
  {
    wfm_frame_t f      = { 0 };
    f.payload.kind     = WFM_SEQ_PN;
    f.payload.len      = 300;
    f.payload.reg_bits = 9;
    f.payload.seed     = 7;

    size_t n = wfm_frame_bits (&f, buf, CAP);
    DP_REQUIRE_MSG (n == 300, "pn payload materialises");

    /* The receiver's side: the same three numbers, through pn directly. This
       is the whole argument for generated kinds -- truth for a long record
       without carrying the array, and a capture reproducible from its
       metadata. If these ever diverge, every regenerated-truth BER is scored
       against the wrong sequence.

       NOTE the poly: `pn_mls_poly (9)`, not the descriptor's literal 0.
       pn_create() takes the tap mask verbatim, so a 0 there is a register
       with NO FEEDBACK. This comparison used to pass `0` on both sides and
       agreed perfectly -- on two all-zero sequences. That is what a
       consistency test does when the defect is shared: it confirms the two
       halves match and says nothing about whether either is a PN. */
    static uint8_t want[300];
    pn_state_t    *p = pn_create (pn_mls_poly (9), 7, 9, 0);
    DP_REQUIRE_MSG (p != NULL, "pn_create");
    DP_REQUIRE_MSG (pn_generate (p, 300, want, 300) == 300, "pn_generate");
    pn_destroy (p);
    DP_REQUIRE_MSG (memcmp (buf, want, 300) == 0,
                    "a PN field IS pn_generate of its own descriptor");

    /* And the property no agreement between two halves can establish: the
       sequence is actually MAXIMAL-LENGTH. One full period of a length-n MLS
       carries exactly 2^(n-1) ones, so a balance check over 2^n-1 bits is a
       direct, cheap test that the descriptor resolved a real polynomial. It
       reads 1 against 256 when it does not. */
    {
      wfm_frame_t bal      = { 0 };
      bal.payload.kind     = WFM_SEQ_PN;
      bal.payload.len      = 511; /* one period of a 9-bit register */
      bal.payload.reg_bits = 9;
      bal.payload.seed     = 7;
      size_t ones          = 0;
      DP_REQUIRE_MSG (wfm_frame_bits (&bal, buf, CAP) == 511, "one period");
      for (size_t i = 0; i < 511; i++)
        ones += buf[i];
      DP_REQUIRE_MSG (ones == 256,
                      "a default-poly PN field is BALANCED over its period "
                      "-- i.e. it is maximal-length, not a drained register");
    }

    /* Same descriptor, same bits, every time. */
    static uint8_t again[300];
    DP_REQUIRE_MSG (wfm_frame_bits (&f, again, 300) == 300, "second build");
    DP_REQUIRE_MSG (memcmp (buf, again, 300) == 0, "deterministic");
  }

  /* ── the CRC: what makes a truth-free FER possible ──────────────────── */
  {
    wfm_frame_t f      = { 0 };
    f.payload.kind     = WFM_SEQ_PN;
    f.payload.len      = 64;
    f.payload.reg_bits = 7;
    f.payload.seed     = 3;
    f.crc              = 1;

    size_t n = wfm_frame_bits (&f, buf, CAP);
    DP_REQUIRE_MSG (n == 80, "64 payload + 16 crc");
    DP_REQUIRE_MSG (wfm_frame_crc_ok (&f, buf) == 1,
                    "a frame we just built must check");

    /* One flipped payload bit must fail -- and it must fail without anyone
       supplying the payload that was sent. That is the property: no truth. */
    for (size_t i = 0; i < 64; i += 17)
      {
        buf[i] ^= 1u;
        DP_REQUIRE_MSG (wfm_frame_crc_ok (&f, buf) == 0,
                        "a corrupted payload must fail the check");
        buf[i] ^= 1u;
      }
    /* A flipped CRC bit too: the trailer is part of what is checked. */
    buf[70] ^= 1u;
    DP_REQUIRE_MSG (wfm_frame_crc_ok (&f, buf) == 0, "corrupted CRC fails");
    buf[70] ^= 1u;
    DP_REQUIRE_MSG (wfm_frame_crc_ok (&f, buf) == 1, "restored, passes again");

    /* No CRC is -1, NOT 0: "this frame carries no check" and "the check
       failed" are different answers, and an FER that conflated them would
       count every unprotected frame as an error. */
    wfm_frame_t g = f;
    g.crc         = 0;
    DP_REQUIRE_MSG (wfm_frame_crc_ok (&g, buf) == -1, "no CRC reports -1");
  }

  /* ── the rules the geometry enforces ─────────────────────────────────── */
  {
    wfm_frame_t f = { 0 };
    f.crc         = 1; /* a CRC over nothing protects nothing */
    wfm_frame_layout_t l;
    wfm_frame_layout (&f, &l);
    DP_REQUIRE_MSG (l.crc_bits == 0 && l.total_bits == 0,
                    "crc is dropped when there is no payload");
    DP_REQUIRE_MSG (wfm_frame_nbits (&f) == 0, "an empty frame is 0 bits");
    DP_REQUIRE_MSG (wfm_frame_bits (&f, buf, CAP) == 0, "and writes nothing");

    /* A field that cannot be built refuses outright rather than writing a
       short frame: a half-materialised frame would be scored against a truth
       nobody can reproduce. */
    wfm_frame_t bad  = { 0 };
    bad.payload.kind = WFM_SEQ_LITERAL;
    bad.payload.len  = 32;
    bad.payload.bits = NULL; /* a literal with no array */
    DP_REQUIRE_MSG (wfm_frame_bits (&bad, buf, CAP) == 0,
                    "a literal with no array cannot build");

    wfm_frame_t small  = { 0 };
    small.payload.kind = WFM_SEQ_DOTTED;
    small.payload.len  = 64;
    DP_REQUIRE_MSG (wfm_frame_bits (&small, buf, 63) == 0,
                    "too small an output buffer writes nothing");
    DP_REQUIRE_MSG (wfm_frame_bits (&small, buf, 64) == 64, "exact fits");

    DP_REQUIRE_MSG (wfm_frame_layout (NULL, &l) == -1, "NULL frame");
    DP_REQUIRE_MSG (wfm_frame_crc_ok (NULL, buf) == -1, "NULL frame, crc");

    /* `preamble_reps = 0` means NO preamble, which this struct documents and
       nothing asserted -- found by sabotage: making a zero count emit one
       period instead of nothing passed every test in this file, in
       test_dp_frame and in test_frame_core. It matters because a preamble is
       the coherent-integration target, so an unasked-for one is 8 bits a
       receiver would try to acquire on. */
    wfm_frame_t norep   = { 0 };
    norep.preamble.kind = WFM_SEQ_DOTTED;
    norep.preamble.len  = 8;
    norep.preamble_reps = 0;
    norep.payload.kind  = WFM_SEQ_DOTTED;
    norep.payload.len   = 16;
    DP_REQUIRE (wfm_frame_layout (&norep, &l) == 0);
    DP_CHECK_MSG (l.preamble_bits == 0,
                  "preamble_reps = 0 must emit no preamble at all");
    DP_CHECK_MSG (l.payload_off == 0 && l.total_bits == 16,
                  "...so the payload starts at bit 0");
  }

  /* ── the description the geometry above is a CONFIGURATION of ─────────
   *
   * `wfm_frame_t` is four fields and one stage of `wfm_frame_desc_t`, and
   * `wfm_frame_layout()` is `wfm_frame_desc_layout()` read back through named
   * members. What is checked here is the general form's own rules, on
   * descriptions the closed struct cannot express -- because those are the
   * rules every future configuration rests on, and none of them is reachable
   * through the four-field face.
   *
   * See docs/design/frame-description.md. The CCSDS coverage table is the
   * other configuration and is checked in test_ccsds_tm_frame.c, beside the
   * standard it comes from.
   */
  {
    /* A stage's cover is DECLARED, never inherited from what ran before it.
       Two stages over the same fields, reaching different distances: if a
       stage took "everything so far", both spans would be equal. That is the
       failure ccsds_tm_frame.h predicts for any chain of optional transforms,
       and it is a property of ordinary frames too, not a CCSDS curiosity. */
    wfm_frame_desc_t d;
    memset (&d, 0, sizeof d);
    d.n_fields = 3u;
    for (unsigned i = 0; i < 3u; i++)
      {
        d.field[i].seq.kind = WFM_SEQ_DOTTED;
        d.field[i].seq.len  = 8u * (i + 1u); /* 8, 16, 24 */
      }
    d.n_stages             = 2u;
    d.stage[0].first_field = 1u; /* fields 1..2: 16 + 24 = 40 bits at 8  */
    d.stage[0].n_fields    = 2u;
    d.stage[1].first_field = 0u; /* fields 0..2: the whole 48 bits at 0  */
    d.stage[1].n_fields    = 3u;

    wfm_frame_desc_layout_t l;
    DP_REQUIRE (wfm_frame_desc_layout (&d, &l) == 0);
    DP_CHECK (l.frame_bits == 48u && l.out_bits == 48u);
    DP_CHECK_MSG (l.stage[0].first == 8u && l.stage[0].n == 40u,
                  "a stage covers what it declares, starting where it says");
    DP_CHECK_MSG (l.stage[1].first == 0u && l.stage[1].n == 48u,
                  "...and a wider stage over the same fields reaches wider");

    /* A stage that did not run reports n == 0 AND first == 0. Both halves:
       an implementation that left `first` at the field offset would report a
       plausible-looking span for a stage that never ran, which a caller
       reading the spans to decide what to undo would act on. */
    d.stage[0].n_fields = 0u;
    DP_REQUIRE (wfm_frame_desc_layout (&d, &l) == 0);
    DP_CHECK_MSG (l.stage[0].n == 0u && l.stage[0].first == 0u,
                  "a stage that did not run reports first = 0 and n = 0");

    /* A derived field is dropped when its stage covers nothing supplied --
       the general form of "a CRC over an empty payload protects nothing".
       Asserted from BOTH sides, because a rule that only ever zeroes is
       satisfied by a field that is always zero. */
    memset (&d, 0, sizeof d);
    d.n_fields             = 2u;
    d.field[0].seq.kind    = WFM_SEQ_DOTTED;
    d.field[0].seq.len     = 24u;
    d.field[1].bits        = 16u;
    d.field[1].derived_by  = 1u;
    d.n_stages             = 1u;
    d.stage[0].first_field = 0u;
    d.stage[0].n_fields    = 2u;
    DP_REQUIRE (wfm_frame_desc_layout (&d, &l) == 0);
    DP_CHECK_MSG (l.field_bits[1] == 16u && l.frame_bits == 40u,
                  "a derived field is emitted when its stage covers data");

    d.field[0].seq.len = 0u; /* nothing left to protect */
    DP_REQUIRE (wfm_frame_desc_layout (&d, &l) == 0);
    DP_CHECK_MSG (l.field_bits[1] == 0u && l.frame_bits == 0u,
                  "...and dropped when it covers nothing");

    /* Refusals: a cover past the end of the field list, and a derived field
       naming a stage that is not there. Both are descriptions a caller can
       write, and neither may be read as a layout. */
    memset (&d, 0, sizeof d);
    d.n_fields          = 1u;
    d.field[0].seq.kind = WFM_SEQ_DOTTED;
    d.field[0].seq.len  = 8u;
    d.n_stages          = 1u;
    d.stage[0].n_fields = 2u; /* one past the single field */
    DP_CHECK_MSG (wfm_frame_desc_layout (&d, &l) == -1,
                  "a cover running past the field list must refuse");

    d.stage[0].n_fields   = 1u;
    d.field[0].derived_by = 9u; /* no such stage */
    DP_CHECK_MSG (wfm_frame_desc_layout (&d, &l) == -1,
                  "a derived field naming no stage must refuse");

    DP_CHECK (wfm_frame_desc_layout (NULL, &l) == -1);
    DP_CHECK (wfm_frame_describe (NULL, &d) == -1);

    /* A derived field must be the LAST field of its stage's cover. That is
       what lets one in-place op signature serve a CRC, an outer code and a
       randomiser alike -- the kernel reads the information at the head of
       the span and writes the check symbols into its tail -- so a
       description that puts the parity in the middle of the data is refused
       rather than handed to a kernel that cannot know its shape. */
    memset (&d, 0, sizeof d);
    d.n_fields             = 2u;
    d.field[0].bits        = 16u;
    d.field[0].derived_by  = 1u; /* derived, but FIRST in the cover */
    d.field[1].seq.kind    = WFM_SEQ_DOTTED;
    d.field[1].seq.len     = 24u;
    d.n_stages             = 1u;
    d.stage[0].first_field = 0u;
    d.stage[0].n_fields    = 2u;
    DP_CHECK_MSG (wfm_frame_desc_layout (&d, &l) == -1,
                  "a derived field must be last in its stage's cover");
  }

  /* ── assembling a description, and what it refuses ────────────────────
   *
   * `wfm_frame_bits` is `wfm_frame_assemble` over the four-field
   * configuration, so the sections above already exercise the field writing
   * and the built-in CRC. What is left is the part only a general
   * description reaches: a stage whose kernel this component does not own.
   */
  {
    uint8_t          buf[256];
    wfm_frame_desc_t d;
    memset (&d, 0, sizeof d);
    d.n_fields             = 1u;
    d.field[0].seq.kind    = WFM_SEQ_DOTTED;
    d.field[0].seq.len     = 32u;
    d.n_stages             = 1u;
    d.stage[0].kind        = WFM_STAGE_RS; /* nobody here implements it */
    d.stage[0].depth       = 1u;
    d.stage[0].first_field = 0u;
    d.stage[0].n_fields    = 1u;

    /* A stage with no kernel is a REFUSAL, never a silent skip. A skipped
       stage produces a frame that still assembles, still decodes against
       itself and syncs to nothing -- and it is indistinguishable in a log
       from one that ran, which is the same reason the validation harnesses
       fail rather than skip on a missing binary.

       Found by sabotage: making the assembler `continue` past an unknown
       kind passed every other test in the tree, because every other test
       supplies the kernels its description names. */
    memset (buf, 0xAAu, sizeof buf);
    DP_CHECK_MSG (wfm_frame_assemble (&d, NULL, buf, sizeof buf) == 0,
                  "a stage with no kernel must refuse, not run silently");
    int untouched = 1;
    for (size_t i = 0; i < sizeof buf; i++)
      if (buf[i] != 0xAAu)
        untouched = 0;
    DP_CHECK_MSG (untouched, "...and must not have written anything");

    /* The same description WITH a kernel must assemble, or the check above
       is satisfied by an assembler that refuses everything. */
    d.stage[0].kind = WFM_STAGE_CRC16; /* the built-in, over 32 - 16 bits */
    d.n_fields      = 2u;
    d.field[1].bits = WFM_FRAME_CRC_BITS;
    d.field[1].derived_by = 1u;
    d.stage[0].n_fields   = 2u;
    DP_CHECK_MSG (wfm_frame_assemble (&d, NULL, buf, sizeof buf) == 48u,
                  "...while a stage the built-ins DO cover assembles");

    DP_CHECK (wfm_frame_assemble (NULL, NULL, buf, sizeof buf) == 0);
    DP_CHECK (wfm_frame_assemble (&d, NULL, buf, 47u) == 0);
  }

  /* ── a DSSS burst from a description: assemble, then spread ───────────
   *
   * The four-field entry point is now this one with the description filled
   * in, so what is worth pinning is the part that only the general form can
   * express -- and the one structural decision underneath it: the preamble
   * is NOT a field of the description, because it is transmitted unspread.
   */
  {
    static const uint8_t acq[4]   = { 1, 0, 1, 1 };
    static const uint8_t dcode[3] = { 1, 0, 0 };
    static const uint8_t sync[5]  = { 1, 1, 0, 1, 0 };
    static const uint8_t pay[8]   = { 0, 1, 1, 0, 1, 0, 0, 1 };
    const size_t         reps = 2, pre = 4u * 2u, dl = 3u;

    uint8_t     legacy[512], general[512];
    wfm_frame_t f  = { 0 };
    f.sync.kind    = WFM_SEQ_LITERAL;
    f.sync.bits    = sync;
    f.sync.len     = sizeof sync;
    f.payload.kind = WFM_SEQ_LITERAL;
    f.payload.bits = pay;
    f.payload.len  = sizeof pay;
    f.crc          = 1;
    wfm_frame_desc_t d;
    DP_CHECK (wfm_frame_describe (&f, &d) == 0);

    const size_t want
        = pre + (sizeof sync + sizeof pay + WFM_FRAME_CRC_BITS) * dl;
    DP_CHECK_MSG (wfm_dsss_desc_nchips (&d, sizeof acq, reps, dl) == want,
                  "burst chips = preamble + spread frame");
    const size_t nl
        = wfm_frame_dsss_chips (acq, sizeof acq, reps, dcode, dl, sync,
                                sizeof sync, pay, sizeof pay, 1, legacy);
    const size_t ng = wfm_dsss_desc_chips (&d, NULL, acq, sizeof acq, reps,
                                           dcode, dl, general, sizeof general);
    DP_CHECK_MSG (nl == want && ng == want,
                  "both entry points write the same count");
    DP_CHECK_MSG (
        memcmp (legacy, general, want) == 0,
        "the four-field burst IS the described burst, chip for chip");

    /* The preamble is unspread and outside every stage's reach: it is the
       acquisition code verbatim, whatever the description does after it.
       Sabotage: make the preamble a FIELD of the description and this fails
       the moment any stage covers "the whole frame". */
    int pre_ok = 1;
    for (size_t r = 0; r < reps; r++)
      for (size_t i = 0; i < sizeof acq; i++)
        if (general[r * sizeof acq + i] != acq[i])
          pre_ok = 0;
    DP_CHECK_MSG (pre_ok, "the preamble is the acq code, unspread");

    /* A stage that lengthens the frame lengthens the burst by exactly its
       own bits, spread -- no second arithmetic anywhere. */
    wfm_frame_t g = f;
    g.crc         = 0;
    wfm_frame_desc_t d0;
    DP_CHECK (wfm_frame_describe (&g, &d0) == 0);
    DP_CHECK_MSG (wfm_dsss_desc_nchips (&d, sizeof acq, reps, dl)
                          - wfm_dsss_desc_nchips (&d0, sizeof acq, reps, dl)
                      == WFM_FRAME_CRC_BITS * dl,
                  "a CRC stage costs exactly its bits, spread");

    /* Refusals, in the shape the rest of this file uses: a stage nobody can
       run, a capacity that cannot hold the burst, and a frame with no code
       to spread it by. Each returns 0 and writes nothing. */
    wfm_frame_desc_t rsd     = d;
    rsd.n_stages             = 1u;
    rsd.stage[0].kind        = WFM_STAGE_RS; /* no kernel is supplied here */
    rsd.stage[0].depth       = 1u;
    rsd.stage[0].first_field = 0u;
    rsd.stage[0].n_fields    = rsd.n_fields;
    memset (general, 0xAAu, sizeof general);
    DP_CHECK_MSG (wfm_dsss_desc_chips (&rsd, NULL, acq, sizeof acq, reps,
                                       dcode, dl, general, sizeof general)
                      == 0,
                  "a stage with no kernel refuses the burst");
    DP_CHECK_MSG (general[0] == 0xAAu, "...and writes nothing");
    DP_CHECK (wfm_dsss_desc_chips (&d, NULL, acq, sizeof acq, reps, dcode, dl,
                                   general, want - 1u)
              == 0);
    DP_CHECK_MSG (wfm_dsss_desc_nchips (&d, sizeof acq, reps, 0u) == 0,
                  "frame bits with no spreading code is not a geometry");
  }

  /* ── the ops table EXTENDS the built-ins ──────────────────────────────
   *
   * The header's claim: a table "EXTENDS the built-ins rather than replacing
   * them -- so a table supplying an outer code does not have to restate the
   * CRC." Nothing pinned it. The paired assertion is what makes it evidence:
   * the SAME description must fail without the table and pass with it, or a
   * lookup that ignored the table entirely would satisfy the second half.
   */
  {
    uint8_t          b[128];
    wfm_frame_desc_t d;
    wfm_frame_ops_t  ops = toy_ops ();
    memset (&d, 0, sizeof d);
    d.n_fields             = 2u;
    d.field[0].seq.kind    = WFM_SEQ_DOTTED;
    d.field[0].seq.len     = 32u;
    d.field[1].bits        = WFM_FRAME_CRC_BITS;
    d.field[1].derived_by  = 1u; /* stage 0 */
    d.n_stages             = 2u;
    d.stage[0].kind        = WFM_STAGE_CRC16; /* built in, NOT in TOY_OPS */
    d.stage[0].first_field = 0u;
    d.stage[0].n_fields    = 2u;
    d.stage[1].kind        = WFM_STAGE_RANDOMISE; /* only in TOY_OPS */
    d.stage[1].first_field = 0u;
    d.stage[1].n_fields    = 2u;

    DP_CHECK_MSG (wfm_frame_assemble (&d, NULL, b, sizeof b) == 0,
                  "without the table the randomise stage has no kernel");
    DP_CHECK_MSG (wfm_frame_assemble (&d, &ops, b, sizeof b) == 48u,
                  "with it, the table's stage AND the built-in CRC resolve");
  }

  /* ── wfm_frame_check reverses in the OPPOSITE order ────────────────────
   *
   * "Stages are reversed in the OPPOSITE order to the one they were applied
   * in." Pinned nowhere. A test that merely watched check() return 1 would
   * not be evidence for it -- two stages that commute pass in either order.
   * So the pair is chosen NOT to commute, and the precondition proves it:
   * undoing the sum while the flip is still on top must FAIL. Only then does
   * check() == 1 mean the order was right.
   */
  {
    uint8_t          b[128], same_order[128];
    wfm_frame_desc_t d;
    wfm_frame_rx_t   rx;
    wfm_frame_ops_t  ops = toy_ops ();
    memset (&d, 0, sizeof d);
    d.n_fields             = 2u;
    d.field[0].seq.kind    = WFM_SEQ_DOTTED;
    d.field[0].seq.len     = 24u;
    d.field[1].bits        = TOY_SUM_BITS;
    d.field[1].derived_by  = 1u; /* stage 0 — the sum */
    d.n_stages             = 2u;
    d.stage[0].kind        = WFM_STAGE_RS; /* toy sum, applied FIRST  */
    d.stage[0].first_field = 0u;
    d.stage[0].n_fields    = 2u;
    d.stage[1].kind        = WFM_STAGE_RANDOMISE; /* toy flip, SECOND */
    d.stage[1].first_field = 0u;
    d.stage[1].n_fields    = 2u;

    DP_CHECK (wfm_frame_assemble (&d, &ops, b, sizeof b) == 32u);

    /* The precondition. Undo the sum WITHOUT undoing the flip first -- the
       same-order mistake -- and it must report not-ok, or the pair commutes
       and the assertion below is decoration. */
    memcpy (same_order, b, 32u);
    wfm_frame_stage_rx_t one;
    memset (&one, 0, sizeof one);
    DP_CHECK (toy_sum_undo (&d.stage[0], same_order, 32u, &one, NULL) == 0);
    DP_CHECK_MSG (one.ok == 0u,
                  "the toy pair must NOT commute, or the order test is "
                  "satisfied by any order at all");

    memset (&rx, 0, sizeof rx);
    DP_CHECK_MSG (wfm_frame_check (&d, &ops, b, &rx) == 1,
                  "reversing flip-then-sum recovers the frame");
    DP_CHECK_MSG (rx.checked == 2u, "both stages were actually reversed");
  }

  /* ── a stage with no undo is NOT CHECKED, never passed ─────────────────
   *
   * "A stage with no @c undo kernel is reported as **not checked**, never as
   * passed." The distinction is the whole point: an FER that read a stage it
   * never reversed as a stage that passed would report a clean link it had
   * not looked at. Asserting `ok` alone would not catch that -- `checked` is
   * the field under test.
   */
  {
    uint8_t          b[128];
    wfm_frame_desc_t d;
    wfm_frame_rx_t   rx;
    wfm_frame_ops_t  ops = toy_ops ();
    memset (&d, 0, sizeof d);
    d.n_fields             = 2u;
    d.field[0].seq.kind    = WFM_SEQ_DOTTED;
    d.field[0].seq.len     = 24u;
    d.field[1].bits        = TOY_SUM_BITS;
    d.field[1].derived_by  = 1u;
    d.n_stages             = 2u;
    d.stage[0].kind        = WFM_STAGE_RS; /* has an undo */
    d.stage[0].first_field = 0u;
    d.stage[0].n_fields    = 2u;
    d.stage[1].kind        = WFM_STAGE_CONV; /* in TOY_OPS with undo=NULL */
    d.stage[1].first_field = 0u;
    d.stage[1].n_fields    = 2u;

    DP_CHECK (wfm_frame_assemble (&d, &ops, b, sizeof b) == 32u);
    memset (&rx, 0, sizeof rx);
    DP_CHECK (wfm_frame_check (&d, &ops, b, &rx) == 1);
    DP_CHECK_MSG (rx.stage[0].checked == 1 && rx.stage[0].ok == 1u,
                  "the reversible stage was checked and passed");
    DP_CHECK_MSG (rx.stage[1].checked == 0,
                  "the stage with no undo is NOT CHECKED...");
    DP_CHECK_MSG (rx.stage[1].ok == 0u,
                  "...and does not get to report itself good");
    DP_CHECK_MSG (rx.checked == 1u, "exactly one stage was reversed here");
  }

  /* ── no checking stage at all is -1, not 1 ─────────────────────────────
   *
   * The header is emphatic and nothing asserted it: "**A description with no
   * checking stage at all returns -1**, not 1 ... an FER that conflated them
   * would score every unprotected frame as perfect." The passing case is
   * carried alongside so that -1 is not simply what this function always
   * returns.
   */
  {
    uint8_t          b[128];
    wfm_frame_desc_t d;
    wfm_frame_ops_t  ops = toy_ops ();
    memset (&d, 0, sizeof d);
    d.n_fields             = 2u;
    d.field[0].seq.kind    = WFM_SEQ_DOTTED;
    d.field[0].seq.len     = 24u;
    d.field[1].bits        = TOY_SUM_BITS;
    d.field[1].derived_by  = 1u;
    d.n_stages             = 1u;
    d.stage[0].kind        = WFM_STAGE_RS;
    d.stage[0].first_field = 0u;
    d.stage[0].n_fields    = 2u;
    DP_CHECK (wfm_frame_assemble (&d, &ops, b, sizeof b) == 32u);
    DP_CHECK_MSG (wfm_frame_check (&d, &ops, b, NULL) == 1,
                  "a description WITH a check answers 1");

    /* Same bits, same geometry — only the stage's reversibility differs. */
    d.stage[0].kind = WFM_STAGE_CONV; /* no undo */
    DP_CHECK_MSG (wfm_frame_check (&d, &ops, b, NULL) == -1,
                  "nothing was checked, so the answer is -1, not 1");

    d.n_stages = 0u;
    DP_CHECK_MSG (wfm_frame_check (&d, &ops, b, NULL) == -1,
                  "a description with no stages carries no check either");
  }

  /* ── wfm_frame_desc_crc_ok is a TRI-state ──────────────────────────────
   *
   * Zero mentions anywhere in the tree before this. "The three are distinct
   * on purpose: an FER that read 'carries no check' as 'the check failed'
   * would count every unprotected frame as an error." All three are asserted
   * here, because two of them passing says nothing about the third.
   */
  {
    uint8_t          b[128];
    wfm_frame_desc_t d;
    memset (&d, 0, sizeof d);
    d.n_fields             = 2u;
    d.field[0].seq.kind    = WFM_SEQ_DOTTED;
    d.field[0].seq.len     = 32u;
    d.field[1].bits        = WFM_FRAME_CRC_BITS;
    d.field[1].derived_by  = 1u;
    d.n_stages             = 1u;
    d.stage[0].kind        = WFM_STAGE_CRC16;
    d.stage[0].first_field = 0u;
    d.stage[0].n_fields    = 2u;

    DP_CHECK (wfm_frame_assemble (&d, NULL, b, sizeof b) == 48u);
    DP_CHECK_MSG (wfm_frame_desc_crc_ok (&d, b) == 1, "a good frame is 1");

    b[0] ^= 1u;
    DP_CHECK_MSG (wfm_frame_desc_crc_ok (&d, b) == 0, "a corrupt one is 0");
    b[0] ^= 1u;
    DP_CHECK (wfm_frame_desc_crc_ok (&d, b) == 1);

    /* Carries no CRC at all — the third answer. */
    wfm_frame_desc_t n = d;
    n.stage[0].kind    = WFM_STAGE_RANDOMISE;
    DP_CHECK_MSG (wfm_frame_desc_crc_ok (&n, b) == -1,
                  "no CRC stage is -1, which is not 'the check failed'");

    DP_CHECK (wfm_frame_desc_crc_ok (NULL, b) == -1);
    DP_CHECK (wfm_frame_desc_crc_ok (&d, NULL) == -1);
  }

  /* ── the second built-in: INTERLEAVE, through the general path ─────────
   *
   * WFM_STAGE_INTERLEAVE had zero mentions in this file; it was reached only
   * through ccsds_tm and frame_core. It needs no table, so it is the cheapest
   * proof that a built-in round-trips on the general descriptor.
   *
   * The non-identity assertion is the guard that matters: an interleaver that
   * permuted nothing would satisfy "undo restores the input" perfectly.
   */
  {
    static uint8_t   pat[32];
    uint8_t          woven[64], plain[64];
    wfm_frame_desc_t d;
    wfm_frame_rx_t   rx;
    for (size_t i = 0; i < sizeof pat; i++)
      pat[i] = (uint8_t)(i < 16u); /* 16 ones then 16 zeros */

    memset (&d, 0, sizeof d);
    d.n_fields          = 1u;
    d.field[0].seq.kind = WFM_SEQ_LITERAL;
    d.field[0].seq.bits = pat;
    d.field[0].seq.len  = sizeof pat;

    DP_CHECK (wfm_frame_assemble (&d, NULL, plain, sizeof plain) == 32u);

    d.n_stages             = 1u;
    d.stage[0].kind        = WFM_STAGE_INTERLEAVE;
    d.stage[0].first_field = 0u;
    d.stage[0].n_fields    = 1u;
    d.stage[0].depth       = 4u;
    d.stage[0].unit_bits   = 1u;
    DP_CHECK (wfm_frame_assemble (&d, NULL, woven, sizeof woven) == 32u);

    DP_CHECK_MSG (memcmp (woven, plain, 32u) != 0,
                  "the interleaver must actually permute, or 'undo restores "
                  "it' is satisfied by doing nothing");

    memset (&rx, 0, sizeof rx);
    DP_CHECK_MSG (wfm_frame_check (&d, NULL, woven, &rx) == 1,
                  "a built-in needs no ops table to be reversed");
    DP_CHECK_MSG (memcmp (woven, plain, 32u) == 0,
                  "...and undoing it restores the original bits exactly");
  }

  /* ── a kind doppler has never heard of ─────────────────────────────────
   *
   * The point of the whole representation, and until the kind became an open
   * uint32_t it was not expressible: a caller allocates from WFM_STAGE_USER
   * up, supplies the kernel through its own table, and the assembler neither
   * knows nor needs to know what the stage does. "A mission that is not
   * CCSDS" is then a configuration rather than a pull request against
   * wfm_frame.h.
   *
   * The refusal half is the same assertion doppler's own kinds get: unknown
   * kind, no kernel, no frame -- never a silent skip.
   */
  {
    uint8_t          b[128];
    wfm_frame_desc_t d;
    wfm_frame_rx_t   rx;
    wfm_frame_ops_t  ops = toy_ops ();
    memset (&d, 0, sizeof d);
    d.n_fields             = 2u;
    d.field[0].seq.kind    = WFM_SEQ_DOTTED;
    d.field[0].seq.len     = 24u;
    d.field[1].bits        = TOY_SUM_BITS;
    d.field[1].derived_by  = 1u;
    d.n_stages             = 2u;
    d.stage[0].kind        = WFM_STAGE_RS;
    d.stage[0].first_field = 0u;
    d.stage[0].n_fields    = 2u;
    d.stage[1].kind        = WFM_STAGE_USER + 1u; /* not doppler's */
    d.stage[1].first_field = 0u;
    d.stage[1].n_fields    = 2u;

    DP_CHECK_MSG (wfm_frame_assemble (&d, NULL, b, sizeof b) == 0,
                  "a user kind with no kernel is refused like any other");
    DP_CHECK_MSG (wfm_frame_assemble (&d, &ops, b, sizeof b) == 32u,
                  "with the caller's table it assembles...");
    memset (&rx, 0, sizeof rx);
    DP_CHECK_MSG (wfm_frame_check (&d, &ops, b, &rx) == 1,
                  "...and reverses through the same open lookup");
    DP_CHECK_MSG (rx.checked == 2u,
                  "the user stage is reversed like a built-in, not skipped");

    /* WFM_STAGE_USER must sit above every kind doppler names, or a caller
       allocating at it would collide with a built-in the day one is added. */
    DP_CHECK_MSG (WFM_STAGE_USER > WFM_STAGE_INTERLEAVE,
                  "the caller range must not overlap doppler's");
  }

  /* ── a field's NAME, and the one lookup that resolves it ──────────────
   *
   * Names exist so the other direction reads: a receiver slicing a capture
   * asks for "payload" rather than for field 2, and `derived_by` /
   * `first_field` / `n_fields` stop being indices a reader has to hold in
   * their head. They resolve to indices in exactly one place, so every
   * index-taking entry point keeps working and a rename can only be wrong
   * once.
   */
  {
    wfm_frame_desc_t d;
    memset (&d, 0, sizeof d);
    d.n_fields = 3u;
    strcpy (d.field[0].name, "sync");
    d.field[0].seq.kind = WFM_SEQ_DOTTED;
    d.field[0].seq.len  = 8u;
    /* field[1] is deliberately left ANONYMOUS. */
    d.field[1].seq.kind = WFM_SEQ_DOTTED;
    d.field[1].seq.len  = 16u;
    strcpy (d.field[2].name, "payload");
    d.field[2].seq.kind = WFM_SEQ_DOTTED;
    d.field[2].seq.len  = 24u;

    DP_CHECK (wfm_frame_field_index (&d, "sync") == 0);
    DP_CHECK (wfm_frame_field_index (&d, "payload") == 2);
    DP_CHECK_MSG (wfm_frame_field_index (&d, "crc") == -1,
                  "a name no field carries is -1, not a guess");

    /* An unnamed field is ANONYMOUS, not named "". Matching it would make an
       unnamed description answer questions about fields it does not have --
       and every description in this file before now is unnamed. */
    DP_CHECK_MSG (wfm_frame_field_index (&d, "") == -1,
                  "the empty name matches nothing, including field 1");

    DP_CHECK (wfm_frame_field_index (NULL, "sync") == -1);
    DP_CHECK (wfm_frame_field_index (&d, NULL) == -1);

    /* Names change nothing about the geometry: the same description lays out
       identically whether or not its fields are named. That is what makes
       this addition safe for every caller that predates it. */
    wfm_frame_desc_layout_t named, anon;
    DP_CHECK (wfm_frame_desc_layout (&d, &named) == 0);
    for (unsigned i = 0; i < d.n_fields; i++)
      d.field[i].name[0] = '\0';
    DP_CHECK (wfm_frame_desc_layout (&d, &anon) == 0);
    DP_CHECK_MSG (named.frame_bits == anon.frame_bits
                      && named.field_off[2] == anon.field_off[2],
                  "a name is not part of the geometry");
    DP_CHECK_MSG (wfm_frame_field_index (&d, "sync") == -1,
                  "...and clearing the names really did clear them");
  }

  /* ── building a description by NAME ───────────────────────────────────
   *
   * The falsification available here is the strong one: a description built
   * by name must be BIT-IDENTICAL to the same description filled in by hand,
   * because the builder adds no arithmetic -- it only spells the indices.
   * Comparing the assembled bits rather than the structs is what makes that
   * a claim about behaviour instead of about layout.
   */
  {
    uint8_t          by_hand[128], by_name[128];
    wfm_frame_desc_t h, n;

    /* By hand: the shape every test above uses. */
    memset (&h, 0, sizeof h);
    h.n_fields             = 2u;
    h.field[0].seq.kind    = WFM_SEQ_DOTTED;
    h.field[0].seq.len     = 32u;
    h.field[1].bits        = WFM_FRAME_CRC_BITS;
    h.field[1].derived_by  = 1u; /* stage 0, PLUS ONE */
    h.n_stages             = 1u;
    h.stage[0].kind        = WFM_STAGE_CRC16;
    h.stage[0].first_field = 0u;
    h.stage[0].n_fields    = 2u;

    /* By name: the same thing said differently. */
    memset (&n, 0, sizeof n);
    wfm_seq_t payload = { 0 };
    payload.kind      = WFM_SEQ_DOTTED;
    payload.len       = 32u;
    DP_CHECK (wfm_frame_add_field (&n, "payload", &payload, 0u) == 0);
    DP_CHECK (wfm_frame_add_derived (&n, "crc", WFM_FRAME_CRC_BITS) == 1);
    DP_CHECK (wfm_frame_add_stage (&n, WFM_STAGE_CRC16, "payload", "crc")
              == 0);

    /* add_stage wired the producer, and it wired the RIGHT one. */
    DP_CHECK_MSG (n.field[1].derived_by == 1u,
                  "the derived field's producer is the stage that covers it");

    const size_t nh = wfm_frame_assemble (&h, NULL, by_hand, sizeof by_hand);
    const size_t nn = wfm_frame_assemble (&n, NULL, by_name, sizeof by_name);
    DP_CHECK (nh == 48u && nn == 48u);
    DP_CHECK_MSG (memcmp (by_hand, by_name, 48u) == 0,
                  "naming the fields changes no bit of the frame");

    /* A stage's cover really came from the NAMES, not from appending order:
       ask for a cover that starts at the second field and the span moves. */
    wfm_frame_desc_t m;
    memset (&m, 0, sizeof m);
    wfm_seq_t eight = { 0 };
    eight.kind      = WFM_SEQ_DOTTED;
    eight.len       = 8u;
    DP_CHECK (wfm_frame_add_field (&m, "a", &eight, 0u) == 0);
    DP_CHECK (wfm_frame_add_field (&m, "b", &eight, 0u) == 1);
    DP_CHECK (wfm_frame_add_field (&m, "c", &eight, 0u) == 2);
    DP_CHECK (wfm_frame_add_stage (&m, WFM_STAGE_INTERLEAVE, "b", "c") == 0);
    DP_CHECK_MSG (m.stage[0].first_field == 1u && m.stage[0].n_fields == 2u,
                  "the cover is the named range, not the whole frame");

    /* Refusals. */
    DP_CHECK_MSG (wfm_frame_add_field (&m, "b", &eight, 0u) == -1,
                  "a duplicate name is refused, not silently shadowed");
    DP_CHECK_MSG (wfm_frame_add_stage (&m, WFM_STAGE_CRC16, "a", "zzz") == -1,
                  "a cover naming a field that does not exist is refused");
    DP_CHECK_MSG (wfm_frame_add_stage (&m, WFM_STAGE_CRC16, "c", "a") == -1,
                  "a cover that runs backwards is refused");
    DP_CHECK (wfm_frame_add_field (NULL, "x", &eight, 0u) == -1);
    DP_CHECK (wfm_frame_add_field (&m, "x", NULL, 0u) == -1);
    DP_CHECK (wfm_frame_add_derived (&m, "x", 0u) == -1);

    /* Anonymous fields never collide, because "" is not a name. */
    wfm_frame_desc_t q;
    memset (&q, 0, sizeof q);
    DP_CHECK (wfm_frame_add_field (&q, NULL, &eight, 0u) == 0);
    DP_CHECK_MSG (wfm_frame_add_field (&q, NULL, &eight, 0u) == 1,
                  "two anonymous fields are two fields, not a collision");

    /* The description fills up and REFUSES rather than overwriting. */
    wfm_frame_desc_t full;
    memset (&full, 0, sizeof full);
    for (unsigned i = 0; i < WFM_FRAME_MAX_FIELDS; i++)
      DP_CHECK (wfm_frame_add_field (&full, NULL, &eight, 0u) == (int)i);
    DP_CHECK_MSG (wfm_frame_add_field (&full, NULL, &eight, 0u) == -1,
                  "a full description refuses the next field");
    DP_CHECK (full.n_fields == WFM_FRAME_MAX_FIELDS);
  }

  /* ── the GENERATED kinds, through that same by-name face ───────────────
   *
   * Everything above reaches a PN or a Gold field through `wfm_frame_t`'s
   * three named slots. The general description -- what wfm_frame_add_field
   * builds and what every by-name caller assembles -- carried only LITERAL
   * and DOTTED fields in this suite, so nothing pinned a generated field
   * reached THIS way to the generator it claims to be. That is the face a
   * user-defined frame is built through, so it is the one that has to hold.
   */
  {
    wfm_seq_t pn = { 0 };
    pn.kind      = WFM_SEQ_PN;
    pn.len       = 20u; /* deliberately NOT a whole period; see below */
    pn.reg_bits  = 5u;
    pn.seed      = 3u;

    wfm_seq_t gold = { 0 };
    gold.kind      = WFM_SEQ_GOLD;
    gold.len       = 64u;
    gold.reg_bits  = 10u;
    gold.taps_a    = 934u;
    gold.seed_a    = 350u;
    gold.taps_b    = 567u;
    gold.seed_b    = 73u;

    wfm_frame_desc_t d;
    memset (&d, 0, sizeof d);
    DP_REQUIRE (wfm_frame_add_field (&d, "sync", &pn, 3u) == 0);
    DP_REQUIRE (wfm_frame_add_field (&d, "payload", &gold, 0u) == 1);

    wfm_frame_desc_layout_t l;
    DP_REQUIRE (wfm_frame_desc_layout (&d, &l) == 0);
    DP_CHECK_MSG (l.field_bits[0] == 60u && l.field_bits[1] == 64u,
                  "a generated field is len*reps like any other");
    DP_REQUIRE (wfm_frame_assemble (&d, NULL, buf, CAP) == l.out_bits);

    /* Gold against its OWN generator. The named starter set compares a Gold
       sync against a PN one and asserts they differ in about half their
       positions -- which a swapped taps_a/taps_b, or an ignored seed_b,
       satisfies just as well. That two independent sequences differ says
       nothing about WHICH sequence either one of them is. */
    static uint8_t want_g[64];
    gold_state_t  *g = gold_create (934u, 350u, 567u, 73u, 10u);
    DP_REQUIRE_MSG (g != NULL, "gold_create");
    DP_REQUIRE (gold_generate (g, 64u, want_g, 64u) == 64u);
    gold_destroy (g);
    DP_CHECK_MSG (memcmp (buf + l.field_off[1], want_g, 64u) == 0,
                  "a Gold field IS gold_generate of its own descriptor");

    /* The PN field, one period of it. */
    static uint8_t want_p[20];
    pn_state_t    *p = pn_create (pn_mls_poly (5u), 3u, 5u, 0);
    DP_REQUIRE_MSG (p != NULL, "pn_create");
    DP_REQUIRE (pn_generate (p, 20u, want_p, 20u) == 20u);
    pn_destroy (p);
    DP_CHECK_MSG (memcmp (buf + l.field_off[0], want_p, 20u) == 0,
                  "a PN field IS pn_generate of its own descriptor");
    for (size_t r = 1u; r < 3u; r++)
      DP_CHECK_MSG (
          memcmp (buf + l.field_off[0] + r * 20u, buf + l.field_off[0], 20u)
              == 0,
          "every repetition of a generated field is identical");

    /* The property DOTTED cannot falsify. wfm_frame.c states that a repeated
       generated field repeats the SAME bits rather than drawing fresh ones,
       because period is what coherent integration across reps depends on.
       Every repeated generated field in this suite was DOTTED -- and dotted
       redrawn is bit-for-bit dotted repeated, so no test here could tell the
       two implementations apart and the claim was prose. A PN field can tell
       them apart, as long as its length is not a whole period: 60 bits of a
       5-bit register IS three periods, and would have agreed by accident. */
    static uint8_t run_on[60];
    pn_state_t    *pc = pn_create (pn_mls_poly (5u), 3u, 5u, 0);
    DP_REQUIRE_MSG (pc != NULL, "pn_create");
    DP_REQUIRE (pn_generate (pc, 60u, run_on, 60u) == 60u);
    pn_destroy (pc);
    DP_CHECK_MSG (memcmp (buf + l.field_off[0], run_on, 60u) != 0,
                  "a repeated PN field REPEATS its period -- it is not the "
                  "LFSR run on for the whole span");
  }

  /* ── an EMITTING stage covers the whole frame, or it is refused ────────
   *
   * `wfm_frame_assemble` hands `emit` the whole assembled frame and demands
   * exactly `out_bits` back. The layout used to compute `out_bits` from the
   * stage's COVER instead -- "the bits it does not cover pass through at
   * their own width" -- which nothing implements. The two disagreed only
   * when a cover was narrower than the frame, and doppler's own three
   * emitting stages all cover everything, so the disagreement never fired
   * in the tree while remaining reachable by any caller.
   *
   * The failure it produced is the expensive kind: `wfm_frame_desc_layout`
   * returned 0, every offset looked right, and `wfm_frame_assemble` then
   * returned 0 for ever with no way to tell a bad description from bad
   * data.
   */
  {
    uint8_t                 buf[512];
    wfm_frame_desc_t        d;
    wfm_frame_desc_layout_t l;

    /* Two fields, an emitting stage over only the first. */
    memset (&d, 0, sizeof d);
    d.n_fields             = 2u;
    d.field[0].seq.kind    = WFM_SEQ_DOTTED;
    d.field[0].seq.len     = 32u;
    d.field[1].seq.kind    = WFM_SEQ_DOTTED;
    d.field[1].seq.len     = 16u;
    d.n_stages             = 1u;
    d.stage[0].kind        = WFM_STAGE_CONV;
    d.stage[0].first_field = 0u;
    d.stage[0].n_fields    = 1u; /* 32 of 48 bits */
    d.stage[0].emit_num    = 2u;
    d.stage[0].emit_den    = 1u;
    DP_CHECK_MSG (wfm_frame_desc_layout (&d, &l) == -1,
                  "an emitting stage over PART of the frame is refused by "
                  "the layout, not discovered as a 0 from assemble");
    DP_CHECK_MSG (wfm_frame_assemble (&d, NULL, buf, sizeof buf) == 0,
                  "and it still assembles nothing, from the same refusal");

    /* Widen it to the whole frame and the same description is fine. Both
       directions: a rule that only ever refuses is satisfied by refusing
       everything, which would quietly retire the inner code. */
    d.stage[0].n_fields = 2u;
    DP_REQUIRE_MSG (wfm_frame_desc_layout (&d, &l) == 0,
                    "covering the whole frame is accepted");
    DP_CHECK_MSG (l.frame_bits == 48u && l.out_bits == 96u,
                  "rate 1/2 doubles the whole frame");

    /* At most ONE emitting stage. A second would have to consume the
       first's output, and nothing passes it that -- `assemble` hands every
       emitting stage the same assembled frame. The old loop simply let the
       last one win, so a two-stage description reported a plausible
       `out_bits` that no pair of kernels could produce. */
    d.n_stages             = 2u;
    d.stage[1].kind        = WFM_STAGE_CONV;
    d.stage[1].first_field = 0u;
    d.stage[1].n_fields    = 2u;
    d.stage[1].emit_num    = 2u;
    d.stage[1].emit_den    = 1u;
    DP_CHECK_MSG (wfm_frame_desc_layout (&d, &l) == -1,
                  "a second emitting stage is refused");

    /* A stage that DID NOT RUN is not an emitting stage. Its span is zero,
       so it cannot be the one that sets the length -- and refusing it would
       break every optional inner code, which is declared and then switched
       off by covering nothing. */
    d.stage[1].n_fields = 0u;
    DP_CHECK_MSG (wfm_frame_desc_layout (&d, &l) == 0,
                  "a declared-but-not-running emitting stage is ignored, "
                  "not counted against the one-emitter rule");
  }

  if (test_seq_bits ())
    return 1;
  if (test_dsss_nchips ())
    return 1;
  DP_TEST_END ("wfm_frame");
}
