/*
 * measure_ext_tonemeas.c — ToneMeasure type for the measure module.
 *
 * Included by measure_ext.c (the module aggregator).
 * Hand-patches to this file are preserved across jm commands.
 * Do NOT compile this file directly — only measure_ext.c is compiled.
 */
/* ======================================================== */
/* ToneMeasureObject — wraps tonemeas_state_t *       */
/* ======================================================== */

#include "tonemeas/tonemeas_core.h"

typedef struct
{
  PyObject_HEAD tonemeas_state_t *handle;
  float *_spectrum_dbfs_buf;     /* pre-allocated output for spectrum_dbfs */
  size_t _spectrum_dbfs_buf_cap; /* allocated capacity for spectrum_dbfs */
  void **_spectrum_dbfs_retired; /* gh-219 deferred free */
  size_t _spectrum_dbfs_retired_n;
  size_t _spectrum_dbfs_retired_cap;
} ToneMeasureObject;

/* ── named-tuple results ───────────────────────────────────────────────────
 * analyze()/time_stats() return a PyStructSequence so callers get attribute
 * access (m.enob, m.sfdr_dbc) AND tuple unpacking.  The types are built lazily
 * on first use (GIL-held) and cached — the module aggregator is regenerated by
 * jm, so all of this lives in the hand-owned fragment, not module init. */
static PyStructSequence_Field _tone_metrics_fields[]
    = { { "snr", "signal-to-noise ratio (dB)" },
        { "sinad", "signal-to-noise-and-distortion ratio (dB)" },
        { "thd", "total harmonic distortion (dBc)" },
        { "thd_pct", "total harmonic distortion (%)" },
        { "thd_n", "THD+N relative to the fundamental (dBc); equals -sinad" },
        { "sfdr_dbc", "spurious-free dynamic range vs the carrier (dBc)" },
        { "sfdr_dbfs", "spurious-free dynamic range vs full scale (dBFS)" },
        { "enob", "effective number of bits" },
        { "enob_fs", "full-scale-corrected effective number of bits" },
        { "noise_floor_dbfs", "mean per-bin noise power (dBFS)" },
        { "fund_freq", "fundamental frequency (Hz)" },
        { "fund_dbfs", "fundamental level (dBFS)" },
        { "worst_spur_freq", "worst-spur frequency (Hz)" },
        { "worst_spur_dbc", "worst-spur level vs the fundamental (dBc)" },
        { "worst_spur_is_harm", "1 if the worst spur is a harmonic" },
        { "rbw_hz", "resolution bandwidth (Hz)" },
        { "enbw_hz", "equivalent noise bandwidth (Hz)" },
        { "bin_hz", "FFT bin spacing (Hz)" },
        { "lobe_bins", "window main-lobe half-width L (bins)" },
        { "n_noise_bins", "number of bins counted as noise" },
        { "proc_gain_db", "FFT processing gain (dB)" },
        { "amp_uncert_db", "amplitude-read uncertainty bound (dB)" },
        { "floor_uncert_db", "noise-floor standard error (dB)" },
        { NULL } };
static PyStructSequence_Desc _tone_metrics_desc
    = { "doppler.measure.ToneMetrics",
        "Single-tone ADC / spectral measurement bag.", _tone_metrics_fields,
        23 };
static PyTypeObject *_ToneMetricsType = NULL;

static PyStructSequence_Field _time_stats_fields[]
    = { { "rms", "root-mean-square (DC included)" },
        { "peak", "peak |x - DC|" },
        { "crest_db", "crest factor (dB)" },
        { "papr_db", "peak-to-average power ratio (dB)" },
        { "dc_offset", "mean(x)" },
        { "fs_util_pct", "full-scale utilisation (%)" },
        { NULL } };
static PyStructSequence_Desc _time_stats_desc
    = { "doppler.measure.TimeStats", "Time-domain capture statistics.",
        _time_stats_fields, 6 };
static PyTypeObject *_TimeStatsType = NULL;

static PyObject *
_build_tone_metrics (const tone_meas_t *r)
{
  if (!_ToneMetricsType)
    {
      _ToneMetricsType = PyStructSequence_NewType (&_tone_metrics_desc);
      if (!_ToneMetricsType)
        return NULL;
    }
  PyObject *o = PyStructSequence_New (_ToneMetricsType);
  if (!o)
    return NULL;
  int i = 0;
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->snr));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->sinad));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->thd));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->thd_pct));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->thd_n));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->sfdr_dbc));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->sfdr_dbfs));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->enob));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->enob_fs));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->noise_floor_dbfs));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->fund_freq));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->fund_dbfs));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->worst_spur_freq));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->worst_spur_dbc));
  PyStructSequence_SetItem (o, i++, PyLong_FromLong (r->worst_spur_is_harm));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->rbw_hz));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->enbw_hz));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->bin_hz));
  PyStructSequence_SetItem (
      o, i++, PyLong_FromUnsignedLongLong ((unsigned long long)r->lobe_bins));
  PyStructSequence_SetItem (
      o, i++,
      PyLong_FromUnsignedLongLong ((unsigned long long)r->n_noise_bins));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->proc_gain_db));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->amp_uncert_db));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->floor_uncert_db));
  if (PyErr_Occurred ())
    {
      Py_DECREF (o);
      return NULL;
    }
  return o;
}

static PyObject *
_build_time_stats (const time_stats_t *r)
{
  if (!_TimeStatsType)
    {
      _TimeStatsType = PyStructSequence_NewType (&_time_stats_desc);
      if (!_TimeStatsType)
        return NULL;
    }
  PyObject *o = PyStructSequence_New (_TimeStatsType);
  if (!o)
    return NULL;
  int i = 0;
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->rms));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->peak));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->crest_db));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->papr_db));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->dc_offset));
  PyStructSequence_SetItem (o, i++, PyFloat_FromDouble (r->fs_util_pct));
  if (PyErr_Occurred ())
    {
      Py_DECREF (o);
      return NULL;
    }
  return o;
}

static void
ToneMeasureObj_dealloc (ToneMeasureObject *self)
{
  if (self->handle)
    tonemeas_destroy (self->handle);
  free (self->_spectrum_dbfs_buf);
  for (size_t _i = 0; _i < self->_spectrum_dbfs_retired_n; _i++)
    free (self->_spectrum_dbfs_retired[_i]);
  free (self->_spectrum_dbfs_retired);
  Py_TYPE (self)->tp_free ((PyObject *)self);
}

static PyObject *
ToneMeasureObj_new (PyTypeObject *type, PyObject *args, PyObject *kwds)
{
  ToneMeasureObject *self = (ToneMeasureObject *)type->tp_alloc (type, 0);
  if (self)
    self->handle = NULL;
  return (PyObject *)self;
}

static int
ToneMeasureObj_init (ToneMeasureObject *self, PyObject *args, PyObject *kwds)
{
  static char *kwlist[]
      = { "window",      "n",          "fs",       "beta", "pad",
          "n_harmonics", "full_scale", "dc_guard", NULL };
  const char *window_str = "kaiser";
  /* jm drops size_t init-param defaults from the generated binding (it only
   * honours float/double defaults), so the integer defaults from
   * objects/tonemeas.toml are applied here by hand. */
  unsigned long long n_raw           = 8192ULL;
  double             fs              = 1.0;
  float              beta            = 12.0f;
  unsigned long long pad_raw         = 2ULL;
  unsigned long long n_harmonics_raw = 8ULL;
  double             full_scale      = 1.0;
  unsigned long long dc_guard_raw    = 0ULL;

  if (!PyArg_ParseTupleAndKeywords (
          args, kwds, "|sKdfKKdK", kwlist, &window_str, &n_raw, &fs, &beta,
          &pad_raw, &n_harmonics_raw, &full_scale, &dc_guard_raw))
    return -1;
  int window = 0;
  if (strcmp (window_str, "hann") == 0)
    window = 0;
  else if (strcmp (window_str, "kaiser") == 0)
    window = 1;
  else
    {
      PyErr_Format (PyExc_ValueError,
                    "window must be one of \"hann\", \"kaiser\", got '%s'",
                    window_str);
      return -1;
    }
  size_t n           = (size_t)n_raw;
  size_t pad         = (size_t)pad_raw;
  size_t n_harmonics = (size_t)n_harmonics_raw;
  size_t dc_guard    = (size_t)dc_guard_raw;
  self->handle       = tonemeas_create (n, fs, window, beta, pad, n_harmonics,
                                        full_scale, dc_guard);
  if (!self->handle)
    {
      PyErr_SetString (PyExc_MemoryError, "tonemeas_create returned NULL");
      return -1;
    }
  {
    size_t _max = tonemeas_spectrum_dbfs_max_out (self->handle);
    if (_max)
      {
        self->_spectrum_dbfs_buf = malloc (_max * sizeof (float));
        if (!self->_spectrum_dbfs_buf)
          {
            PyErr_NoMemory ();
            return -1;
          }
        self->_spectrum_dbfs_buf_cap = _max;
      }
  }
  return 0;
}

static PyObject *
ToneMeasureObj_reset (ToneMeasureObject *self, PyObject *Py_UNUSED (ignored))
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  tonemeas_reset (self->handle);
  Py_RETURN_NONE;
}

static PyObject *
ToneMeasureObj_analyze (ToneMeasureObject *self, PyObject *args)
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  PyObject *in_obj = NULL;
  if (!PyArg_ParseTuple (args, "O", &in_obj))
    return NULL;
  PyArrayObject *in_arr = (PyArrayObject *)PyArray_FROM_OTF (
      in_obj, NPY_FLOAT, NPY_ARRAY_C_CONTIGUOUS);
  if (!in_arr)
    return NULL;
  size_t       n_in  = (size_t)PyArray_SIZE (in_arr);
  const float *_data = (const float *)PyArray_DATA (in_arr);
  tone_meas_t  r;
  Py_BEGIN_ALLOW_THREADS
    tonemeas_analyze (self->handle, _data, n_in, &r, 1);
  Py_END_ALLOW_THREADS
  Py_DECREF (in_arr);
  return _build_tone_metrics (&r);
}

static PyObject *
ToneMeasureObj_analyze_complex (ToneMeasureObject *self, PyObject *args)
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  PyObject *in_obj = NULL;
  if (!PyArg_ParseTuple (args, "O", &in_obj))
    return NULL;
  PyArrayObject *in_arr = (PyArrayObject *)PyArray_FROM_OTF (
      in_obj, NPY_COMPLEX64, NPY_ARRAY_C_CONTIGUOUS);
  if (!in_arr)
    return NULL;
  size_t               n_in  = (size_t)PyArray_SIZE (in_arr);
  const float complex *_data = (const float complex *)PyArray_DATA (in_arr);
  tone_meas_t          r;
  Py_BEGIN_ALLOW_THREADS
    tonemeas_analyze_complex (self->handle, _data, n_in, &r, 1);
  Py_END_ALLOW_THREADS
  Py_DECREF (in_arr);
  return _build_tone_metrics (&r);
}

static PyObject *
ToneMeasureObj_time_stats (ToneMeasureObject *self, PyObject *args)
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  PyObject *in_obj = NULL;
  if (!PyArg_ParseTuple (args, "O", &in_obj))
    return NULL;
  PyArrayObject *in_arr = (PyArrayObject *)PyArray_FROM_OTF (
      in_obj, NPY_FLOAT, NPY_ARRAY_C_CONTIGUOUS);
  if (!in_arr)
    return NULL;
  size_t       n_in = (size_t)PyArray_SIZE (in_arr);
  time_stats_t r;
  tonemeas_time_stats (self->handle, (const float *)PyArray_DATA (in_arr),
                       n_in, &r, 1);
  Py_DECREF (in_arr);
  return _build_time_stats (&r);
}

static PyObject *
ToneMeasureObj_spectrum_dbfs (ToneMeasureObject *self, PyObject *args)
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  PyObject      *x_obj = NULL;
  PyArrayObject *x_arr = NULL;
  if (!PyArg_ParseTuple (args, "O", &x_obj))
    return NULL;
  x_arr = (PyArrayObject *)PyArray_FROM_OTF (x_obj, NPY_FLOAT,
                                             NPY_ARRAY_C_CONTIGUOUS);
  if (!x_arr)
    return NULL;
  size_t _need = (size_t)PyArray_SIZE (x_arr);
  if (!self->_spectrum_dbfs_buf || self->_spectrum_dbfs_buf_cap < _need)
    {
      size_t _max = tonemeas_spectrum_dbfs_max_out (self->handle);
      if (!_max || _max < _need)
        _max = _need;
      if (self->_spectrum_dbfs_buf
          && self->_spectrum_dbfs_retired_n
                 == self->_spectrum_dbfs_retired_cap)
        {
          size_t _rcap = self->_spectrum_dbfs_retired_cap
                             ? self->_spectrum_dbfs_retired_cap * 2
                             : 4;
          void **_rt   = realloc (self->_spectrum_dbfs_retired,
                                  _rcap * sizeof (void *));
          if (!_rt)
            {
              Py_DECREF (x_arr);
              PyErr_NoMemory ();
              return NULL;
            }
          self->_spectrum_dbfs_retired     = _rt;
          self->_spectrum_dbfs_retired_cap = _rcap;
        }
      float *_tmp = malloc (_max * sizeof (float));
      if (!_tmp)
        {
          Py_DECREF (x_arr);
          PyErr_NoMemory ();
          return NULL;
        }
      if (self->_spectrum_dbfs_buf)
        self->_spectrum_dbfs_retired[self->_spectrum_dbfs_retired_n++]
            = self->_spectrum_dbfs_buf;
      self->_spectrum_dbfs_buf     = _tmp;
      self->_spectrum_dbfs_buf_cap = _max;
    }
  size_t n_out = tonemeas_spectrum_dbfs (
      self->handle, (const float *)PyArray_DATA (x_arr),
      (size_t)PyArray_SIZE (x_arr), self->_spectrum_dbfs_buf);
  npy_intp  dim = (npy_intp)n_out;
  PyObject *arr = PyArray_SimpleNewFromData (1, &dim, NPY_FLOAT,
                                             self->_spectrum_dbfs_buf);
  if (!arr)
    return NULL;
  PyArray_SetBaseObject ((PyArrayObject *)arr, (PyObject *)self);
  Py_INCREF (self);
  Py_DECREF (x_arr);
  return arr;
}
static PyObject *
ToneMeasure_getprop_n (ToneMeasureObject *self, void *Py_UNUSED (closure))
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  return PyLong_FromUnsignedLongLong ((unsigned long long)self->handle->n);
}
static PyObject *
ToneMeasure_getprop_nfft (ToneMeasureObject *self, void *Py_UNUSED (closure))
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  return PyLong_FromUnsignedLongLong ((unsigned long long)self->handle->nfft);
}
static PyObject *
ToneMeasure_getprop_fs (ToneMeasureObject *self, void *Py_UNUSED (closure))
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  return PyFloat_FromDouble (self->handle->fs);
}
static PyObject *
ToneMeasure_getprop_enbw (ToneMeasureObject *self, void *Py_UNUSED (closure))
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  return PyFloat_FromDouble (self->handle->enbw);
}
static PyObject *
ToneMeasure_getprop_lobe_bins (ToneMeasureObject *self,
                               void              *Py_UNUSED (closure))
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  return PyLong_FromUnsignedLongLong (
      (unsigned long long)self->handle->lobe_bins);
}
static PyObject *
ToneMeasure_getprop_rbw (ToneMeasureObject *self, void *Py_UNUSED (closure))
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  return PyFloat_FromDouble (self->handle->enbw * self->handle->fs
                             / (double)self->handle->n);
}
static PyObject *
ToneMeasure_getprop_bin_hz (ToneMeasureObject *self, void *Py_UNUSED (closure))
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  return PyFloat_FromDouble (self->handle->fs / (double)self->handle->nfft);
}
static PyObject *
ToneMeasure_getprop_proc_gain_db (ToneMeasureObject *self,
                                  void              *Py_UNUSED (closure))
{
  if (!self->handle)
    {
      PyErr_SetString (PyExc_RuntimeError, "destroyed");
      return NULL;
    }
  return PyFloat_FromDouble (10.0 * log10 ((double)self->handle->nfft / 2.0));
}

static PyGetSetDef ToneMeasure_getset[]
    = { { "n", (getter)ToneMeasure_getprop_n, NULL, "N.\n", NULL },
        { "nfft", (getter)ToneMeasure_getprop_nfft, NULL, "Nfft.\n", NULL },
        { "fs", (getter)ToneMeasure_getprop_fs, NULL, "Fs.\n", NULL },
        { "enbw", (getter)ToneMeasure_getprop_enbw, NULL, "Enbw.\n", NULL },
        { "lobe_bins", (getter)ToneMeasure_getprop_lobe_bins, NULL,
          "Lobe bins.\n", NULL },
        { "rbw", (getter)ToneMeasure_getprop_rbw, NULL, "Rbw.\n", NULL },
        { "bin_hz", (getter)ToneMeasure_getprop_bin_hz, NULL, "Bin hz.\n",
          NULL },
        { "proc_gain_db", (getter)ToneMeasure_getprop_proc_gain_db, NULL,
          "Proc gain db.\n", NULL },
        { NULL } };

static PyObject *
ToneMeasureObj_destroy (ToneMeasureObject *self, PyObject *Py_UNUSED (ignored))
{
  if (self->handle)
    {
      tonemeas_destroy (self->handle);
      self->handle = NULL;
    }
  Py_RETURN_NONE;
}

static PyObject *
ToneMeasureObj_enter (ToneMeasureObject *self, PyObject *Py_UNUSED (ignored))
{
  Py_INCREF (self);
  return (PyObject *)self;
}

static PyObject *
ToneMeasureObj_exit (ToneMeasureObject *self, PyObject *args)
{
  (void)args;
  if (self->handle)
    {
      tonemeas_destroy (self->handle);
      self->handle = NULL;
    }
  Py_RETURN_NONE;
}

static PyMethodDef ToneMeasureObj_methods[] = {
  { "reset", (PyCFunction)ToneMeasureObj_reset, METH_NOARGS,
    "Reset state to post-create defaults." },

  { "analyze", (PyCFunction)ToneMeasureObj_analyze, METH_VARARGS,
    "analyze(x) -> ToneMetrics\n"
    "\n"
    "Analyse a real time-domain capture; returns a named ToneMetrics result\n"
    "(snr, sinad, thd, thd_n, sfdr_dbc/dbfs, enob, ... plus accuracy "
    "fields),\n"
    "with attribute access and tuple unpacking.\n"
    "\n"
    "    >>> import numpy as np\n"
    "    >>> from doppler.measure import ToneMeasure\n"
    "    >>> m = ToneMeasure(\"kaiser\", 4096, 1.0, 12.0, 2, 8, 1.0, 0)\n"
    "    >>> x = np.cos(2*np.pi*300*np.arange(4096)/4096).astype(np.float32)\n"
    "    >>> r = m.analyze(x)\n"
    "    >>> abs(r.fund_dbfs) < 0.1   # full-scale tone -> ~0 dBFS\n"
    "    True\n" },
  { "analyze_complex", (PyCFunction)ToneMeasureObj_analyze_complex,
    METH_VARARGS,
    "analyze_complex(x) -> ToneMetrics\n"
    "\n"
    "Analyse a complex baseband capture (two-sided spectrum); returns the "
    "same\n"
    "named ToneMetrics result as analyze().\n"
    "\n"
    "    >>> import numpy as np\n"
    "    >>> from doppler.measure import ToneMeasure\n"
    "    >>> m = ToneMeasure(\"kaiser\", 4096, 1.0, 12.0, 2, 8, 1.0, 0)\n"
    "    >>> x = "
    "np.exp(2j*np.pi*137*np.arange(4096)/4096).astype(np.complex64)\n"
    "    >>> r = m.analyze_complex(x)\n"
    "    >>> abs(r.fund_freq - 137/4096) < 2e-3\n"
    "    True\n" },
  { "time_stats", (PyCFunction)ToneMeasureObj_time_stats, METH_VARARGS,
    "time_stats(x) -> TimeStats\n"
    "\n"
    "Time-domain statistics (rms, peak, crest_db, papr_db, dc_offset,\n"
    "fs_util_pct) of a real capture, as a named TimeStats result.\n"
    "\n"
    "    >>> import numpy as np\n"
    "    >>> from doppler.measure import ToneMeasure\n"
    "    >>> m = ToneMeasure(\"kaiser\", 4096, 1.0, 12.0, 2, 8, 1.0, 0)\n"
    "    >>> x = "
    "(0.8*np.cos(2*np.pi*50*np.arange(4096)/4096)).astype(np.float32)\n"
    "    >>> round(m.time_stats(x).crest_db, 1)\n"
    "    3.0\n" },
  { "spectrum_dbfs", (PyCFunction)ToneMeasureObj_spectrum_dbfs, METH_VARARGS,
    "spectrum_dbfs(x) -> ndarray\n"
    "\n"
    "DC-centred dBFS magnitude spectrum of a capture (length nfft, for "
    "plots).\n"
    "\n"
    "    >>> import numpy as np\n"
    "    >>> from doppler import ToneMeasure\n"
    "    >>> obj = ToneMeasure(\"kaiser\", 8192, 1.0, 12.0, 2, 8, 1.0, 0)\n"
    "    >>> y = obj.spectrum_dbfs(np.zeros(4))\n"
    "    >>> y.dtype\n"
    "    dtype('float32')\n" },
  { "destroy", (PyCFunction)ToneMeasureObj_destroy, METH_NOARGS,
    "Release resources." },
  { "__enter__", (PyCFunction)ToneMeasureObj_enter, METH_NOARGS, NULL },
  { "__exit__", (PyCFunction)ToneMeasureObj_exit, METH_VARARGS, NULL },
  { NULL }
};

static PyTypeObject ToneMeasureObjType = {
  PyVarObject_HEAD_INIT (NULL, 0).tp_name = "measure.ToneMeasure",
  .tp_basicsize                           = sizeof (ToneMeasureObject),
  .tp_dealloc                             = (destructor)ToneMeasureObj_dealloc,
  .tp_flags                               = Py_TPFLAGS_DEFAULT,
  .tp_doc                                 = "Create a ToneMeasure analyser.\n",
  .tp_methods                             = ToneMeasureObj_methods,
  .tp_getset                              = ToneMeasure_getset,
  .tp_new                                 = ToneMeasureObj_new,
  .tp_init                                = (initproc)ToneMeasureObj_init,
};
