#!/usr/bin/env python3
"""Generate the C initialisers for a wfm source and segment, from the manifest.

**One declaration, both directions.** `just-makeit.toml` already declares
every default with `default = ...`, and jm generates Python's from it. C had
no path to that declaration: `native/src/app/wfmgen.c` restated the values as
a struct literal inside `main()`, its own comment saying they *"mirror the
Python Synth/Composer defaults"* — mirrored in three places, shared from
none, with no gate comparing them (doppler#1142).

Two of them were worse than a plain duplicate. `modulation` and `crc` were
restated as enum **indices** (`1`, `1`) while the manifest names them as
**strings** (`"bpsk"`, `"crc16"`), so the literal silently depended on the
ORDER of `[[enum]] bitmod` and `[[enum]] crc`. Append-only protects the tail,
not the head: prepend an entry to either and the manifest still means `bpsk`
while `1` becomes the new second entry — a wrong default with nothing
failing. That is the rot `wfm_names.h` exists to end (doppler#760), one level
up, in a literal no enum gate scans.

This resolves such a default through the field's OWN `enum = "..."` key, never
by searching the enums for a matching string. `"bpsk"` appears in both
`[[enum]] bitmod` (index 1) and `[[enum]] wfm_type` (index 3); a
search-by-value would have picked the wrong one, which is precisely the
mistake a hand-written index invites.

Only fields whose default is NON-ZERO are emitted. A zero default is what a
zero-initialised struct already gives, so writing it would add noise that
says nothing — and the generated macro is meant to be read.

Usage:
    python scripts/gen_wfm_defaults.py --check   # exit 1 if header is stale
    python scripts/gen_wfm_defaults.py --write   # regenerate it
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import textwrap
from pathlib import Path

from _layout import header
from check_wfm_enum_tables import _tables

# test_wfm_surface_roundtrip.py imports this module, and the Python 3.9/3.10
# CI jobs run it there: the stdlib has no tomllib before 3.11. `tomli` is the
# same parser under its pre-stdlib name, as check_wfm_enum_tables.py does.
if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover - exercised by the 3.9/3.10 CI matrix jobs
    import tomli as tomllib

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "just-makeit.toml"
HEADER = ROOT / header("wfm/wfm_defaults.h")
COMPOSE_H = ROOT / header("wfm/wfm_compose.h")
NAMES_H = ROOT / header("wfm/wfm_names.h")
SURFACE = ROOT / header("wfm/wfm_surface.h")
WFMGEN_C = ROOT / "native" / "src" / "app" / "wfmgen.c"
SCHEMA = ROOT / "docs" / "schema" / "wfmgen.schema.json"
REFERENCE = ROOT / "docs" / "guide" / "wfmgen" / "options.md"

# The C struct each manifest table describes.
STRUCTS = {"source": "wfm_source_t", "segment": "wfm_segment_t"}

BANNER = "wfm_defaults.h — GENERATED by scripts/gen_wfm_defaults.py"


def member(f: dict) -> str:
    """The C struct member a manifest field is: its own name, or -- for a
    field whose bits jm reaches through `c_ptr = "<member>.bits"`, the four
    `wfm_seq_t` sequences -- that member (the manifest's `bits` is the
    struct's `payload`)."""
    ptr = f.get("c_ptr")
    return ptr.split(".", 1)[0] if ptr else f["name"]


def _enums(man: dict) -> dict[str, list[str]]:
    return {e["name"]: list(e["values"]) for e in man.get("enum", [])}


def _literal(field: dict, enums: dict[str, list[str]]) -> str | None:
    """The C initialiser for one field's default, or None to omit it.

    Returns None for a default that is zero in C, because a zero-initialised
    struct already carries it.
    """
    raw = field.get("default")
    if raw is None:
        return None
    name = field["name"]

    # An enum-valued default resolves through the field's OWN declared enum.
    en = field.get("enum")
    if en is not None:
        values = enums.get(en)
        if values is None:
            raise SystemExit(
                f"{name}: enum = {en!r}, which no [[enum]] declares"
            )
        if raw not in values:
            raise SystemExit(
                f"{name}: default {raw!r} is not a member of [[enum]] {en} "
                f"({', '.join(values)})"
            )
        idx = values.index(raw)
        return None if idx == 0 else f"{idx} /* {en}: {raw} */"

    text = str(raw).strip()
    ctype = field.get("type", "")
    if ctype in ("double", "float"):
        return None if float(text) == 0.0 else text
    # Everything else is an integer-ish scalar. A non-numeric default here is
    # a string type (a path, a name); those have no place in a struct literal.
    try:
        n = int(text, 0)
    except ValueError:
        return None
    return None if n == 0 else str(n)


_DECL = re.compile(r"^([ \t]*)[A-Za-z_][\w \t\*]*?\b(\w+)(?:\[\w*\])?;", re.M)


def member_docs(text: str, struct: str) -> dict[str, dict]:
    """Each member's doc comment in `typedef struct { ... } <struct>;`.

    **A member's doc is its trailing comment** -- the `/* ... */` that opens
    on the declaration's own line -- **or, when it has none, the block
    comment directly above it** (only whitespace between the two). A block
    comment above a member that ALSO has a trailing comment is a design note
    and is not its doc.

    Returns ``{name: {"doc", "start", "end", "col", "form"}}`` where the doc
    is the comment's words joined by single spaces, ``start``/``end`` span
    the whole comment in `text`, ``col`` is the column the ``/*`` opens at,
    and ``form`` is ``"trailing"`` or ``"above"``. A member with neither has
    no entry.
    """
    end = text.index(f"}} {struct};")
    begin = text.rindex("typedef struct {", 0, end)
    # A comment line can read like a declaration ("... other types;"), so
    # every match inside a comment is skipped rather than trusted.
    comments = [
        (c.start(), c.end())
        for c in re.finditer(r"/\*.*?\*/", text[:end], re.S)
        if c.end() > begin
    ]
    out: dict[str, dict] = {}
    for m in _DECL.finditer(text, begin, end):
        if any(a <= m.start() < b for a, b in comments):
            continue
        name = m.group(2)
        line_end = text.index("\n", m.end())
        rest = text[m.end() : line_end]
        if "/*" in rest:
            start = m.end() + rest.index("/*")
            form = "trailing"
        else:
            above = text[begin : m.start()].rstrip()
            if not above.endswith("*/"):
                continue
            start = text.rindex("/*", begin, m.start())
            line_start = text.rindex("\n", 0, start) + 1
            if text[line_start:start].strip():
                continue  # the previous member's trailing comment
            form = "above"
        close = text.index("*/", start) + 2
        doc = " ".join(text[start + 2 : close - 2].split())
        col = start - (text.rindex("\n", 0, start) + 1)
        out[name] = {
            "doc": doc,
            "start": start,
            "end": close,
            "col": col,
            "form": form,
            "decl": m.group(0).strip(),
        }
    return out


def doc_drift(man: dict, header_text: str) -> list[str]:
    """Fields whose manifest `doc` differs from the header's comment.

    The header is the field's one text (docs/design/wfmgen.md, "One surface
    table"); the manifest `doc` exists only because jm still reads it for
    the Python docstring (just-makeit#1703), so it must be the same words.
    """
    bad = []
    mc = man["module"]["wfm_compose"]
    for kind, struct in STRUCTS.items():
        docs = member_docs(header_text, struct)
        for f in mc[kind].get("fields", []):
            have = " ".join(str(f.get("doc", "")).split())
            want = docs.get(member(f), {}).get("doc", "")
            if have != want:
                bad.append(
                    f"{kind}.{f['name']}: manifest doc != header comment\n"
                    f"    manifest: {have or '(none)'}\n"
                    f"    header:   {want or '(none)'}"
                )
    return bad


def render() -> str:
    man = tomllib.loads(MANIFEST.read_text(encoding="utf-8"))
    enums = _enums(man)
    mc = man["module"]["wfm_compose"]

    out: list[str] = [
        "/*",
        f" * {BANNER}",
        " *",
        " * Do not edit. `just-makeit.toml` is the one declaration of a",
        " * default; this is that declaration rendered for C, so the CLI, a",
        " * C caller and Python cannot disagree about one (doppler#1142).",
        " *",
        " * Only NON-ZERO defaults appear: a zero is what a zero-initialised",
        " * struct already gives, and spelling it would say nothing.",
        " *",
        " * An enum-valued default is rendered as the index of its name in",
        " * the field's OWN declared [[enum]], with the name in a comment, so",
        " * reordering that enum moves this file rather than silently",
        " * changing what the value means.",
        " */",
        "#ifndef WFM_DEFAULTS_H",
        "#define WFM_DEFAULTS_H",
        "",
    ]

    for kind, macro in (
        ("source", "WFM_SOURCE_DEFAULTS"),
        ("segment", "WFM_SEGMENT_DEFAULTS"),
    ):
        rows = []
        for f in mc[kind].get("fields", []):
            lit = _literal(f, enums)
            if lit is not None:
                rows.append((f["name"], lit))
        out.append(f"/* Non-zero defaults for a wfm_{kind}_t. */")
        out.append(f"#define {macro} \\")
        body = ", \\\n".join(f"    .{n} = {v}" for n, v in rows)
        out.append("  { \\")
        out.append(body + " \\")
        out.append("  }")
        out.append("")

    out.append("#endif /* WFM_DEFAULTS_H */")
    return "\n".join(out) + "\n"


# A field's C type, as the kind of value the surface reads into it.
_KINDS = {
    "double": "WFM_SV_DOUBLE",
    "int": "WFM_SV_INT",
    "size_t": "WFM_SV_SIZE",
    "uint32_t": "WFM_SV_U32",
    "uint64_t": "WFM_SV_U64",
    "float _Complex*": "WFM_SV_SYMBOLS",
}

SURFACE_BANNER = "wfm_surface.h — GENERATED by scripts/gen_wfm_defaults.py"


def surface_rows(man: dict) -> list[dict]:
    """The surface table: one row per field that declares `cli` or `json`.

    Everything but the spelling is DERIVED from what the manifest and the
    headers already say -- the value kind from the field's C type, the
    choice table from its `enum` (through `wfm_names.h`'s `SSOT: enum=`
    markers, read by the same parser that gates them), the upper bound and
    the range bit from the table's `ranged` list. The new keys are only
    what nothing else states: the spellings (`cli`, `json`), the help
    placement, and the JSON policy (`json_omit`, `json_when`,
    `json_required`, `json_type`).
    """
    mc = man["module"]["wfm_compose"]
    parsed = [
        t for t in _tables(NAMES_H.read_text(encoding="utf-8")) if t.enum
    ]
    tables = {t.enum: t.name for t in parsed}
    values_of = {t.enum: t.values for t in parsed}
    rows = []
    for kind in STRUCTS:
        ranged = {r["name"]: r["flag"] for r in mc[kind].get("ranged", [])}
        for f in mc[kind].get("fields", []):
            if "cli" not in f and "json" not in f:
                continue
            name = f["name"]
            en = f.get("enum")
            if en is not None:
                if en not in tables:
                    raise SystemExit(
                        f"{kind}.{name}: enum = {en!r} has no table in "
                        f"{NAMES_H.relative_to(ROOT)}"
                    )
                vkind, choices = "WFM_SV_CHOICE", tables[en]
            elif f.get("surface") == "bespoke":
                # A row whose VALUE each face reads with its own code (the
                # frame description: --frame FILE, a scene's "frame" object,
                # an owned pointer in Python). The row still names it, so
                # help, the schema and every exclusion derive from it; the
                # generic readers and writers skip it.
                vkind, choices = "WFM_SV_BESPOKE", None
            elif f.get("c_ptr"):
                # A `wfm_seq_t` reached through `<member>.bits`: a Field.
                vkind, choices = "WFM_SV_FIELD", None
            else:
                ctype = f.get("type", "")
                if ctype not in _KINDS:
                    raise SystemExit(
                        f"{kind}.{name}: type {ctype!r} has no surface kind"
                    )
                vkind, choices = _KINDS[ctype], None
            # The CLI stores a range bit in `src.ranged` for a double and in
            # `seg.ranged` for a size_t (OPT_RANGE_D / OPT_RANGE_N), so any
            # other pairing would set the wrong struct's bitmask silently.
            if name in ranged and (kind, vkind) not in (
                ("source", "WFM_SV_DOUBLE"),
                ("segment", "WFM_SV_SIZE"),
            ):
                raise SystemExit(
                    f"{kind}.{name}: a ranged {vkind} {kind} field has no "
                    "CLI range kind; wfmgen ranges source doubles and "
                    "segment sizes only"
                )
            rows.extend(_surface_only(kind, f))
            rows.append(
                {
                    "owner": kind,
                    "name": name,
                    "member": member(f),
                    "field_reps": f.get("field_reps"),
                    "cli": f.get("cli"),
                    "json": f.get("json"),
                    "json_required": bool(f.get("json_required")),
                    "json_omit": f.get("json_omit"),
                    "json_bool": f.get("json_type") == "bool",
                    "json_when": f.get("json_when"),
                    "json_schema": dict(f.get("json_schema", {})),
                    "json_range": f.get("json_range"),
                    "kind": vkind,
                    "choices": choices,
                    "range_bit": ranged.get(name),
                    "unit_interval": bool(f.get("unit_interval")),
                    "metavar": f.get("metavar"),
                    "section": f.get("help_section"),
                    "default": f.get("default"),
                    "values": values_of.get(en) if en else None,
                    "exclusive": list(f.get("exclusive", [])),
                }
            )
    _resolve_when(rows)
    return rows


def _surface_only(kind: str, f: dict) -> list[dict]:
    """The SURFACE-ONLY rows a field's exclusions declare: `row = {...}`.

    A surface-only row has a C member and every face but Python, and no jm
    field -- a file path, which no jm composer type carries and which the
    Python face deliberately lacks (`--data-from-file`, payload-data-source
    .md section 4.9). It is declared inside the ONE exclusion that is its
    reason to exist, beside the field it excludes, because jm does not read
    inside `exclusive`: a table of its own would cost a jm diagnostic on
    every apply. It is bespoke -- each face reads its value with its own
    code -- and its doc is its member's header comment, like every row's.
    `surface_only_errors` checks it against the struct both ways.
    """
    out = []
    for e in f.get("exclusive", []):
        r = e.get("row")
        if r is None:
            continue
        if not r.get("member"):
            raise SystemExit(
                f"{kind}.{f['name']}: the surface-only row {e.get('with')!r} "
                "needs `member`"
            )
        out.append(
            {
                "owner": kind,
                "name": e["with"],
                "member": r["member"],
                "field_reps": None,
                "cli": r.get("cli"),
                "json": r.get("json"),
                "json_required": False,
                "json_omit": None,
                "json_bool": False,
                "json_when": None,
                "json_schema": {},
                "json_range": None,
                "kind": "WFM_SV_BESPOKE",
                "choices": None,
                "range_bit": None,
                "unit_interval": False,
                "metavar": r.get("metavar"),
                "section": r.get("help_section"),
                "default": None,
                "values": None,
                "exclusive": [],
                "surface_only": True,
            }
        )
    return out


def surface_only_errors(man: dict, header_text: str) -> list[str]:
    """A surface-only row against its struct, BOTH ways.

    Forward: its `member` is a documented member of the struct, so the row
    reaches real storage and has the doc every row takes from the header.
    Backward: a `const char *` member -- the one C type a surface-only row
    exists for -- has a row, so a path member cannot be added that no face
    can set.
    """
    bad = []
    rows = [r for r in surface_rows(man) if r.get("surface_only")]
    for kind, struct in STRUCTS.items():
        docs = member_docs(header_text, struct)
        mine = {r["member"] for r in rows if r["owner"] == kind}
        for r in rows:
            if r["owner"] == kind and r["member"] not in docs:
                bad.append(
                    f"{kind}.{r['name']}: surface-only row's member "
                    f"{r['member']!r} is not a documented member of {struct}"
                )
        for name, d in docs.items():
            if re.match(r"const\s+char\s*\*", d["decl"]) and name not in mine:
                bad.append(
                    f"{struct}.{name}: a `const char *` member with no "
                    "surface-only row, so no face can set it; declare one in "
                    "the exclusion that is its reason to exist"
                )
    return bad


#: The kinds a struct can hold as "unset" (an empty sequence, a NULL
#: pointer, no symbols), so the object face can tell a pair was both GIVEN.
#: A number has no unset value -- its default is a value -- so an exclusion
#: over one could be refused on the CLI and in a scene but never on the
#: object, and the generator refuses to declare it.
_SETTABLE = ("WFM_SV_FIELD", "WFM_SV_BESPOKE", "WFM_SV_SYMBOLS")


def _both(r: dict, other: dict, key: str, fmt: str, why: str) -> str | None:
    """One face's reason: its two spellings, then the reason. None when the
    face spells only one of the pair, so it has nothing to refuse."""
    if not (r[key] and other[key]):
        return None
    return (
        f"{fmt.format(r[key])} and {fmt.format(other[key])} "
        f"cannot both be given: {why}"
    )


def exclusions(rows: list[dict]) -> list[dict]:
    """Every `exclusive = [{ with = "<field>", why = "<reason>" }]` pair.

    ONE declaration, on either field of the pair. Each face refuses from
    the row it generates -- the CLI (both flags given), the JSON reader
    (both keys present), the object face (both members set, at
    dp_wfm_source_error) -- and help, the schema and the reference say so.
    The reason is written once; the generator spells it per face, as a
    literal, so every `why` points at static text (error-convention.md).
    """
    by = {(r["owner"], r["name"]): r for r in rows}
    out: list[dict] = []
    for r in rows:
        for e in r["exclusive"]:
            other = by.get((r["owner"], e.get("with")))
            if other is None:
                raise SystemExit(
                    f"{r['owner']}.{r['name']}: exclusive with "
                    f"{e.get('with')!r}, which is not a surface row of the "
                    "same struct"
                )
            if not e.get("why"):
                raise SystemExit(
                    f"{r['owner']}.{r['name']}: an exclusion needs `why`"
                )
            for x in (r, other):
                if x["kind"] not in _SETTABLE:
                    raise SystemExit(
                        f"{x['owner']}.{x['name']}: a {x['kind']} row has no "
                        "unset value, so the object face could not refuse "
                        "the pair; an exclusion is between rows of kind "
                        + ", ".join(_SETTABLE)
                    )
            if any(
                {x["a"], x["b"]} == {r["name"], other["name"]} for x in out
            ):
                raise SystemExit(
                    f"{r['owner']}.{r['name']}/{other['name']}: the exclusion "
                    "is declared twice; declare it on one field"
                )
            why = e["why"]
            out.append(
                {
                    "owner": r["owner"],
                    "a": r["name"],
                    "b": other["name"],
                    "cli_why": _both(r, other, "cli", "{}", why),
                    "json_why": _both(r, other, "json", '"{}"', why),
                    "obj_why": (
                        f"a source's {r['member']} and {other['member']} "
                        f"cannot both be set: {why}"
                    ),
                    "why": why,
                }
            )
    return out


def _excluded_by(r: dict, excl: list[dict]) -> list[dict]:
    """The rows `r` may not sit beside."""
    return [
        e
        for e in excl
        if e["owner"] == r["owner"] and r["name"] in (e["a"], e["b"])
    ]


def _other(r: dict, e: dict, rows: list[dict]) -> dict:
    name = e["b"] if e["a"] == r["name"] else e["a"]
    return next(
        x for x in rows if x["owner"] == r["owner"] and x["name"] == name
    )


def _resolve_when(rows: list[dict]) -> None:
    """Turn each `json_when = { <field> = "<choice>" }` into a row index and
    a choice index, refusing a condition the table cannot evaluate."""
    by = {(r["owner"], r["name"]): r for r in rows}
    for r in rows:
        w = r["json_when"]
        if not w:
            continue
        if r["json_omit"] not in (None, "default"):
            raise SystemExit(f'{r["name"]}: json_omit must be "default"')
        if len(w) != 1:
            raise SystemExit(f"{r['name']}: json_when names ONE field")
        ((field, value),) = w.items()
        cond = by.get((r["owner"], field))
        if cond is None or not cond["values"]:
            raise SystemExit(
                f"{r['owner']}.{r['name']}: json_when names {field!r}, "
                "which is not a choice row of the same struct"
            )
        if value not in cond["values"]:
            raise SystemExit(
                f"{r['owner']}.{r['name']}: json_when {field} = {value!r} "
                f"is not one of {', '.join(cond['values'])}"
            )
        r["when_row"] = f"WFM_SURFACE_{r['owner']}_{field}"
        r["when_value"] = cond["values"].index(value)


# The column a flag's description starts at, and the line width. A flag
# and metavar that reach the column put the description on the next line.
HELP_COL = 18
HELP_WIDTH = 79

_SENTENCE = re.compile(r"^(.*?[.])(?:\s|$)", re.S)


def first_sentence(doc: str) -> str:
    """A field's help line: the first sentence of its header comment."""
    m = _SENTENCE.match(doc)
    return m.group(1) if m else doc


def help_lines(row: dict, doc: str) -> list[str]:
    """One option's --help lines: flag, metavar, description, wrapped.

    The description is the header comment's first sentence, then the
    choices and the default from the table -- never restated by hand, so
    they cannot disagree with what the parser accepts.
    """
    mv = row["metavar"]
    if row["range_bit"]:
        mv = f"{mv}[:{mv}]"
    head = f"  {row['cli']} {mv}" if mv else f"  {row['cli']}"
    text = first_sentence(doc)
    if row["values"]:
        text += " One of: " + " | ".join(row["values"]) + "."
    others = [o["cli"] for o in row.get("not_with", []) if o["cli"]]
    if others:
        text += " Not with " + ", ".join(others) + "."
    if row["default"] is not None:
        # A no-break space: the wrap may not split "(default" from its
        # value, and textwrap does not count U+00A0 as a place to break.
        text += f" (default\u00a0{row['default']})"
    words = textwrap.wrap(
        text,
        width=HELP_WIDTH - HELP_COL,
        break_on_hyphens=False,
        break_long_words=False,
    )
    pad = " " * HELP_COL
    if len(head) < HELP_COL:
        out = [head.ljust(HELP_COL) + words[0]]
    else:
        out = [head, pad + words[0]]
    out += [pad + w for w in words[1:]]
    return [x.replace("\u00a0", " ") for x in out]


def _c_string(line: str) -> str:
    esc = line.replace("\\", "\\\\").replace('"', '\\"')
    return f'  "{esc}\\n"'


def render_help(rows: list[dict]) -> list[str]:
    """`#define WFM_SURFACE_HELP_<SECTION>`, one string per help section.

    wfmgen's USAGE[] keeps its section headings and prose and splices these
    in where the option lines go, so an option's help is generated from
    the same row the parser reads.
    """
    docs = {
        kind: member_docs(COMPOSE_H.read_text(encoding="utf-8"), struct)
        for kind, struct in STRUCTS.items()
    }
    sections: dict[str, list[str]] = {}
    excl = exclusions(rows)
    for r in rows:
        r["not_with"] = [_other(r, e, rows) for e in _excluded_by(r, excl)]
    # Segment rows first: --fs and --count lead the signal section.
    cli_rows = [r for r in rows if r["cli"]]
    for r in sorted(cli_rows, key=lambda r: r["owner"] != "segment"):
        # A bool row is a switch on the command line (wfmgen.c: OPT_SET),
        # so it takes no value and has no metavar; every other row does.
        if not r["section"] or (not r["metavar"] and not r["json_bool"]):
            raise SystemExit(
                f"{r['owner']}.{r['name']}: a `cli` row needs `metavar` and "
                "`help_section` (a json_type bool row, a switch, no metavar)"
            )
        doc = docs[r["owner"]].get(r["member"], {}).get("doc")
        if not doc:
            raise SystemExit(
                f"{r['owner']}.{r['name']}: no header comment to take its "
                f"help from, in {COMPOSE_H.relative_to(ROOT)}"
            )
        sections.setdefault(r["section"], []).extend(help_lines(r, doc))
    out = ["/* --help option lines, one string per USAGE section. */"]
    for sec, lines in sections.items():
        out.append(f"#define WFM_SURFACE_HELP_{sec} \\")
        out += [_c_string(x) + " \\" for x in lines[:-1]]
        out.append(_c_string(lines[-1]))
        out.append("")
    return out


def help_splice_errors(man: dict) -> list[str]:
    """Where wfmgen's USAGE[] and the generated help lines disagree.

    Two failures, and the compiler sees neither: a section macro USAGE never
    splices in (its options vanish from --help), and a HAND-WRITTEN line for
    a flag the table owns (a second, drifting copy of its help -- the thing
    generating the lines exists to end).
    """
    src = WFMGEN_C.read_text(encoding="utf-8")
    a = src.index("static const char USAGE[]")
    usage = src[a : src.index(";\n", a)]
    rows = [r for r in surface_rows(man) if r["cli"]]
    bad = []
    for sec in sorted({r["section"] for r in rows if r["section"]}):
        if f"WFM_SURFACE_HELP_{sec}" not in usage:
            bad.append(
                f"USAGE[] never splices WFM_SURFACE_HELP_{sec}, so its "
                "options are missing from --help"
            )
    hand = "".join(re.findall(r'"((?:[^"\\]|\\.)*)"', usage))
    for line in hand.split("\\n"):
        # An OPTION line, not prose that opens with a flag ("--count is
        # honoured verbatim"): two spaces, the flag, an optional UPPERCASE
        # metavar, then a two-space gap or the end of the line.
        m = re.match(
            r"  (--[A-Za-z0-9-]+)(?: [A-Z][A-Z0-9_:\[\]-]*)?(?: {2,}|$)", line
        )
        if m and m.group(1) in {r["cli"] for r in rows}:
            bad.append(
                f"USAGE[] has a hand-written line for {m.group(1)}, which "
                "the surface table generates: delete it"
            )
    return bad


def _typed_default(r: dict):
    """A row's manifest default as the JSON value a scene would carry."""
    raw = r["default"]
    if raw is None:
        return None
    if r["kind"] == "WFM_SV_CHOICE":
        return raw
    if r["json_bool"]:
        return int(raw, 0) != 0
    if r["kind"] == "WFM_SV_DOUBLE":
        return float(raw)
    return int(raw, 0)


def row_schema(r: dict, doc: str) -> dict:
    """One row's JSON Schema property, from the row alone.

    The type from the C type (unsigned -> `minimum: 0`), the enum from the
    choice table, `(0, 1]` from `unit_interval`, a range as `oneOf` scalar
    or a [lo, hi] pair, then the row's own `json_schema` constraints. The
    description is the header comment, plus what only the JSON face adds.
    """
    if r["kind"] == "WFM_SV_CHOICE":
        scalar: dict = {"type": "string", "enum": list(r["values"])}
    elif r["kind"] == "WFM_SV_FIELD":
        # The Field grammar (frame-description.md F.1); dp_wfm_field_parse
        # is its one reader, so the schema checks only that it is text.
        scalar = {"type": "string", "minLength": 1}
    elif r["json_bool"]:
        scalar = {"type": "boolean"}
    elif r["kind"] == "WFM_SV_DOUBLE":
        scalar = {"type": "number"}
    elif r["kind"] in ("WFM_SV_SIZE", "WFM_SV_U32", "WFM_SV_U64"):
        scalar = {"type": "integer", "minimum": 0}
    else:
        scalar = {"type": "integer"}
    if r["unit_interval"]:
        scalar.update({"exclusiveMinimum": 0, "maximum": 1})
    scalar.update(r["json_schema"])
    if r["range_bit"]:
        rng = r["json_range"] or (
            "number_range" if r["kind"] == "WFM_SV_DOUBLE" else "count_range"
        )
        prop: dict = {"oneOf": [scalar, {"$ref": f"#/$defs/{rng}"}]}
        doc += " Scalar, or a [lo, hi] pair drawn uniformly per repeat."
    else:
        prop = scalar
    if r["json_omit"]:
        doc += " Omitted from a record at its default."
    d = _typed_default(r)
    if d is not None:
        prop["default"] = d
    prop["description"] = doc
    return prop


#: The schema keys their owner writes by hand, per object: every OTHER key
#: on these objects is a surface row's, generated -- and removed with it.
HAND_OWNED = {
    "source": {"symbols", "crc"},
    "inline_segment": {"symbols", "crc"},
    "sum_segment": {"sum"},
}


def render_schema() -> str:
    """docs/schema/wfmgen.schema.json with every table row's property
    generated, and every other key -- the frame, the payload, the codes --
    left exactly as its owner wrote it.

    A source row is defined once, under `source`; `inline_segment` refers
    to it. A segment row is defined under `inline_segment`; `sum_segment`
    refers to it. Nothing else in the file is touched.
    """
    man = tomllib.loads(MANIFEST.read_text(encoding="utf-8"))
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    defs = schema["$defs"]
    text = COMPOSE_H.read_text(encoding="utf-8")
    docs = {k: member_docs(text, st) for k, st in STRUCTS.items()}
    rows = surface_rows(man)
    for r in rows:
        if not r["json"]:
            continue
        if r["kind"] == "WFM_SV_BESPOKE":
            # Its shape is its owner's (a frame is a whole object); the
            # table only checks the key is there to be excluded against.
            if (
                r["json"]
                not in defs[
                    "source" if r["owner"] == "source" else "inline_segment"
                ]["properties"]
            ):
                raise SystemExit(
                    f"{r['owner']}.{r['name']}: a bespoke row's key "
                    f"{r['json']!r} is not in {SCHEMA.relative_to(ROOT)}"
                )
            continue
        key, doc = r["json"], docs[r["owner"]][r["member"]]["doc"]
        if r["owner"] == "source":
            defs["source"]["properties"][key] = row_schema(r, doc)
            defs["inline_segment"]["properties"][key] = {
                "$ref": f"#/$defs/source/properties/{key}"
            }
        else:
            defs["inline_segment"]["properties"][key] = row_schema(r, doc)
            defs["sum_segment"]["properties"][key] = {
                "$ref": f"#/$defs/inline_segment/properties/{key}"
            }
    # A key no row owns and no owner declared is a row that was DELETED:
    # its property goes with it, both directions from one table. Without
    # this a retired key (doppler#1718's "payload") stayed in the schema,
    # documented and accepted, after every face refused it.
    owned = {
        "source": {
            r["json"] for r in rows if r["json"] and r["owner"] == "source"
        },
        "inline_segment": {r["json"] for r in rows if r["json"]},
        "sum_segment": {
            r["json"] for r in rows if r["json"] and r["owner"] != "source"
        },
    }
    for name, keys in owned.items():
        props = defs[name]["properties"]
        for key in [k for k in props if k not in keys | HAND_OWNED[name]]:
            del props[key]
    # Each exclusion, as "not both keys": on every object a source's keys
    # appear in (a source, and the inline one-source segment).
    targets = {
        "source": ("source", "inline_segment"),
        "segment": ("inline_segment", "sum_segment"),
    }
    for name in {n for t in targets.values() for n in t}:
        defs[name].pop("allOf", None)
    for e in exclusions(rows):
        if not e["json_why"]:
            continue
        ja, jb = (
            next(
                r["json"]
                for r in rows
                if r["owner"] == e["owner"] and r["name"] == n
            )
            for n in (e["a"], e["b"])
        )
        for name in targets[e["owner"]]:
            defs[name].setdefault("allOf", []).append(
                {"not": {"required": [ja, jb]}, "description": e["json_why"]}
            )
    # A $defs entry only the table rows referred to is gone with them.
    body = json.dumps(schema)
    for name in list(defs):
        if f'"#/$defs/{name}"' not in body.replace(
            json.dumps({name: defs[name]})[1:-1], ""
        ):
            del defs[name]
            body = json.dumps(schema)
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n"


def _md(text: str) -> str:
    """A table cell the generator wrote as markdown (a type's link): only
    the cell separator is escaped, so its own links stay links."""
    return text.replace("|", "\\|")


def _md_prose(text: str) -> str:
    """A table cell of PROSE -- a field's doc, from its header comment.

    Prose is literal: `[preamble x reps | sync | data:LEN | crc]` is frame
    notation, not a link, and left bare markdown reads it as an unresolved
    link reference (zensical --strict refused #1721 for exactly that). So
    `[` and `]` are escaped outside code spans -- inside one they are
    already literal -- and `|` everywhere, which a table cell needs even in
    a code span. Fixed here, where every doc reaches the page, so no field
    doc with brackets can break the build again.
    """
    out = []
    for i, part in enumerate(text.split("`")):
        if i % 2 == 0:  # outside a code span
            part = part.replace("[", "\\[").replace("]", "\\]")
        out.append(part.replace("|", "\\|"))
    return "`".join(out)


def render_reference() -> str:
    """docs/guide/wfmgen/options.md: every table field on every face.

    One row per field, so the flag, the scene key, the Python keyword, the
    type, the default and the meaning are read off one line rather than
    matched up across three pages -- and none of it is typed twice.
    """
    man = tomllib.loads(MANIFEST.read_text(encoding="utf-8"))
    text = COMPOSE_H.read_text(encoding="utf-8")
    docs = {k: member_docs(text, st) for k, st in STRUCTS.items()}
    out = [
        "# Field reference",
        "",
        "<!-- GENERATED by scripts/gen_wfm_defaults.py from just-makeit.toml",
        "     and wfm/wfm_compose.h. Do not edit: change the field's header",
        "     comment or its manifest row, then run",
        "     `python scripts/gen_wfm_defaults.py --write`. -->",
        "",
        "Every field of a wfmgen source or segment, on each face that",
        "exposes it: the `wfmgen` flag, the scene-file key, and the Python",
        "keyword. The description is the field's header comment, the same",
        "text as `wfmgen --help` (its first sentence) and the Python",
        "docstring. A ranged field also takes a `LO:HI` range on the command",
        "line, or a `[lo, hi]` pair in a scene, drawn uniformly per repeat.",
        "",
        "On the command line an integer is decimal or `0x` hex, and a",
        "leading `0` is decimal, never octal. Every number must be the",
        "whole value: `4x`, `0.1abc` and an empty value are refused, naming",
        "the flag. A sample count (`--count`, `--off`, `--delay`, each",
        "side of a range) is a whole, non-negative number: `1e3` is 1000,",
        "and `1.5` or `-1` is refused.",
        "",
        "Framing, payload and coding keys are described in",
        "[Waveforms](waveforms.md) and [Scenes](scenes.md).",
    ]
    titles = {"source": "Source fields", "segment": "Segment fields"}
    rows = surface_rows(man)
    excl = exclusions(rows)
    for owner in ("segment", "source"):
        out += [
            "",
            f"## {titles[owner]}",
            "",
            "| Python | CLI | JSON | Type | Default | Description |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for r in (r for r in rows if r["owner"] == owner):
            if r["kind"] == "WFM_SV_CHOICE":
                typ = "one of " + ", ".join(f"`{v}`" for v in r["values"])
            elif r["json_bool"]:
                typ = "bool"
            elif r["kind"] == "WFM_SV_DOUBLE":
                typ = "number"
            elif r["kind"] == "WFM_SV_SYMBOLS":
                typ = "complex stream"
            elif r["kind"] == "WFM_SV_FIELD":
                typ = (
                    "[Field](../../design/frame-description.md#f1-the-grammar)"
                )
            elif r.get("surface_only"):
                typ = "path"  # a file, or - for stdin
            elif r["kind"] == "WFM_SV_BESPOKE":
                typ = (
                    "[frame description](waveforms.md#coded-frames-frame-file)"
                )
            else:
                typ = "integer"
            if r["range_bit"]:
                typ += ", or a range"
            # A switch (a json_type bool row) takes no value on the CLI.
            spell = f"{r['cli']} {r['metavar']}" if r["metavar"] else r["cli"]
            cli = f"`{spell}`" if r["cli"] else "—"
            js = f"`{r['json']}`" if r["json"] else "—"
            dflt = f"`{r['default']}`" if r["default"] is not None else "—"
            doc = docs[owner][r["member"]]["doc"]
            for e in _excluded_by(r, excl):
                o = _other(r, e, rows)
                doc += f" Not with `{o['name']}`: {e['why']}."
            out.append(
                f"| `{r['name']}` | {cli} | {js} | {_md(typ)} | {dflt} | "
                f"{_md_prose(doc)} |"
            )
    return "\n".join(out) + "\n"


def render_surface() -> str:
    man = tomllib.loads(MANIFEST.read_text(encoding="utf-8"))
    rows = surface_rows(man)
    owner_c = {"source": "WFM_SURF_SOURCE", "segment": "WFM_SURF_SEGMENT"}
    out = [
        "/*",
        f" * {SURFACE_BANNER}",
        " *",
        " * Do not edit. One row per wfm source or segment field that a",
        " * face other than Python exposes, generated from `just-makeit.toml`",
        " * (the rows that declare `cli`) and the headers it names. Every",
        " * face that reads a field by name reads it from here, so a field",
        " * cannot be spelled, typed or bounded two ways",
        ' * (docs/design/wfmgen.md, "One surface table"; doppler#853).',
        " */",
        "#ifndef WFM_SURFACE_H",
        "#define WFM_SURFACE_H",
        "",
        "#include <stddef.h>",
        "",
        '#include "doppler/wfm/wfm_compose.h"',
        '#include "doppler/wfm/wfm_names.h"',
        "",
        "/* Which struct a row's offsets are into. */",
        "typedef enum",
        "{",
        "  WFM_SURF_SOURCE,  /* wfm_source_t */",
        "  WFM_SURF_SEGMENT, /* wfm_segment_t */",
        "} wfm_surf_owner_t;",
        "",
        "/* What kind of value a row holds. */",
        "typedef enum",
        "{",
        "  WFM_SV_DOUBLE,",
        "  WFM_SV_INT,",
        "  WFM_SV_SIZE,",
        "  WFM_SV_U32,",
        "  WFM_SV_U64,",
        "  WFM_SV_CHOICE,  /* an int index into `choices` */",
        "  WFM_SV_SYMBOLS, /* float _Complex *, its count at `len_off` */",
        "  WFM_SV_FIELD,   /* a wfm_seq_t, as a Field (wfm_frame.h) */",
        "  WFM_SV_BESPOKE, /* a pointer each face reads with its own code;",
        "                     the generic readers and writers skip it */",
        "} wfm_sv_kind_t;",
        "",
        "typedef struct",
        "{",
        "  const char        *name;  /* the struct member */",
        "  const char        *cli;   /* the flag; NULL = not on the CLI */",
        "  wfm_surf_owner_t   owner;",
        "  wfm_sv_kind_t      kind;",
        "  size_t             off;       /* offsetof the member */",
        "  unsigned           range_bit; /* WFM_RANGE_*; 0 = not ranged */",
        "  size_t             hi_off;    /* `<name>_hi`, if ranged */",
        "  size_t             len_off;   /* WFM_SV_SYMBOLS: the count */",
        "  size_t             reps_off;  /* WFM_SV_FIELD: where *REPS goes;",
        "                                    0 = the field does not repeat */",
        "  const char *const *choices;   /* WFM_SV_CHOICE: the names */",
        "  int                n_choices;",
        "  int                unit_interval; /* require 0 < v <= 1 */",
        "  const char        *json;          /* the scene/record key */",
        "  int                json_required; /* absent/unknown: refuse */",
        "  int                json_omit;     /* not written at its default */",
        "  int                json_bool;     /* written as true/false */",
        "  int                has_when;      /* written only when ... */",
        "  int                when_row;      /* ... this row's choice ... */",
        "  int                when_value;    /* ... is this index */",
        "} wfm_surface_row_t;",
        "",
        "/* A row's index: WFM_SURFACE_<owner>_<name>. */",
        "enum",
        "{",
    ]
    for r in rows:
        out.append(f"  WFM_SURFACE_{r['owner']}_{r['name']},")
    out += ["  WFM_SURFACE_N", "};", ""]
    out.append("static const wfm_surface_row_t WFM_SURFACE[WFM_SURFACE_N] = {")
    for r in rows:
        struct = STRUCTS[r["owner"]]
        n = r["name"]
        fields = [f'.name = "{n}"']
        if r["cli"]:
            fields.append(f'.cli = "{r["cli"]}"')
        fields += [
            f".owner = {owner_c[r['owner']]}",
            f".kind = {r['kind']}",
            f".off = offsetof ({struct}, {r['member']})",
        ]
        if r["range_bit"]:
            fields += [
                f".range_bit = {r['range_bit']}",
                f".hi_off = offsetof ({struct}, {n}_hi)",
            ]
        if r["kind"] == "WFM_SV_SYMBOLS":
            fields.append(f".len_off = offsetof ({struct}, n_{n})")
        if r["field_reps"]:
            fields.append(
                f".reps_off = offsetof ({struct}, {r['field_reps']})"
            )
        if r["choices"]:
            c = r["choices"]
            fields += [
                f".choices = {c}",
                f".n_choices = (int)(sizeof {c} / sizeof *{c})",
            ]
        if r["unit_interval"]:
            fields.append(".unit_interval = 1")
        if r["json"]:
            fields.append(f'.json = "{r["json"]}"')
        if r["json_required"]:
            fields.append(".json_required = 1")
        if r["json_omit"] == "default":
            fields.append(".json_omit = 1")
        if r["json_bool"]:
            fields.append(".json_bool = 1")
        if r.get("when_row"):
            fields += [
                ".has_when = 1",
                f".when_row = {r['when_row']}",
                f".when_value = {r['when_value']}",
            ]
        out.append(f"  [WFM_SURFACE_{r['owner']}_{n}] = {{")
        out += [f"    {x}," for x in fields]
        out.append("  },")
    out += ["};", ""]
    out += render_exclusive(rows)
    out += render_reps(rows)
    out += render_help(rows)
    out += render_json_keys(json.loads(render_schema()))
    out.append("#endif /* WFM_SURFACE_H */")
    return "\n".join(out) + "\n"


#: Every object a scene is made of, in the order the reader meets them:
#: (C level name, path to its `properties` in the schema). The reader
#: refuses a key that is not in its level's table, and the table IS the
#: schema's properties -- one declaration, both directions (doppler#1153,
#: where a top-level "fs" was dropped in silence and every segment ran at
#: fs = 1).
JSON_LEVELS = (
    ("ROOT", ()),
    ("INLINE_SEGMENT", ("$defs", "inline_segment")),
    ("SUM_SEGMENT", ("$defs", "sum_segment")),
    ("SOURCE", ("$defs", "source")),
    ("FRAME", ("$defs", "frame_desc")),
    ("FIELD", ("$defs", "frame_desc", "properties", "fields", "items")),
    ("STAGE", ("$defs", "frame_desc", "properties", "stages", "items")),
)


def render_json_keys(schema: dict) -> list[str]:
    """`WFM_JSON_KEYS[]`: the keys each scene object takes, from the schema.

    The schema says `additionalProperties: false` on every one of these
    objects; this is what makes the reader agree. A level whose object
    stops refusing extra keys is a schema change the reader cannot honour,
    so it fails here rather than generating an open level.
    """
    out = [
        "/* The keys each object of a scene takes, generated from the "
        "schema's",
        "   `properties` (docs/schema/wfmgen.schema.json). The reader "
        "refuses any",
        "   other key by name: the schema and the reader are one table "
        "(#1153). */",
        "typedef enum",
        "{",
    ]
    out += [f"  WFM_JSON_{name}," for name, _ in JSON_LEVELS]
    out += ["  WFM_JSON_N_LEVELS", "} wfm_json_level_t;", ""]
    for name, path in JSON_LEVELS:
        obj = schema
        for k in path:
            obj = obj[k]
        if obj.get("additionalProperties") is not False:
            raise SystemExit(
                f"gen_wfm_defaults: schema object {'/'.join(path) or '$'} "
                "does not set additionalProperties: false, so the reader "
                "cannot refuse an unknown key there"
            )
        keys = sorted(obj["properties"])
        out.append(f"static const char *const WFM_JSON_KEYS_{name}[] = {{")
        out += [f"  {_c_lit(k)}," for k in keys]
        out += ["  NULL", "};", ""]
    out.append(
        "static const char *const *const WFM_JSON_KEYS[WFM_JSON_N_LEVELS] = {"
    )
    out += [f"  WFM_JSON_KEYS_{name}," for name, _ in JSON_LEVELS]
    out += ["};", ""]
    return out


def _c_lit(text: str | None) -> str:
    if text is None:
        return "NULL"
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _c_field(name: str, text: str | None) -> list[str]:
    """`    <name> = "<text>",`, the literal split into adjacent pieces so no
    line passes 79 columns (the header is generated, not clang-formatted)."""
    if text is None:
        return [f"    {name} = NULL,"]
    pieces = textwrap.wrap(
        text, width=54, drop_whitespace=False, break_on_hyphens=False
    )
    lines = [f"    {name} = {_c_lit(pieces[0])}"]
    lines += [f"        {_c_lit(p)}" for p in pieces[1:]]
    lines[-1] += ","
    return lines


def render_exclusive(rows: list[dict]) -> list[str]:
    """`WFM_SURFACE_EXCLUSIVE[]`: the pairs no face may take together.

    One declaration per pair (the manifest's `exclusive`), each reason a
    literal per face so a `why` never points at a formatted buffer.
    """
    out = [
        "/* Two rows no face takes together, and the reason, spelled for each",
        "   face that can be given both: the CLI (both flags), a scene (both",
        "   keys), the object (both members set). NULL: that face cannot",
        "   carry one of the two, so it has nothing to refuse. */",
        "typedef struct",
        "{",
        "  int         a, b; /* WFM_SURFACE_<owner>_<name> */",
        "  const char *cli_why;",
        "  const char *json_why;",
        "  const char *obj_why;",
        "} wfm_surface_exclusive_t;",
        "",
    ]
    excl = exclusions(rows)
    out.append(f"#define WFM_SURFACE_N_EXCLUSIVE {len(excl)}")
    # C has no empty array: with no pair declared, one zeroed entry that
    # WFM_SURFACE_N_EXCLUSIVE (0) keeps every loop from reading.
    out += [
        "static const wfm_surface_exclusive_t",
        f"    WFM_SURFACE_EXCLUSIVE[{max(len(excl), 1)}] = {{",
    ]
    if not excl:
        out.append("  { 0 },")
    for e in excl:
        o = e["owner"]
        out += [
            "  {",
            f"    .a = WFM_SURFACE_{o}_{e['a']},",
            f"    .b = WFM_SURFACE_{o}_{e['b']},",
        ]
        for k in ("cli_why", "json_why", "obj_why"):
            out += _c_field(f".{k}", e[k])
        out.append("  },")
    out += [
        "};",
        "",
        "/* Whether a row's member holds a value: the object face's",
        '   "given". Only the kinds an exclusion may name (the generator',
        "   refuses any other) have an unset value to test for. */",
        "static inline int",
        "wfm_surface_row_is_set (const wfm_surface_row_t *r,",
        "                        const void              *base)",
        "{",
        "  const char *m = (const char *)base + r->off;",
        "  switch (r->kind)",
        "    {",
        "    case WFM_SV_FIELD:",
        "      return ((const wfm_seq_t *)m)->len != 0;",
        "    case WFM_SV_BESPOKE:",
        "      return *(const void *const *)m != NULL;",
        "    case WFM_SV_SYMBOLS:",
        "      return *(const size_t *)((const char *)base + r->len_off)",
        "             != 0;",
        "    default:",
        "      return 0;",
        "    }",
        "}",
        "",
    ]
    return out


def render_reps(rows: list[dict]) -> list[str]:
    """The one reason a Field that does not repeat refuses `*REPS`, per face.

    Which field repeats is the manifest's `field_reps`; the sentence names
    it from there, so the CLI and a scene cannot say it two ways.
    """
    reps = [r for r in rows if r["field_reps"]]
    if not reps:
        return []
    cli = ", ".join(r["cli"] for r in reps if r["cli"])
    js = ", ".join(f'"{r["json"]}"' for r in reps if r["json"])
    return [
        "/* A Field row with no repetition count refuses *REPS: only the",
        "   rows with `field_reps` repeat (a preamble). One reason per face.",
        "*/",
        "#define WFM_SURFACE_REPS_WHY_CLI \\",
        f"  {_c_lit(f'only {cli} repeats (a preamble): drop the *REPS')}",
        "#define WFM_SURFACE_REPS_WHY_JSON \\",
        f"  {_c_lit(f'only {js} repeats (a preamble): drop the *REPS')}",
        "",
    ]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = ap.parse_args()

    drift = doc_drift(
        tomllib.loads(MANIFEST.read_text(encoding="utf-8")),
        COMPOSE_H.read_text(encoding="utf-8"),
    )
    if drift:
        # Not fixable by --write: which of the two texts is right is a
        # judgement, and the header is the one to edit (then copy it).
        print(
            "gen_wfm_defaults: a field's manifest `doc` differs from its "
            f"comment in {COMPOSE_H.relative_to(ROOT)}. The header is the "
            "one text; make the manifest doc match it.",
            file=sys.stderr,
        )
        for d in drift:
            print("  " + d, file=sys.stderr)
        return 1

    only = surface_only_errors(
        tomllib.loads(MANIFEST.read_text(encoding="utf-8")),
        COMPOSE_H.read_text(encoding="utf-8"),
    )
    if only:
        for d in only:
            print(f"gen_wfm_defaults: {d}", file=sys.stderr)
        return 1

    splice = help_splice_errors(
        tomllib.loads(MANIFEST.read_text(encoding="utf-8"))
    )
    if splice:
        for d in splice:
            print(f"gen_wfm_defaults: {d}", file=sys.stderr)
        return 1

    outputs = (
        (HEADER, render()),
        (SURFACE, render_surface()),
        (SCHEMA, render_schema()),
        (REFERENCE, render_reference()),
    )
    if args.write:
        for path, fresh in outputs:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(fresh, encoding="utf-8")
            print(f"gen_wfm_defaults: wrote {path.relative_to(ROOT)}")
        return 0

    bad = 0
    for path, fresh in outputs:
        rel = path.relative_to(ROOT)
        if not path.is_file():
            print(
                f"gen_wfm_defaults: {rel} is MISSING — run `python "
                "scripts/gen_wfm_defaults.py --write`",
                file=sys.stderr,
            )
            bad = 1
        elif path.read_text(encoding="utf-8") != fresh:
            print(
                f"gen_wfm_defaults: {rel} is STALE — the manifest has moved "
                "since it was generated. Run `python "
                "scripts/gen_wfm_defaults.py --write`.",
                file=sys.stderr,
            )
            bad = 1
    if bad:
        return 1
    print(
        "gen_wfm_defaults: OK — the C defaults and the surface table match "
        "the manifest, and every field's doc matches its header comment"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
