#!/usr/bin/env python3
"""Generate the C initialisers for a wfm source and segment, from the manifest.

**One declaration, both directions.** `just-makeit.toml` already declares
every default with `default = ...`, and jm generates Python's from it. C had
no path to that declaration: `native/src/app/wfmgen.c` restated the values as
a struct literal inside `main()`, its own comment saying they *"mirror the
Python Synth/Composer defaults"* — mirrored in three places, shared from
none, with no gate comparing them (doppler#1142).

Two of them were worse than a plain duplicate. `modulation` and `crc` were
restated as enum **indices** (`1`, `1`) while the manifest names them as
**strings** (`"bpsk"`, `"crc16"`), so the literal silently depended on the
ORDER of `[[enum]] bitmod` and `[[enum]] crc`. Append-only protects the tail,
not the head: prepend an entry to either and the manifest still means `bpsk`
while `1` becomes the new second entry — a wrong default with nothing
failing. That is the rot `wfm_names.h` exists to end (doppler#760), one level
up, in a literal no enum gate scans.

This resolves such a default through the field's OWN `enum = "..."` key, never
by searching the enums for a matching string. `"bpsk"` appears in both
`[[enum]] bitmod` (index 1) and `[[enum]] wfm_type` (index 3); a
search-by-value would have picked the wrong one, which is precisely the
mistake a hand-written index invites.

Only fields whose default is NON-ZERO are emitted. A zero default is what a
zero-initialised struct already gives, so writing it would add noise that
says nothing — and the generated macro is meant to be read.

Usage:
    python scripts/gen_wfm_defaults.py --check   # exit 1 if header is stale
    python scripts/gen_wfm_defaults.py --write   # regenerate it
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import tomllib
from _layout import header

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "just-makeit.toml"
HEADER = ROOT / header("wfm/wfm_defaults.h")
COMPOSE_H = ROOT / header("wfm/wfm_compose.h")

# The C struct each manifest table describes.
STRUCTS = {"source": "wfm_source_t", "segment": "wfm_segment_t"}

# Fields whose manifest `doc` may still differ from the header. Each one is a
# field doppler#853 converts or deletes (items 10 and 11: the sequences and
# the frame sugar), so reconciling its prose now would be written twice.
# RATCHET: this may only shrink. A field leaves it when it is deleted, or
# when its two texts are made equal -- and a new field never joins it.
DOC_DRIFT_ALLOWED = {
    ("source", "bits"),
    ("source", "acq_code"),
    ("source", "acq_reps"),
    ("source", "data_code"),
    ("source", "sync"),
    ("source", "rs_depth"),
    ("source", "randomise"),
    ("source", "attach_asm"),
    ("source", "convolutional"),
}

BANNER = "wfm_defaults.h — GENERATED by scripts/gen_wfm_defaults.py"


def _enums(man: dict) -> dict[str, list[str]]:
    return {e["name"]: list(e["values"]) for e in man.get("enum", [])}


def _literal(field: dict, enums: dict[str, list[str]]) -> str | None:
    """The C initialiser for one field's default, or None to omit it.

    Returns None for a default that is zero in C, because a zero-initialised
    struct already carries it.
    """
    raw = field.get("default")
    if raw is None:
        return None
    name = field["name"]

    # An enum-valued default resolves through the field's OWN declared enum.
    en = field.get("enum")
    if en is not None:
        values = enums.get(en)
        if values is None:
            raise SystemExit(
                f"{name}: enum = {en!r}, which no [[enum]] declares"
            )
        if raw not in values:
            raise SystemExit(
                f"{name}: default {raw!r} is not a member of [[enum]] {en} "
                f"({', '.join(values)})"
            )
        idx = values.index(raw)
        return None if idx == 0 else f"{idx} /* {en}: {raw} */"

    text = str(raw).strip()
    ctype = field.get("type", "")
    if ctype in ("double", "float"):
        return None if float(text) == 0.0 else text
    # Everything else is an integer-ish scalar. A non-numeric default here is
    # a string type (a path, a name); those have no place in a struct literal.
    try:
        n = int(text, 0)
    except ValueError:
        return None
    return None if n == 0 else str(n)


_DECL = re.compile(r"^([ \t]*)[A-Za-z_][\w \t\*]*?\b(\w+)(?:\[\w*\])?;", re.M)


def member_docs(text: str, struct: str) -> dict[str, dict]:
    """Each member's doc comment in `typedef struct { ... } <struct>;`.

    **A member's doc is its trailing comment** -- the `/* ... */` that opens
    on the declaration's own line -- **or, when it has none, the block
    comment directly above it** (only whitespace between the two). A block
    comment above a member that ALSO has a trailing comment is a design note
    and is not its doc.

    Returns ``{name: {"doc", "start", "end", "col", "form"}}`` where the doc
    is the comment's words joined by single spaces, ``start``/``end`` span
    the whole comment in `text`, ``col`` is the column the ``/*`` opens at,
    and ``form`` is ``"trailing"`` or ``"above"``. A member with neither has
    no entry.
    """
    end = text.index(f"}} {struct};")
    begin = text.rindex("typedef struct {", 0, end)
    # A comment line can read like a declaration ("... other types;"), so
    # every match inside a comment is skipped rather than trusted.
    comments = [
        (c.start(), c.end())
        for c in re.finditer(r"/\*.*?\*/", text[:end], re.S)
        if c.end() > begin
    ]
    out: dict[str, dict] = {}
    for m in _DECL.finditer(text, begin, end):
        if any(a <= m.start() < b for a, b in comments):
            continue
        name = m.group(2)
        line_end = text.index("\n", m.end())
        rest = text[m.end() : line_end]
        if "/*" in rest:
            start = m.end() + rest.index("/*")
            form = "trailing"
        else:
            above = text[begin : m.start()].rstrip()
            if not above.endswith("*/"):
                continue
            start = text.rindex("/*", begin, m.start())
            line_start = text.rindex("\n", 0, start) + 1
            if text[line_start:start].strip():
                continue  # the previous member's trailing comment
            form = "above"
        close = text.index("*/", start) + 2
        doc = " ".join(text[start + 2 : close - 2].split())
        col = start - (text.rindex("\n", 0, start) + 1)
        out[name] = {
            "doc": doc,
            "start": start,
            "end": close,
            "col": col,
            "form": form,
        }
    return out


def doc_drift(man: dict, header_text: str) -> list[str]:
    """Fields whose manifest `doc` differs from the header's comment.

    The header is the field's one text (docs/design/wfmgen.md, "One surface
    table"); the manifest `doc` exists only because jm still reads it for
    the Python docstring (just-makeit#1703), so it must be the same words.
    """
    bad = []
    mc = man["module"]["wfm_compose"]
    for kind, struct in STRUCTS.items():
        docs = member_docs(header_text, struct)
        for f in mc[kind].get("fields", []):
            key = (kind, f["name"])
            if key in DOC_DRIFT_ALLOWED:
                continue
            have = " ".join(str(f.get("doc", "")).split())
            want = docs.get(f["name"], {}).get("doc", "")
            if have != want:
                bad.append(
                    f"{kind}.{f['name']}: manifest doc != header comment\n"
                    f"    manifest: {have or '(none)'}\n"
                    f"    header:   {want or '(none)'}"
                )
    return bad


def render() -> str:
    man = tomllib.loads(MANIFEST.read_text(encoding="utf-8"))
    enums = _enums(man)
    mc = man["module"]["wfm_compose"]

    out: list[str] = [
        "/*",
        f" * {BANNER}",
        " *",
        " * Do not edit. `just-makeit.toml` is the one declaration of a",
        " * default; this is that declaration rendered for C, so the CLI, a",
        " * C caller and Python cannot disagree about one (doppler#1142).",
        " *",
        " * Only NON-ZERO defaults appear: a zero is what a zero-initialised",
        " * struct already gives, and spelling it would say nothing.",
        " *",
        " * An enum-valued default is rendered as the index of its name in",
        " * the field's OWN declared [[enum]], with the name in a comment, so",
        " * reordering that enum moves this file rather than silently",
        " * changing what the value means.",
        " */",
        "#ifndef WFM_DEFAULTS_H",
        "#define WFM_DEFAULTS_H",
        "",
    ]

    for kind, macro in (
        ("source", "WFM_SOURCE_DEFAULTS"),
        ("segment", "WFM_SEGMENT_DEFAULTS"),
    ):
        rows = []
        for f in mc[kind].get("fields", []):
            lit = _literal(f, enums)
            if lit is not None:
                rows.append((f["name"], lit))
        out.append(f"/* Non-zero defaults for a wfm_{kind}_t. */")
        out.append(f"#define {macro} \\")
        body = ", \\\n".join(f"    .{n} = {v}" for n, v in rows)
        out.append("  { \\")
        out.append(body + " \\")
        out.append("  }")
        out.append("")

    out.append("#endif /* WFM_DEFAULTS_H */")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = ap.parse_args()

    fresh = render()
    drift = doc_drift(
        tomllib.loads(MANIFEST.read_text(encoding="utf-8")),
        COMPOSE_H.read_text(encoding="utf-8"),
    )
    if drift:
        # Not fixable by --write: which of the two texts is right is a
        # judgement, and the header is the one to edit (then copy it).
        print(
            "gen_wfm_defaults: a field's manifest `doc` differs from its "
            f"comment in {COMPOSE_H.relative_to(ROOT)}. The header is the "
            "one text; make the manifest doc match it.",
            file=sys.stderr,
        )
        for d in drift:
            print("  " + d, file=sys.stderr)
        return 1
    if args.write:
        HEADER.parent.mkdir(parents=True, exist_ok=True)
        HEADER.write_text(fresh, encoding="utf-8")
        print(f"gen_wfm_defaults: wrote {HEADER.relative_to(ROOT)}")
        return 0

    if not HEADER.is_file():
        print(
            f"gen_wfm_defaults: {HEADER.relative_to(ROOT)} is MISSING — run "
            "`python scripts/gen_wfm_defaults.py --write`",
            file=sys.stderr,
        )
        return 1
    if HEADER.read_text(encoding="utf-8") != fresh:
        print(
            f"gen_wfm_defaults: {HEADER.relative_to(ROOT)} is STALE — the "
            "manifest's defaults have moved. Run `python "
            "scripts/gen_wfm_defaults.py --write`.",
            file=sys.stderr,
        )
        return 1
    print(
        "gen_wfm_defaults: OK — the C defaults match the manifest, and "
        "every field's doc matches its header comment"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
