#!/usr/bin/env python3
"""Write ``cmake/public-symbols.txt``: every symbol a public header publishes.

The shared libraries export exactly what the headers under ``native/inc``
promise and nothing else (doppler#1164). Before this, ``libdoppler.so``
exported every symbol with external linkage -- 1658 of them, among them the
whole of vendored cJSON and PFFFT under their own names, so a consumer that
linked its own cJSON had the loader pick ONE copy for both libraries and
doppler called the consumer's parser (``make vendored-collision-check``
measured it: exit 2).

The headers are the one declaration of "public". This script reads them
with the same parser ``check_installed_headers.py`` uses
(``public_symbols()``) and writes one line per symbol, ``<name> function``
or ``<name> data``. The build reads that list without Python:
``cmake/export_list.cmake`` intersects it with what each library's archive
defines and writes the linker's export file -- a version script on ELF, an
``-exported_symbols_list`` on macOS, a ``.def`` on Windows.

Committed, not generated at build time, so building doppler from a tarball
needs no Python. ``--check`` (``make lint``) fails when a header has moved
and the list has not; ``make public-symbols`` rewrites it.

Usage
-----
    python3 scripts/gen_public_symbols.py           # rewrite the list
    python3 scripts/gen_public_symbols.py --check   # exit 1 if stale
"""

from __future__ import annotations

import argparse
import pathlib
import sys

from check_installed_headers import ROOT, public_symbols

OUT = ROOT / "cmake" / "public-symbols.txt"

HEADER = (
    "# Every symbol a header under native/inc publishes: <name> <kind>.\n"
    "# GENERATED by scripts/gen_public_symbols.py -- `make public-symbols`.\n"
    "# cmake/export_list.cmake intersects it with each library's archive\n"
    "# to write the shared library's export list (doppler#1164).\n"
)


def render() -> str:
    """The list's text, sorted so a diff names the symbol that moved."""
    syms = public_symbols()
    return HEADER + "".join(f"{n} {syms[n]}\n" for n in sorted(syms))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--out", type=pathlib.Path, default=OUT)
    args = ap.parse_args(argv)
    want = render()
    have = args.out.read_text(encoding="utf-8") if args.out.is_file() else ""
    if args.check:
        if have == want:
            return 0
        old = {ln for ln in have.splitlines() if not ln.startswith("#")}
        new = {ln for ln in want.splitlines() if not ln.startswith("#")}
        for ln in sorted(new - old):
            print(f"  + {ln}")
        for ln in sorted(old - new):
            print(f"  - {ln}")
        print(
            f"gen-public-symbols: {args.out.relative_to(ROOT)} is stale "
            "against native/inc -- run `make public-symbols`"
        )
        return 1
    args.out.write_text(want, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
