#!/usr/bin/env python3
"""Generate `doppler.wfm`'s stage-kind constants from the C enum.

**One declaration, both directions.** `wfm_stage_kind_t`
(`native/inc/wfm/wfm_frame.h`) fixes the numbering; the scene JSON reaches it
by NAME through `[[enum]] stage_kind`, and `wfm_json.c` pins it with
`_Static_assert` because it matters. Python reached it by nothing at all —
`add_stage(kind=...)` takes a bare int and no named constant was exported
anywhere, so every caller re-declared the mapping locally. There were five
copies (doppler#1223), plus the prose in two docstrings, and the numbering
they all restate is one prepended enumerator away from being wrong with
nothing failing.

**Why constants and not a string enum.** `wfm_stage_kind_t` is an OPEN
`uint32_t`: `WFM_STAGE_USER` is reserved for callers, who allocate upward and
supply the kernel through `wfm_frame_ops_t`. jm's `enum` key models a CLOSED
choice list and rejects an integer outright, so binding `kind` that way was
tried, measured — `add_stage(0x1001, ...)` became
`TypeError: argument 1 must be str, not int` — and reverted. Named constants
keep the parameter an int and the open range reachable, which is why
`STAGE_USER` is emitted alongside the five doppler names rather than being
left to prose the way the number 4096 was.

**The C header is the source, not the manifest.** `[[enum]] stage_kind` holds
the five names doppler allocates and deliberately not the whole enum — a
boundary is not a name — so it cannot express `STAGE_USER`. The header carries
every enumerator with an explicit value, and `check_wfm_enum_tables.py`
already gates the manifest against it, so reading the header here derives from
the deepest declaration without re-checking what another gate owns.

A new enumerator therefore reaches Python by existing. That is the property
worth having: the failure this replaces is not a mismatch anyone would see,
it is a caller's `RS = 1` still saying 1 after `rs` moved.

Usage:
    python scripts/gen_stage_kinds.py --check   # exit 1 if the module is stale
    python scripts/gen_stage_kinds.py --write   # regenerate it
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "native" / "inc" / "wfm" / "wfm_frame.h"
MODULE = ROOT / "src" / "doppler" / "wfm" / "stage_kinds.py"

#: The enum whose enumerators become the constants.
CENUM = "wfm_stage_kind_t"

#: `WFM_STAGE_CRC16 = 0,` / `WFM_STAGE_USER = 0x1000u`. Only an EXPLICIT value
#: is accepted: an implicit one would make the constant depend on the position
#: of every enumerator above it, which is the drift this file exists to end,
#: reintroduced in the generator.
ENUMERATOR = re.compile(
    r"^\s*WFM_STAGE_([A-Z0-9_]+)\s*=\s*(0[xX][0-9a-fA-F]+|\d+)[uUlL]*\s*,?",
    re.MULTILINE,
)

BANNER = "GENERATED by scripts/gen_stage_kinds.py — do not edit"


def _enum_body(text: str) -> str:
    """The braces of the `wfm_stage_kind_t` typedef, and nothing else.

    Anchored on the trailing type name and scanned BACKWARDS to its opening
    brace, so a second enum in the same header cannot contribute an
    enumerator. Raises rather than returning a partial body: a generator that
    silently emitted four of five constants would be the failure mode this
    gate is for.
    """
    end = text.index(f"}} {CENUM};")
    start = text.rindex("{", 0, end)
    return text[start + 1 : end]


def kinds() -> list[tuple[str, int]]:
    """Every enumerator of the C enum, as `(python_name, value)`."""
    body = _enum_body(HEADER.read_text(encoding="utf-8"))
    found = [(name, int(value, 0)) for name, value in ENUMERATOR.findall(body)]
    if not found:
        raise SystemExit(
            f"gen_stage_kinds: no enumerator matched in {CENUM} — the header "
            "moved and this generator did not. Reading nothing is not a "
            "reason to write nothing."
        )
    return [(f"STAGE_{name}", value) for name, value in found]


def render() -> str:
    """The module text, already in the project's ruff style.

    Emitted the way `make format` would leave it — 79 columns, unaligned,
    one `__all__` entry per line — because ruff runs over `src/` and a
    generator that emitted anything else would be reformatted on the next
    commit and then read as STALE by its own `--check`. A generated file that
    fights the formatter is a gate that fails for the wrong reason — and
    ruff's LINTER counts: RUF022 sorts `__all__`, which is why that list
    is emitted sorted while the constants keep enum order.
    """
    rows = kinds()

    out = [
        '"""Stage kinds for `FrameDesc.add_stage`.',
        "",
        f"{BANNER}.",
        "",
        "The `WFM_` prefix the C carries is dropped: inside `doppler.wfm` it",
        "says the module's own name back. The values are read from",
        "`native/inc/wfm/wfm_frame.h` rather than restated here, so a new",
        "stage kind arrives in Python by existing.",
        "",
        "A stage's kind is an **open** `uint32_t`, not a closed menu. These",
        "are the kinds doppler allocates; a caller allocates its own from",
        "`STAGE_USER` upward and supplies the kernel through the ops table.",
        "That is why these are plain ints and not an `IntEnum`, which would",
        "refuse `STAGE_USER + 1` — the one value a caller actually writes.",
        "",
        "Examples",
        "--------",
        ">>> from doppler.wfm import STAGE_CRC16, STAGE_USER",
        ">>> STAGE_CRC16",
        "0",
        ">>> STAGE_USER > STAGE_CRC16  # doppler never allocates up here",
        "True",
        '"""',
        "",
    ]
    for name, value in rows:
        out.append(f"{name} = {hex(value) if value >= 0x1000 else value}")
    out.append("")
    # The constants keep ENUM order, which is the thing being expressed.
    # `__all__` is SORTED, because ruff's RUF022 sorts it and a generator
    # that disagreed with the linter would be rewritten on the next commit
    # and then read as STALE by its own --check. Order carries no meaning
    # here, so the formatter wins and the file stops moving.
    out.append("__all__ = [")
    out.extend(f'    "{name}",' for name in sorted(n for n, _ in rows))
    out.append("]")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = ap.parse_args()

    fresh = render()
    if args.write:
        MODULE.write_text(fresh, encoding="utf-8")
        print(f"gen_stage_kinds: wrote {MODULE.relative_to(ROOT)}")
        return 0

    if not MODULE.is_file():
        print(
            f"gen_stage_kinds: {MODULE.relative_to(ROOT)} is MISSING — run "
            "`python scripts/gen_stage_kinds.py --write`",
            file=sys.stderr,
        )
        return 1
    if MODULE.read_text(encoding="utf-8") != fresh:
        print(
            f"gen_stage_kinds: {MODULE.relative_to(ROOT)} is STALE — "
            f"{CENUM} has moved. Run `python scripts/gen_stage_kinds.py "
            "--write`.",
            file=sys.stderr,
        )
        return 1
    print(f"gen_stage_kinds: OK — the Python constants match {CENUM}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
