#!/usr/bin/env bash
# Regenerate the jm-owned buffer binding into ./generated/.
#
#   ./regenerate.sh [<just-makeit-ref>]
#
# Nothing here touches doppler's build. It scaffolds a throwaway project,
# applies the declaration beside this script, and copies the generated glue
# back so it can be diffed against the hand-written binding in
# native/src/buffer/.
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)

# PINNED, because the artifacts in generated/ can only have come from a jm
# newer than this repo's `just-makeit==0.75.5` -- the features they use are
# unreleased. A bare `just-makeit` from PATH silently produces something else:
# CLAUDE.md records `make bench` resolving to 0.19.28 while the pin said
# 0.33.12, which made the local benchmark path unrunnable for weeks.
JM_REF="${1:-${JM_REF:-git+https://github.com/just-buildit/just-makeit@d9a1cb2}}"
JM=(uvx --from "$JM_REF" just-makeit)

tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
cd "$tmp"
"${JM[@]}" new dpring >/dev/null
cd dpring
"${JM[@]}" module buffer >/dev/null
cp "$here/f32_buffer.toml" objects/
"${JM[@]}" apply >/dev/null

mkdir -p "$here/generated"
stamp="/* Generated by just-makeit @ $JM_REF on $(date -u +%Y-%m-%d). Do not edit. */"
{ echo "$stamp"; cat native/src/buffer/buffer_ext_f32_buffer.c; } \
    > "$here/generated/buffer_ext_f32_buffer.c"
{ echo "# ${stamp#/* }"; cat src/dpring/buffer/buffer.pyi; } \
    > "$here/generated/buffer.pyi"

# NO raw clang-format here: the Makefile is the SSOT for how every tool runs,
# and this repo already formats jm-generated C two ways that agree -- jm's own
# `c_format_command` on apply, and the pre-commit hook on commit. Committing is
# what normalises it; a third invocation would be a second opinion about style.
#
#   ./regenerate.sh && git add -A && git commit
echo "regenerated into $here/generated/ (jm: $JM_REF)"
