#!/usr/bin/env bash
# Regenerate the jm-owned buffer binding into ./generated/.
#
#   ./regenerate.sh [<just-makeit-ref>]
#
# Nothing here touches doppler's build. It scaffolds a throwaway project,
# applies the declaration beside this script, and copies the generated glue
# back so it can be diffed against the hand-written binding in
# native/src/buffer/.
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)

# PINNED, because the artifacts in generated/ can only have come from a jm
# newer than this repo's `just-makeit==0.75.5` -- the features they use are
# unreleased. A bare `just-makeit` from PATH silently produces something else:
# CLAUDE.md records `make bench` resolving to 0.19.28 while the pin said
# 0.33.12, which made the local benchmark path unrunnable for weeks.
JM_REF="${1:-${JM_REF:-git+https://github.com/just-buildit/just-makeit@v0.76.0}}"
JM=(uvx --from "$JM_REF" just-makeit)

tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
cd "$tmp"
"${JM[@]}" new dpring >/dev/null
cd dpring
"${JM[@]}" module buffer >/dev/null
# `jm new` does not create objects/ -- `jm object` does, and this proposal
# ships the fragment instead of running the CLI. And `jm module` writes
# `objects = []`, so the object has to be REGISTERED or apply generates
# nothing for it and says nothing about why. Without both, this script could
# not reproduce generated/ at all.
mkdir -p objects
cp "$here/f32_buffer.toml" objects/
sed -i 's/^objects = \[\]$/objects = ["f32_buffer"]/' modules/buffer.toml
"${JM[@]}" apply >/dev/null

mkdir -p "$here/generated"
stamp="/* Generated by just-makeit @ $JM_REF on $(date -u +%Y-%m-%d). Do not edit. */"
{ echo "$stamp"; cat native/src/buffer/buffer_ext_f32_buffer.c; } \
    > "$here/generated/buffer_ext_f32_buffer.c"
{ echo "# ${stamp#/* }"; cat src/dpring/buffer/buffer.pyi; } \
    > "$here/generated/buffer.pyi"

# NO raw clang-format here: the Makefile is the SSOT for how every tool runs,
# and this repo already formats jm-generated C two ways that agree -- jm's own
# `c_format_command` on apply, and the pre-commit hook on commit. Committing is
# what normalises it; a third invocation would be a second opinion about style.
#
#   ./regenerate.sh && git add -A && git commit

# --- build what was just generated ------------------------------------------
#
# The proposal's first version claimed "verified: the generated binding calls
# the real functions" on the strength of READING it. The probe was added to
# fix that, but it lived only in the README as a command naming two files that
# are not in the tree (`shim.h`, `frag.c`), so it could not run -- a claim
# nothing runs is prose. It runs here now, on every regeneration.
#
# COMPILE catches a signature mismatch and an undeclared callee; LINK catches
# a symbol that is declared and never defined. Both, because the two see
# different defects.
cd "$here"
py=${PYTHON:-$here/../../.venv/bin/python}
[ -x "$py" ] || py=$(command -v python3)
inc="-I. -I../../native/inc"
inc="$inc -I$("$py" -c 'import sysconfig;print(sysconfig.get_paths()["include"])')"
inc="$inc -I$("$py" -c 'import numpy;print(numpy.get_include())')"
libdir=$("$py" -c 'import sysconfig;print(sysconfig.get_config_var("LIBDIR"))')
pyver=$("$py" -c 'import sysconfig;print(sysconfig.get_config_var("LDVERSION"))')

o=$(mktemp -d); trap 'rm -rf "$tmp" "$o"' EXIT
# -Wall, not -Wextra: -Wextra flags unused parameters in jm-generated CPython
# slot signatures (tp_new's kwds, and so on), which is not what this probe
# asks. A warning here should mean a mismatch between the binding and the ring.
cc -std=c11 -fPIC -Wall -c compile-probe.c -o "$o/probe.o" $inc
cc -shared "$o/probe.o" -o "$o/probe.so" -Wl,--no-undefined \
   -L"$libdir" -lpython"$pyver"
echo "probe: compiles and links clean"

echo "regenerated into $here/generated/ (jm: $JM_REF)"
