"""ddc_fn_scaling.py — thread-per-shard core-scaling benchmark for Ddcr.

`Ddcr.execute` runs the C kernel with the **GIL released** (the kernel touches
only its own state and the caller's buffers — no Python objects, no
shared state), so a thread-per-shard worker scales across cores instead of
serialising on the GIL.

This measures that: N worker threads, each owning its **own** Ddcr and
`out` buffer, all running `execute` concurrently. It plots realised speedup
versus an ideal-linear reference and saves ``ddc_fn_scaling.png``.

The curve is near-linear through a handful of cores, then flattens — the kernel
streams large buffers, so it becomes **memory-bandwidth bound**, not GIL bound.
Numbers are machine-specific (regenerated by ``make gallery``).

Run:
  python ddc_fn_scaling.py
"""

from __future__ import annotations

import os
import threading
import time

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from doppler.ddc import Ddcr

F_CARRIER = 0.18
LO = -(2.0 * F_CARRIER + 0.5)
RATE = 0.25
NBLK = 8192  # samples per block
BPT = 6000  # blocks each thread processes per run
TRIALS = 3  # keep the best (least-noisy) of this many runs


def _worker(barrier: threading.Barrier) -> None:
    """One shard: own object, own output buffer, tight execute loop."""
    ddcr = Ddcr(LO, RATE)
    out = np.empty(NBLK, dtype=np.complex64)
    x = np.cos(2.0 * np.pi * F_CARRIER * np.arange(NBLK)).astype(np.float32)
    barrier.wait()  # release all threads together
    for _ in range(BPT):
        ddcr.execute(x, out)
    ddcr.close()


def _throughput(n_threads: int) -> float:
    """Best-of-TRIALS aggregate throughput (blocks/s) for *n_threads*."""
    best = 0.0
    for _ in range(TRIALS):
        barrier = threading.Barrier(n_threads + 1)
        threads = [
            threading.Thread(target=_worker, args=(barrier,))
            for _ in range(n_threads)
        ]
        for t in threads:
            t.start()
        barrier.wait()
        t0 = time.perf_counter()
        for t in threads:
            t.join()
        best = max(best, n_threads * BPT / (time.perf_counter() - t0))
    return best


def main(out_path: str = "ddc_fn_scaling.png") -> None:
    ncpu = os.cpu_count() or 8
    counts = [c for c in (1, 2, 4, 8, 12, 16, 24, 32) if c <= ncpu]
    if counts[-1] != ncpu:
        counts.append(ncpu)

    # Sanity-check the kernel the workers hammer: the carrier must park at
    # DC and the 4× decimation must hold, else the benchmark times noise.
    ddcr = Ddcr(LO, RATE)
    out = np.empty(NBLK, dtype=np.complex64)
    x = np.cos(2.0 * np.pi * F_CARRIER * np.arange(NBLK)).astype(np.float32)
    y = np.array(ddcr.execute(x, out), copy=True)
    ddcr.close()
    assert len(y) == int(NBLK * RATE), (
        f"{len(y)} outputs from {NBLK} inputs at rate {RATE}"
    )
    spec = np.abs(np.fft.fft(y[len(y) // 10 :]))  # drop filter transient
    assert int(np.argmax(spec)) == 0, "down-converted carrier not at DC"

    _throughput(1)  # warm up caches / allocator
    base = _throughput(1)
    print(f"--- thread-per-shard scaling ({ncpu} logical cores) ---")
    print(f"  {'threads':>8} {'Mblk/s':>9} {'speedup':>8} {'eff':>6}")
    speedups = []
    for n in counts:
        thru = _throughput(n)
        su = thru / base
        speedups.append(su)
        print(f"  {n:>8} {thru / 1e6:>9.3f} {su:>7.2f}x {su / n * 100:>5.0f}%")

    # The GIL-release claim is the whole demo: with the GIL held across
    # execute, N threads would aggregate ≈1× base throughput AT EVERY N.
    # That last clause is the load-bearing one, and this assertion used to
    # miss it -- it read ONE point, the 2-thread speedup, and called
    # anything under 1.25× GIL-bound.
    #
    # A 2-thread sample cannot carry that claim on a machine whose
    # single-thread boost clock is well above its all-core clock, which is
    # an ordinary cloud-VM property. doppler#990: a CI runner measured
    #
    #     1 thread  0.015 Mblk/s   1.00×
    #     2 threads 0.016          1.02×   <- "GIL-bound", said the assert
    #     4 threads 0.029          1.90×   <- ...while scaling 1.9×
    #
    # and both points imply the SAME per-thread rate (0.510 and 0.475 of
    # the single-thread rate). A machine clocking ~2× on one core as on
    # four produces exactly that, and on such a box su2 ≈ 1.0 is the
    # CORRECT result for a kernel that has fully released the GIL.
    # Contention would have distorted the two ratios differently; it did
    # not, and 24 local runs across four topologies and load regimes never
    # moved su2 below 1.92×, so "flaky runner" was not the answer either.
    #
    # So read the CURVE, not a point: take the best speedup over every
    # measured thread count. A held GIL caps ALL of them near 1× -- proven
    # by sabotage, swapping the kernel for a pure-Python loop, which scores
    # 1.00× at 1, 2 and 4 threads and fails this assertion as it must --
    # while frequency scaling merely flattens the curve without stopping it
    # climbing. Taking the maximum is what survives the second and still
    # catches the first.
    #
    # None of that holds under profile instrumentation, where the number is
    # not the receiver's. `make coverage` builds with
    # -fprofile-instr-generate, and every counter update is an atomic on a
    # page shared between threads, so the threads serialise on the profiling
    # runtime rather than on the GIL: measured 0.98x here against ~1.9x
    # uninstrumented. Asserting anyway would make a threading claim out of a
    # measurement of llvm's counters.
    #
    # Keyed on LLVM_PROFILE_FILE, which the coverage recipe sets and nothing
    # else does -- a precise precondition, not a guess about the environment.
    # Everything above still runs and still contributes coverage; only the
    # claim that cannot hold is withheld, and it says so out loud.
    if os.environ.get("LLVM_PROFILE_FILE"):
        print(
            "  scaling assertion skipped: LLVM_PROFILE_FILE is set, so the "
            "profiling runtime's atomics dominate the threading it measures"
        )
    elif max(counts) >= 4:
        parallel = [(n, su) for n, su in zip(counts, speedups) if n >= 2]
        n_best, best = max(parallel, key=lambda ns: ns[1])
        assert best > 1.25, (
            f"no thread count beat {best:.2f}x (best was {n_best} threads) "
            f"— execute appears GIL-bound"
        )
        print(
            f"  best speedup {best:.2f}x at {n_best} threads > 1.25x "
            f"— GIL released, OK"
        )
    else:
        # Fewer than four usable cores, so the curve is one or two points
        # and the frequency effect above is indistinguishable from a held
        # GIL -- the information is not in the measurement, at any
        # threshold. Say so rather than assert something the data cannot
        # support; the plot is still produced and still useful.
        print(
            f"  scaling assertion skipped: {ncpu} core(s) gives no thread "
            f"count where a released GIL and a boost-clocked one differ"
        )

    # ── plot ────────────────────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(9, 5.2), constrained_layout=True)
    fig.suptitle(
        "doppler — Ddcr thread-per-shard scaling\n"
        "GIL released across Ddcr.execute; one object + buffer per thread",
        fontsize=12,
        color="#f1f5f9",
    )

    ax.plot(
        counts,
        counts,
        "--",
        color="#6b7280",
        lw=1.2,
        label="ideal (linear)",
    )
    ax.plot(
        counts,
        speedups,
        "-o",
        color="#4ade80",
        lw=1.8,
        markersize=6,
        label="measured speedup",
    )
    # mark where scaling departs ideal (memory-bandwidth-bound region)
    knee = next(
        (
            counts[i]
            for i in range(len(counts))
            if speedups[i] < 0.7 * counts[i]
        ),
        None,
    )
    if knee is not None:
        ax.axvspan(knee, counts[-1], color="#7c2d12", alpha=0.18)
        ax.text(
            knee,
            0.5,
            "  memory-bandwidth bound",
            color="#fb923c",
            fontsize=9,
            va="bottom",
            rotation=0,
        )

    ax.set_xlabel("worker threads (= shards)")
    ax.set_ylabel("speedup vs 1 thread")
    ax.set_xlim(0, counts[-1] + 1)
    ax.set_ylim(0, counts[-1] + 1)
    ax.set_facecolor("#111827")
    ax.grid(True, color="#374151", lw=0.4)
    ax.tick_params(colors="#d1d5db")
    for sp in ax.spines.values():
        sp.set_color("#374151")
    ax.xaxis.label.set_color("#d1d5db")
    ax.yaxis.label.set_color("#d1d5db")
    ax.legend(
        facecolor="#1f2937",
        edgecolor="#4b5563",
        labelcolor="#d1d5db",
        fontsize=10,
        loc="upper left",
    )
    # annotate the best realised speedup
    bi = int(np.argmax(speedups))
    ax.annotate(
        f"{speedups[bi]:.1f}× @ {counts[bi]} threads",
        xy=(counts[bi], speedups[bi]),
        xytext=(counts[bi] - 0.5, speedups[bi] + 1.5),
        color="#4ade80",
        fontsize=10,
        arrowprops={"arrowstyle": "->", "color": "#4ade80", "lw": 1.0},
    )

    fig.patch.set_facecolor("#0f172a")
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"\nScaling plot saved → {out_path}")


if __name__ == "__main__":
    main()
