"""ddc_fn_scaling.py — thread-per-shard core-scaling benchmark for Ddcr.

`Ddcr.execute` runs the C kernel with the **GIL released** (the kernel touches
only its own handle's state and the caller's buffers — no Python objects, no
shared state), so a thread-per-shard worker scales across cores instead of
serialising on the GIL.

This measures that: N worker threads, each owning its **own** Ddcr handle and
`out` buffer, all running `execute` concurrently. It plots realised speedup
versus an ideal-linear reference and saves ``ddc_fn_scaling.png``.

The curve is near-linear through a handful of cores, then flattens — the kernel
streams large buffers, so it becomes **memory-bandwidth bound**, not GIL bound.
Numbers are machine-specific (regenerated by ``make gallery``).

Run:
  python examples/python/ddc_fn_scaling.py
"""

from __future__ import annotations

import os
import threading
import time

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from doppler.ddc import Ddcr

F_CARRIER = 0.18
LO = -(2.0 * F_CARRIER + 0.5)
RATE = 0.25
NBLK = 8192  # samples per block
BPT = 6000  # blocks each thread processes per run
TRIALS = 3  # keep the best (least-noisy) of this many runs


def _worker(barrier: threading.Barrier) -> None:
    """One shard: own handle, own output buffer, tight execute loop."""
    ddcr = Ddcr(LO, RATE)
    out = np.empty(NBLK, dtype=np.complex64)
    x = np.cos(2.0 * np.pi * F_CARRIER * np.arange(NBLK)).astype(np.float32)
    barrier.wait()  # release all threads together
    for _ in range(BPT):
        ddcr.execute(x, out)
    ddcr.close()


def _throughput(n_threads: int) -> float:
    """Best-of-TRIALS aggregate throughput (blocks/s) for *n_threads*."""
    best = 0.0
    for _ in range(TRIALS):
        barrier = threading.Barrier(n_threads + 1)
        threads = [
            threading.Thread(target=_worker, args=(barrier,))
            for _ in range(n_threads)
        ]
        for t in threads:
            t.start()
        barrier.wait()
        t0 = time.perf_counter()
        for t in threads:
            t.join()
        best = max(best, n_threads * BPT / (time.perf_counter() - t0))
    return best


def main(out_path: str = "ddc_fn_scaling.png") -> None:
    ncpu = os.cpu_count() or 8
    counts = [c for c in (1, 2, 4, 8, 12, 16, 24, 32) if c <= ncpu]
    if counts[-1] != ncpu:
        counts.append(ncpu)

    # Sanity-check the kernel the workers hammer: the carrier must park at
    # DC and the 4× decimation must hold, else the benchmark times noise.
    ddcr = Ddcr(LO, RATE)
    out = np.empty(NBLK, dtype=np.complex64)
    x = np.cos(2.0 * np.pi * F_CARRIER * np.arange(NBLK)).astype(np.float32)
    y = np.array(ddcr.execute(x, out), copy=True)
    ddcr.close()
    assert len(y) == int(NBLK * RATE), (
        f"{len(y)} outputs from {NBLK} inputs at rate {RATE}"
    )
    spec = np.abs(np.fft.fft(y[len(y) // 10 :]))  # drop filter transient
    assert int(np.argmax(spec)) == 0, "down-converted carrier not at DC"

    _throughput(1)  # warm up caches / allocator
    base = _throughput(1)
    print(f"--- thread-per-shard scaling ({ncpu} logical cores) ---")
    print(f"  {'threads':>8} {'Mblk/s':>9} {'speedup':>8} {'eff':>6}")
    speedups = []
    for n in counts:
        thru = _throughput(n)
        su = thru / base
        speedups.append(su)
        print(f"  {n:>8} {thru / 1e6:>9.3f} {su:>7.2f}x {su / n * 100:>5.0f}%")

    # The GIL-release claim is the whole demo: with the GIL held across
    # execute, two threads would aggregate ≈1× base throughput.  Genuine
    # parallelism must clear that by a wide margin on any 2+ core box
    # (measured ≈1.9×; the memory-bandwidth ceiling only bites later).
    if ncpu >= 2 and 2 in counts:
        su2 = speedups[counts.index(2)]
        assert su2 > 1.25, (
            f"2-thread speedup {su2:.2f}x — execute appears GIL-bound"
        )
        print(f"  2-thread speedup {su2:.2f}x > 1.25x — GIL released, OK")

    # ── plot ────────────────────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(9, 5.2), constrained_layout=True)
    fig.suptitle(
        "doppler — Ddcr thread-per-shard scaling\n"
        "GIL released across Ddcr.execute; one handle + buffer per thread",
        fontsize=12,
        color="#f1f5f9",
    )

    ax.plot(
        counts,
        counts,
        "--",
        color="#6b7280",
        lw=1.2,
        label="ideal (linear)",
    )
    ax.plot(
        counts,
        speedups,
        "-o",
        color="#4ade80",
        lw=1.8,
        markersize=6,
        label="measured speedup",
    )
    # mark where scaling departs ideal (memory-bandwidth-bound region)
    knee = next(
        (
            counts[i]
            for i in range(len(counts))
            if speedups[i] < 0.7 * counts[i]
        ),
        None,
    )
    if knee is not None:
        ax.axvspan(knee, counts[-1], color="#7c2d12", alpha=0.18)
        ax.text(
            knee,
            0.5,
            "  memory-bandwidth bound",
            color="#fb923c",
            fontsize=9,
            va="bottom",
            rotation=0,
        )

    ax.set_xlabel("worker threads (= shards)")
    ax.set_ylabel("speedup vs 1 thread")
    ax.set_xlim(0, counts[-1] + 1)
    ax.set_ylim(0, counts[-1] + 1)
    ax.set_facecolor("#111827")
    ax.grid(True, color="#374151", lw=0.4)
    ax.tick_params(colors="#d1d5db")
    for sp in ax.spines.values():
        sp.set_color("#374151")
    ax.xaxis.label.set_color("#d1d5db")
    ax.yaxis.label.set_color("#d1d5db")
    ax.legend(
        facecolor="#1f2937",
        edgecolor="#4b5563",
        labelcolor="#d1d5db",
        fontsize=10,
        loc="upper left",
    )
    # annotate the best realised speedup
    bi = int(np.argmax(speedups))
    ax.annotate(
        f"{speedups[bi]:.1f}× @ {counts[bi]} threads",
        xy=(counts[bi], speedups[bi]),
        xytext=(counts[bi] - 0.5, speedups[bi] + 1.5),
        color="#4ade80",
        fontsize=10,
        arrowprops={"arrowstyle": "->", "color": "#4ade80", "lw": 1.0},
    )

    fig.patch.set_facecolor("#0f172a")
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"\nScaling plot saved → {out_path}")


if __name__ == "__main__":
    main()
