"""measure_demo.py — single-tone ADC measurement suite (doppler.measure).

Four panels built from `doppler.measure.ToneMeasure`, the IEEE Std 1241
windowed-tone analyzer (each component's power is integrated over its window
main lobe; the noise sum excludes the leakage bins around DC, the fundamental
and each harmonic):

  (a) Annotated single-tone spectrum of a 12-bit ADC capture — fundamental,
      harmonics, worst spur (SFDR), noise floor, with the metric bag.
  (b) ENOB vs ADC resolution — an ideal N-bit converter recovers ENOB ~= N.
  (c) Per-harmonic distortion that THD aggregates.
  (d) SNR / SINAD / SFDR / ENOB vs input back-off (the dynamic-range sweep),
      showing how the full-scale-corrected ENOB stays flat as the tone backs
      off while raw ENOB falls.

Every panel feeds an `M = NAVG * N` capture, so `analyze()` averages `NAVG = 8`
segments (Welch's method) — a smoother backdrop and a lower-variance floor than
a single periodogram, at the same resolution bandwidth.

Run:
    python examples/python/measure_demo.py
"""

from __future__ import annotations

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from doppler.cvt import ADC
from doppler.measure import ToneMeasure
from doppler.source import AWGN, LO

FS = 100e6  # 100 MHz sample rate
N = 1 << 14  # 16384-sample segment (sets the resolution bandwidth)
NAVG = 8  # segments averaged per measurement (Welch's method)
M = NAVG * N  # total capture length fed to analyze()
# matplotlib standard palette (tab10) by role
ACCENT, FUND, HARM, SPUR, FLOOR = "C0", "C2", "C1", "C3", "C7"


def real_tone(freq, n, amp):
    """A real cosine at `freq` Hz, generated by doppler's NCO (`source.LO`)."""
    return (amp * LO(freq / FS).steps(n).real).astype(np.float32)


def adc_capture(bits, ftone, amp=0.999, harmonics=(), noise=0.0, seed=0):
    """A real ADC capture: a doppler-NCO tone (+ optional harmonics and a
    seeded noise floor) quantised to `bits` by `doppler.cvt.ADC`.  The analyzer
    is told the depth via `bits=`, so it derives the 0-dBFS reference itself.
    The capture spans `M = NAVG * N` samples, so `analyze()` averages `NAVG`
    segments (Welch's method)."""
    x = real_tone(ftone, M, amp)
    for k, dbc in harmonics:
        x = x + real_tone(k * ftone, M, amp * 10 ** (dbc / 20))
    if noise:
        x = x + (noise * AWGN(seed, 1.0).generate(M).real).astype(np.float32)
    return ADC(bits, 0.0, 0).steps(x).astype(np.float32)


def main() -> None:
    fig, axes = plt.subplots(2, 2, figsize=(13, 9))

    # ── (a) annotated single-tone spectrum ────────────────────────────────
    ax = axes[0, 0]
    ftone = 10.017e6  # ~10 MHz, non-coherent so quantisation noise spreads
    codes = adc_capture(12, ftone, harmonics=[(2, -62), (3, -70), (5, -78)])
    m = ToneMeasure(
        n=N,
        fs=FS,
        n_harmonics=8,
        bits=12,
    )
    r = m.analyze(codes)
    # self-validation: a 0.999-FS tone must read ~0 dBFS; the worst spur
    # is the injected H2 at -62 dBc; SNR sits on the 12-bit quantisation
    # floor 6.02*12 + 1.76 = 74.0 dB (harmonics are excluded from noise).
    print(
        f"(a) fund {r.fund_dbfs:+.2f} dBFS  SNR {r.snr:.1f} dB  "
        f"SFDR {r.sfdr_dbc:.1f} dBc  ENOB {r.enob:.2f} bits"
    )
    assert abs(r.fund_dbfs) < 0.1, "full-scale tone did not read 0 dBFS"
    assert abs(r.sfdr_dbc - 62.0) < 2.0, "SFDR missed the injected H2"
    assert abs(r.snr - 74.0) < 2.0, "SNR off the 12-bit quantisation floor"
    spec = m.spectrum_dbfs(codes)  # DC-centred, length nfft
    half = m.nfft // 2
    freqs = np.arange(half) * FS / m.nfft / 1e6  # MHz, DC..just-below-Nyquist
    ax.plot(freqs, spec[half:], color=ACCENT, lw=0.7)
    ax.axhline(
        r.noise_floor_dbfs,
        color=FLOOR,
        ls="--",
        lw=1,
        label=f"noise floor {r.noise_floor_dbfs:.0f} dBFS",
    )
    ax.plot(
        r.fund_freq / 1e6,
        r.fund_dbfs,
        "v",
        color=FUND,
        ms=10,
        label="fundamental",
    )
    for k in range(2, 6):
        fk = (k * r.fund_freq) % FS
        fk = fk if fk <= FS / 2 else FS - fk
        ax.axvline(fk / 1e6, color=HARM, ls=":", lw=0.8, alpha=0.7)
    ax.axvline(
        r.worst_spur_freq / 1e6, color=SPUR, ls="-", lw=0.8, label="worst spur"
    )
    ax.annotate(
        "",
        xy=(r.worst_spur_freq / 1e6, r.fund_dbfs - r.sfdr_dbc),
        xytext=(r.worst_spur_freq / 1e6, r.fund_dbfs),
        arrowprops={"arrowstyle": "<->", "color": SPUR, "lw": 1.2},
    )
    ax.text(
        r.worst_spur_freq / 1e6 + 1.5,
        r.fund_dbfs - r.sfdr_dbc / 2,
        f"SFDR\n{r.sfdr_dbc:.1f} dBc",
        color=SPUR,
        fontsize=8,
        va="center",
    )
    box = (
        f"fund   {r.fund_dbfs:+.2f} dBFS\nSNR    {r.snr:.1f} dB\n"
        f"SINAD  {r.sinad:.1f} dB\nTHD    {r.thd:.1f} dBc\n"
        f"SFDR   {r.sfdr_dbc:.1f} dBc\nENOB   {r.enob:.2f} bits"
    )
    ax.text(
        0.97,
        0.95,
        box,
        transform=ax.transAxes,
        ha="right",
        va="top",
        family="monospace",
        fontsize=8,
        bbox={"boxstyle": "round", "fc": "#f8fafc", "ec": "#cbd5e1"},
    )
    ax.set(
        title="(a) 12-bit ADC capture — annotated metrics",
        xlabel="frequency (MHz)",
        ylabel="dBFS",
        ylim=(-130, 5),
    )
    ax.legend(loc="lower left", fontsize=7)

    # ── (b) ENOB vs ADC resolution ────────────────────────────────────────
    ax = axes[0, 1]
    bits_list = list(range(6, 17))
    enobs = []
    for b in bits_list:
        codes = adc_capture(b, 9.013e6)
        mb = ToneMeasure(
            n=N, fs=FS, dynamic_range_db=106.0, n_harmonics=10, bits=b
        )
        enobs.append(mb.analyze(codes).enob)
    # self-validation: an ideal converter recovers ENOB ~= N to a small
    # fraction of a bit until the analysis noise floor (N=16k segments,
    # NAVG=8) caps the very top of the sweep; it must stay monotonic.
    err_b = np.abs(np.array(enobs) - np.array(bits_list))
    print(f"(b) max |ENOB - N| over 6..13 bits: {err_b[:8].max():.2f}")
    assert np.all(err_b[:8] < 0.3), "ENOB departs from the ideal N-bit line"
    assert np.all(np.diff(enobs) > 0), "ENOB not monotonic in resolution"
    ax.plot(bits_list, bits_list, color=FLOOR, ls="-", label="ideal (ENOB=N)")
    ax.plot(bits_list, enobs, "o", color=ACCENT, label="measured")
    ax.set(
        title="(b) ENOB recovers the ideal N-bit resolution",
        xlabel="ADC bits",
        ylabel="measured ENOB",
    )
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)

    # ── (c) per-harmonic distortion (what THD aggregates) ─────────────────
    ax = axes[1, 0]
    inj = [(2, -55), (3, -63), (4, -72), (5, -68)]
    codes = adc_capture(14, 7.011e6, harmonics=inj)
    mc = ToneMeasure(n=N, fs=FS, dynamic_range_db=90.0, n_harmonics=8, bits=14)
    rc = mc.analyze(codes)
    spec_c = mc.spectrum_dbfs(codes)
    ks = [2, 3, 4, 5, 6, 7]
    levels = []
    for k in ks:
        fk = (k * rc.fund_freq) % FS
        fk = fk if fk <= FS / 2 else FS - fk
        b = round(fk / FS * mc.nfft) + mc.nfft // 2
        levels.append(float(np.max(spec_c[b - 3 : b + 4]) - rc.fund_dbfs))
    # self-validation: THD must recover the power sum of the injected
    # harmonic set (the 14-bit quantisation contribution is negligible).
    thd_inj = 10 * np.log10(sum(10 ** (d / 10) for _, d in inj))
    print(f"(c) THD {rc.thd:.1f} dBc vs injected power sum {thd_inj:.1f} dBc")
    assert abs(rc.thd - thd_inj) < 1.5, "THD missed the injected harmonics"
    ax.bar([str(k) for k in ks], levels, color=HARM)
    ax.axhline(
        rc.thd, color=ACCENT, ls="--", label=f"THD (total) {rc.thd:.1f} dBc"
    )
    ax.set(
        title="(c) per-harmonic levels — THD is their power sum",
        xlabel="harmonic",
        ylabel="level vs fundamental (dBc)",
    )
    ax.legend(fontsize=8)

    # ── (d) dynamic-range sweep vs input back-off ─────────────────────────
    ax = axes[1, 1]
    backoffs = np.arange(0, 40, 3)  # dB below full scale
    snr, sinad, sfdr, enob, enob_fs = [], [], [], [], []
    for bo in backoffs:
        amp = 0.999 * 10 ** (-bo / 20)
        codes = adc_capture(12, 9.013e6, amp=amp)
        md = ToneMeasure(
            n=N, fs=FS, dynamic_range_db=106.0, n_harmonics=10, bits=12
        )
        rd = md.analyze(codes)
        snr.append(rd.snr)
        sinad.append(rd.sinad)
        sfdr.append(rd.sfdr_dbfs)
        enob.append(rd.enob)
        enob_fs.append(rd.enob_fs)
    # self-validation: raw ENOB falls 1 bit per 6.02 dB of back-off while
    # the full-scale-corrected ENOB stays pinned at the converter's 12.
    drop = enob[0] - enob[-1]
    spread = max(enob_fs) - min(enob_fs)
    print(
        f"(d) raw ENOB drop {drop:.2f} bits over {backoffs[-1]} dB, "
        f"FS-corrected spread {spread:.2f} bits"
    )
    assert abs(drop - backoffs[-1] / 6.02) < 0.5, "raw ENOB slope wrong"
    assert spread < 0.3, "FS-corrected ENOB is not flat with back-off"
    x = -backoffs
    ax.plot(x, snr, "-", color=ACCENT, label="SNR")
    ax.plot(x, sinad, "-", color=FUND, label="SINAD")
    ax.plot(x, sfdr, "-", color=SPUR, label="SFDR (dBFS)")
    ax2 = ax.twinx()
    ax2.plot(x, enob, ":", color=HARM, label="ENOB")
    ax2.plot(x, enob_fs, "--", color="C4", label="ENOB (FS-corrected)")
    ax2.set_ylabel("ENOB (bits)")
    ax.set(
        title="(d) dynamic range vs input level",
        xlabel="input level (dBFS)",
        ylabel="dB",
    )
    lines = ax.get_lines() + ax2.get_lines()
    ax.legend(
        lines, [ln.get_label() for ln in lines], fontsize=7, loc="center left"
    )
    ax.grid(alpha=0.3)

    fig.suptitle(
        "doppler.measure — single-tone ADC characterisation",
        fontsize=14,
        weight="bold",
    )
    fig.tight_layout(rect=(0, 0, 1, 0.98))
    fig.savefig("measure_demo.png", dpi=110)
    print("wrote measure_demo.png")


if __name__ == "__main__":
    main()
